# -*- coding: utf-8 -*-
# =============================================================================
# !! AUTO-GENERATED FILE -- DO NOT EDIT !!
#
# Generated by: rubi_integrate/codegen/generate.py
# Source: 1.1.4.2 (c x)^m (a x^j+b x^n)^p.m
# Module: 1.1.4.2 (c x)^m (a x^j+b x^n)^p
#
# This file contains Rubi integration rules as SymPyReplacementPattern objects.
# Re-run the generator to update.
# =============================================================================
import sympy
from sympy import Symbol
from rubi_integrate.utils.rubi_utils import *  # bare-name access; sympy imports below override any conflicts (e.g. Not)
from sympy.logic.boolalg import Or, Not
from sympy import (
    sqrt,
)

from sympy_matching.wild import WildSymbol, IDENTITY_ELEMENT
from rubi_integrate.base_objects import Int, SymPyReplacementPattern
# Inert trig markers (Rubi's lowercase sin/cos/... patterns). Distinct opaque heads,
# NOT subclasses of sympy.sin -- see rubi-trig-deactivation-dispatch project note.
from rubi_integrate.utils import (
    # Wolfram standard constraints
    FreeQ, IntegerQ, EqQ, NeQ, IGtQ, ILtQ, GtQ, LtQ, PosQ, IntegersQ, LinearPairQ,
)

# --- Integration variable ---
x = Symbol('x')

# --- Rubi global option stubs (default False/placeholder) ---
UseGamma = sympy.Symbol('UseGamma')  # Rubi global option; treated as False in Python
u = Symbol('u')  # Generic integrand placeholder used in some Rubi constraint calls

# --- Rubi selector symbols ---
# Rubi passes Min/Max as bare SYMBOLS, not calls: Expon[Px, x, Min] selects the
# minimum exponent. The code emitter round-trips through SymPy's printer, which
# renders Symbol('Min') as the bare name `Min`, so the name must exist here.
# (A genuine Min[a, b] call is emitted qualified, as sympy.Min(...), so these
# bindings cannot shadow it.)
Min = Symbol('Min')
Max = Symbol('Max')

# --- Wildcard symbols ---
# dot wildcards (must match exactly one expression)
# optional wildcards (can match identity element if absent in commutative ops)

_a_ = WildSymbol('a', optional_value=IDENTITY_ELEMENT)
a_ = WildSymbol('a')
_b_ = WildSymbol('b', optional_value=IDENTITY_ELEMENT)
b_ = WildSymbol('b')
_c_ = WildSymbol('c', optional_value=IDENTITY_ELEMENT)
c_ = WildSymbol('c')
_j_ = WildSymbol('j', optional_value=IDENTITY_ELEMENT)
j_ = WildSymbol('j')
_m_ = WildSymbol('m', optional_value=IDENTITY_ELEMENT)
m_ = WildSymbol('m')
_n_ = WildSymbol('n', optional_value=IDENTITY_ELEMENT)
n_ = WildSymbol('n')
_p_ = WildSymbol('p', optional_value=IDENTITY_ELEMENT)
p_ = WildSymbol('p')
u_ = WildSymbol('u')
v_ = WildSymbol('v')

RULES = [
    # Rule 1
    SymPyReplacementPattern(
        pattern=Int(x**_m_*(x**_j_*_a_ + x**n_*_b_)**p_, x),
        constraints=(FreeQ([_a_, _b_, _j_, _m_, n_, p_], x), Not(IntegerQ(p_)), NeQ(n_, _j_), IntegerQ(Simplify(_j_/n_)), EqQ(Simplify(_m_ - n_ + 1), 0),),
        replacement=Subst(Int((x*_b_ + x**Simplify(_j_/n_)*_a_)**p_, x), x, x**n_)/n_,
        module_name='1.1.4.2 (c x)^m (a x^j+b x^n)^p',
        rule_number=1,
    ),
    # Rule 2
    SymPyReplacementPattern(
        pattern=Int((x*_c_)**_m_*(x**_j_*_a_ + x**_n_*_b_)**p_, x),
        constraints=(FreeQ([_a_, _b_, _c_, _j_, _m_, _n_, p_], x), Not(IntegerQ(p_)), NeQ(_n_, _j_), EqQ(-_j_ + _m_ + _n_*p_ + _n_ + 1, 0), Or(IntegerQ(_j_), GtQ(_c_, 0)),),
        replacement=-_c_**(_j_ - 1)*(x*_c_)**(-_j_ + _m_ + 1)*(x**_j_*_a_ + x**_n_*_b_)**(p_ + 1)/(_a_*(-_j_ + _n_)*(p_ + 1)),
        module_name='1.1.4.2 (c x)^m (a x^j+b x^n)^p',
        rule_number=2,
    ),
    # Rule 3
    SymPyReplacementPattern(
        pattern=Int((x*_c_)**_m_*(x**_j_*_a_ + x**_n_*_b_)**p_, x),
        constraints=(FreeQ([_a_, _b_, _c_, _j_, _m_, _n_], x), Not(IntegerQ(p_)), NeQ(_n_, _j_), ILtQ(Simplify((-_j_ + _m_ + _n_*p_ + _n_ + 1)/(-_j_ + _n_)), 0), LtQ(p_, -1), Or(IntegerQ(_j_), GtQ(_c_, 0)),),
        replacement=_c_**_j_*(-_j_ + _m_ + _n_*p_ + _n_ + 1)*Int((x*_c_)**(-_j_ + _m_)*(x**_j_*_a_ + x**_n_*_b_)**(p_ + 1), x)/(_a_*(-_j_ + _n_)*(p_ + 1)) - _c_**(_j_ - 1)*(x*_c_)**(-_j_ + _m_ + 1)*(x**_j_*_a_ + x**_n_*_b_)**(p_ + 1)/(_a_*(-_j_ + _n_)*(p_ + 1)),
        module_name='1.1.4.2 (c x)^m (a x^j+b x^n)^p',
        rule_number=3,
    ),
    # Rule 4
    SymPyReplacementPattern(
        pattern=Int((x*_c_)**_m_*(x**_j_*_a_ + x**_n_*_b_)**p_, x),
        constraints=(FreeQ([_a_, _b_, _c_, _j_, _m_, _n_, p_], x), Not(IntegerQ(p_)), NeQ(_n_, _j_), ILtQ(Simplify((-_j_ + _m_ + _n_*p_ + _n_ + 1)/(-_j_ + _n_)), 0), NeQ(_j_*p_ + _m_ + 1, 0), Or(IntegersQ(_j_, _n_), GtQ(_c_, 0)),),
        replacement=-_b_*_c_**(_j_ - _n_)*(-_j_ + _m_ + _n_*p_ + _n_ + 1)*Int((x*_c_)**(-_j_ + _m_ + _n_)*(x**_j_*_a_ + x**_n_*_b_)**p_, x)/(_a_*(_j_*p_ + _m_ + 1)) + _c_**(_j_ - 1)*(x*_c_)**(-_j_ + _m_ + 1)*(x**_j_*_a_ + x**_n_*_b_)**(p_ + 1)/(_a_*(_j_*p_ + _m_ + 1)),
        module_name='1.1.4.2 (c x)^m (a x^j+b x^n)^p',
        rule_number=4,
    ),
    # Rule 5
    SymPyReplacementPattern(
        pattern=Int((x*c_)**_m_*(x**_j_*_a_ + x**_n_*_b_)**p_, x),
        constraints=(FreeQ([_a_, _b_, c_, _j_, _m_, _n_, p_], x), Not(IntegerQ(p_)), NeQ(_n_, _j_), ILtQ(Simplify((-_j_ + _m_ + _n_*p_ + _n_ + 1)/(-_j_ + _n_)), 0),),
        replacement=c_**IntPart(_m_)*(x*c_)**FracPart(_m_)*Int(x**_m_*(x**_j_*_a_ + x**_n_*_b_)**p_, x)/x**FracPart(_m_),
        module_name='1.1.4.2 (c x)^m (a x^j+b x^n)^p',
        rule_number=5,
    ),
    # Rule 6
    SymPyReplacementPattern(
        pattern=Int(x**_m_*(x**_j_*_a_ + x**n_*_b_)**p_, x),
        constraints=(FreeQ([_a_, _b_, _j_, _m_, n_, p_], x), Not(IntegerQ(p_)), NeQ(n_, _j_), IntegerQ(Simplify(_j_/n_)), IntegerQ(Simplify((_m_ + 1)/n_)), NeQ(n_**2, 1),),
        replacement=Subst(Int(x**(Simplify((_m_ + 1)/n_) - 1)*(x*_b_ + x**Simplify(_j_/n_)*_a_)**p_, x), x, x**n_)/n_,
        module_name='1.1.4.2 (c x)^m (a x^j+b x^n)^p',
        rule_number=6,
    ),
    # Rule 7
    SymPyReplacementPattern(
        pattern=Int((x*c_)**_m_*(x**_j_*_a_ + x**n_*_b_)**p_, x),
        constraints=(FreeQ([_a_, _b_, c_, _j_, _m_, n_, p_], x), Not(IntegerQ(p_)), NeQ(n_, _j_), IntegerQ(Simplify(_j_/n_)), IntegerQ(Simplify((_m_ + 1)/n_)), NeQ(n_**2, 1),),
        replacement=c_**IntPart(_m_)*(x*c_)**FracPart(_m_)*Int(x**_m_*(x**_j_*_a_ + x**n_*_b_)**p_, x)/x**FracPart(_m_),
        module_name='1.1.4.2 (c x)^m (a x^j+b x^n)^p',
        rule_number=7,
    ),
    # Rule 8
    SymPyReplacementPattern(
        pattern=Int((x*_c_)**m_*(x**_j_*_a_ + x**_n_*_b_)**p_, x),
        constraints=(FreeQ([_a_, _b_, _c_], x), Not(IntegerQ(p_)), LtQ(0, _j_, _n_), Or(IntegersQ(_j_, _n_), GtQ(_c_, 0)), GtQ(p_, 0), LtQ(_j_*p_ + m_ + 1, 0),),
        replacement=-_b_*p_*(-_j_ + _n_)*Int((x*_c_)**(m_ + _n_)*(x**_j_*_a_ + x**_n_*_b_)**(p_ - 1), x)/(_c_**_n_*(_j_*p_ + m_ + 1)) + (x*_c_)**(m_ + 1)*(x**_j_*_a_ + x**_n_*_b_)**p_/(_c_*(_j_*p_ + m_ + 1)),
        module_name='1.1.4.2 (c x)^m (a x^j+b x^n)^p',
        rule_number=8,
    ),
    # Rule 9
    SymPyReplacementPattern(
        pattern=Int((x*_c_)**_m_*(x**_j_*_a_ + x**_n_*_b_)**p_, x),
        constraints=(FreeQ([_a_, _b_, _c_, _m_], x), Not(IntegerQ(p_)), LtQ(0, _j_, _n_), Or(IntegersQ(_j_, _n_), GtQ(_c_, 0)), GtQ(p_, 0), NeQ(_m_ + _n_*p_ + 1, 0),),
        replacement=_a_*p_*(-_j_ + _n_)*Int((x*_c_)**(_j_ + _m_)*(x**_j_*_a_ + x**_n_*_b_)**(p_ - 1), x)/(_c_**_j_*(_m_ + _n_*p_ + 1)) + (x*_c_)**(_m_ + 1)*(x**_j_*_a_ + x**_n_*_b_)**p_/(_c_*(_m_ + _n_*p_ + 1)),
        module_name='1.1.4.2 (c x)^m (a x^j+b x^n)^p',
        rule_number=9,
    ),
    # Rule 10
    SymPyReplacementPattern(
        pattern=Int((x*_c_)**_m_*(x**_j_*_a_ + x**_n_*_b_)**p_, x),
        constraints=(FreeQ([_a_, _b_, _c_], x), Not(IntegerQ(p_)), LtQ(0, _j_, _n_), Or(IntegersQ(_j_, _n_), GtQ(_c_, 0)), LtQ(p_, -1), GtQ(_j_*p_ + _m_ + 1, -_j_ + _n_),),
        replacement=-_c_**_n_*(_j_*p_ + _j_ + _m_ - _n_ + 1)*Int((x*_c_)**(_m_ - _n_)*(x**_j_*_a_ + x**_n_*_b_)**(p_ + 1), x)/(_b_*(-_j_ + _n_)*(p_ + 1)) + _c_**(_n_ - 1)*(x*_c_)**(_m_ - _n_ + 1)*(x**_j_*_a_ + x**_n_*_b_)**(p_ + 1)/(_b_*(-_j_ + _n_)*(p_ + 1)),
        module_name='1.1.4.2 (c x)^m (a x^j+b x^n)^p',
        rule_number=10,
    ),
    # Rule 11
    SymPyReplacementPattern(
        pattern=Int((x*_c_)**_m_*(x**_j_*_a_ + x**_n_*_b_)**p_, x),
        constraints=(FreeQ([_a_, _b_, _c_, _m_], x), Not(IntegerQ(p_)), LtQ(0, _j_, _n_), Or(IntegersQ(_j_, _n_), GtQ(_c_, 0)), LtQ(p_, -1),),
        replacement=_c_**_j_*(-_j_ + _m_ + _n_*p_ + _n_ + 1)*Int((x*_c_)**(-_j_ + _m_)*(x**_j_*_a_ + x**_n_*_b_)**(p_ + 1), x)/(_a_*(-_j_ + _n_)*(p_ + 1)) - _c_**(_j_ - 1)*(x*_c_)**(-_j_ + _m_ + 1)*(x**_j_*_a_ + x**_n_*_b_)**(p_ + 1)/(_a_*(-_j_ + _n_)*(p_ + 1)),
        module_name='1.1.4.2 (c x)^m (a x^j+b x^n)^p',
        rule_number=11,
    ),
    # Rule 12
    SymPyReplacementPattern(
        pattern=Int((x*_c_)**_m_*(x**_j_*_a_ + x**_n_*_b_)**p_, x),
        constraints=(FreeQ([_a_, _b_, _c_, _m_, p_], x), Not(IntegerQ(p_)), LtQ(0, _j_, _n_), Or(IntegersQ(_j_, _n_), GtQ(_c_, 0)), GtQ(_j_*p_ + _j_ + _m_ - _n_ + 1, 0), NeQ(_m_ + _n_*p_ + 1, 0),),
        replacement=-_a_*_c_**(-_j_ + _n_)*(_j_*p_ + _j_ + _m_ - _n_ + 1)*Int((x*_c_)**(_j_ + _m_ - _n_)*(x**_j_*_a_ + x**_n_*_b_)**p_, x)/(_b_*(_m_ + _n_*p_ + 1)) + _c_**(_n_ - 1)*(x*_c_)**(_m_ - _n_ + 1)*(x**_j_*_a_ + x**_n_*_b_)**(p_ + 1)/(_b_*(_m_ + _n_*p_ + 1)),
        module_name='1.1.4.2 (c x)^m (a x^j+b x^n)^p',
        rule_number=12,
    ),
    # Rule 13
    SymPyReplacementPattern(
        pattern=Int((x*_c_)**_m_*(x**_j_*_a_ + x**_n_*_b_)**p_, x),
        constraints=(FreeQ([_a_, _b_, _c_, _m_, p_], x), Not(IntegerQ(p_)), LtQ(0, _j_, _n_), Or(IntegersQ(_j_, _n_), GtQ(_c_, 0)), LtQ(_j_*p_ + _m_ + 1, 0),),
        replacement=-_b_*_c_**(_j_ - _n_)*(-_j_ + _m_ + _n_*p_ + _n_ + 1)*Int((x*_c_)**(-_j_ + _m_ + _n_)*(x**_j_*_a_ + x**_n_*_b_)**p_, x)/(_a_*(_j_*p_ + _m_ + 1)) + _c_**(_j_ - 1)*(x*_c_)**(-_j_ + _m_ + 1)*(x**_j_*_a_ + x**_n_*_b_)**(p_ + 1)/(_a_*(_j_*p_ + _m_ + 1)),
        module_name='1.1.4.2 (c x)^m (a x^j+b x^n)^p',
        rule_number=13,
    ),
    # Rule 14
    SymPyReplacementPattern(
        pattern=Int(x**_m_*(x**_j_*_a_ + x**n_*_b_)**p_, x),
        constraints=(FreeQ([_a_, _b_, _j_, _m_, n_, p_], x), Not(IntegerQ(p_)), NeQ(n_, _j_), IntegerQ(Simplify(_j_/n_)), NeQ(_m_, -1), IntegerQ(Simplify(n_/(_m_ + 1))), Not(IntegerQ(n_)),),
        replacement=Subst(Int((x**Simplify(_j_/(_m_ + 1))*_a_ + x**Simplify(n_/(_m_ + 1))*_b_)**p_, x), x, x**(_m_ + 1))/(_m_ + 1),
        module_name='1.1.4.2 (c x)^m (a x^j+b x^n)^p',
        rule_number=14,
    ),
    # Rule 15
    SymPyReplacementPattern(
        pattern=Int((x*c_)**_m_*(x**_j_*_a_ + x**n_*_b_)**p_, x),
        constraints=(FreeQ([_a_, _b_, c_, _j_, _m_, n_, p_], x), Not(IntegerQ(p_)), NeQ(n_, _j_), IntegerQ(Simplify(_j_/n_)), NeQ(_m_, -1), IntegerQ(Simplify(n_/(_m_ + 1))), Not(IntegerQ(n_)),),
        replacement=c_**IntPart(_m_)*(x*c_)**FracPart(_m_)*Int(x**_m_*(x**_j_*_a_ + x**n_*_b_)**p_, x)/x**FracPart(_m_),
        module_name='1.1.4.2 (c x)^m (a x^j+b x^n)^p',
        rule_number=15,
    ),
    # Rule 16
    SymPyReplacementPattern(
        pattern=Int((x*_c_)**_m_*(x**_j_*_a_ + x**_n_*_b_)**p_, x),
        constraints=(FreeQ([_a_, _b_, _c_, _j_, _m_, _n_], x), IGtQ(p_ + sympy.S.Half, 0), NeQ(_n_, _j_), EqQ(Simplify(_j_*p_ + _m_ + 1), 0), Or(IntegerQ(_j_), GtQ(_c_, 0)),),
        replacement=_a_*Int((x*_c_)**(_j_ + _m_)*(x**_j_*_a_ + x**_n_*_b_)**(p_ - 1), x)/_c_**_j_ + (x*_c_)**(_m_ + 1)*(x**_j_*_a_ + x**_n_*_b_)**p_/(_c_*p_*(-_j_ + _n_)),
        module_name='1.1.4.2 (c x)^m (a x^j+b x^n)^p',
        rule_number=16,
    ),
    # Rule 17
    SymPyReplacementPattern(
        pattern=Int(x**_m_/sqrt(x**_j_*_a_ + x**_n_*_b_), x),
        constraints=(FreeQ([_a_, _b_, _j_, _n_], x), EqQ(_m_, _j_/2 - 1), NeQ(_n_, _j_),),
        replacement=-2*Subst(Int(1/(-x**2*_a_ + 1), x), x, x**(_j_/2)/sqrt(x**_j_*_a_ + x**_n_*_b_))/(-_j_ + _n_),
        module_name='1.1.4.2 (c x)^m (a x^j+b x^n)^p',
        rule_number=17,
    ),
    # Rule 18
    SymPyReplacementPattern(
        pattern=Int((x*_c_)**_m_*(x**_j_*_a_ + x**_n_*_b_)**p_, x),
        constraints=(FreeQ([_a_, _b_, _c_, _j_, _m_, _n_], x), ILtQ(p_ + sympy.S.Half, 0), NeQ(_n_, _j_), EqQ(Simplify(_j_*p_ + _m_ + 1), 0), Or(IntegerQ(_j_), GtQ(_c_, 0)),),
        replacement=_c_**_j_*(-_j_ + _m_ + _n_*p_ + _n_ + 1)*Int((x*_c_)**(-_j_ + _m_)*(x**_j_*_a_ + x**_n_*_b_)**(p_ + 1), x)/(_a_*(-_j_ + _n_)*(p_ + 1)) - _c_**(_j_ - 1)*(x*_c_)**(-_j_ + _m_ + 1)*(x**_j_*_a_ + x**_n_*_b_)**(p_ + 1)/(_a_*(-_j_ + _n_)*(p_ + 1)),
        module_name='1.1.4.2 (c x)^m (a x^j+b x^n)^p',
        rule_number=18,
    ),
    # Rule 19
    SymPyReplacementPattern(
        pattern=Int((x*c_)**_m_*(x**_j_*_a_ + x**n_*_b_)**p_, x),
        constraints=(FreeQ([_a_, _b_, c_, _j_, _m_, n_, p_], x), IntegerQ(p_ + sympy.S.Half), NeQ(n_, _j_), EqQ(Simplify(_j_*p_ + _m_ + 1), 0),),
        replacement=c_**IntPart(_m_)*(x*c_)**FracPart(_m_)*Int(x**_m_*(x**_j_*_a_ + x**n_*_b_)**p_, x)/x**FracPart(_m_),
        module_name='1.1.4.2 (c x)^m (a x^j+b x^n)^p',
        rule_number=19,
    ),
    # Rule 20
    SymPyReplacementPattern(
        pattern=Int((x*_c_)**_m_*(x**_j_*_a_ + x**_n_*_b_)**p_, x),
        constraints=(FreeQ([_a_, _b_, _c_, _j_, _m_, _n_, p_], x), Not(IntegerQ(p_)), NeQ(_n_, _j_), PosQ(-_j_ + _n_),),
        replacement=x**(-_j_*FracPart(p_) - FracPart(_m_))*_c_**IntPart(_m_)*(x*_c_)**FracPart(_m_)*(x**_j_*_a_ + x**_n_*_b_)**FracPart(p_)*Int(x**(_j_*p_ + _m_)*(x**(-_j_ + _n_)*_b_ + _a_)**p_, x)/(x**(-_j_ + _n_)*_b_ + _a_)**FracPart(p_),
        module_name='1.1.4.2 (c x)^m (a x^j+b x^n)^p',
        rule_number=20,
    ),
    # Rule 21
    SymPyReplacementPattern(
        pattern=Int(u_**_m_*(_a_*v_**_j_ + _b_*v_**_n_)**_p_, x),
        constraints=(FreeQ([_a_, _b_, _j_, _m_, _n_, _p_], x), LinearPairQ(u_, v_, x),),
        replacement=u_**_m_*Subst(Int(x**_m_*(x**_j_*_a_ + x**_n_*_b_)**_p_, x), x, v_)/(v_**_m_*Coefficient(v_, x, 1)),
        module_name='1.1.4.2 (c x)^m (a x^j+b x^n)^p',
        rule_number=21,
    ),

]

# Summary: 21 rules translated, 0 skipped
