# -*- coding: utf-8 -*-
# =============================================================================
# !! AUTO-GENERATED FILE -- DO NOT EDIT !!
#
# Generated by: rubi_integrate/codegen/generate.py
# Source: 4.3.4.2 (a+b tan)^m (c+d tan)^n (A+B tan+C tan^2).m
# Module: 4.3.4.2 (a+b tan)^m (c+d tan)^n (A+B tan+C tan^2)
#
# This file contains Rubi integration rules as SymPyReplacementPattern objects.
# Re-run the generator to update.
# =============================================================================
import sympy
from sympy import Symbol
from rubi_integrate.utils.rubi_utils import *  # bare-name access; sympy imports below override any conflicts (e.g. Not)
from sympy.logic.boolalg import Or, Not, And
from sympy import (
    tan,
)

from sympy_matching.wild import WildSymbol, IDENTITY_ELEMENT
from rubi_integrate.base_objects import Int, SymPyReplacementPattern
# Inert trig markers (Rubi's lowercase sin/cos/... patterns). Distinct opaque heads,
# NOT subclasses of sympy.sin -- see rubi-trig-deactivation-dispatch project note.
from rubi_integrate.utils.inert_functions import (
    InertTan)
from rubi_integrate.utils import (
    # Wolfram standard constraints
    FreeQ, IntegerQ, EqQ, NeQ, IGtQ, ILtQ, GtQ, LtQ, LeQ,
)

# --- Integration variable ---
x = Symbol('x')

# --- Rubi global option stubs (default False/placeholder) ---
UseGamma = sympy.Symbol('UseGamma')  # Rubi global option; treated as False in Python
u = Symbol('u')  # Generic integrand placeholder used in some Rubi constraint calls

# --- Rubi selector symbols ---
# Rubi passes Min/Max as bare SYMBOLS, not calls: Expon[Px, x, Min] selects the
# minimum exponent. The code emitter round-trips through SymPy's printer, which
# renders Symbol('Min') as the bare name `Min`, so the name must exist here.
# (A genuine Min[a, b] call is emitted qualified, as sympy.Min(...), so these
# bindings cannot shadow it.)
Min = Symbol('Min')
Max = Symbol('Max')

# --- Wildcard symbols ---
# dot wildcards (must match exactly one expression)
# optional wildcards (can match identity element if absent in commutative ops)

ff = Symbol('ff')

_A_ = WildSymbol('A', optional_value=IDENTITY_ELEMENT)
A_ = WildSymbol('A')
_B_ = WildSymbol('B', optional_value=IDENTITY_ELEMENT)
B_ = WildSymbol('B')
_C_ = WildSymbol('C', optional_value=IDENTITY_ELEMENT)
C_ = WildSymbol('C')
_a_ = WildSymbol('a', optional_value=IDENTITY_ELEMENT)
a_ = WildSymbol('a')
_b_ = WildSymbol('b', optional_value=IDENTITY_ELEMENT)
b_ = WildSymbol('b')
_c_ = WildSymbol('c', optional_value=IDENTITY_ELEMENT)
c_ = WildSymbol('c')
_d_ = WildSymbol('d', optional_value=IDENTITY_ELEMENT)
d_ = WildSymbol('d')
_e_ = WildSymbol('e', optional_value=IDENTITY_ELEMENT)
e_ = WildSymbol('e')
_f_ = WildSymbol('f', optional_value=IDENTITY_ELEMENT)
f_ = WildSymbol('f')
_m_ = WildSymbol('m', optional_value=IDENTITY_ELEMENT)
m_ = WildSymbol('m')
_n_ = WildSymbol('n', optional_value=IDENTITY_ELEMENT)
n_ = WildSymbol('n')

RULES = [
    # Rule 1
    SymPyReplacementPattern(
        pattern=Int((_a_ + _b_*InertTan(x*_f_ + _e_))**_m_*(_c_ + _d_*InertTan(x*_f_ + _e_))**_n_*(_A_ + _B_*InertTan(x*_f_ + _e_) + _C_*InertTan(x*_f_ + _e_)**2), x),
        constraints=(FreeQ([_a_, _b_, _c_, _d_, _e_, _f_, _A_, _B_, _C_, _m_, _n_], x), NeQ(-_a_*_d_ + _b_*_c_, 0), EqQ(_A_*_b_**2 - _B_*_a_*_b_ + _C_*_a_**2, 0),),
        replacement=Int((_a_ + _b_*tan(x*_f_ + _e_))**(_m_ + 1)*(_c_ + _d_*tan(x*_f_ + _e_))**_n_*(_B_*_b_ - _C_*_a_ + _C_*_b_*tan(x*_f_ + _e_)), x)/_b_**2,
        module_name='4.3.4.2 (a+b tan)^m (c+d tan)^n (A+B tan+C tan^2)',
        rule_number=1,
    ),
    # Rule 2
    SymPyReplacementPattern(
        pattern=Int((_A_ + _C_*InertTan(x*_f_ + _e_)**2)*(_a_ + _b_*InertTan(x*_f_ + _e_))**_m_*(_c_ + _d_*InertTan(x*_f_ + _e_))**_n_, x),
        constraints=(FreeQ([_a_, _b_, _c_, _d_, _e_, _f_, _A_, _C_, _m_, _n_], x), NeQ(-_a_*_d_ + _b_*_c_, 0), EqQ(_A_*_b_**2 + _C_*_a_**2, 0),),
        replacement=-_C_*Int((_a_ - _b_*tan(x*_f_ + _e_))*(_a_ + _b_*tan(x*_f_ + _e_))**(_m_ + 1)*(_c_ + _d_*tan(x*_f_ + _e_))**_n_, x)/_b_**2,
        module_name='4.3.4.2 (a+b tan)^m (c+d tan)^n (A+B tan+C tan^2)',
        rule_number=2,
    ),
    # Rule 3
    SymPyReplacementPattern(
        pattern=Int((A_ + _C_*InertTan(x*_f_ + _e_)**2)*(_a_ + _b_*InertTan(x*_f_ + _e_))**_m_*(_c_ + _d_*InertTan(x*_f_ + _e_))**_n_, x),
        constraints=(FreeQ([_a_, _b_, _c_, _d_, _e_, _f_, A_, _C_, _m_, _n_], x), EqQ(A_, _C_),),
        replacement=A_*Subst(Int((x*_b_ + _a_)**_m_*(x*_d_ + _c_)**_n_, x), x, tan(x*_f_ + _e_))/_f_,
        module_name='4.3.4.2 (a+b tan)^m (c+d tan)^n (A+B tan+C tan^2)',
        rule_number=3,
    ),
    # Rule 4
    SymPyReplacementPattern(
        pattern=Int((_a_ + _b_*InertTan(x*_f_ + _e_))*(_c_ + _d_*InertTan(x*_f_ + _e_))**n_*(_A_ + _B_*InertTan(x*_f_ + _e_) + _C_*InertTan(x*_f_ + _e_)**2), x),
        constraints=(FreeQ([_a_, _b_, _c_, _d_, _e_, _f_, _A_, _B_, _C_], x), NeQ(-_a_*_d_ + _b_*_c_, 0), NeQ(_c_**2 + _d_**2, 0), LtQ(n_, -1),),
        replacement=Int((_c_ + _d_*tan(x*_f_ + _e_))**(n_ + 1)*Simp(_C_*_b_*(_c_**2 + _d_**2)*tan(x*_f_ + _e_)**2 + _a_*_d_*(_A_*_c_ + _B_*_d_ - _C_*_c_) + _b_*(_A_*_d_**2 - _B_*_c_*_d_ + _C_*_c_**2) + _d_*(-_A_*_a_*_d_ + _A_*_b_*_c_ + _B_*_a_*_c_ + _B_*_b_*_d_ + _C_*_a_*_d_ - _C_*_b_*_c_)*tan(x*_f_ + _e_), x), x)/(_d_*(_c_**2 + _d_**2)) + (_c_ + _d_*tan(x*_f_ + _e_))**(n_ + 1)*(_a_*_d_ - _b_*_c_)*(_A_*_d_**2 - _B_*_c_*_d_ + _C_*_c_**2)/(_d_**2*_f_*(_c_**2 + _d_**2)*(n_ + 1)),
        module_name='4.3.4.2 (a+b tan)^m (c+d tan)^n (A+B tan+C tan^2)',
        rule_number=4,
    ),
    # Rule 5
    SymPyReplacementPattern(
        pattern=Int((_A_ + _C_*InertTan(x*_f_ + _e_)**2)*(_a_ + _b_*InertTan(x*_f_ + _e_))*(_c_ + _d_*InertTan(x*_f_ + _e_))**n_, x),
        constraints=(FreeQ([_a_, _b_, _c_, _d_, _e_, _f_, _A_, _C_], x), NeQ(-_a_*_d_ + _b_*_c_, 0), NeQ(_c_**2 + _d_**2, 0), LtQ(n_, -1),),
        replacement=Int((_c_ + _d_*tan(x*_f_ + _e_))**(n_ + 1)*Simp(_C_*_b_*(_c_**2 + _d_**2)*tan(x*_f_ + _e_)**2 + _a_*_d_*(_A_*_c_ - _C_*_c_) + _b_*(_A_*_d_**2 + _C_*_c_**2) + _d_*(-_A_*_a_*_d_ + _A_*_b_*_c_ + _C_*_a_*_d_ - _C_*_b_*_c_)*tan(x*_f_ + _e_), x), x)/(_d_*(_c_**2 + _d_**2)) + (_c_ + _d_*tan(x*_f_ + _e_))**(n_ + 1)*(_A_*_d_**2 + _C_*_c_**2)*(_a_*_d_ - _b_*_c_)/(_d_**2*_f_*(_c_**2 + _d_**2)*(n_ + 1)),
        module_name='4.3.4.2 (a+b tan)^m (c+d tan)^n (A+B tan+C tan^2)',
        rule_number=5,
    ),
    # Rule 6
    SymPyReplacementPattern(
        pattern=Int((a_ + _b_*InertTan(x*_f_ + _e_))*(_c_ + _d_*InertTan(x*_f_ + _e_))**_n_*(_A_ + _B_*InertTan(x*_f_ + _e_) + _C_*InertTan(x*_f_ + _e_)**2), x),
        constraints=(FreeQ([a_, _b_, _c_, _d_, _e_, _f_, _A_, _B_, _C_, _n_], x), NeQ(-a_*_d_ + _b_*_c_, 0), NeQ(_c_**2 + _d_**2, 0), Not(LtQ(_n_, -1)),),
        replacement=_C_*_b_*(_c_ + _d_*tan(x*_f_ + _e_))**(_n_ + 1)*tan(x*_f_ + _e_)/(_d_*_f_*(_n_ + 2)) - Int((_c_ + _d_*tan(x*_f_ + _e_))**_n_*Simp(-_A_*a_*_d_*(_n_ + 2) + _C_*_b_*_c_ - _d_*(_n_ + 2)*(_A_*_b_ + _B_*a_ - _C_*_b_)*tan(x*_f_ + _e_) - (_C_*a_*_d_*(_n_ + 2) - _b_*(-_B_*_d_*(_n_ + 2) + _C_*_c_))*tan(x*_f_ + _e_)**2, x), x)/(_d_*(_n_ + 2)),
        module_name='4.3.4.2 (a+b tan)^m (c+d tan)^n (A+B tan+C tan^2)',
        rule_number=6,
    ),
    # Rule 7
    SymPyReplacementPattern(
        pattern=Int((_A_ + _C_*InertTan(x*_f_ + _e_)**2)*(a_ + _b_*InertTan(x*_f_ + _e_))*(_c_ + _d_*InertTan(x*_f_ + _e_))**_n_, x),
        constraints=(FreeQ([a_, _b_, _c_, _d_, _e_, _f_, _A_, _C_, _n_], x), NeQ(-a_*_d_ + _b_*_c_, 0), NeQ(_c_**2 + _d_**2, 0), Not(LtQ(_n_, -1)),),
        replacement=_C_*_b_*(_c_ + _d_*tan(x*_f_ + _e_))**(_n_ + 1)*tan(x*_f_ + _e_)/(_d_*_f_*(_n_ + 2)) - Int((_c_ + _d_*tan(x*_f_ + _e_))**_n_*Simp(-_A_*a_*_d_*(_n_ + 2) + _C_*_b_*_c_ - _d_*(_n_ + 2)*(_A_*_b_ - _C_*_b_)*tan(x*_f_ + _e_) - (_C_*a_*_d_*(_n_ + 2) - _C_*_b_*_c_)*tan(x*_f_ + _e_)**2, x), x)/(_d_*(_n_ + 2)),
        module_name='4.3.4.2 (a+b tan)^m (c+d tan)^n (A+B tan+C tan^2)',
        rule_number=7,
    ),
    # Rule 8
    SymPyReplacementPattern(
        pattern=Int((a_ + _b_*InertTan(x*_f_ + _e_))**m_*(_c_ + _d_*InertTan(x*_f_ + _e_))**_n_*(_A_ + _B_*InertTan(x*_f_ + _e_) + _C_*InertTan(x*_f_ + _e_)**2), x),
        constraints=(FreeQ([a_, _b_, _c_, _d_, _e_, _f_, _A_, _B_, _C_, _n_], x), NeQ(-a_*_d_ + _b_*_c_, 0), EqQ(a_**2 + _b_**2, 0), Or(LtQ(m_, 0), EqQ(m_ + _n_ + 1, 0)),),
        replacement=(a_ + _b_*tan(x*_f_ + _e_))**m_*(_c_ + _d_*tan(x*_f_ + _e_))**(_n_ + 1)*(_A_*a_ + _B_*_b_ - _C_*a_)/(2*_f_*m_*(-a_*_d_ + _b_*_c_)) + Int((a_ + _b_*tan(x*_f_ + _e_))**(m_ + 1)*(_c_ + _d_*tan(x*_f_ + _e_))**_n_*Simp(a_*(-_A_*_d_*(2*m_ + _n_ + 1) + _B_*_c_*m_ + _C_*_d_*(_n_ + 1)) + _b_*(-_B_*_d_*(_n_ + 1) + _c_*m_*(_A_ + _C_)) + (_A_*_b_*_d_*(m_ + _n_ + 1) + _C_*_b_*_d_*(m_ - _n_ - 1) + a_*(-_B_*_d_*(m_ + _n_ + 1) + 2*_C_*_c_*m_))*tan(x*_f_ + _e_), x), x)/(2*a_*m_*(-a_*_d_ + _b_*_c_)),
        module_name='4.3.4.2 (a+b tan)^m (c+d tan)^n (A+B tan+C tan^2)',
        rule_number=8,
    ),
    # Rule 9
    SymPyReplacementPattern(
        pattern=Int((_A_ + _C_*InertTan(x*_f_ + _e_)**2)*(a_ + _b_*InertTan(x*_f_ + _e_))**m_*(_c_ + _d_*InertTan(x*_f_ + _e_))**_n_, x),
        constraints=(FreeQ([a_, _b_, _c_, _d_, _e_, _f_, _A_, _C_, _n_], x), NeQ(-a_*_d_ + _b_*_c_, 0), EqQ(a_**2 + _b_**2, 0), Or(LtQ(m_, 0), EqQ(m_ + _n_ + 1, 0)),),
        replacement=a_*(_A_ - _C_)*(a_ + _b_*tan(x*_f_ + _e_))**m_*(_c_ + _d_*tan(x*_f_ + _e_))**(_n_ + 1)/(2*_f_*m_*(-a_*_d_ + _b_*_c_)) + Int((a_ + _b_*tan(x*_f_ + _e_))**(m_ + 1)*(_c_ + _d_*tan(x*_f_ + _e_))**_n_*Simp(a_*(-_A_*_d_*(2*m_ + _n_ + 1) + _C_*_d_*(_n_ + 1)) + _b_*_c_*m_*(_A_ + _C_) + (_A_*_b_*_d_*(m_ + _n_ + 1) + 2*_C_*a_*_c_*m_ + _C_*_b_*_d_*(m_ - _n_ - 1))*tan(x*_f_ + _e_), x), x)/(2*a_*m_*(-a_*_d_ + _b_*_c_)),
        module_name='4.3.4.2 (a+b tan)^m (c+d tan)^n (A+B tan+C tan^2)',
        rule_number=9,
    ),
    # Rule 10
    SymPyReplacementPattern(
        pattern=Int((a_ + _b_*InertTan(x*_f_ + _e_))**_m_*(_c_ + _d_*InertTan(x*_f_ + _e_))**n_*(_A_ + _B_*InertTan(x*_f_ + _e_) + _C_*InertTan(x*_f_ + _e_)**2), x),
        constraints=(FreeQ([a_, _b_, _c_, _d_, _e_, _f_, _A_, _B_, _C_, _m_], x), NeQ(-a_*_d_ + _b_*_c_, 0), EqQ(a_**2 + _b_**2, 0), Not(LtQ(_m_, 0)), LtQ(n_, -1), NeQ(_c_**2 + _d_**2, 0),),
        replacement=(a_ + _b_*tan(x*_f_ + _e_))**_m_*(_c_ + _d_*tan(x*_f_ + _e_))**(n_ + 1)*(_A_*_d_**2 - _B_*_c_*_d_ + _C_*_c_**2)/(_d_*_f_*(_c_**2 + _d_**2)*(n_ + 1)) - Int((a_ + _b_*tan(x*_f_ + _e_))**_m_*(_c_ + _d_*tan(x*_f_ + _e_))**(n_ + 1)*Simp(-a_*_d_*(n_ + 1)*(_A_*_c_ + _B_*_d_ - _C_*_c_) - a_*(-_C_*(_c_**2*_m_ - _d_**2*(n_ + 1)) + _d_*(-_A_*_d_ + _B_*_c_)*(_m_ + n_ + 1))*tan(x*_f_ + _e_) + _b_*_m_*(_A_*_d_**2 - _B_*_c_*_d_ + _C_*_c_**2), x), x)/(a_*_d_*(_c_**2 + _d_**2)*(n_ + 1)),
        module_name='4.3.4.2 (a+b tan)^m (c+d tan)^n (A+B tan+C tan^2)',
        rule_number=10,
    ),
    # Rule 11
    SymPyReplacementPattern(
        pattern=Int((_A_ + _C_*InertTan(x*_f_ + _e_)**2)*(a_ + _b_*InertTan(x*_f_ + _e_))**_m_*(_c_ + _d_*InertTan(x*_f_ + _e_))**n_, x),
        constraints=(FreeQ([a_, _b_, _c_, _d_, _e_, _f_, _A_, _C_, _m_], x), NeQ(-a_*_d_ + _b_*_c_, 0), EqQ(a_**2 + _b_**2, 0), Not(LtQ(_m_, 0)), LtQ(n_, -1), NeQ(_c_**2 + _d_**2, 0),),
        replacement=(a_ + _b_*tan(x*_f_ + _e_))**_m_*(_c_ + _d_*tan(x*_f_ + _e_))**(n_ + 1)*(_A_*_d_**2 + _C_*_c_**2)/(_d_*_f_*(_c_**2 + _d_**2)*(n_ + 1)) - Int((a_ + _b_*tan(x*_f_ + _e_))**_m_*(_c_ + _d_*tan(x*_f_ + _e_))**(n_ + 1)*Simp(-a_*_d_*(n_ + 1)*(_A_*_c_ - _C_*_c_) - a_*(-_A_*_d_**2*(_m_ + n_ + 1) - _C_*(_c_**2*_m_ - _d_**2*(n_ + 1)))*tan(x*_f_ + _e_) + _b_*_m_*(_A_*_d_**2 + _C_*_c_**2), x), x)/(a_*_d_*(_c_**2 + _d_**2)*(n_ + 1)),
        module_name='4.3.4.2 (a+b tan)^m (c+d tan)^n (A+B tan+C tan^2)',
        rule_number=11,
    ),
    # Rule 12
    SymPyReplacementPattern(
        pattern=Int((a_ + _b_*InertTan(x*_f_ + _e_))**_m_*(_c_ + _d_*InertTan(x*_f_ + _e_))**_n_*(_A_ + _B_*InertTan(x*_f_ + _e_) + _C_*InertTan(x*_f_ + _e_)**2), x),
        constraints=(FreeQ([a_, _b_, _c_, _d_, _e_, _f_, _A_, _B_, _C_, _m_, _n_], x), NeQ(-a_*_d_ + _b_*_c_, 0), EqQ(a_**2 + _b_**2, 0), Not(LtQ(_m_, 0)), NeQ(_m_ + _n_ + 1, 0),),
        replacement=_C_*(a_ + _b_*tan(x*_f_ + _e_))**_m_*(_c_ + _d_*tan(x*_f_ + _e_))**(_n_ + 1)/(_d_*_f_*(_m_ + _n_ + 1)) + Int((a_ + _b_*tan(x*_f_ + _e_))**_m_*(_c_ + _d_*tan(x*_f_ + _e_))**_n_*Simp(_A_*_b_*_d_*(_m_ + _n_ + 1) + _C_*(a_*_c_*_m_ - _b_*_d_*(_n_ + 1)) - (-_B_*_b_*_d_*(_m_ + _n_ + 1) + _C_*_m_*(-a_*_d_ + _b_*_c_))*tan(x*_f_ + _e_), x), x)/(_b_*_d_*(_m_ + _n_ + 1)),
        module_name='4.3.4.2 (a+b tan)^m (c+d tan)^n (A+B tan+C tan^2)',
        rule_number=12,
    ),
    # Rule 13
    SymPyReplacementPattern(
        pattern=Int((_A_ + _C_*InertTan(x*_f_ + _e_)**2)*(a_ + _b_*InertTan(x*_f_ + _e_))**_m_*(_c_ + _d_*InertTan(x*_f_ + _e_))**_n_, x),
        constraints=(FreeQ([a_, _b_, _c_, _d_, _e_, _f_, _A_, _C_, _m_, _n_], x), NeQ(-a_*_d_ + _b_*_c_, 0), EqQ(a_**2 + _b_**2, 0), Not(LtQ(_m_, 0)), NeQ(_m_ + _n_ + 1, 0),),
        replacement=_C_*(a_ + _b_*tan(x*_f_ + _e_))**_m_*(_c_ + _d_*tan(x*_f_ + _e_))**(_n_ + 1)/(_d_*_f_*(_m_ + _n_ + 1)) + Int((a_ + _b_*tan(x*_f_ + _e_))**_m_*(_c_ + _d_*tan(x*_f_ + _e_))**_n_*Simp(_A_*_b_*_d_*(_m_ + _n_ + 1) - _C_*_m_*(-a_*_d_ + _b_*_c_)*tan(x*_f_ + _e_) + _C_*(a_*_c_*_m_ - _b_*_d_*(_n_ + 1)), x), x)/(_b_*_d_*(_m_ + _n_ + 1)),
        module_name='4.3.4.2 (a+b tan)^m (c+d tan)^n (A+B tan+C tan^2)',
        rule_number=13,
    ),
    # Rule 14
    SymPyReplacementPattern(
        pattern=Int((_a_ + _b_*InertTan(x*_f_ + _e_))**m_*(_c_ + _d_*InertTan(x*_f_ + _e_))**n_*(_A_ + _B_*InertTan(x*_f_ + _e_) + _C_*InertTan(x*_f_ + _e_)**2), x),
        constraints=(FreeQ([_a_, _b_, _c_, _d_, _e_, _f_, _A_, _B_, _C_], x), NeQ(-_a_*_d_ + _b_*_c_, 0), NeQ(_a_**2 + _b_**2, 0), NeQ(_c_**2 + _d_**2, 0), GtQ(m_, 0), LtQ(n_, -1),),
        replacement=-Int((_a_ + _b_*tan(x*_f_ + _e_))**(m_ - 1)*(_c_ + _d_*tan(x*_f_ + _e_))**(n_ + 1)*Simp(_A_*_d_*(-_a_*_c_*(n_ + 1) + _b_*_d_*m_) - _b_*(-_C_*(_c_**2*m_ - _d_**2*(n_ + 1)) + _d_*(-_A_*_d_ + _B_*_c_)*(m_ + n_ + 1))*tan(x*_f_ + _e_)**2 - _d_*(n_ + 1)*(_B_*(_a_*_c_ + _b_*_d_) + (_A_ - _C_)*(-_a_*_d_ + _b_*_c_))*tan(x*_f_ + _e_) + (-_B_*_d_ + _C_*_c_)*(_a_*_d_*(n_ + 1) + _b_*_c_*m_), x), x)/(_d_*(_c_**2 + _d_**2)*(n_ + 1)) + (_a_ + _b_*tan(x*_f_ + _e_))**m_*(_c_ + _d_*tan(x*_f_ + _e_))**(n_ + 1)*(_A_*_d_**2 + _c_*(-_B_*_d_ + _C_*_c_))/(_d_*_f_*(_c_**2 + _d_**2)*(n_ + 1)),
        module_name='4.3.4.2 (a+b tan)^m (c+d tan)^n (A+B tan+C tan^2)',
        rule_number=14,
    ),
    # Rule 15
    SymPyReplacementPattern(
        pattern=Int((_A_ + _C_*InertTan(x*_f_ + _e_)**2)*(_a_ + _b_*InertTan(x*_f_ + _e_))**m_*(_c_ + _d_*InertTan(x*_f_ + _e_))**n_, x),
        constraints=(FreeQ([_a_, _b_, _c_, _d_, _e_, _f_, _A_, _C_], x), NeQ(-_a_*_d_ + _b_*_c_, 0), NeQ(_a_**2 + _b_**2, 0), NeQ(_c_**2 + _d_**2, 0), GtQ(m_, 0), LtQ(n_, -1),),
        replacement=-Int((_a_ + _b_*tan(x*_f_ + _e_))**(m_ - 1)*(_c_ + _d_*tan(x*_f_ + _e_))**(n_ + 1)*Simp(_A_*_d_*(-_a_*_c_*(n_ + 1) + _b_*_d_*m_) + _C_*_c_*(_a_*_d_*(n_ + 1) + _b_*_c_*m_) + _b_*(_A_*_d_**2*(m_ + n_ + 1) + _C_*(_c_**2*m_ - _d_**2*(n_ + 1)))*tan(x*_f_ + _e_)**2 - _d_*(_A_ - _C_)*(n_ + 1)*(-_a_*_d_ + _b_*_c_)*tan(x*_f_ + _e_), x), x)/(_d_*(_c_**2 + _d_**2)*(n_ + 1)) + (_a_ + _b_*tan(x*_f_ + _e_))**m_*(_c_ + _d_*tan(x*_f_ + _e_))**(n_ + 1)*(_A_*_d_**2 + _C_*_c_**2)/(_d_*_f_*(_c_**2 + _d_**2)*(n_ + 1)),
        module_name='4.3.4.2 (a+b tan)^m (c+d tan)^n (A+B tan+C tan^2)',
        rule_number=15,
    ),
    # Rule 16
    SymPyReplacementPattern(
        pattern=Int((_a_ + _b_*InertTan(x*_f_ + _e_))**_m_*(_c_ + _d_*InertTan(x*_f_ + _e_))**n_*(_A_ + _B_*InertTan(x*_f_ + _e_) + _C_*InertTan(x*_f_ + _e_)**2), x),
        constraints=(FreeQ([_a_, _b_, _c_, _d_, _e_, _f_, _A_, _B_, _C_, n_], x), NeQ(-_a_*_d_ + _b_*_c_, 0), NeQ(_a_**2 + _b_**2, 0), NeQ(_c_**2 + _d_**2, 0), GtQ(_m_, 0), Not(And(IGtQ(n_, 0), Or(Not(IntegerQ(_m_)), And(EqQ(_c_, 0), NeQ(_a_, 0))))),),
        replacement=_C_*(_a_ + _b_*tan(x*_f_ + _e_))**_m_*(_c_ + _d_*tan(x*_f_ + _e_))**(n_ + 1)/(_d_*_f_*(_m_ + n_ + 1)) + Int((_a_ + _b_*tan(x*_f_ + _e_))**(_m_ - 1)*(_c_ + _d_*tan(x*_f_ + _e_))**n_*Simp(_A_*_a_*_d_*(_m_ + n_ + 1) - _C_*(_a_*_d_*(n_ + 1) + _b_*_c_*_m_) + _d_*(_m_ + n_ + 1)*(_A_*_b_ + _B_*_a_ - _C_*_b_)*tan(x*_f_ + _e_) - (-_B_*_b_*_d_*(_m_ + n_ + 1) + _C_*_m_*(-_a_*_d_ + _b_*_c_))*tan(x*_f_ + _e_)**2, x), x)/(_d_*(_m_ + n_ + 1)),
        module_name='4.3.4.2 (a+b tan)^m (c+d tan)^n (A+B tan+C tan^2)',
        rule_number=16,
    ),
    # Rule 17
    SymPyReplacementPattern(
        pattern=Int((_A_ + _C_*InertTan(x*_f_ + _e_)**2)*(_a_ + _b_*InertTan(x*_f_ + _e_))**_m_*(_c_ + _d_*InertTan(x*_f_ + _e_))**n_, x),
        constraints=(FreeQ([_a_, _b_, _c_, _d_, _e_, _f_, _A_, _C_, n_], x), NeQ(-_a_*_d_ + _b_*_c_, 0), NeQ(_a_**2 + _b_**2, 0), NeQ(_c_**2 + _d_**2, 0), GtQ(_m_, 0), Not(And(IGtQ(n_, 0), Or(Not(IntegerQ(_m_)), And(EqQ(_c_, 0), NeQ(_a_, 0))))),),
        replacement=_C_*(_a_ + _b_*tan(x*_f_ + _e_))**_m_*(_c_ + _d_*tan(x*_f_ + _e_))**(n_ + 1)/(_d_*_f_*(_m_ + n_ + 1)) + Int((_a_ + _b_*tan(x*_f_ + _e_))**(_m_ - 1)*(_c_ + _d_*tan(x*_f_ + _e_))**n_*Simp(_A_*_a_*_d_*(_m_ + n_ + 1) - _C_*_m_*(-_a_*_d_ + _b_*_c_)*tan(x*_f_ + _e_)**2 - _C_*(_a_*_d_*(n_ + 1) + _b_*_c_*_m_) + _d_*(_A_*_b_ - _C_*_b_)*(_m_ + n_ + 1)*tan(x*_f_ + _e_), x), x)/(_d_*(_m_ + n_ + 1)),
        module_name='4.3.4.2 (a+b tan)^m (c+d tan)^n (A+B tan+C tan^2)',
        rule_number=17,
    ),
    # Rule 18
    SymPyReplacementPattern(
        pattern=Int((_a_ + _b_*InertTan(x*_f_ + _e_))**m_*(_c_ + _d_*InertTan(x*_f_ + _e_))**n_*(_A_ + _B_*InertTan(x*_f_ + _e_) + _C_*InertTan(x*_f_ + _e_)**2), x),
        constraints=(FreeQ([_a_, _b_, _c_, _d_, _e_, _f_, _A_, _B_, _C_, n_], x), NeQ(-_a_*_d_ + _b_*_c_, 0), NeQ(_a_**2 + _b_**2, 0), NeQ(_c_**2 + _d_**2, 0), LtQ(m_, -1), Not(And(ILtQ(n_, -1), Or(Not(IntegerQ(m_)), And(EqQ(_c_, 0), NeQ(_a_, 0))))),),
        replacement=Int((_a_ + _b_*tan(x*_f_ + _e_))**(m_ + 1)*(_c_ + _d_*tan(x*_f_ + _e_))**n_*Simp(_A_*(_a_*(m_ + 1)*(-_a_*_d_ + _b_*_c_) - _b_**2*_d_*(m_ + n_ + 2)) - _d_*(_A_*_b_**2 - _a_*(_B_*_b_ - _C_*_a_))*(m_ + n_ + 2)*tan(x*_f_ + _e_)**2 - (m_ + 1)*(-_a_*_d_ + _b_*_c_)*(_A_*_b_ - _B_*_a_ - _C_*_b_)*tan(x*_f_ + _e_) + (_B_*_b_ - _C_*_a_)*(_a_*_d_*(n_ + 1) + _b_*_c_*(m_ + 1)), x), x)/((_a_**2 + _b_**2)*(m_ + 1)*(-_a_*_d_ + _b_*_c_)) + (_a_ + _b_*tan(x*_f_ + _e_))**(m_ + 1)*(_c_ + _d_*tan(x*_f_ + _e_))**(n_ + 1)*(_A_*_b_**2 - _a_*(_B_*_b_ - _C_*_a_))/(_f_*(_a_**2 + _b_**2)*(m_ + 1)*(-_a_*_d_ + _b_*_c_)),
        module_name='4.3.4.2 (a+b tan)^m (c+d tan)^n (A+B tan+C tan^2)',
        rule_number=18,
    ),
    # Rule 19
    SymPyReplacementPattern(
        pattern=Int((_A_ + _C_*InertTan(x*_f_ + _e_)**2)*(_a_ + _b_*InertTan(x*_f_ + _e_))**m_*(_c_ + _d_*InertTan(x*_f_ + _e_))**n_, x),
        constraints=(FreeQ([_a_, _b_, _c_, _d_, _e_, _f_, _A_, _C_, n_], x), NeQ(-_a_*_d_ + _b_*_c_, 0), NeQ(_a_**2 + _b_**2, 0), NeQ(_c_**2 + _d_**2, 0), LtQ(m_, -1), Not(And(ILtQ(n_, -1), Or(Not(IntegerQ(m_)), And(EqQ(_c_, 0), NeQ(_a_, 0))))),),
        replacement=Int((_a_ + _b_*tan(x*_f_ + _e_))**(m_ + 1)*(_c_ + _d_*tan(x*_f_ + _e_))**n_*Simp(_A_*(_a_*(m_ + 1)*(-_a_*_d_ + _b_*_c_) - _b_**2*_d_*(m_ + n_ + 2)) - _C_*_a_*(_a_*_d_*(n_ + 1) + _b_*_c_*(m_ + 1)) - _d_*(_A_*_b_**2 + _C_*_a_**2)*(m_ + n_ + 2)*tan(x*_f_ + _e_)**2 - (m_ + 1)*(_A_*_b_ - _C_*_b_)*(-_a_*_d_ + _b_*_c_)*tan(x*_f_ + _e_), x), x)/((_a_**2 + _b_**2)*(m_ + 1)*(-_a_*_d_ + _b_*_c_)) + (_a_ + _b_*tan(x*_f_ + _e_))**(m_ + 1)*(_c_ + _d_*tan(x*_f_ + _e_))**(n_ + 1)*(_A_*_b_**2 + _C_*_a_**2)/(_f_*(_a_**2 + _b_**2)*(m_ + 1)*(-_a_*_d_ + _b_*_c_)),
        module_name='4.3.4.2 (a+b tan)^m (c+d tan)^n (A+B tan+C tan^2)',
        rule_number=19,
    ),
    # Rule 20
    SymPyReplacementPattern(
        pattern=Int((_A_ + _B_*InertTan(x*_f_ + _e_) + _C_*InertTan(x*_f_ + _e_)**2)/((a_ + _b_*InertTan(x*_f_ + _e_))*(_c_ + _d_*InertTan(x*_f_ + _e_))), x),
        constraints=(FreeQ([a_, _b_, _c_, _d_, _e_, _f_, _A_, _B_, _C_], x), NeQ(-a_*_d_ + _b_*_c_, 0), NeQ(a_**2 + _b_**2, 0), NeQ(_c_**2 + _d_**2, 0),),
        replacement=x*(a_*(_A_*_c_ + _B_*_d_ - _C_*_c_) + _b_*(-_A_*_d_ + _B_*_c_ + _C_*_d_))/((a_**2 + _b_**2)*(_c_**2 + _d_**2)) - (_A_*_d_**2 - _B_*_c_*_d_ + _C_*_c_**2)*Int((-_c_*tan(x*_f_ + _e_) + _d_)/(_c_ + _d_*tan(x*_f_ + _e_)), x)/((_c_**2 + _d_**2)*(-a_*_d_ + _b_*_c_)) + (_A_*_b_**2 - _B_*a_*_b_ + _C_*a_**2)*Int((-a_*tan(x*_f_ + _e_) + _b_)/(a_ + _b_*tan(x*_f_ + _e_)), x)/((a_**2 + _b_**2)*(-a_*_d_ + _b_*_c_)),
        module_name='4.3.4.2 (a+b tan)^m (c+d tan)^n (A+B tan+C tan^2)',
        rule_number=20,
    ),
    # Rule 21
    SymPyReplacementPattern(
        pattern=Int((_A_ + _C_*InertTan(x*_f_ + _e_)**2)/((a_ + _b_*InertTan(x*_f_ + _e_))*(_c_ + _d_*InertTan(x*_f_ + _e_))), x),
        constraints=(FreeQ([a_, _b_, _c_, _d_, _e_, _f_, _A_, _C_], x), NeQ(-a_*_d_ + _b_*_c_, 0), NeQ(a_**2 + _b_**2, 0), NeQ(_c_**2 + _d_**2, 0),),
        replacement=x*(a_*(_A_*_c_ - _C_*_c_) - _b_*(_A_*_d_ - _C_*_d_))/((a_**2 + _b_**2)*(_c_**2 + _d_**2)) - (_A_*_d_**2 + _C_*_c_**2)*Int((-_c_*tan(x*_f_ + _e_) + _d_)/(_c_ + _d_*tan(x*_f_ + _e_)), x)/((_c_**2 + _d_**2)*(-a_*_d_ + _b_*_c_)) + (_A_*_b_**2 + _C_*a_**2)*Int((-a_*tan(x*_f_ + _e_) + _b_)/(a_ + _b_*tan(x*_f_ + _e_)), x)/((a_**2 + _b_**2)*(-a_*_d_ + _b_*_c_)),
        module_name='4.3.4.2 (a+b tan)^m (c+d tan)^n (A+B tan+C tan^2)',
        rule_number=21,
    ),
    # Rule 22
    SymPyReplacementPattern(
        pattern=Int((_c_ + _d_*InertTan(x*_f_ + _e_))**n_*(_A_ + _B_*InertTan(x*_f_ + _e_) + _C_*InertTan(x*_f_ + _e_)**2)/(_a_ + _b_*InertTan(x*_f_ + _e_)), x),
        constraints=(FreeQ([_a_, _b_, _c_, _d_, _e_, _f_, _A_, _B_, _C_, n_], x), NeQ(-_a_*_d_ + _b_*_c_, 0), NeQ(_a_**2 + _b_**2, 0), NeQ(_c_**2 + _d_**2, 0), Not(GtQ(n_, 0)), Not(LeQ(n_, -1)),),
        replacement=(_A_*_b_**2 - _B_*_a_*_b_ + _C_*_a_**2)*Int((_c_ + _d_*tan(x*_f_ + _e_))**n_*(tan(x*_f_ + _e_)**2 + 1)/(_a_ + _b_*tan(x*_f_ + _e_)), x)/(_a_**2 + _b_**2) + Int((_c_ + _d_*tan(x*_f_ + _e_))**n_*Simp(_B_*_b_ + _a_*(_A_ - _C_) + (_B_*_a_ - _b_*(_A_ - _C_))*tan(x*_f_ + _e_), x), x)/(_a_**2 + _b_**2),
        module_name='4.3.4.2 (a+b tan)^m (c+d tan)^n (A+B tan+C tan^2)',
        rule_number=22,
    ),
    # Rule 23
    SymPyReplacementPattern(
        pattern=Int((_A_ + _C_*InertTan(x*_f_ + _e_)**2)*(_c_ + _d_*InertTan(x*_f_ + _e_))**n_/(_a_ + _b_*InertTan(x*_f_ + _e_)), x),
        constraints=(FreeQ([_a_, _b_, _c_, _d_, _e_, _f_, _A_, _C_, n_], x), NeQ(-_a_*_d_ + _b_*_c_, 0), NeQ(_a_**2 + _b_**2, 0), NeQ(_c_**2 + _d_**2, 0), Not(GtQ(n_, 0)), Not(LeQ(n_, -1)),),
        replacement=(_A_*_b_**2 + _C_*_a_**2)*Int((_c_ + _d_*tan(x*_f_ + _e_))**n_*(tan(x*_f_ + _e_)**2 + 1)/(_a_ + _b_*tan(x*_f_ + _e_)), x)/(_a_**2 + _b_**2) + Int((_c_ + _d_*tan(x*_f_ + _e_))**n_*Simp(_a_*(_A_ - _C_) - (_A_*_b_ - _C_*_b_)*tan(x*_f_ + _e_), x), x)/(_a_**2 + _b_**2),
        module_name='4.3.4.2 (a+b tan)^m (c+d tan)^n (A+B tan+C tan^2)',
        rule_number=23,
    ),
    # Rule 24
    SymPyReplacementPattern(
        pattern=Int((_a_ + _b_*InertTan(x*_f_ + _e_))**m_*(_c_ + _d_*InertTan(x*_f_ + _e_))**n_*(_A_ + _B_*InertTan(x*_f_ + _e_) + _C_*InertTan(x*_f_ + _e_)**2), x),
        constraints=(FreeQ([_a_, _b_, _c_, _d_, _e_, _f_, _A_, _B_, _C_, m_, n_], x), NeQ(-_a_*_d_ + _b_*_c_, 0), NeQ(_a_**2 + _b_**2, 0), NeQ(_c_**2 + _d_**2, 0),),
        replacement=With({ff: FreeFactors(tan(x*_f_ + _e_), x)}, ff*Subst(Int((ff*x*_b_ + _a_)**m_*(ff*x*_d_ + _c_)**n_*(ff**2*x**2*_C_ + ff*x*_B_ + _A_)/(ff**2*x**2 + 1), x), x, tan(x*_f_ + _e_)/ff)/_f_),
        module_name='4.3.4.2 (a+b tan)^m (c+d tan)^n (A+B tan+C tan^2)',
        rule_number=24,
    ),
    # Rule 25
    SymPyReplacementPattern(
        pattern=Int((_A_ + _C_*InertTan(x*_f_ + _e_)**2)*(_a_ + _b_*InertTan(x*_f_ + _e_))**m_*(_c_ + _d_*InertTan(x*_f_ + _e_))**n_, x),
        constraints=(FreeQ([_a_, _b_, _c_, _d_, _e_, _f_, _A_, _C_, m_, n_], x), NeQ(-_a_*_d_ + _b_*_c_, 0), NeQ(_a_**2 + _b_**2, 0), NeQ(_c_**2 + _d_**2, 0),),
        replacement=With({ff: FreeFactors(tan(x*_f_ + _e_), x)}, ff*Subst(Int((ff*x*_b_ + _a_)**m_*(ff*x*_d_ + _c_)**n_*(ff**2*x**2*_C_ + _A_)/(ff**2*x**2 + 1), x), x, tan(x*_f_ + _e_)/ff)/_f_),
        module_name='4.3.4.2 (a+b tan)^m (c+d tan)^n (A+B tan+C tan^2)',
        rule_number=25,
    ),

]

# Summary: 25 rules translated, 0 skipped
