# -*- coding: utf-8 -*-
# =============================================================================
# !! AUTO-GENERATED FILE -- DO NOT EDIT !!
#
# Generated by: rubi_integrate/codegen/generate.py
# Source: 4.3.1.2 (d sec)^m (a+b tan)^n.m
# Module: 4.3.1.2 (d sec)^m (a+b tan)^n
#
# This file contains Rubi integration rules as SymPyReplacementPattern objects.
# Re-run the generator to update.
# =============================================================================
import sympy
from sympy import Symbol
from rubi_integrate.utils.rubi_utils import *  # bare-name access; sympy imports below override any conflicts (e.g. Not)
from sympy.logic.boolalg import Or, Not, And
from sympy import (
    atanh, cos, sec, sin, sqrt, tan,
)

from sympy_matching.wild import WildSymbol, IDENTITY_ELEMENT
from rubi_integrate.base_objects import Int, SymPyReplacementPattern
# Inert trig markers (Rubi's lowercase sin/cos/... patterns). Distinct opaque heads,
# NOT subclasses of sympy.sin -- see rubi-trig-deactivation-dispatch project note.
from rubi_integrate.utils.inert_functions import (
    InertCos, InertTan, InertSec)
from rubi_integrate.utils import (
    # Wolfram standard constraints
    FreeQ, IntegerQ, EqQ, NeQ, IGtQ, ILtQ, GtQ, LtQ, LeQ, IntegersQ, RationalQ,
)

# --- Integration variable ---
x = Symbol('x')

# --- Rubi global option stubs (default False/placeholder) ---
UseGamma = sympy.Symbol('UseGamma')  # Rubi global option; treated as False in Python
u = Symbol('u')  # Generic integrand placeholder used in some Rubi constraint calls

# --- Rubi selector symbols ---
# Rubi passes Min/Max as bare SYMBOLS, not calls: Expon[Px, x, Min] selects the
# minimum exponent. The code emitter round-trips through SymPy's printer, which
# renders Symbol('Min') as the bare name `Min`, so the name must exist here.
# (A genuine Min[a, b] call is emitted qualified, as sympy.Min(...), so these
# bindings cannot shadow it.)
Min = Symbol('Min')
Max = Symbol('Max')

# --- Wildcard symbols ---
# dot wildcards (must match exactly one expression)
# optional wildcards (can match identity element if absent in commutative ops)

a_ = WildSymbol('a')
_b_ = WildSymbol('b', optional_value=IDENTITY_ELEMENT)
b_ = WildSymbol('b')
_d_ = WildSymbol('d', optional_value=IDENTITY_ELEMENT)
d_ = WildSymbol('d')
_e_ = WildSymbol('e', optional_value=IDENTITY_ELEMENT)
e_ = WildSymbol('e')
_f_ = WildSymbol('f', optional_value=IDENTITY_ELEMENT)
f_ = WildSymbol('f')
_m_ = WildSymbol('m', optional_value=IDENTITY_ELEMENT)
m_ = WildSymbol('m')
_n_ = WildSymbol('n', optional_value=IDENTITY_ELEMENT)
n_ = WildSymbol('n')

RULES = [
    # Rule 1
    SymPyReplacementPattern(
        pattern=Int((_d_*InertSec(x*_f_ + _e_))**_m_*(a_ + _b_*InertTan(x*_f_ + _e_)), x),
        constraints=(FreeQ([a_, _b_, _d_, _e_, _f_, _m_], x), Or(IntegerQ(2*_m_), NeQ(a_**2 + _b_**2, 0)),),
        replacement=a_*Int((_d_*sec(x*_f_ + _e_))**_m_, x) + _b_*(_d_*sec(x*_f_ + _e_))**_m_/(_f_*_m_),
        module_name='4.3.1.2 (d sec)^m (a+b tan)^n',
        rule_number=1,
    ),
    # Rule 2
    SymPyReplacementPattern(
        pattern=Int((a_ + _b_*InertTan(x*_f_ + _e_))**n_*InertSec(x*_f_ + _e_)**m_, x),
        constraints=(FreeQ([a_, _b_, _e_, _f_, n_], x), EqQ(a_**2 + _b_**2, 0), IntegerQ(m_/2),),
        replacement=a_**(2 - m_)*Subst(Int((-x + a_)**(m_/2 - 1)*(x + a_)**(m_/2 + n_ - 1), x), x, _b_*tan(x*_f_ + _e_))/(_b_*_f_),
        module_name='4.3.1.2 (d sec)^m (a+b tan)^n',
        rule_number=2,
    ),
    # Rule 3
    SymPyReplacementPattern(
        pattern=Int((_d_*InertSec(x*_f_ + _e_))**_m_*(a_ + _b_*InertTan(x*_f_ + _e_))**n_, x),
        constraints=(FreeQ([a_, _b_, _d_, _e_, _f_, _m_, n_], x), EqQ(a_**2 + _b_**2, 0), EqQ(Simplify(_m_ + n_), 0),),
        replacement=_b_*(_d_*sec(x*_f_ + _e_))**_m_*(a_ + _b_*tan(x*_f_ + _e_))**n_/(a_*_f_*_m_),
        module_name='4.3.1.2 (d sec)^m (a+b tan)^n',
        rule_number=3,
    ),
    # Rule 4
    SymPyReplacementPattern(
        pattern=Int(InertSec(x*_f_ + _e_)/sqrt(a_ + _b_*InertTan(x*_f_ + _e_)), x),
        constraints=(FreeQ([a_, _b_, _e_, _f_], x), EqQ(a_**2 + _b_**2, 0),),
        replacement=-2*a_*Subst(Int(1/(-x**2*a_ + 2), x), x, sec(x*_f_ + _e_)/sqrt(a_ + _b_*tan(x*_f_ + _e_)))/(_b_*_f_),
        module_name='4.3.1.2 (d sec)^m (a+b tan)^n',
        rule_number=4,
    ),
    # Rule 5
    SymPyReplacementPattern(
        pattern=Int((_d_*InertSec(x*_f_ + _e_))**_m_*(a_ + _b_*InertTan(x*_f_ + _e_))**n_, x),
        constraints=(FreeQ([a_, _b_, _d_, _e_, _f_], x), EqQ(a_**2 + _b_**2, 0), EqQ(_m_/2 + n_, 0), GtQ(n_, 0),),
        replacement=a_*Int((_d_*sec(x*_f_ + _e_))**(_m_ + 2)*(a_ + _b_*tan(x*_f_ + _e_))**(n_ - 1), x)/(2*_d_**2) + _b_*(_d_*sec(x*_f_ + _e_))**_m_*(a_ + _b_*tan(x*_f_ + _e_))**n_/(a_*_f_*_m_),
        module_name='4.3.1.2 (d sec)^m (a+b tan)^n',
        rule_number=5,
    ),
    # Rule 6
    SymPyReplacementPattern(
        pattern=Int((_d_*InertSec(x*_f_ + _e_))**_m_*(a_ + _b_*InertTan(x*_f_ + _e_))**n_, x),
        constraints=(FreeQ([a_, _b_, _d_, _e_, _f_], x), EqQ(a_**2 + _b_**2, 0), EqQ(_m_/2 + n_, 0), LtQ(n_, -1),),
        replacement=2*_d_**2*(_d_*sec(x*_f_ + _e_))**(_m_ - 2)*(a_ + _b_*tan(x*_f_ + _e_))**(n_ + 1)/(_b_*_f_*(_m_ - 2)) + 2*_d_**2*Int((_d_*sec(x*_f_ + _e_))**(_m_ - 2)*(a_ + _b_*tan(x*_f_ + _e_))**(n_ + 1), x)/a_,
        module_name='4.3.1.2 (d sec)^m (a+b tan)^n',
        rule_number=6,
    ),
    # Rule 7
    SymPyReplacementPattern(
        pattern=Int((_d_*InertSec(x*_f_ + _e_))**m_*(a_ + _b_*InertTan(x*_f_ + _e_))**n_, x),
        constraints=(FreeQ([a_, _b_, _d_, _e_, _f_, m_, n_], x), EqQ(a_**2 + _b_**2, 0), EqQ(Simplify(m_/2 + n_), 0),),
        replacement=(a_/_d_)**(2*IntPart(n_))*(a_ - _b_*tan(x*_f_ + _e_))**FracPart(n_)*(a_ + _b_*tan(x*_f_ + _e_))**FracPart(n_)*Int((a_ - _b_*tan(x*_f_ + _e_))**(-n_), x)/(_d_*sec(x*_f_ + _e_))**(2*FracPart(n_)),
        module_name='4.3.1.2 (d sec)^m (a+b tan)^n',
        rule_number=7,
    ),
    # Rule 8
    SymPyReplacementPattern(
        pattern=Int((_d_*InertSec(x*_f_ + _e_))**_m_*(a_ + _b_*InertTan(x*_f_ + _e_))**n_, x),
        constraints=(FreeQ([a_, _b_, _d_, _e_, _f_, _m_, n_], x), EqQ(a_**2 + _b_**2, 0), EqQ(Simplify(_m_/2 + n_ - 1), 0),),
        replacement=2*_b_*(_d_*sec(x*_f_ + _e_))**_m_*(a_ + _b_*tan(x*_f_ + _e_))**(n_ - 1)/(_f_*_m_),
        module_name='4.3.1.2 (d sec)^m (a+b tan)^n',
        rule_number=8,
    ),
    # Rule 9
    SymPyReplacementPattern(
        pattern=Int((_d_*InertSec(x*_f_ + _e_))**_m_*(a_ + _b_*InertTan(x*_f_ + _e_))**n_, x),
        constraints=(FreeQ([a_, _b_, _d_, _e_, _f_, _m_, n_], x), EqQ(a_**2 + _b_**2, 0), IGtQ(Simplify(_m_/2 + n_ - 1), 0), Not(IntegerQ(n_)),),
        replacement=a_*(_m_ + 2*n_ - 2)*Int((_d_*sec(x*_f_ + _e_))**_m_*(a_ + _b_*tan(x*_f_ + _e_))**(n_ - 1), x)/(_m_ + n_ - 1) + _b_*(_d_*sec(x*_f_ + _e_))**_m_*(a_ + _b_*tan(x*_f_ + _e_))**(n_ - 1)/(_f_*(_m_ + n_ - 1)),
        module_name='4.3.1.2 (d sec)^m (a+b tan)^n',
        rule_number=9,
    ),
    # Rule 10
    SymPyReplacementPattern(
        pattern=Int(sqrt(_d_*InertSec(x*_f_ + _e_))*sqrt(a_ + _b_*InertTan(x*_f_ + _e_)), x),
        constraints=(FreeQ([a_, _b_, _d_, _e_, _f_], x), EqQ(a_**2 + _b_**2, 0),),
        replacement=-4*_b_*_d_**2*Subst(Int(x**2/(x**4*_d_**2 + a_**2), x), x, sqrt(a_ + _b_*tan(x*_f_ + _e_))/sqrt(_d_*sec(x*_f_ + _e_)))/_f_,
        module_name='4.3.1.2 (d sec)^m (a+b tan)^n',
        rule_number=10,
    ),
    # Rule 11
    SymPyReplacementPattern(
        pattern=Int((_d_*InertSec(x*_f_ + _e_))**m_*(a_ + _b_*InertTan(x*_f_ + _e_))**n_, x),
        constraints=(FreeQ([a_, _b_, _d_, _e_, _f_], x), EqQ(a_**2 + _b_**2, 0), GtQ(n_, 1), Or(And(IGtQ(n_/2, 0), ILtQ(m_ + sympy.S(-1)/2, 0)), And(EqQ(n_, 2), LtQ(m_, 0)), And(LeQ(m_, -1), GtQ(m_ + n_, 0)), And(ILtQ(m_, 0), LtQ(m_/2 + n_ - 1, 0), IntegerQ(n_)), And(EqQ(n_, sympy.S(3)/2), EqQ(m_, sympy.S(-1)/2))), IntegerQ(2*m_),),
        replacement=-_b_**2*(m_ + 2*n_ - 2)*Int((_d_*sec(x*_f_ + _e_))**(m_ + 2)*(a_ + _b_*tan(x*_f_ + _e_))**(n_ - 2), x)/(_d_**2*m_) + 2*_b_*(_d_*sec(x*_f_ + _e_))**m_*(a_ + _b_*tan(x*_f_ + _e_))**(n_ - 1)/(_f_*m_),
        module_name='4.3.1.2 (d sec)^m (a+b tan)^n',
        rule_number=11,
    ),
    # Rule 12
    SymPyReplacementPattern(
        pattern=Int((_d_*InertSec(x*_f_ + _e_))**m_*(a_ + _b_*InertTan(x*_f_ + _e_))**n_, x),
        constraints=(FreeQ([a_, _b_, _d_, _e_, _f_], x), EqQ(a_**2 + _b_**2, 0), GtQ(n_, 0), LtQ(m_, -1), IntegersQ(2*m_, 2*n_),),
        replacement=a_*(m_ + n_)*Int((_d_*sec(x*_f_ + _e_))**(m_ + 2)*(a_ + _b_*tan(x*_f_ + _e_))**(n_ - 1), x)/(_d_**2*m_) + _b_*(_d_*sec(x*_f_ + _e_))**m_*(a_ + _b_*tan(x*_f_ + _e_))**n_/(a_*_f_*m_),
        module_name='4.3.1.2 (d sec)^m (a+b tan)^n',
        rule_number=12,
    ),
    # Rule 13
    SymPyReplacementPattern(
        pattern=Int((_d_*InertSec(x*_f_ + _e_))**_m_*(a_ + _b_*InertTan(x*_f_ + _e_))**n_, x),
        constraints=(FreeQ([a_, _b_, _d_, _e_, _f_, _m_], x), EqQ(a_**2 + _b_**2, 0), GtQ(n_, 0), NeQ(_m_ + n_ - 1, 0), IntegersQ(2*_m_, 2*n_),),
        replacement=a_*(_m_ + 2*n_ - 2)*Int((_d_*sec(x*_f_ + _e_))**_m_*(a_ + _b_*tan(x*_f_ + _e_))**(n_ - 1), x)/(_m_ + n_ - 1) + _b_*(_d_*sec(x*_f_ + _e_))**_m_*(a_ + _b_*tan(x*_f_ + _e_))**(n_ - 1)/(_f_*(_m_ + n_ - 1)),
        module_name='4.3.1.2 (d sec)^m (a+b tan)^n',
        rule_number=13,
    ),
    # Rule 14
    SymPyReplacementPattern(
        pattern=Int((_d_*InertSec(x*_f_ + _e_))**(sympy.S(3)/2)/sqrt(a_ + _b_*InertTan(x*_f_ + _e_)), x),
        constraints=(FreeQ([a_, _b_, _d_, _e_, _f_], x), EqQ(a_**2 + _b_**2, 0),),
        replacement=_d_*Int(sqrt(_d_*sec(x*_f_ + _e_))*sqrt(a_ - _b_*tan(x*_f_ + _e_)), x)*sec(x*_f_ + _e_)/(sqrt(a_ - _b_*tan(x*_f_ + _e_))*sqrt(a_ + _b_*tan(x*_f_ + _e_))),
        module_name='4.3.1.2 (d sec)^m (a+b tan)^n',
        rule_number=14,
    ),
    # Rule 15
    SymPyReplacementPattern(
        pattern=Int((_d_*InertSec(x*_f_ + _e_))**m_*(a_ + _b_*InertTan(x*_f_ + _e_))**n_, x),
        constraints=(FreeQ([a_, _b_, _d_, _e_, _f_, m_], x), EqQ(a_**2 + _b_**2, 0), LtQ(n_, -1), Or(And(ILtQ(n_/2, 0), IGtQ(m_ + sympy.S(-1)/2, 0)), EqQ(n_, -2), IGtQ(m_ + n_, 0), And(IntegersQ(n_, m_ + sympy.S.Half), GtQ(2*m_ + n_ + 1, 0))), IntegerQ(2*m_),),
        replacement=2*_d_**2*(_d_*sec(x*_f_ + _e_))**(m_ - 2)*(a_ + _b_*tan(x*_f_ + _e_))**(n_ + 1)/(_b_*_f_*(m_ + 2*n_)) - _d_**2*(m_ - 2)*Int((_d_*sec(x*_f_ + _e_))**(m_ - 2)*(a_ + _b_*tan(x*_f_ + _e_))**(n_ + 2), x)/(_b_**2*(m_ + 2*n_)),
        module_name='4.3.1.2 (d sec)^m (a+b tan)^n',
        rule_number=15,
    ),
    # Rule 16
    SymPyReplacementPattern(
        pattern=Int((_d_*InertSec(x*_f_ + _e_))**_m_*(a_ + _b_*InertTan(x*_f_ + _e_))**n_, x),
        constraints=(FreeQ([a_, _b_, _d_, _e_, _f_], x), EqQ(a_**2 + _b_**2, 0), LtQ(n_, 0), GtQ(_m_, 1), Not(ILtQ(_m_ + n_, 0)), NeQ(_m_ + n_ - 1, 0), IntegersQ(2*_m_, 2*n_),),
        replacement=_d_**2*(_d_*sec(x*_f_ + _e_))**(_m_ - 2)*(a_ + _b_*tan(x*_f_ + _e_))**(n_ + 1)/(_b_*_f_*(_m_ + n_ - 1)) + _d_**2*(_m_ - 2)*Int((_d_*sec(x*_f_ + _e_))**(_m_ - 2)*(a_ + _b_*tan(x*_f_ + _e_))**(n_ + 1), x)/(a_*(_m_ + n_ - 1)),
        module_name='4.3.1.2 (d sec)^m (a+b tan)^n',
        rule_number=16,
    ),
    # Rule 17
    SymPyReplacementPattern(
        pattern=Int((_d_*InertSec(x*_f_ + _e_))**_m_*(a_ + _b_*InertTan(x*_f_ + _e_))**n_, x),
        constraints=(FreeQ([a_, _b_, _d_, _e_, _f_, _m_], x), EqQ(a_**2 + _b_**2, 0), LtQ(n_, 0), NeQ(_m_ + 2*n_, 0), IntegersQ(2*_m_, 2*n_),),
        replacement=a_*(_d_*sec(x*_f_ + _e_))**_m_*(a_ + _b_*tan(x*_f_ + _e_))**n_/(_b_*_f_*(_m_ + 2*n_)) + Int((_d_*sec(x*_f_ + _e_))**_m_*(a_ + _b_*tan(x*_f_ + _e_))**(n_ + 1), x)*Simplify(_m_ + n_)/(a_*(_m_ + 2*n_)),
        module_name='4.3.1.2 (d sec)^m (a+b tan)^n',
        rule_number=17,
    ),
    # Rule 18
    SymPyReplacementPattern(
        pattern=Int((_d_*InertSec(x*_f_ + _e_))**_m_*(a_ + _b_*InertTan(x*_f_ + _e_))**n_, x),
        constraints=(FreeQ([a_, _b_, _d_, _e_, _f_, _m_, n_], x), EqQ(a_**2 + _b_**2, 0), IGtQ(Simplify(_m_ + n_ - 1), 0), RationalQ(n_),),
        replacement=a_*(_m_ + 2*n_ - 2)*Int((_d_*sec(x*_f_ + _e_))**_m_*(a_ + _b_*tan(x*_f_ + _e_))**(n_ - 1), x)/Simplify(_m_ + n_ - 1) + _b_*(_d_*sec(x*_f_ + _e_))**_m_*(a_ + _b_*tan(x*_f_ + _e_))**(n_ - 1)/(_f_*Simplify(_m_ + n_ - 1)),
        module_name='4.3.1.2 (d sec)^m (a+b tan)^n',
        rule_number=18,
    ),
    # Rule 19
    SymPyReplacementPattern(
        pattern=Int((_d_*InertSec(x*_f_ + _e_))**_m_*(a_ + _b_*InertTan(x*_f_ + _e_))**n_, x),
        constraints=(FreeQ([a_, _b_, _d_, _e_, _f_, _m_, n_], x), EqQ(a_**2 + _b_**2, 0), ILtQ(Simplify(_m_ + n_), 0), NeQ(_m_ + 2*n_, 0),),
        replacement=a_*(_d_*sec(x*_f_ + _e_))**_m_*(a_ + _b_*tan(x*_f_ + _e_))**n_/(_b_*_f_*(_m_ + 2*n_)) + Int((_d_*sec(x*_f_ + _e_))**_m_*(a_ + _b_*tan(x*_f_ + _e_))**(n_ + 1), x)*Simplify(_m_ + n_)/(a_*(_m_ + 2*n_)),
        module_name='4.3.1.2 (d sec)^m (a+b tan)^n',
        rule_number=19,
    ),
    # Rule 20
    SymPyReplacementPattern(
        pattern=Int((_d_*InertSec(x*_f_ + _e_))**_m_*(a_ + _b_*InertTan(x*_f_ + _e_))**_n_, x),
        constraints=(FreeQ([a_, _b_, _d_, _e_, _f_, _m_, _n_], x), EqQ(a_**2 + _b_**2, 0),),
        replacement=(_d_*sec(x*_f_ + _e_))**_m_*Int((a_ - _b_*tan(x*_f_ + _e_))**(_m_/2)*(a_ + _b_*tan(x*_f_ + _e_))**(_m_/2 + _n_), x)/((a_ - _b_*tan(x*_f_ + _e_))**(_m_/2)*(a_ + _b_*tan(x*_f_ + _e_))**(_m_/2)),
        module_name='4.3.1.2 (d sec)^m (a+b tan)^n',
        rule_number=20,
    ),
    # Rule 21
    SymPyReplacementPattern(
        pattern=Int((a_ + _b_*InertTan(x*_f_ + _e_))**n_*InertSec(x*_f_ + _e_)**m_, x),
        constraints=(FreeQ([a_, _b_, _e_, _f_, n_], x), NeQ(a_**2 + _b_**2, 0), IntegerQ(m_/2),),
        replacement=Subst(Int((x + a_)**n_*(x**2/_b_**2 + 1)**(m_/2 - 1), x), x, _b_*tan(x*_f_ + _e_))/(_b_*_f_),
        module_name='4.3.1.2 (d sec)^m (a+b tan)^n',
        rule_number=21,
    ),
    # Rule 22
    SymPyReplacementPattern(
        pattern=Int((a_ + _b_*InertTan(x*_f_ + _e_))**2/InertSec(x*_f_ + _e_), x),
        constraints=(FreeQ([a_, _b_, _e_, _f_], x), NeQ(a_**2 + _b_**2, 0),),
        replacement=-2*a_*_b_*cos(x*_f_ + _e_)/_f_ + _b_**2*atanh(sin(x*_f_ + _e_))/_f_ + (a_**2 - _b_**2)*sin(x*_f_ + _e_)/_f_,
        module_name='4.3.1.2 (d sec)^m (a+b tan)^n',
        rule_number=22,
    ),
    # Rule 23
    SymPyReplacementPattern(
        pattern=Int((_d_*InertSec(x*_f_ + _e_))**_m_*(a_ + _b_*InertTan(x*_f_ + _e_))**2, x),
        constraints=(FreeQ([a_, _b_, _d_, _e_, _f_, _m_], x), NeQ(a_**2 + _b_**2, 0), NeQ(_m_, -1),),
        replacement=_b_*(_d_*sec(x*_f_ + _e_))**_m_*(a_ + _b_*tan(x*_f_ + _e_))/(_f_*(_m_ + 1)) + Int((_d_*sec(x*_f_ + _e_))**_m_*(a_**2*(_m_ + 1) + a_*_b_*(_m_ + 2)*tan(x*_f_ + _e_) - _b_**2), x)/(_m_ + 1),
        module_name='4.3.1.2 (d sec)^m (a+b tan)^n',
        rule_number=23,
    ),
    # Rule 24
    SymPyReplacementPattern(
        pattern=Int(InertSec(x*_f_ + _e_)/(a_ + _b_*InertTan(x*_f_ + _e_)), x),
        constraints=(FreeQ([a_, _b_, _e_, _f_], x), NeQ(a_**2 + _b_**2, 0),),
        replacement=-Subst(Int(1/(-x**2 + a_**2 + _b_**2), x), x, (-a_*tan(x*_f_ + _e_) + _b_)/sec(x*_f_ + _e_))/_f_,
        module_name='4.3.1.2 (d sec)^m (a+b tan)^n',
        rule_number=24,
    ),
    # Rule 25
    SymPyReplacementPattern(
        pattern=Int((_d_*InertSec(x*_f_ + _e_))**m_/(a_ + _b_*InertTan(x*_f_ + _e_)), x),
        constraints=(FreeQ([a_, _b_, _d_, _e_, _f_], x), NeQ(a_**2 + _b_**2, 0), IGtQ(m_, 1),),
        replacement=_d_**2*(a_**2 + _b_**2)*Int((_d_*sec(x*_f_ + _e_))**(m_ - 2)/(a_ + _b_*tan(x*_f_ + _e_)), x)/_b_**2 - _d_**2*Int((_d_*sec(x*_f_ + _e_))**(m_ - 2)*(a_ - _b_*tan(x*_f_ + _e_)), x)/_b_**2,
        module_name='4.3.1.2 (d sec)^m (a+b tan)^n',
        rule_number=25,
    ),
    # Rule 26
    SymPyReplacementPattern(
        pattern=Int((_d_*InertSec(x*_f_ + _e_))**m_/(a_ + _b_*InertTan(x*_f_ + _e_)), x),
        constraints=(FreeQ([a_, _b_, _d_, _e_, _f_], x), NeQ(a_**2 + _b_**2, 0), ILtQ(m_, 0),),
        replacement=_b_**2*Int((_d_*sec(x*_f_ + _e_))**(m_ + 2)/(a_ + _b_*tan(x*_f_ + _e_)), x)/(_d_**2*(a_**2 + _b_**2)) + Int((_d_*sec(x*_f_ + _e_))**m_*(a_ - _b_*tan(x*_f_ + _e_)), x)/(a_**2 + _b_**2),
        module_name='4.3.1.2 (d sec)^m (a+b tan)^n',
        rule_number=26,
    ),
    # Rule 27
    SymPyReplacementPattern(
        pattern=Int((_d_*InertSec(x*_f_ + _e_))**_m_*(a_ + _b_*InertTan(x*_f_ + _e_))**n_, x),
        constraints=(FreeQ([a_, _b_, _d_, _e_, _f_, _m_, n_], x), NeQ(a_**2 + _b_**2, 0), Not(IntegerQ(_m_/2)),),
        replacement=_d_**(2*IntPart(_m_/2))*(_d_*sec(x*_f_ + _e_))**(2*FracPart(_m_/2))*Subst(Int((x + a_)**n_*(x**2/_b_**2 + 1)**(_m_/2 - 1), x), x, _b_*tan(x*_f_ + _e_))/(_b_*_f_*(sec(x*_f_ + _e_)**2)**FracPart(_m_/2)),
        module_name='4.3.1.2 (d sec)^m (a+b tan)^n',
        rule_number=27,
    ),
    # Rule 28
    SymPyReplacementPattern(
        pattern=Int(sqrt(a_ + _b_*InertTan(x*_f_ + _e_))/sqrt(_d_*InertCos(x*_f_ + _e_)), x),
        constraints=(FreeQ([a_, _b_, _d_, _e_, _f_], x), EqQ(a_**2 + _b_**2, 0),),
        replacement=-4*_b_*Subst(Int(x**2/(x**4 + a_**2*_d_**2), x), x, sqrt(_d_*cos(x*_f_ + _e_))*sqrt(a_ + _b_*tan(x*_f_ + _e_)))/_f_,
        module_name='4.3.1.2 (d sec)^m (a+b tan)^n',
        rule_number=28,
    ),
    # Rule 29
    SymPyReplacementPattern(
        pattern=Int(1/((_d_*InertCos(x*_f_ + _e_))**(sympy.S(3)/2)*sqrt(a_ + _b_*InertTan(x*_f_ + _e_))), x),
        constraints=(FreeQ([a_, _b_, _d_, _e_, _f_], x), EqQ(a_**2 + _b_**2, 0),),
        replacement=Int(sqrt(a_ - _b_*tan(x*_f_ + _e_))/sqrt(_d_*cos(x*_f_ + _e_)), x)/(_d_*sqrt(a_ - _b_*tan(x*_f_ + _e_))*sqrt(a_ + _b_*tan(x*_f_ + _e_))*cos(x*_f_ + _e_)),
        module_name='4.3.1.2 (d sec)^m (a+b tan)^n',
        rule_number=29,
    ),
    # Rule 30
    SymPyReplacementPattern(
        pattern=Int((_d_*InertCos(x*_f_ + _e_))**m_*(a_ + _b_*InertTan(x*_f_ + _e_))**_n_, x),
        constraints=(FreeQ([a_, _b_, _d_, _e_, _f_, m_, _n_], x), Not(IntegerQ(m_)),),
        replacement=(_d_*cos(x*_f_ + _e_))**m_*(_d_*sec(x*_f_ + _e_))**m_*Int((a_ + _b_*tan(x*_f_ + _e_))**_n_/(_d_*sec(x*_f_ + _e_))**m_, x),
        module_name='4.3.1.2 (d sec)^m (a+b tan)^n',
        rule_number=30,
    ),

]

# Summary: 30 rules translated, 0 skipped
