# -*- coding: utf-8 -*-
"""Rubi's rule-file LOAD ORDER, which is its rule PRIORITY.

Rubi applies the FIRST matching rule and stops, and it tries rules in the order its
files are loaded by ``Rubi.m`` -- an EXPLICIT sequence, not a directory glob and NOT
sorted by the dotted section number. Sorting by section number (what `_rule_priority`
did before) disagrees with the real order in 22 places; e.g. Rubi loads
"9.2 Piecewise linear functions" at position 69 but "9.1 Derivative integration rules"
at position 199.

Extracted from Rubi 4.17.3.0 with:

    grep -n "LoadRules\\[" Rubi/Rubi.m | grep FileNameJoin

Modules absent from this list -- the obsolete alternate-numbering files the codegen
picked up by walking the IntegrationRules directory, plus a few whose section numbers
drifted between Rubi checkouts -- keep a section-number ordering and sort AFTER every
listed one, so they can never pre-empt a rule Rubi actually has. See
`rubi_integrate.base_objects._module_load_index`.
"""

# Ordered exactly as Rubi.m loads them; index == priority (lower fires first).
RUBI_LOAD_ORDER = (
    '1.1.1.1 (a+b x)^m',
    '1.1.1.2 (a+b x)^m (c+d x)^n',
    '1.1.1.3 (a+b x)^m (c+d x)^n (e+f x)^p',
    '1.1.1.4 (a+b x)^m (c+d x)^n (e+f x)^p (g+h x)^q',
    '1.1.2.1 (a+b x^2)^p',
    '1.1.2.2 (c x)^m (a+b x^2)^p',
    '1.1.2.3 (a+b x^2)^p (c+d x^2)^q',
    '1.1.2.4 (e x)^m (a+b x^2)^p (c+d x^2)^q',
    '1.1.2.5 (a+b x^2)^p (c+d x^2)^q (e+f x^2)^r',
    '1.1.2.6 (g x)^m (a+b x^2)^p (c+d x^2)^q (e+f x^2)^r',
    '1.1.2.7 (c+d x)^n (a+b x^2)^p',
    '1.1.2.8 (e x)^m (c+d x)^n (a+b x^2)^p',
    '1.1.2.9 (c+d x)^m (e+f x)^n (a+b x^2)^p',
    '1.1.3.1 (a+b x^n)^p',
    '1.1.3.2 (c x)^m (a+b x^n)^p',
    '1.1.3.3 (a+b x^n)^p (c+d x^n)^q',
    '1.1.3.4 (e x)^m (a+b x^n)^p (c+d x^n)^q',
    '1.1.3.5 (a+b x^n)^p (c+d x^n)^q (e+f x^n)^r',
    '1.1.3.6 (g x)^m (a+b x^n)^p (c+d x^n)^q (e+f x^n)^r',
    '1.2.1.1 (a+b x+c x^2)^p',
    '1.2.1.2 (d+e x)^m (a+b x+c x^2)^p',
    '1.2.1.3 (d+e x)^m (f+g x)^n (a+b x+c x^2)^p',
    '1.2.1.4 (a+b x+c x^2)^p (d+e x+f x^2)^q',
    '1.2.1.5 (g+h x)^m (a+b x+c x^2)^p (d+e x+f x^2)^q',
    '1.2.2.1 (a+b x^2+c x^4)^p',
    '1.2.2.2 (d x)^m (a+b x^2+c x^4)^p',
    '1.2.2.3 (d+e x^2)^q (a+b x^2+c x^4)^p',
    '1.2.2.4 (f x)^m (d+e x^2)^q (a+b x^2+c x^4)^p',
    '1.2.3.1 (a+b x^n+c x^(2 n))^p',
    '1.2.3.2 (d x)^m (a+b x^n+c x^(2 n))^p',
    '1.2.3.3 (d+e x^n)^q (a+b x^n+c x^(2 n))^p',
    '1.2.3.4 (f x)^m (d+e x^n)^q (a+b x^n+c x^(2 n))^p',
    '1.1.4.1 (a x^j+b x^n)^p',
    '1.1.4.2 (c x)^m (a x^j+b x^n)^p',
    '1.1.4.3 (e x)^m (a x^j+b x^k)^p (c+d x^n)^q',
    '1.2.4.1 (a x^q+b x^n+c x^(2 n-q))^p',
    '1.2.4.2 (d x)^m (a x^q+b x^n+c x^(2 n-q))^p',
    '1.2.4.3 (d+e x^(n-q)) (a x^q+b x^n+c x^(2 n-q))^p',
    '1.2.4.4 (f x)^m (d+e x^(n-q)) (a x^q+b x^n+c x^(2 n-q))^p',
    '1.4.1 Algebraic function simplification',
    '1.4.2 Algebraic function normalization',
    '1.1.1.7 P(x) (a+b x)^m (c+d x)^n (e+f x)^p (g+h x)^q',
    '1.1.1.6 P(x) (a+b x)^m (c+d x)^n (e+f x)^p',
    '1.1.1.5 P(x) (a+b x)^m (c+d x)^n',
    '1.2.1.9 P(x) (a+b x+c x^2)^p (d+e x+f x^2)^q',
    '1.2.1.8 P(x) (d+e x)^m (f+g x)^n (a+b x+c x^2)^p',
    '1.2.1.7 P(x) (d+e x)^m (a+b x+c x^2)^p',
    '1.2.1.6 P(x) (a+b x+c x^2)^p',
    '1.2.2.6 P(x) (d x)^m (a+b x^2+c x^4)^p',
    '1.2.2.5 P(x) (a+b x^2+c x^4)^p',
    '1.2.2.7 P(x) (d+e x^2)^q (a+b x^2+c x^4)^p',
    '1.2.2.8 P(x) (d+e x)^q (a+b x^2+c x^4)^p',
    '1.2.3.6 P(x) (d x)^m (a+b x^n+c x^(2 n))^p',
    '1.2.3.5 P(x) (a+b x^n+c x^(2 n))^p',
    '1.1.2.11 P(x) (c x)^m (a+b x^2)^p',
    '1.1.2.10 P(x) (a+b x^2)^p',
    '1.1.2.14 P(x) (c+d x)^m (e+f x)^n (a+b x^2)^p',
    '1.1.2.13 P(x) (e x)^m (c+d x)^n (a+b x^2)^p',
    '1.1.2.12 P(x) (c+d x)^n (a+b x^2)^p',
    '1.1.3.8 P(x) (c x)^m (a+b x^n)^p',
    '1.1.3.7 P(x) (a+b x^n)^p',
    '1.1.4.4 P(x) (c x)^m (a x^j+b x^n)^p',
    '1.3.3 P(x)^p',
    '1.3.1 u (a+b x+c x^2+d x^3)^p',
    '1.3.2 u (a+b x+c x^2+d x^3+e x^4)^p',
    '1.3.4 P(x) Q(x)^p',
    '1.4.3 Miscellaneous algebraic functions',
    '9.2 Piecewise linear functions',
    '2.1 (c+d x)^m (a+b (F^(g (e+f x)))^n)^p',
    '2.2 (c+d x)^m (F^(g (e+f x)))^n (a+b (F^(g (e+f x)))^n)^p',
    '2.3 Miscellaneous exponentials',
    '3.1.1 (a+b log(c x^n))^p',
    '3.1.2 (d x)^m (a+b log(c x^n))^p',
    '3.1.3 (d+e x^r)^q (a+b log(c x^n))^p',
    '3.1.4 (f x)^m (d+e x^r)^q (a+b log(c x^n))^p',
    '3.1.5 u (a+b log(c x^n))^p',
    '3.3 u (a+b log(c (d+e x)^n))^p',
    '3.4 u (a+b log(c (d+e x^m)^n))^p',
    '3.2.1 (f+g x)^m (A+B log(e ((a+b x) over (c+d x))^n))^p',
    '3.2.2 (f+g x)^m (h+i x)^q (A+B log(e ((a+b x) over (c+d x))^n))^p',
    '3.2.3 u log(e (f (a+b x)^p (c+d x)^q)^r)^s',
    '3.5 Miscellaneous logarithms',
    '4.1.0.1 (a sin)^m (b trg)^n',
    '4.1.0.2 (a trg)^m (b tan)^n',
    '4.1.0.3 (a csc)^m (b sec)^n',
    '4.1.1.1 (a+b sin)^n',
    '4.1.1.2 (g cos)^p (a+b sin)^m',
    '4.1.1.3 (g tan)^p (a+b sin)^m',
    '4.1.2.1 (a+b sin)^m (c+d sin)^n',
    '4.1.2.2 (g cos)^p (a+b sin)^m (c+d sin)^n',
    '4.1.2.3 (g sin)^p (a+b sin)^m (c+d sin)^n',
    '4.1.3.1 (a+b sin)^m (c+d sin)^n (A+B sin)',
    '4.1.4.1 (a+b sin)^m (A+B sin+C sin^2)',
    '4.1.4.2 (a+b sin)^m (c+d sin)^n (A+B sin+C sin^2)',
    '4.1.5 trig^m (a cos+b sin)^n',
    '4.1.6 (a+b cos+c sin)^n',
    '4.1.7 (d trig)^m (a+b (c sin)^n)^p',
    '4.1.8 trig^m (a+b cos^p+c sin^q)^n',
    '4.1.9 trig^m (a+b sin^n+c sin^(2 n))^p',
    '4.1.10 (c+d x)^m (a+b sin)^n',
    '4.1.11 (e x)^m (a+b x^n)^p sin',
    '4.1.12 (e x)^m (a+b sin(c+d x^n))^p',
    '4.1.13 (d+e x)^m sin(a+b x+c x^2)^n',
    '4.3.1.1 (a+b tan)^n',
    '4.3.1.2 (d sec)^m (a+b tan)^n',
    '4.3.1.3 (d sin)^m (a+b tan)^n',
    '4.3.2.1 (a+b tan)^m (c+d tan)^n',
    '4.3.2.3 (g tan)^p (a+b tan)^m (c+d tan)^n',
    '4.3.3.1 (a+b tan)^m (c+d tan)^n (A+B tan)',
    '4.3.4.1 (a+b tan)^m (A+B tan+C tan^2)',
    '4.3.4.2 (a+b tan)^m (c+d tan)^n (A+B tan+C tan^2)',
    '4.3.7 (d trig)^m (a+b (c tan)^n)^p',
    '4.3.9 trig^m (a+b tan^n+c tan^(2 n))^p',
    '4.3.10 (c+d x)^m (a+b tan)^n',
    '4.3.11 (e x)^m (a+b tan(c+d x^n))^p',
    '4.3.12 (d+e x)^m tan(a+b x+c x^2)^n',
    '4.5.1.1 (a+b sec)^n',
    '4.5.1.2 (d sec)^n (a+b sec)^m',
    '4.5.1.3 (d sin)^n (a+b sec)^m',
    '4.5.1.4 (d tan)^n (a+b sec)^m',
    '4.5.2.1 (a+b sec)^m (c+d sec)^n',
    '4.5.2.2 (g sec)^p (a+b sec)^m (c+d sec)^n',
    '4.5.3.1 (a+b sec)^m (d sec)^n (A+B sec)',
    '4.5.4.1 (a+b sec)^m (A+B sec+C sec^2)',
    '4.5.4.2 (a+b sec)^m (d sec)^n (A+B sec+C sec^2)',
    '4.5.7 (d trig)^m (a+b (c sec)^n)^p',
    '4.5.9 trig^m (a+b sec^n+c sec^(2 n))^p',
    '4.5.10 (c+d x)^m (a+b sec)^n',
    '4.5.11 (e x)^m (a+b sec(c+d x^n))^p',
    '4.7.1 Sine normalization rules',
    '4.7.2 Tangent normalization rules',
    '4.7.3 Secant normalization rules',
    '4.7.4 (c trig)^m (d trig)^n',
    '4.7.5 Inert trig functions',
    '4.7.6 (c+d x)^m trig(a+b x)^n trig(a+b x)^p',
    '4.7.7 F^(c (a+b x)) trig(d+e x)^n',
    '4.7.8 u trig(a+b log(c x^n))^p',
    '4.7.9 Active trig functions',
    '5.1.1 (a+b arcsin(c x))^n',
    '5.1.2 (d x)^m (a+b arcsin(c x))^n',
    '5.1.3 (d+e x^2)^p (a+b arcsin(c x))^n',
    '5.1.4 (f x)^m (d+e x^2)^p (a+b arcsin(c x))^n',
    '5.1.5 u (a+b arcsin(c x))^n',
    '5.1.6 Miscellaneous inverse sine',
    '5.3.1 (a+b arctan(c x^n))^p',
    '5.3.2 (d x)^m (a+b arctan(c x^n))^p',
    '5.3.3 (d+e x)^m (a+b arctan(c x^n))^p',
    '5.3.4 u (a+b arctan(c x))^p',
    '5.3.5 u (a+b arctan(c+d x))^p',
    '5.3.6 Exponentials of inverse tangent',
    '5.3.7 Miscellaneous inverse tangent',
    '5.5.1 u (a+b arcsec(c x))^n',
    '5.5.2 Miscellaneous inverse secant',
    '6.1.10 (c+d x)^m (a+b sinh)^n',
    '6.1.11 (e x)^m (a+b x^n)^p sinh',
    '6.1.12 (e x)^m (a+b sinh(c+d x^n))^p',
    '6.1.13 (d+e x)^m sinh(a+b x+c x^2)^n',
    '6.3.10 (c+d x)^m (a+b tanh)^n',
    '6.3.11 (e x)^m (a+b tanh(c+d x^n))^p',
    '6.3.12 (d+e x)^m tanh(a+b x+c x^2)^n',
    '6.5.10 (c+d x)^m (a+b sech)^n',
    '6.5.11 (e x)^m (a+b sech(c+d x^n))^p',
    '6.7.6 (c+d x)^m hyper(a+b x)^n hyper(a+b x)^p',
    '6.7.7 F^(c (a+b x)) hyper(d+e x)^n',
    '6.7.8 u hyper(a+b log(c x^n))^p',
    '6.7.9 Active hyperbolic functions',
    '7.1.1 (a+b arcsinh(c x))^n',
    '7.1.2 (d x)^m (a+b arcsinh(c x))^n',
    '7.1.3 (d+e x^2)^p (a+b arcsinh(c x))^n',
    '7.1.4 (f x)^m (d+e x^2)^p (a+b arcsinh(c x))^n',
    '7.1.5 u (a+b arcsinh(c x))^n',
    '7.1.6 Miscellaneous inverse hyperbolic sine',
    '7.2.1 (a+b arccosh(c x))^n',
    '7.2.2 (d x)^m (a+b arccosh(c x))^n',
    '7.2.3 (d+e x^2)^p (a+b arccosh(c x))^n',
    '7.2.4 (f x)^m (d+e x^2)^p (a+b arccosh(c x))^n',
    '7.2.5 u (a+b arccosh(c x))^n',
    '7.2.6 Miscellaneous inverse hyperbolic cosine',
    '7.3.1 (a+b arctanh(c x^n))^p',
    '7.3.2 (d x)^m (a+b arctanh(c x^n))^p',
    '7.3.3 (d+e x)^m (a+b arctanh(c x^n))^p',
    '7.3.4 u (a+b arctanh(c x))^p',
    '7.3.5 u (a+b arctanh(c+d x))^p',
    '7.3.6 Exponentials of inverse hyperbolic tangent',
    '7.3.7 Miscellaneous inverse hyperbolic tangent',
    '7.5.1 u (a+b arcsech(c x))^n',
    '7.5.2 Miscellaneous inverse hyperbolic secant',
    '8.1 Error functions',
    '8.2 Fresnel integral functions',
    '8.3 Exponential integral functions',
    '8.4 Trig integral functions',
    '8.5 Hyperbolic integral functions',
    '8.6 Gamma functions',
    '8.7 Zeta function',
    '8.8 Polylogarithm function',
    '8.9 Product logarithm function',
    '8.10 Bessel functions',
    '9.1 Derivative integration rules',
    '9.3 Miscellaneous integration rules',
)


# Modules the codegen picked up by walking the IntegrationRules directory that Rubi.m
# NEVER loads -- an obsolete alternate numbering. They share a TITLE with a file Rubi
# does load ("9.4 Miscellaneous integration rules" vs "9.3 ..."), so the title fallback
# in `_module_load_index` would otherwise hand them the REAL file's priority. Listing
# them here forces them last instead.
#
# They are deliberately NOT excluded from loading: only 18/23 and 12/20 of their
# patterns duplicate the loaded files, and dropping them loses
# `Int[Sin[3a+3bx] Csc[a+bx]/(c+dx)]` -- which Rubi solves using rules this port is still
# missing (the Piecewise linear module is absent entirely).
NOT_IN_RUBI_LOAD_LIST = frozenset({
    '9.2 Derivative integration rules',
    '9.4 Miscellaneous integration rules',
})
