# -*- coding: utf-8 -*-
# =============================================================================
# !! AUTO-GENERATED FILE -- DO NOT EDIT !!
#
# Generated by: rubi_integrate/codegen/generate.py
# Source: 1.4.2 Algebraic function normalization.m
# Module: 1.4.2 Algebraic function normalization
#
# This file contains Rubi integration rules as SymPyReplacementPattern objects.
# Re-run the generator to update.
# =============================================================================
import sympy
from sympy import Integer, Symbol
from rubi_integrate.utils.rubi_utils import *  # bare-name access; sympy imports below override any conflicts (e.g. Not)
from sympy.logic.boolalg import Not, And

from sympy_matching.wild import WildSymbol, IDENTITY_ELEMENT
from rubi_integrate.base_objects import Int, SymPyReplacementPattern
# Inert trig markers (Rubi's lowercase sin/cos/... patterns). Distinct opaque heads,
# NOT subclasses of sympy.sin -- see rubi-trig-deactivation-dispatch project note.
from rubi_integrate.utils import (
    # Wolfram standard constraints
    FreeQ, MatchQ, EqQ, PolyQ, LinearQ, QuadraticQ, BinomialQ,
    TrinomialQ, LinearMatchQ, QuadraticMatchQ, BinomialMatchQ, TrinomialMatchQ,
    GeneralizedBinomialQ, GeneralizedBinomialMatchQ,
    GeneralizedTrinomialQ, GeneralizedTrinomialMatchQ,
)

# --- Integration variable ---
x = Symbol('x')

# --- Rubi global option stubs (default False/placeholder) ---
UseGamma = sympy.Symbol('UseGamma')  # Rubi global option; treated as False in Python
u = Symbol('u')  # Generic integrand placeholder used in some Rubi constraint calls

# --- Rubi selector symbols ---
# Rubi passes Min/Max as bare SYMBOLS, not calls: Expon[Px, x, Min] selects the
# minimum exponent. The code emitter round-trips through SymPy's printer, which
# renders Symbol('Min') as the bare name `Min`, so the name must exist here.
# (A genuine Min[a, b] call is emitted qualified, as sympy.Min(...), so these
# bindings cannot shadow it.)
Min = Symbol('Min')
Max = Symbol('Max')

# --- Wildcard symbols ---
# dot wildcards (must match exactly one expression)
# optional wildcards (can match identity element if absent in commutative ops)

Px_ = WildSymbol('Px')
_a_ = WildSymbol('a', optional_value=IDENTITY_ELEMENT)
a_ = WildSymbol('a')
_b_ = WildSymbol('b', optional_value=IDENTITY_ELEMENT)
b_ = WildSymbol('b')
_c_ = WildSymbol('c', optional_value=IDENTITY_ELEMENT)
c_ = WildSymbol('c')
_d_ = WildSymbol('d', optional_value=IDENTITY_ELEMENT)
d_ = WildSymbol('d')
_e_ = WildSymbol('e', optional_value=IDENTITY_ELEMENT)
e_ = WildSymbol('e')
_f_ = WildSymbol('f', optional_value=IDENTITY_ELEMENT)
f_ = WildSymbol('f')
_g_ = WildSymbol('g', optional_value=IDENTITY_ELEMENT)
g_ = WildSymbol('g')
_m_ = WildSymbol('m', optional_value=IDENTITY_ELEMENT)
m_ = WildSymbol('m')
_n_ = WildSymbol('n', optional_value=IDENTITY_ELEMENT)
n_ = WildSymbol('n')
_p_ = WildSymbol('p', optional_value=IDENTITY_ELEMENT)
p_ = WildSymbol('p')
_q_ = WildSymbol('q', optional_value=IDENTITY_ELEMENT)
q_ = WildSymbol('q')
_r_ = WildSymbol('r', optional_value=IDENTITY_ELEMENT)
r_ = WildSymbol('r')
_t_ = WildSymbol('t', optional_value=IDENTITY_ELEMENT)
t_ = WildSymbol('t')
u_ = WildSymbol('u')
v_ = WildSymbol('v')
w_ = WildSymbol('w')
z_ = WildSymbol('z')

RULES = [
    # Rule 1
    SymPyReplacementPattern(
        pattern=Int(u_**m_, x),
        constraints=(FreeQ(m_, x), LinearQ(u_, x), Not(LinearMatchQ(u_, x)),),
        replacement=Int(ExpandToSum(u_, x)**m_, x),
        module_name='1.4.2 Algebraic function normalization',
        rule_number=1,
    ),
    # Rule 2
    SymPyReplacementPattern(
        pattern=Int(u_**_m_*v_**_n_, x),
        constraints=(FreeQ([_m_, _n_], x), LinearQ([u_, v_], x), Not(LinearMatchQ([u_, v_], x)),),
        replacement=Int(ExpandToSum(u_, x)**_m_*ExpandToSum(v_, x)**_n_, x),
        module_name='1.4.2 Algebraic function normalization',
        rule_number=2,
    ),
    # Rule 3
    SymPyReplacementPattern(
        pattern=Int(u_**_m_*v_**_n_*w_**_p_, x),
        constraints=(FreeQ([_m_, _n_, _p_], x), LinearQ([u_, v_, w_], x), Not(LinearMatchQ([u_, v_, w_], x)),),
        replacement=Int(ExpandToSum(u_, x)**_m_*ExpandToSum(v_, x)**_n_*ExpandToSum(w_, x)**_p_, x),
        module_name='1.4.2 Algebraic function normalization',
        rule_number=3,
    ),
    # Rule 4
    SymPyReplacementPattern(
        pattern=Int(u_**_m_*v_**_n_*w_**_p_*z_**_q_, x),
        constraints=(FreeQ([_m_, _n_, _p_, _q_], x), LinearQ([u_, v_, w_, z_], x), Not(LinearMatchQ([u_, v_, w_, z_], x)),),
        replacement=Int(ExpandToSum(u_, x)**_m_*ExpandToSum(v_, x)**_n_*ExpandToSum(w_, x)**_p_*ExpandToSum(z_, x)**_q_, x),
        module_name='1.4.2 Algebraic function normalization',
        rule_number=4,
    ),
    # Rule 5
    SymPyReplacementPattern(
        pattern=Int(u_**p_, x),
        constraints=(FreeQ(p_, x), BinomialQ(u_, x), Not(BinomialMatchQ(u_, x)),),
        replacement=Int(ExpandToSum(u_, x)**p_, x),
        module_name='1.4.2 Algebraic function normalization',
        rule_number=5,
    ),
    # Rule 6
    SymPyReplacementPattern(
        pattern=Int(u_**_p_*(x*_c_)**_m_, x),
        constraints=(FreeQ([_c_, _m_, _p_], x), BinomialQ(u_, x), Not(BinomialMatchQ(u_, x)),),
        replacement=Int((x*_c_)**_m_*ExpandToSum(u_, x)**_p_, x),
        module_name='1.4.2 Algebraic function normalization',
        rule_number=6,
    ),
    # Rule 7
    SymPyReplacementPattern(
        pattern=Int(u_**_p_*v_**_q_, x),
        constraints=(FreeQ([_p_, _q_], x), BinomialQ([u_, v_], x), EqQ(BinomialDegree(u_, x) - BinomialDegree(v_, x), 0), Not(BinomialMatchQ([u_, v_], x)),),
        replacement=Int(ExpandToSum(u_, x)**_p_*ExpandToSum(v_, x)**_q_, x),
        module_name='1.4.2 Algebraic function normalization',
        rule_number=7,
    ),
    # Rule 8
    SymPyReplacementPattern(
        pattern=Int(u_**_p_*v_**_q_*(x*_e_)**_m_, x),
        constraints=(FreeQ([_e_, _m_, _p_, _q_], x), BinomialQ([u_, v_], x), EqQ(BinomialDegree(u_, x) - BinomialDegree(v_, x), 0), Not(BinomialMatchQ([u_, v_], x)),),
        replacement=Int((x*_e_)**_m_*ExpandToSum(u_, x)**_p_*ExpandToSum(v_, x)**_q_, x),
        module_name='1.4.2 Algebraic function normalization',
        rule_number=8,
    ),
    # Rule 9
    SymPyReplacementPattern(
        pattern=Int(u_**_m_*v_**_p_*w_**_q_, x),
        constraints=(FreeQ([_m_, _p_, _q_], x), BinomialQ([u_, v_, w_], x), EqQ(BinomialDegree(u_, x) - BinomialDegree(v_, x), 0), EqQ(BinomialDegree(u_, x) - BinomialDegree(w_, x), 0), Not(BinomialMatchQ([u_, v_, w_], x)),),
        replacement=Int(ExpandToSum(u_, x)**_m_*ExpandToSum(v_, x)**_p_*ExpandToSum(w_, x)**_q_, x),
        module_name='1.4.2 Algebraic function normalization',
        rule_number=9,
    ),
    # Rule 10
    SymPyReplacementPattern(
        pattern=Int(u_**_p_*v_**_q_*z_**_r_*(x*_g_)**_m_, x),
        constraints=(FreeQ([_g_, _m_, _p_, _q_, _r_], x), BinomialQ([u_, v_, z_], x), EqQ(BinomialDegree(u_, x) - BinomialDegree(v_, x), 0), EqQ(BinomialDegree(u_, x) - BinomialDegree(z_, x), 0), Not(BinomialMatchQ([u_, v_, z_], x)),),
        replacement=Int((x*_g_)**_m_*ExpandToSum(u_, x)**_p_*ExpandToSum(v_, x)**_q_*ExpandToSum(z_, x)**_r_, x),
        module_name='1.4.2 Algebraic function normalization',
        rule_number=10,
    ),
    # Rule 11
    SymPyReplacementPattern(
        pattern=Int(u_**p_, x),
        constraints=(FreeQ(p_, x), GeneralizedBinomialQ(u_, x), Not(GeneralizedBinomialMatchQ(u_, x)),),
        replacement=Int(ExpandToSum(u_, x)**p_, x),
        module_name='1.4.2 Algebraic function normalization',
        rule_number=11,
    ),
    # Rule 12
    SymPyReplacementPattern(
        pattern=Int(u_**_p_*(x*_c_)**_m_, x),
        constraints=(FreeQ([_c_, _m_, _p_], x), GeneralizedBinomialQ(u_, x), Not(GeneralizedBinomialMatchQ(u_, x)),),
        replacement=Int((x*_c_)**_m_*ExpandToSum(u_, x)**_p_, x),
        module_name='1.4.2 Algebraic function normalization',
        rule_number=12,
    ),
    # Rule 13
    SymPyReplacementPattern(
        pattern=Int(u_**p_, x),
        constraints=(FreeQ(p_, x), QuadraticQ(u_, x), Not(QuadraticMatchQ(u_, x)),),
        replacement=Int(ExpandToSum(u_, x)**p_, x),
        module_name='1.4.2 Algebraic function normalization',
        rule_number=13,
    ),
    # Rule 14
    SymPyReplacementPattern(
        pattern=Int(u_**_m_*v_**_p_, x),
        constraints=(FreeQ([_m_, _p_], x), LinearQ(u_, x), QuadraticQ(v_, x), Not(And(LinearMatchQ(u_, x), QuadraticMatchQ(v_, x))),),
        replacement=Int(ExpandToSum(u_, x)**_m_*ExpandToSum(v_, x)**_p_, x),
        module_name='1.4.2 Algebraic function normalization',
        rule_number=14,
    ),
    # Rule 15
    SymPyReplacementPattern(
        pattern=Int(u_**_m_*v_**_n_*w_**_p_, x),
        constraints=(FreeQ([_m_, _n_, _p_], x), LinearQ([u_, v_], x), QuadraticQ(w_, x), Not(And(LinearMatchQ([u_, v_], x), QuadraticMatchQ(w_, x))),),
        replacement=Int(ExpandToSum(u_, x)**_m_*ExpandToSum(v_, x)**_n_*ExpandToSum(w_, x)**_p_, x),
        module_name='1.4.2 Algebraic function normalization',
        rule_number=15,
    ),
    # Rule 16
    SymPyReplacementPattern(
        pattern=Int(u_**_p_*v_**_q_, x),
        constraints=(FreeQ([_p_, _q_], x), QuadraticQ([u_, v_], x), Not(QuadraticMatchQ([u_, v_], x)),),
        replacement=Int(ExpandToSum(u_, x)**_p_*ExpandToSum(v_, x)**_q_, x),
        module_name='1.4.2 Algebraic function normalization',
        rule_number=16,
    ),
    # Rule 17
    SymPyReplacementPattern(
        pattern=Int(u_**_p_*v_**_q_*z_**_m_, x),
        constraints=(FreeQ([_m_, _p_, _q_], x), LinearQ(z_, x), QuadraticQ([u_, v_], x), Not(And(LinearMatchQ(z_, x), QuadraticMatchQ([u_, v_], x))), Not(MatchQ(((z_)**(_m_) * (u_)**(_p_) * (v_)**(_q_)), Condition((((_d_ + (_e_ * x)))**(_m_) * ((_f_ + (_g_ * x)))**(Integer(2)) * ((_a_ + (_b_ * x) + (_c_ * (x)**(Integer(2)))))**(_t_)), FreeQ([_a_, _b_, _c_, _d_, _e_, _f_, _g_, _t_], x)))), Not(MatchQ(((z_)**(_m_) * (u_)**(_p_) * (v_)**(_q_)), Condition((((_d_ + (_e_ * x)))**(_m_) * ((_f_ + (_g_ * x)))**(Integer(2)) * ((_a_ + (_c_ * (x)**(Integer(2)))))**(_t_)), FreeQ([_a_, _c_, _d_, _e_, _f_, _g_, _t_], x)))),),
        replacement=Int(ExpandToSum(u_, x)**_p_*ExpandToSum(v_, x)**_q_*ExpandToSum(z_, x)**_m_, x),
        module_name='1.4.2 Algebraic function normalization',
        rule_number=17,
    ),
    # Rule 18
    SymPyReplacementPattern(
        pattern=Int(u_**p_, x),
        constraints=(FreeQ(p_, x), TrinomialQ(u_, x), Not(TrinomialMatchQ(u_, x)),),
        replacement=Int(ExpandToSum(u_, x)**p_, x),
        module_name='1.4.2 Algebraic function normalization',
        rule_number=18,
    ),
    # Rule 19
    SymPyReplacementPattern(
        pattern=Int(u_**_p_*(x*_d_)**_m_, x),
        constraints=(FreeQ([_d_, _m_, _p_], x), TrinomialQ(u_, x), Not(TrinomialMatchQ(u_, x)),),
        replacement=Int((x*_d_)**_m_*ExpandToSum(u_, x)**_p_, x),
        module_name='1.4.2 Algebraic function normalization',
        rule_number=19,
    ),
    # Rule 20
    SymPyReplacementPattern(
        pattern=Int(u_**_q_*v_**_p_, x),
        constraints=(FreeQ([_p_, _q_], x), BinomialQ(u_, x), TrinomialQ(v_, x), Not(And(BinomialMatchQ(u_, x), TrinomialMatchQ(v_, x))),),
        replacement=Int(ExpandToSum(u_, x)**_q_*ExpandToSum(v_, x)**_p_, x),
        module_name='1.4.2 Algebraic function normalization',
        rule_number=20,
    ),
    # Rule 21
    SymPyReplacementPattern(
        pattern=Int(u_**_q_*v_**_p_, x),
        constraints=(FreeQ([_p_, _q_], x), BinomialQ(u_, x), BinomialQ(v_, x), Not(And(BinomialMatchQ(u_, x), BinomialMatchQ(v_, x))),),
        replacement=Int(ExpandToSum(u_, x)**_q_*ExpandToSum(v_, x)**_p_, x),
        module_name='1.4.2 Algebraic function normalization',
        rule_number=21,
    ),
    # Rule 22
    SymPyReplacementPattern(
        pattern=Int(u_**_p_*z_**_q_*(x*_f_)**_m_, x),
        constraints=(FreeQ([_f_, _m_, _p_, _q_], x), BinomialQ(z_, x), TrinomialQ(u_, x), Not(And(BinomialMatchQ(z_, x), TrinomialMatchQ(u_, x))),),
        replacement=Int((x*_f_)**_m_*ExpandToSum(u_, x)**_p_*ExpandToSum(z_, x)**_q_, x),
        module_name='1.4.2 Algebraic function normalization',
        rule_number=22,
    ),
    # Rule 23
    SymPyReplacementPattern(
        pattern=Int(u_**_p_*z_**_q_*(x*_f_)**_m_, x),
        constraints=(FreeQ([_f_, _m_, _p_, _q_], x), BinomialQ(z_, x), BinomialQ(u_, x), Not(And(BinomialMatchQ(z_, x), BinomialMatchQ(u_, x))),),
        replacement=Int((x*_f_)**_m_*ExpandToSum(u_, x)**_p_*ExpandToSum(z_, x)**_q_, x),
        module_name='1.4.2 Algebraic function normalization',
        rule_number=23,
    ),
    # Rule 24
    SymPyReplacementPattern(
        pattern=Int(Px_*u_**_p_*z_**_q_, x),
        constraints=(FreeQ([_p_, _q_], x), PolyQ(Px_, x), BinomialQ(z_, x), TrinomialQ(u_, x), Not(And(BinomialMatchQ(z_, x), TrinomialMatchQ(u_, x))),),
        replacement=Int(Px_*ExpandToSum(u_, x)**_p_*ExpandToSum(z_, x)**_q_, x),
        module_name='1.4.2 Algebraic function normalization',
        rule_number=24,
    ),
    # Rule 25
    SymPyReplacementPattern(
        pattern=Int(Px_*u_**_p_*z_**_q_, x),
        constraints=(FreeQ([_p_, _q_], x), BinomialQ(z_, x), BinomialQ(u_, x), Not(And(BinomialMatchQ(z_, x), BinomialMatchQ(u_, x))),),
        replacement=Int(Px_*ExpandToSum(u_, x)**_p_*ExpandToSum(z_, x)**_q_, x),
        module_name='1.4.2 Algebraic function normalization',
        rule_number=25,
    ),
    # Rule 26
    SymPyReplacementPattern(
        pattern=Int(u_**p_, x),
        constraints=(FreeQ(p_, x), GeneralizedTrinomialQ(u_, x), Not(GeneralizedTrinomialMatchQ(u_, x)),),
        replacement=Int(ExpandToSum(u_, x)**p_, x),
        module_name='1.4.2 Algebraic function normalization',
        rule_number=26,
    ),
    # Rule 27
    SymPyReplacementPattern(
        pattern=Int(u_**_p_*(x*_d_)**_m_, x),
        constraints=(FreeQ([_d_, _m_, _p_], x), GeneralizedTrinomialQ(u_, x), Not(GeneralizedTrinomialMatchQ(u_, x)),),
        replacement=Int((x*_d_)**_m_*ExpandToSum(u_, x)**_p_, x),
        module_name='1.4.2 Algebraic function normalization',
        rule_number=27,
    ),
    # Rule 28
    SymPyReplacementPattern(
        pattern=Int(u_**_p_*z_, x),
        constraints=(FreeQ(_p_, x), BinomialQ(z_, x), GeneralizedTrinomialQ(u_, x), EqQ(BinomialDegree(z_, x) - GeneralizedTrinomialDegree(u_, x), 0), Not(And(BinomialMatchQ(z_, x), GeneralizedTrinomialMatchQ(u_, x))),),
        replacement=Int(ExpandToSum(u_, x)**_p_*ExpandToSum(z_, x), x),
        module_name='1.4.2 Algebraic function normalization',
        rule_number=28,
    ),
    # Rule 29
    SymPyReplacementPattern(
        pattern=Int(u_**_p_*z_*(x*_f_)**_m_, x),
        constraints=(FreeQ([_f_, _m_, _p_], x), BinomialQ(z_, x), GeneralizedTrinomialQ(u_, x), EqQ(BinomialDegree(z_, x) - GeneralizedTrinomialDegree(u_, x), 0), Not(And(BinomialMatchQ(z_, x), GeneralizedTrinomialMatchQ(u_, x))),),
        replacement=Int((x*_f_)**_m_*ExpandToSum(u_, x)**_p_*ExpandToSum(z_, x), x),
        module_name='1.4.2 Algebraic function normalization',
        rule_number=29,
    ),

]

# Summary: 29 rules translated, 0 skipped
