# -*- coding: utf-8 -*-
# =============================================================================
# !! AUTO-GENERATED FILE -- DO NOT EDIT !!
#
# Generated by: rubi_integrate/codegen/generate.py
# Source: 5.5.1 u (a+b arcsec(c x))^n.m
# Module: 5.5.1 u (a+b arcsec(c x))^n
#
# This file contains Rubi integration rules as SymPyReplacementPattern objects.
# Re-run the generator to update.
# =============================================================================
import sympy
from sympy import Symbol
from rubi_integrate.utils.rubi_utils import *  # bare-name access; sympy imports below override any conflicts (e.g. Not)
from sympy.logic.boolalg import Or, Not, And
from sympy import (
    I, acos, acsc, asec, asin, cot, csc, exp, log, sec, sqrt, tan,
)

from sympy_matching.wild import WildSymbol, IDENTITY_ELEMENT
from rubi_integrate.base_objects import Int, SymPyReplacementPattern
# Inert trig markers (Rubi's lowercase sin/cos/... patterns). Distinct opaque heads,
# NOT subclasses of sympy.sin -- see rubi-trig-deactivation-dispatch project note.
from rubi_integrate.utils import (
    # Wolfram standard constraints
    FreeQ, IntegerQ, EqQ, NeQ, IGtQ, ILtQ, GtQ, LtQ, InverseFunctionFreeQ,
)

# --- Integration variable ---
x = Symbol('x')

# --- Rubi global option stubs (default False/placeholder) ---
UseGamma = sympy.Symbol('UseGamma')  # Rubi global option; treated as False in Python
u = Symbol('u')  # Generic integrand placeholder used in some Rubi constraint calls

# --- Rubi selector symbols ---
# Rubi passes Min/Max as bare SYMBOLS, not calls: Expon[Px, x, Min] selects the
# minimum exponent. The code emitter round-trips through SymPy's printer, which
# renders Symbol('Min') as the bare name `Min`, so the name must exist here.
# (A genuine Min[a, b] call is emitted qualified, as sympy.Min(...), so these
# bindings cannot shadow it.)
Min = Symbol('Min')
Max = Symbol('Max')

# --- Wildcard symbols ---
# dot wildcards (must match exactly one expression)
# optional wildcards (can match identity element if absent in commutative ops)

v = Symbol('v')

_a_ = WildSymbol('a', optional_value=IDENTITY_ELEMENT)
a_ = WildSymbol('a')
_b_ = WildSymbol('b', optional_value=IDENTITY_ELEMENT)
b_ = WildSymbol('b')
_c_ = WildSymbol('c', optional_value=IDENTITY_ELEMENT)
c_ = WildSymbol('c')
_d_ = WildSymbol('d', optional_value=IDENTITY_ELEMENT)
d_ = WildSymbol('d')
_e_ = WildSymbol('e', optional_value=IDENTITY_ELEMENT)
e_ = WildSymbol('e')
_f_ = WildSymbol('f', optional_value=IDENTITY_ELEMENT)
f_ = WildSymbol('f')
_m_ = WildSymbol('m', optional_value=IDENTITY_ELEMENT)
m_ = WildSymbol('m')
_n_ = WildSymbol('n', optional_value=IDENTITY_ELEMENT)
n_ = WildSymbol('n')
_p_ = WildSymbol('p', optional_value=IDENTITY_ELEMENT)
p_ = WildSymbol('p')
_u_ = WildSymbol('u', optional_value=IDENTITY_ELEMENT)
u_ = WildSymbol('u')

RULES = [
    # Rule 1
    SymPyReplacementPattern(
        pattern=Int(asec(x*_c_), x),
        constraints=(FreeQ(_c_, x),),
        replacement=x*asec(x*_c_) - Int(1/(x*sqrt(1 - 1/(x**2*_c_**2))), x)/_c_,
        module_name='5.5.1 u (a+b arcsec(c x))^n',
        rule_number=1,
    ),
    # Rule 2
    SymPyReplacementPattern(
        pattern=Int(acsc(x*_c_), x),
        constraints=(FreeQ(_c_, x),),
        replacement=x*acsc(x*_c_) + Int(1/(x*sqrt(1 - 1/(x**2*_c_**2))), x)/_c_,
        module_name='5.5.1 u (a+b arcsec(c x))^n',
        rule_number=2,
    ),
    # Rule 3
    SymPyReplacementPattern(
        pattern=Int((_a_ + _b_*asec(x*_c_))**n_, x),
        constraints=(FreeQ([_a_, _b_, _c_, n_], x), IGtQ(n_, 0),),
        replacement=Subst(Int((x*_b_ + _a_)**n_*tan(x)*sec(x), x), x, asec(x*_c_))/_c_,
        module_name='5.5.1 u (a+b arcsec(c x))^n',
        rule_number=3,
    ),
    # Rule 4
    SymPyReplacementPattern(
        pattern=Int((_a_ + _b_*acsc(x*_c_))**n_, x),
        constraints=(FreeQ([_a_, _b_, _c_, n_], x), IGtQ(n_, 0),),
        replacement=-Subst(Int((x*_b_ + _a_)**n_*cot(x)*csc(x), x), x, acsc(x*_c_))/_c_,
        module_name='5.5.1 u (a+b arcsec(c x))^n',
        rule_number=4,
    ),
    # Rule 5
    SymPyReplacementPattern(
        pattern=Int((_a_ + _b_*asec(x*_c_))/x, x),
        constraints=(FreeQ([_a_, _b_, _c_], x),),
        replacement=-Subst(Int((_a_ + _b_*acos(x/_c_))/x, x), x, 1/x),
        module_name='5.5.1 u (a+b arcsec(c x))^n',
        rule_number=5,
    ),
    # Rule 6
    SymPyReplacementPattern(
        pattern=Int((_a_ + _b_*acsc(x*_c_))/x, x),
        constraints=(FreeQ([_a_, _b_, _c_], x),),
        replacement=-Subst(Int((_a_ + _b_*asin(x/_c_))/x, x), x, 1/x),
        module_name='5.5.1 u (a+b arcsec(c x))^n',
        rule_number=6,
    ),
    # Rule 7
    SymPyReplacementPattern(
        pattern=Int((x*_d_)**_m_*(_a_ + _b_*asec(x*_c_)), x),
        constraints=(FreeQ([_a_, _b_, _c_, _d_, _m_], x), NeQ(_m_, -1),),
        replacement=-_b_*_d_*Int((x*_d_)**(_m_ - 1)/sqrt(1 - 1/(x**2*_c_**2)), x)/(_c_*(_m_ + 1)) + (x*_d_)**(_m_ + 1)*(_a_ + _b_*asec(x*_c_))/(_d_*(_m_ + 1)),
        module_name='5.5.1 u (a+b arcsec(c x))^n',
        rule_number=7,
    ),
    # Rule 8
    SymPyReplacementPattern(
        pattern=Int((x*_d_)**_m_*(_a_ + _b_*acsc(x*_c_)), x),
        constraints=(FreeQ([_a_, _b_, _c_, _d_, _m_], x), NeQ(_m_, -1),),
        replacement=_b_*_d_*Int((x*_d_)**(_m_ - 1)/sqrt(1 - 1/(x**2*_c_**2)), x)/(_c_*(_m_ + 1)) + (x*_d_)**(_m_ + 1)*(_a_ + _b_*acsc(x*_c_))/(_d_*(_m_ + 1)),
        module_name='5.5.1 u (a+b arcsec(c x))^n',
        rule_number=8,
    ),
    # Rule 9
    SymPyReplacementPattern(
        pattern=Int(x**_m_*(_a_ + _b_*asec(x*_c_))**n_, x),
        constraints=(FreeQ([_a_, _b_, _c_], x), IntegerQ(n_), IntegerQ(_m_), Or(GtQ(n_, 0), LtQ(_m_, -1)),),
        replacement=_c_**(-_m_ - 1)*Subst(Int((x*_b_ + _a_)**n_*tan(x)*sec(x)**(_m_ + 1), x), x, asec(x*_c_)),
        module_name='5.5.1 u (a+b arcsec(c x))^n',
        rule_number=9,
    ),
    # Rule 10
    SymPyReplacementPattern(
        pattern=Int(x**_m_*(_a_ + _b_*acsc(x*_c_))**n_, x),
        constraints=(FreeQ([_a_, _b_, _c_], x), IntegerQ(n_), IntegerQ(_m_), Or(GtQ(n_, 0), LtQ(_m_, -1)),),
        replacement=-_c_**(-_m_ - 1)*Subst(Int((x*_b_ + _a_)**n_*cot(x)*csc(x)**(_m_ + 1), x), x, acsc(x*_c_)),
        module_name='5.5.1 u (a+b arcsec(c x))^n',
        rule_number=10,
    ),
    # Rule 11
    SymPyReplacementPattern(
        pattern=Int((_a_ + _b_*asec(x*_c_))/(x*_e_ + _d_), x),
        constraints=(FreeQ([_a_, _b_, _c_, _d_, _e_], x),),
        replacement=-_b_*Int(log(1 + (_e_ - sqrt(-_c_**2*_d_**2 + _e_**2))*exp(I*asec(x*_c_))/(_c_*_d_))/(x**2*sqrt(1 - 1/(x**2*_c_**2))), x)/(_c_*_e_) - _b_*Int(log(1 + (_e_ + sqrt(-_c_**2*_d_**2 + _e_**2))*exp(I*asec(x*_c_))/(_c_*_d_))/(x**2*sqrt(1 - 1/(x**2*_c_**2))), x)/(_c_*_e_) + _b_*Int(log(exp(2*I*asec(x*_c_)) + 1)/(x**2*sqrt(1 - 1/(x**2*_c_**2))), x)/(_c_*_e_) + (_a_ + _b_*asec(x*_c_))*log(1 + (_e_ - sqrt(-_c_**2*_d_**2 + _e_**2))*exp(I*asec(x*_c_))/(_c_*_d_))/_e_ + (_a_ + _b_*asec(x*_c_))*log(1 + (_e_ + sqrt(-_c_**2*_d_**2 + _e_**2))*exp(I*asec(x*_c_))/(_c_*_d_))/_e_ - (_a_ + _b_*asec(x*_c_))*log(exp(2*I*asec(x*_c_)) + 1)/_e_,
        module_name='5.5.1 u (a+b arcsec(c x))^n',
        rule_number=11,
    ),
    # Rule 12
    SymPyReplacementPattern(
        pattern=Int((_a_ + _b_*acsc(x*_c_))/(x*_e_ + _d_), x),
        constraints=(FreeQ([_a_, _b_, _c_, _d_, _e_], x),),
        replacement=_b_*Int(log(1 - I*(_e_ - sqrt(-_c_**2*_d_**2 + _e_**2))*exp(I*acsc(x*_c_))/(_c_*_d_))/(x**2*sqrt(1 - 1/(x**2*_c_**2))), x)/(_c_*_e_) + _b_*Int(log(1 - I*(_e_ + sqrt(-_c_**2*_d_**2 + _e_**2))*exp(I*acsc(x*_c_))/(_c_*_d_))/(x**2*sqrt(1 - 1/(x**2*_c_**2))), x)/(_c_*_e_) - _b_*Int(log(1 - exp(2*I*acsc(x*_c_)))/(x**2*sqrt(1 - 1/(x**2*_c_**2))), x)/(_c_*_e_) + (_a_ + _b_*acsc(x*_c_))*log(1 - I*(_e_ - sqrt(-_c_**2*_d_**2 + _e_**2))*exp(I*acsc(x*_c_))/(_c_*_d_))/_e_ + (_a_ + _b_*acsc(x*_c_))*log(1 - I*(_e_ + sqrt(-_c_**2*_d_**2 + _e_**2))*exp(I*acsc(x*_c_))/(_c_*_d_))/_e_ - (_a_ + _b_*acsc(x*_c_))*log(1 - exp(2*I*acsc(x*_c_)))/_e_,
        module_name='5.5.1 u (a+b arcsec(c x))^n',
        rule_number=12,
    ),
    # Rule 13
    SymPyReplacementPattern(
        pattern=Int((_a_ + _b_*asec(x*_c_))*(x*_e_ + _d_)**_m_, x),
        constraints=(FreeQ([_a_, _b_, _c_, _d_, _e_, _m_], x), NeQ(_m_, -1),),
        replacement=-_b_*Int((x*_e_ + _d_)**(_m_ + 1)/(x**2*sqrt(1 - 1/(x**2*_c_**2))), x)/(_c_*_e_*(_m_ + 1)) + (_a_ + _b_*asec(x*_c_))*(x*_e_ + _d_)**(_m_ + 1)/(_e_*(_m_ + 1)),
        module_name='5.5.1 u (a+b arcsec(c x))^n',
        rule_number=13,
    ),
    # Rule 14
    SymPyReplacementPattern(
        pattern=Int((_a_ + _b_*acsc(x*_c_))*(x*_e_ + _d_)**_m_, x),
        constraints=(FreeQ([_a_, _b_, _c_, _d_, _e_, _m_], x), NeQ(_m_, -1),),
        replacement=_b_*Int((x*_e_ + _d_)**(_m_ + 1)/(x**2*sqrt(1 - 1/(x**2*_c_**2))), x)/(_c_*_e_*(_m_ + 1)) + (_a_ + _b_*acsc(x*_c_))*(x*_e_ + _d_)**(_m_ + 1)/(_e_*(_m_ + 1)),
        module_name='5.5.1 u (a+b arcsec(c x))^n',
        rule_number=14,
    ),
    # Rule 15
    SymPyReplacementPattern(
        pattern=Int((_a_ + _b_*asec(x*_c_))*(x**2*_e_ + _d_)**_p_, x),
        constraints=(FreeQ([_a_, _b_, _c_, _d_, _e_], x), Or(IGtQ(_p_, 0), ILtQ(_p_ + sympy.S.Half, 0)),),
        replacement=With({u: IntHide((x**2*_e_ + _d_)**_p_, x)}, -x*_b_*_c_*Int(SimplifyIntegrand(u/(x*sqrt(x**2*_c_**2 - 1)), x), x)/sqrt(x**2*_c_**2) + Dist(_a_ + _b_*asec(x*_c_), u, x)),
        module_name='5.5.1 u (a+b arcsec(c x))^n',
        rule_number=15,
    ),
    # Rule 16
    SymPyReplacementPattern(
        pattern=Int((_a_ + _b_*acsc(x*_c_))*(x**2*_e_ + _d_)**_p_, x),
        constraints=(FreeQ([_a_, _b_, _c_, _d_, _e_], x), Or(IGtQ(_p_, 0), ILtQ(_p_ + sympy.S.Half, 0)),),
        replacement=With({u: IntHide((x**2*_e_ + _d_)**_p_, x)}, x*_b_*_c_*Int(SimplifyIntegrand(u/(x*sqrt(x**2*_c_**2 - 1)), x), x)/sqrt(x**2*_c_**2) + Dist(_a_ + _b_*acsc(x*_c_), u, x)),
        module_name='5.5.1 u (a+b arcsec(c x))^n',
        rule_number=16,
    ),
    # Rule 17
    SymPyReplacementPattern(
        pattern=Int((_a_ + _b_*asec(x*_c_))**_n_*(x**2*_e_ + _d_)**_p_, x),
        constraints=(FreeQ([_a_, _b_, _c_, _d_, _e_, _n_], x), IGtQ(_n_, 0), IntegerQ(_p_),),
        replacement=-Subst(Int(x**(-2*_p_ - 2)*(_a_ + _b_*acos(x/_c_))**_n_*(x**2*_d_ + _e_)**_p_, x), x, 1/x),
        module_name='5.5.1 u (a+b arcsec(c x))^n',
        rule_number=17,
    ),
    # Rule 18
    SymPyReplacementPattern(
        pattern=Int((_a_ + _b_*acsc(x*_c_))**_n_*(x**2*_e_ + _d_)**_p_, x),
        constraints=(FreeQ([_a_, _b_, _c_, _d_, _e_, _n_], x), IGtQ(_n_, 0), IntegerQ(_p_),),
        replacement=-Subst(Int(x**(-2*_p_ - 2)*(_a_ + _b_*asin(x/_c_))**_n_*(x**2*_d_ + _e_)**_p_, x), x, 1/x),
        module_name='5.5.1 u (a+b arcsec(c x))^n',
        rule_number=18,
    ),
    # Rule 19
    SymPyReplacementPattern(
        pattern=Int((_a_ + _b_*asec(x*_c_))**_n_*(x**2*_e_ + _d_)**p_, x),
        constraints=(FreeQ([_a_, _b_, _c_, _d_, _e_, _n_], x), IGtQ(_n_, 0), EqQ(_c_**2*_d_ + _e_, 0), IntegerQ(p_ + sympy.S.Half), GtQ(_e_, 0), LtQ(_d_, 0),),
        replacement=-sqrt(x**2)*Subst(Int(x**(-2*p_ - 2)*(_a_ + _b_*acos(x/_c_))**_n_*(x**2*_d_ + _e_)**p_, x), x, 1/x)/x,
        module_name='5.5.1 u (a+b arcsec(c x))^n',
        rule_number=19,
    ),
    # Rule 20
    SymPyReplacementPattern(
        pattern=Int((_a_ + _b_*acsc(x*_c_))**_n_*(x**2*_e_ + _d_)**p_, x),
        constraints=(FreeQ([_a_, _b_, _c_, _d_, _e_, _n_], x), IGtQ(_n_, 0), EqQ(_c_**2*_d_ + _e_, 0), IntegerQ(p_ + sympy.S.Half), GtQ(_e_, 0), LtQ(_d_, 0),),
        replacement=-sqrt(x**2)*Subst(Int(x**(-2*p_ - 2)*(_a_ + _b_*asin(x/_c_))**_n_*(x**2*_d_ + _e_)**p_, x), x, 1/x)/x,
        module_name='5.5.1 u (a+b arcsec(c x))^n',
        rule_number=20,
    ),
    # Rule 21
    SymPyReplacementPattern(
        pattern=Int((_a_ + _b_*asec(x*_c_))**_n_*(x**2*_e_ + _d_)**p_, x),
        constraints=(FreeQ([_a_, _b_, _c_, _d_, _e_, _n_], x), IGtQ(_n_, 0), EqQ(_c_**2*_d_ + _e_, 0), IntegerQ(p_ + sympy.S.Half), Not(And(GtQ(_e_, 0), LtQ(_d_, 0))),),
        replacement=-sqrt(x**2*_e_ + _d_)*Subst(Int(x**(-2*p_ - 2)*(_a_ + _b_*acos(x/_c_))**_n_*(x**2*_d_ + _e_)**p_, x), x, 1/x)/(x*sqrt(_e_ + _d_/x**2)),
        module_name='5.5.1 u (a+b arcsec(c x))^n',
        rule_number=21,
    ),
    # Rule 22
    SymPyReplacementPattern(
        pattern=Int((_a_ + _b_*acsc(x*_c_))**_n_*(x**2*_e_ + _d_)**p_, x),
        constraints=(FreeQ([_a_, _b_, _c_, _d_, _e_, _n_], x), IGtQ(_n_, 0), EqQ(_c_**2*_d_ + _e_, 0), IntegerQ(p_ + sympy.S.Half), Not(And(GtQ(_e_, 0), LtQ(_d_, 0))),),
        replacement=-sqrt(x**2*_e_ + _d_)*Subst(Int(x**(-2*p_ - 2)*(_a_ + _b_*asin(x/_c_))**_n_*(x**2*_d_ + _e_)**p_, x), x, 1/x)/(x*sqrt(_e_ + _d_/x**2)),
        module_name='5.5.1 u (a+b arcsec(c x))^n',
        rule_number=22,
    ),
    # Rule 23
    SymPyReplacementPattern(
        pattern=Int(x*(_a_ + _b_*asec(x*_c_))*(x**2*_e_ + _d_)**_p_, x),
        constraints=(FreeQ([_a_, _b_, _c_, _d_, _e_, _p_], x), NeQ(_p_, -1),),
        replacement=-x*_b_*_c_*Int((x**2*_e_ + _d_)**(_p_ + 1)/(x*sqrt(x**2*_c_**2 - 1)), x)/(2*_e_*sqrt(x**2*_c_**2)*(_p_ + 1)) + (_a_ + _b_*asec(x*_c_))*(x**2*_e_ + _d_)**(_p_ + 1)/(2*_e_*(_p_ + 1)),
        module_name='5.5.1 u (a+b arcsec(c x))^n',
        rule_number=23,
    ),
    # Rule 24
    SymPyReplacementPattern(
        pattern=Int(x*(_a_ + _b_*acsc(x*_c_))*(x**2*_e_ + _d_)**_p_, x),
        constraints=(FreeQ([_a_, _b_, _c_, _d_, _e_, _p_], x), NeQ(_p_, -1),),
        replacement=x*_b_*_c_*Int((x**2*_e_ + _d_)**(_p_ + 1)/(x*sqrt(x**2*_c_**2 - 1)), x)/(2*_e_*sqrt(x**2*_c_**2)*(_p_ + 1)) + (_a_ + _b_*acsc(x*_c_))*(x**2*_e_ + _d_)**(_p_ + 1)/(2*_e_*(_p_ + 1)),
        module_name='5.5.1 u (a+b arcsec(c x))^n',
        rule_number=24,
    ),
    # Rule 25
    SymPyReplacementPattern(
        pattern=Int((x*_f_)**_m_*(_a_ + _b_*asec(x*_c_))*(x**2*_e_ + _d_)**_p_, x),
        constraints=(FreeQ([_a_, _b_, _c_, _d_, _e_, _f_, _m_, _p_], x), Or(And(IGtQ(_p_, 0), Not(And(ILtQ(_m_/2 + sympy.S(-1)/2, 0), GtQ(_m_ + 2*_p_ + 3, 0)))), And(IGtQ(_m_/2 + sympy.S.Half, 0), Not(And(ILtQ(_p_, 0), GtQ(_m_ + 2*_p_ + 3, 0)))), And(ILtQ(_m_/2 + _p_ + sympy.S.Half, 0), Not(ILtQ(_m_/2 + sympy.S(-1)/2, 0)))),),
        replacement=With({u: IntHide((x*_f_)**_m_*(x**2*_e_ + _d_)**_p_, x)}, -x*_b_*_c_*Int(SimplifyIntegrand(u/(x*sqrt(x**2*_c_**2 - 1)), x), x)/sqrt(x**2*_c_**2) + Dist(_a_ + _b_*asec(x*_c_), u, x)),
        module_name='5.5.1 u (a+b arcsec(c x))^n',
        rule_number=25,
    ),
    # Rule 26
    SymPyReplacementPattern(
        pattern=Int((x*_f_)**_m_*(_a_ + _b_*acsc(x*_c_))*(x**2*_e_ + _d_)**_p_, x),
        constraints=(FreeQ([_a_, _b_, _c_, _d_, _e_, _f_, _m_, _p_], x), Or(And(IGtQ(_p_, 0), Not(And(ILtQ(_m_/2 + sympy.S(-1)/2, 0), GtQ(_m_ + 2*_p_ + 3, 0)))), And(IGtQ(_m_/2 + sympy.S.Half, 0), Not(And(ILtQ(_p_, 0), GtQ(_m_ + 2*_p_ + 3, 0)))), And(ILtQ(_m_/2 + _p_ + sympy.S.Half, 0), Not(ILtQ(_m_/2 + sympy.S(-1)/2, 0)))),),
        replacement=With({u: IntHide((x*_f_)**_m_*(x**2*_e_ + _d_)**_p_, x)}, x*_b_*_c_*Int(SimplifyIntegrand(u/(x*sqrt(x**2*_c_**2 - 1)), x), x)/sqrt(x**2*_c_**2) + Dist(_a_ + _b_*acsc(x*_c_), u, x)),
        module_name='5.5.1 u (a+b arcsec(c x))^n',
        rule_number=26,
    ),
    # Rule 27
    SymPyReplacementPattern(
        pattern=Int(x**_m_*(_a_ + _b_*asec(x*_c_))**_n_*(x**2*_e_ + _d_)**_p_, x),
        constraints=(FreeQ([_a_, _b_, _c_, _d_, _e_, _n_], x), IGtQ(_n_, 0), IntegerQ(_m_), IntegerQ(_p_),),
        replacement=-Subst(Int(x**(-_m_ - 2*_p_ - 2)*(_a_ + _b_*acos(x/_c_))**_n_*(x**2*_d_ + _e_)**_p_, x), x, 1/x),
        module_name='5.5.1 u (a+b arcsec(c x))^n',
        rule_number=27,
    ),
    # Rule 28
    SymPyReplacementPattern(
        pattern=Int(x**_m_*(_a_ + _b_*acsc(x*_c_))**_n_*(x**2*_e_ + _d_)**_p_, x),
        constraints=(FreeQ([_a_, _b_, _c_, _d_, _e_, _n_], x), IGtQ(_n_, 0), IntegerQ(_m_), IntegerQ(_p_),),
        replacement=-Subst(Int(x**(-_m_ - 2*_p_ - 2)*(_a_ + _b_*asin(x/_c_))**_n_*(x**2*_d_ + _e_)**_p_, x), x, 1/x),
        module_name='5.5.1 u (a+b arcsec(c x))^n',
        rule_number=28,
    ),
    # Rule 29
    SymPyReplacementPattern(
        pattern=Int(x**_m_*(_a_ + _b_*asec(x*_c_))**_n_*(x**2*_e_ + _d_)**p_, x),
        constraints=(FreeQ([_a_, _b_, _c_, _d_, _e_, _n_], x), IGtQ(_n_, 0), EqQ(_c_**2*_d_ + _e_, 0), IntegerQ(_m_), IntegerQ(p_ + sympy.S.Half), GtQ(_e_, 0), LtQ(_d_, 0),),
        replacement=-sqrt(x**2)*Subst(Int(x**(-_m_ - 2*p_ - 2)*(_a_ + _b_*acos(x/_c_))**_n_*(x**2*_d_ + _e_)**p_, x), x, 1/x)/x,
        module_name='5.5.1 u (a+b arcsec(c x))^n',
        rule_number=29,
    ),
    # Rule 30
    SymPyReplacementPattern(
        pattern=Int(x**_m_*(_a_ + _b_*acsc(x*_c_))**_n_*(x**2*_e_ + _d_)**p_, x),
        constraints=(FreeQ([_a_, _b_, _c_, _d_, _e_, _n_], x), IGtQ(_n_, 0), EqQ(_c_**2*_d_ + _e_, 0), IntegerQ(_m_), IntegerQ(p_ + sympy.S.Half), GtQ(_e_, 0), LtQ(_d_, 0),),
        replacement=-sqrt(x**2)*Subst(Int(x**(-_m_ - 2*p_ - 2)*(_a_ + _b_*asin(x/_c_))**_n_*(x**2*_d_ + _e_)**p_, x), x, 1/x)/x,
        module_name='5.5.1 u (a+b arcsec(c x))^n',
        rule_number=30,
    ),
    # Rule 31
    SymPyReplacementPattern(
        pattern=Int(x**_m_*(_a_ + _b_*asec(x*_c_))**_n_*(x**2*_e_ + _d_)**p_, x),
        constraints=(FreeQ([_a_, _b_, _c_, _d_, _e_, _n_], x), IGtQ(_n_, 0), EqQ(_c_**2*_d_ + _e_, 0), IntegerQ(_m_), IntegerQ(p_ + sympy.S.Half), Not(And(GtQ(_e_, 0), LtQ(_d_, 0))),),
        replacement=-sqrt(x**2*_e_ + _d_)*Subst(Int(x**(-_m_ - 2*p_ - 2)*(_a_ + _b_*acos(x/_c_))**_n_*(x**2*_d_ + _e_)**p_, x), x, 1/x)/(x*sqrt(_e_ + _d_/x**2)),
        module_name='5.5.1 u (a+b arcsec(c x))^n',
        rule_number=31,
    ),
    # Rule 32
    SymPyReplacementPattern(
        pattern=Int(x**_m_*(_a_ + _b_*acsc(x*_c_))**_n_*(x**2*_e_ + _d_)**p_, x),
        constraints=(FreeQ([_a_, _b_, _c_, _d_, _e_, _n_], x), IGtQ(_n_, 0), EqQ(_c_**2*_d_ + _e_, 0), IntegerQ(_m_), IntegerQ(p_ + sympy.S.Half), Not(And(GtQ(_e_, 0), LtQ(_d_, 0))),),
        replacement=-sqrt(x**2*_e_ + _d_)*Subst(Int(x**(-_m_ - 2*p_ - 2)*(_a_ + _b_*asin(x/_c_))**_n_*(x**2*_d_ + _e_)**p_, x), x, 1/x)/(x*sqrt(_e_ + _d_/x**2)),
        module_name='5.5.1 u (a+b arcsec(c x))^n',
        rule_number=32,
    ),
    # Rule 33
    SymPyReplacementPattern(
        pattern=Int(u_*(_a_ + _b_*asec(x*_c_)), x),
        constraints=(FreeQ([_a_, _b_, _c_], x), InverseFunctionFreeQ(IntHide(u_, x), x),),
        replacement=With({v: IntHide(u_, x)}, -_b_*Int(SimplifyIntegrand(v/(x**2*sqrt(1 - 1/(x**2*_c_**2))), x), x)/_c_ + Dist(_a_ + _b_*asec(x*_c_), v, x)),
        module_name='5.5.1 u (a+b arcsec(c x))^n',
        rule_number=33,
    ),
    # Rule 34
    SymPyReplacementPattern(
        pattern=Int(u_*(_a_ + _b_*acsc(x*_c_)), x),
        constraints=(FreeQ([_a_, _b_, _c_], x), InverseFunctionFreeQ(IntHide(u_, x), x),),
        replacement=With({v: IntHide(u_, x)}, _b_*Int(SimplifyIntegrand(v/(x**2*sqrt(1 - 1/(x**2*_c_**2))), x), x)/_c_ + Dist(_a_ + _b_*acsc(x*_c_), v, x)),
        module_name='5.5.1 u (a+b arcsec(c x))^n',
        rule_number=34,
    ),
    # Rule 35
    SymPyReplacementPattern(
        pattern=Int(_u_*(_a_ + _b_*asec(x*_c_))**_n_, x),
        constraints=(FreeQ([_a_, _b_, _c_, _n_], x),),
        replacement=Unintegrable(_u_*(_a_ + _b_*asec(x*_c_))**_n_, x),
        module_name='5.5.1 u (a+b arcsec(c x))^n',
        rule_number=35,
    ),
    # Rule 36
    SymPyReplacementPattern(
        pattern=Int(_u_*(_a_ + _b_*acsc(x*_c_))**_n_, x),
        constraints=(FreeQ([_a_, _b_, _c_, _n_], x),),
        replacement=Unintegrable(_u_*(_a_ + _b_*acsc(x*_c_))**_n_, x),
        module_name='5.5.1 u (a+b arcsec(c x))^n',
        rule_number=36,
    ),

]

# Summary: 36 rules translated, 0 skipped
