# -*- coding: utf-8 -*-
# =============================================================================
# !! AUTO-GENERATED FILE -- DO NOT EDIT !!
#
# Generated by: rubi_integrate/codegen/generate.py
# Source: 1.2.1.9 P(x) (a+b x+c x^2)^p (d+e x+f x^2)^q.m
# Module: 1.2.1.9 P(x) (a+b x+c x^2)^p (d+e x+f x^2)^q
#
# This file contains Rubi integration rules as SymPyReplacementPattern objects.
# Re-run the generator to update.
# =============================================================================
import sympy
from sympy import Symbol
from rubi_integrate.utils.rubi_utils import *  # bare-name access; sympy imports below override any conflicts (e.g. Not)
from sympy.logic.boolalg import Or, Not, And
from sympy import (
    sqrt,
)

from sympy_matching.wild import WildSymbol, IDENTITY_ELEMENT
from rubi_integrate.base_objects import Int, SymPyReplacementPattern
# Inert trig markers (Rubi's lowercase sin/cos/... patterns). Distinct opaque heads,
# NOT subclasses of sympy.sin -- see rubi-trig-deactivation-dispatch project note.
from rubi_integrate.utils import (
    # Wolfram standard constraints
    FreeQ, IntegerQ, EqQ, NeQ, IGtQ, ILtQ, GtQ, LtQ, PolyQ, LinearQ,
)

# --- Integration variable ---
x = Symbol('x')

# --- Rubi global option stubs (default False/placeholder) ---
UseGamma = sympy.Symbol('UseGamma')  # Rubi global option; treated as False in Python
u = Symbol('u')  # Generic integrand placeholder used in some Rubi constraint calls

# --- Rubi selector symbols ---
# Rubi passes Min/Max as bare SYMBOLS, not calls: Expon[Px, x, Min] selects the
# minimum exponent. The code emitter round-trips through SymPy's printer, which
# renders Symbol('Min') as the bare name `Min`, so the name must exist here.
# (A genuine Min[a, b] call is emitted qualified, as sympy.Min(...), so these
# bindings cannot shadow it.)
Min = Symbol('Min')
Max = Symbol('Max')

# --- Wildcard symbols ---
# dot wildcards (must match exactly one expression)
# optional wildcards (can match identity element if absent in commutative ops)

A = Symbol('A')
B = Symbol('B')
C = Symbol('C')
q = Symbol('q')

_A_ = WildSymbol('A', optional_value=IDENTITY_ELEMENT)
A_ = WildSymbol('A')
_B_ = WildSymbol('B', optional_value=IDENTITY_ELEMENT)
B_ = WildSymbol('B')
_C_ = WildSymbol('C', optional_value=IDENTITY_ELEMENT)
C_ = WildSymbol('C')
Px_ = WildSymbol('Px')
_a_ = WildSymbol('a', optional_value=IDENTITY_ELEMENT)
a_ = WildSymbol('a')
_b_ = WildSymbol('b', optional_value=IDENTITY_ELEMENT)
b_ = WildSymbol('b')
_c_ = WildSymbol('c', optional_value=IDENTITY_ELEMENT)
c_ = WildSymbol('c')
_d_ = WildSymbol('d', optional_value=IDENTITY_ELEMENT)
d_ = WildSymbol('d')
_e_ = WildSymbol('e', optional_value=IDENTITY_ELEMENT)
e_ = WildSymbol('e')
_f_ = WildSymbol('f', optional_value=IDENTITY_ELEMENT)
f_ = WildSymbol('f')
_p_ = WildSymbol('p', optional_value=IDENTITY_ELEMENT)
p_ = WildSymbol('p')
_q_ = WildSymbol('q', optional_value=IDENTITY_ELEMENT)
q_ = WildSymbol('q')
u_ = WildSymbol('u')

RULES = [
    # Rule 1
    SymPyReplacementPattern(
        pattern=Int(Px_*(x**2*_c_ + x*_b_ + a_)**_p_*(x**2*_f_ + x*_e_ + d_)**_q_, x),
        constraints=(FreeQ([a_, _b_, _c_, d_, _e_, _f_, _p_, _q_], x), PolyQ(Px_, x), EqQ(-a_*_f_ + _c_*d_, 0), EqQ(-a_*_e_ + _b_*d_, 0), Or(IntegerQ(_p_), GtQ(_c_/_f_, 0)), Or(Not(IntegerQ(_q_)), LeafCount(x**2*_f_ + x*_e_ + d_) <= LeafCount(x**2*_c_ + x*_b_ + a_)),),
        replacement=Star((_c_/_f_)**_p_, Int(Px_*(x**2*_f_ + x*_e_ + d_)**(_p_ + _q_), x)),
        module_name='1.2.1.9 P(x) (a+b x+c x^2)^p (d+e x+f x^2)^q',
        rule_number=1,
    ),
    # Rule 2
    SymPyReplacementPattern(
        pattern=Int(Px_*(x**2*_c_ + x*_b_ + a_)**_p_*(x**2*_f_ + x*_e_ + d_)**_q_, x),
        constraints=(FreeQ([a_, _b_, _c_, d_, _e_, _f_, _p_, _q_], x), PolyQ(Px_, x), EqQ(-a_*_f_ + _c_*d_, 0), EqQ(-a_*_e_ + _b_*d_, 0), Not(IntegerQ(_p_)), Not(IntegerQ(_q_)), Not(GtQ(_c_/_f_, 0)),),
        replacement=Star(a_**IntPart(_p_)*(x**2*_c_ + x*_b_ + a_)**FracPart(_p_)/(d_**IntPart(_p_)*(x**2*_f_ + x*_e_ + d_)**FracPart(_p_)), Int(Px_*(x**2*_f_ + x*_e_ + d_)**(_p_ + _q_), x)),
        module_name='1.2.1.9 P(x) (a+b x+c x^2)^p (d+e x+f x^2)^q',
        rule_number=2,
    ),
    # Rule 3
    SymPyReplacementPattern(
        pattern=Int(Px_*(x**2*_c_ + x*_b_ + a_)**_p_*(x**2*_f_ + x*_e_ + _d_)**_q_, x),
        constraints=(FreeQ([a_, _b_, _c_, _d_, _e_, _f_, _p_, _q_], x), PolyQ(Px_, x), EqQ(-4*a_*_c_ + _b_**2, 0), IntegerQ(_p_),),
        replacement=Star(_c_**(-_p_), Int(Px_*(x*_c_ + _b_/2)**(2*_p_)*(x**2*_f_ + x*_e_ + _d_)**_q_, x)),
        module_name='1.2.1.9 P(x) (a+b x+c x^2)^p (d+e x+f x^2)^q',
        rule_number=3,
    ),
    # Rule 4
    SymPyReplacementPattern(
        pattern=Int(Px_*(x**2*_f_ + _d_)**_q_*(x**2*_c_ + x*_b_ + a_)**_p_, x),
        constraints=(FreeQ([a_, _b_, _c_, _d_, _f_, _p_, _q_], x), PolyQ(Px_, x), EqQ(-4*a_*_c_ + _b_**2, 0), IntegerQ(_p_),),
        replacement=Star(_c_**(-_p_), Int(Px_*(x*_c_ + _b_/2)**(2*_p_)*(x**2*_f_ + _d_)**_q_, x)),
        module_name='1.2.1.9 P(x) (a+b x+c x^2)^p (d+e x+f x^2)^q',
        rule_number=4,
    ),
    # Rule 5
    SymPyReplacementPattern(
        pattern=Int(Px_*(x**2*_c_ + x*_b_ + a_)**_p_*(x**2*_f_ + x*_e_ + _d_)**_q_, x),
        constraints=(FreeQ([a_, _b_, _c_, _d_, _e_, _f_, _p_, _q_], x), PolyQ(Px_, x), EqQ(-4*a_*_c_ + _b_**2, 0), Not(IntegerQ(_p_)),),
        replacement=Star((x**2*_c_ + x*_b_ + a_)**FracPart(_p_)/((4*_c_)**IntPart(_p_)*(2*x*_c_ + _b_)**(2*FracPart(_p_))), Int((2*x*_c_ + _b_)**(2*_p_)*(x**2*_f_ + x*_e_ + _d_)**_q_, x)),
        module_name='1.2.1.9 P(x) (a+b x+c x^2)^p (d+e x+f x^2)^q',
        rule_number=5,
    ),
    # Rule 6
    SymPyReplacementPattern(
        pattern=Int(Px_*(x**2*_f_ + _d_)**_q_*(x**2*_c_ + x*_b_ + a_)**_p_, x),
        constraints=(FreeQ([a_, _b_, _c_, _d_, _f_, _p_, _q_], x), PolyQ(Px_, x), EqQ(-4*a_*_c_ + _b_**2, 0), Not(IntegerQ(_p_)),),
        replacement=Star((x**2*_c_ + x*_b_ + a_)**FracPart(_p_)/((4*_c_)**IntPart(_p_)*(2*x*_c_ + _b_)**(2*FracPart(_p_))), Int((2*x*_c_ + _b_)**(2*_p_)*(x**2*_f_ + _d_)**_q_, x)),
        module_name='1.2.1.9 P(x) (a+b x+c x^2)^p (d+e x+f x^2)^q',
        rule_number=6,
    ),
    # Rule 7
    SymPyReplacementPattern(
        pattern=Int(Px_*(x**2*_c_ + x*_b_ + a_)**p_*(x**2*_f_ + x*_e_ + d_)**q_, x),
        constraints=(FreeQ([a_, _b_, _c_, d_, _e_, _f_], x), PolyQ(Px_, x, 2), LtQ(p_, -1), GtQ(q_, 0), Not(IGtQ(q_, 0)),),
        replacement=With({A: Coeff(Px_, x, 0), B: Coeff(Px_, x, 1), C: Coeff(Px_, x, 2)}, -Star(1/(_c_*(p_ + 1)*(-4*a_*_c_ + _b_**2)), Int((x**2*_c_ + x*_b_ + a_)**(p_ + 1)*(x**2*_f_ + x*_e_ + d_)**(q_ - 1)*Simp(-x**2*_f_*(C*(2*a_*_c_*(2*q_ + 1) - _b_**2*(p_ + 2*q_ + 2)) + _c_*(-2*A*_c_ + B*_b_)*(2*p_ + 2*q_ + 3)) + x*(-_e_*(C*(2*a_*_c_*(q_ + 1) - _b_**2*(p_ + q_ + 2)) + _c_*(-2*A*_c_ + B*_b_)*(2*p_ + q_ + 3)) + 2*_f_*q_*(A*_b_*_c_ - 2*B*a_*_c_ + C*a_*_b_)) - d_*(C*(2*a_*_c_ - _b_**2*(p_ + 2)) + _c_*(2*p_ + 3)*(-2*A*_c_ + B*_b_)) + _e_*q_*(A*_b_*_c_ - 2*B*a_*_c_ + C*a_*_b_), x), x)) + (x**2*_c_ + x*_b_ + a_)**(p_ + 1)*(x**2*_f_ + x*_e_ + d_)**q_*(A*_b_*_c_ - 2*B*a_*_c_ + C*a_*_b_ - x*(-C*(-2*a_*_c_ + _b_**2) + _c_*(-2*A*_c_ + B*_b_)))/(_c_*(p_ + 1)*(-4*a_*_c_ + _b_**2))),
        module_name='1.2.1.9 P(x) (a+b x+c x^2)^p (d+e x+f x^2)^q',
        rule_number=7,
    ),
    # Rule 8
    SymPyReplacementPattern(
        pattern=Int(Px_*(x**2*_c_ + a_)**p_*(x**2*_f_ + x*_e_ + d_)**q_, x),
        constraints=(FreeQ([a_, _c_, d_, _e_, _f_], x), PolyQ(Px_, x, 2), LtQ(p_, -1), GtQ(q_, 0), Not(IGtQ(q_, 0)),),
        replacement=With({A: Coeff(Px_, x, 0), B: Coeff(Px_, x, 1), C: Coeff(Px_, x, 2)}, -Star(-1/(2*a_*_c_*(p_ + 1)), Int((x**2*_c_ + a_)**(p_ + 1)*(x**2*_f_ + x*_e_ + d_)**(q_ - 1)*Simp(A*_c_*d_*(2*p_ + 3) - x**2*_f_*(-A*_c_*(2*p_ + 2*q_ + 3) + C*a_*(2*q_ + 1)) + x*(A*_c_*_e_*(2*p_ + q_ + 3) - a_*(2*B*_f_*q_ + C*_e_*(q_ + 1))) - a_*(B*_e_*q_ + C*d_), x), x)) + (B*a_ - x*(A*_c_ - C*a_))*(x**2*_c_ + a_)**(p_ + 1)*(x**2*_f_ + x*_e_ + d_)**q_/(2*a_*_c_*(p_ + 1))),
        module_name='1.2.1.9 P(x) (a+b x+c x^2)^p (d+e x+f x^2)^q',
        rule_number=8,
    ),
    # Rule 9
    SymPyReplacementPattern(
        pattern=Int(Px_*(x**2*_f_ + d_)**q_*(x**2*_c_ + x*_b_ + a_)**p_, x),
        constraints=(FreeQ([a_, _b_, _c_, d_, _f_], x), PolyQ(Px_, x, 2), LtQ(p_, -1), GtQ(q_, 0), Not(IGtQ(q_, 0)),),
        replacement=With({A: Coeff(Px_, x, 0), B: Coeff(Px_, x, 1), C: Coeff(Px_, x, 2)}, -Star(1/(_c_*(p_ + 1)*(-4*a_*_c_ + _b_**2)), Int((x**2*_f_ + d_)**(q_ - 1)*(x**2*_c_ + x*_b_ + a_)**(p_ + 1)*Simp(-x**2*_f_*(C*(2*a_*_c_*(2*q_ + 1) - _b_**2*(p_ + 2*q_ + 2)) + _c_*(-2*A*_c_ + B*_b_)*(2*p_ + 2*q_ + 3)) + 2*x*_f_*q_*(A*_b_*_c_ - 2*B*a_*_c_ + C*a_*_b_) - d_*(C*(2*a_*_c_ - _b_**2*(p_ + 2)) + _c_*(2*p_ + 3)*(-2*A*_c_ + B*_b_)), x), x)) + (x**2*_f_ + d_)**q_*(x**2*_c_ + x*_b_ + a_)**(p_ + 1)*(A*_b_*_c_ - 2*B*a_*_c_ + C*a_*_b_ - x*(-C*(-2*a_*_c_ + _b_**2) + _c_*(-2*A*_c_ + B*_b_)))/(_c_*(p_ + 1)*(-4*a_*_c_ + _b_**2))),
        module_name='1.2.1.9 P(x) (a+b x+c x^2)^p (d+e x+f x^2)^q',
        rule_number=9,
    ),
    # Rule 10
    SymPyReplacementPattern(
        pattern=Int(Px_*(x**2*_c_ + x*_b_ + a_)**p_*(x**2*_f_ + x*_e_ + d_)**q_, x),
        constraints=(FreeQ([a_, _b_, _c_, d_, _e_, _f_, q_], x), PolyQ(Px_, x, 2), LtQ(p_, -1), NeQ(-(-a_*_e_ + _b_*d_)*(-_b_*_f_ + _c_*_e_) + (-a_*_f_ + _c_*d_)**2, 0), Not(And(Not(IntegerQ(p_)), ILtQ(q_, -1))), Not(IGtQ(q_, 0)),),
        replacement=With({A: Coeff(Px_, x, 0), B: Coeff(Px_, x, 1), C: Coeff(Px_, x, 2)}, Star(1/((p_ + 1)*(-4*a_*_c_ + _b_**2)*(-(-a_*_e_ + _b_*d_)*(-_b_*_f_ + _c_*_e_) + (-a_*_f_ + _c_*d_)**2)), Int((x**2*_c_ + x*_b_ + a_)**(p_ + 1)*(x**2*_f_ + x*_e_ + d_)**q_*Simp(-x**2*_c_*_f_*(2*p_ + 2*q_ + 5)*(2*A*_c_*(-a_*_f_ + _c_*d_) - 2*a_*(-B*_c_*_e_ - C*a_*_f_ + C*_c_*d_) + _b_**2*(A*_f_ + C*d_) - _b_*(A*_c_*_e_ + B*a_*_f_ + B*_c_*d_ + C*a_*_e_)) - x*(2*_f_*((A*_b_ - B*a_)*(_b_**2*_f_ + 2*_c_**2*d_ - _c_*(2*a_*_f_ + _b_*_e_)) + (A*_c_ - C*a_)*(2*a_*_c_*_e_ - _b_*(a_*_f_ + _c_*d_)))*(p_ + q_ + 2) - (_b_*_f_*(p_ + 1) - _c_*_e_*(2*p_ + q_ + 4))*(2*A*_c_*(-a_*_f_ + _c_*d_) - 2*a_*(-B*_c_*_e_ - C*a_*_f_ + C*_c_*d_) + _b_**2*(A*_f_ + C*d_) - _b_*(A*_c_*_e_ + B*a_*_f_ + B*_c_*d_ + C*a_*_e_))) - _e_*((A*_b_ - B*a_)*(_b_**2*_f_ + 2*_c_**2*d_ - _c_*(2*a_*_f_ + _b_*_e_)) + (A*_c_ - C*a_)*(2*a_*_c_*_e_ - _b_*(a_*_f_ + _c_*d_)))*(p_ + q_ + 2) + (p_ + 1)*(-(-a_*_e_ + _b_*d_)*(-_b_*_f_ + _c_*_e_) + (-a_*_f_ + _c_*d_)**2)*(-2*A*_c_ + B*_b_ - 2*C*a_) + (a_*_f_*(p_ + 1) - _c_*d_*(p_ + 2))*(2*A*_c_*(-a_*_f_ + _c_*d_) - 2*a_*(-B*_c_*_e_ - C*a_*_f_ + C*_c_*d_) + _b_**2*(A*_f_ + C*d_) - _b_*(A*_c_*_e_ + B*a_*_f_ + B*_c_*d_ + C*a_*_e_)), x), x)) + (x**2*_c_ + x*_b_ + a_)**(p_ + 1)*(x**2*_f_ + x*_e_ + d_)**(q_ + 1)*(x*_c_*(A*(_b_**2*_f_ + 2*_c_**2*d_ - _c_*(2*a_*_f_ + _b_*_e_)) - B*(a_*_b_*_f_ - 2*a_*_c_*_e_ + _b_*_c_*d_) + C*(-a_*_b_*_e_ - 2*a_*(-a_*_f_ + _c_*d_) + _b_**2*d_)) + (A*_b_ - B*a_)*(_b_**2*_f_ + 2*_c_**2*d_ - _c_*(2*a_*_f_ + _b_*_e_)) + (A*_c_ - C*a_)*(2*a_*_c_*_e_ - _b_*(a_*_f_ + _c_*d_)))/((p_ + 1)*(-4*a_*_c_ + _b_**2)*(-(-a_*_e_ + _b_*d_)*(-_b_*_f_ + _c_*_e_) + (-a_*_f_ + _c_*d_)**2))),
        module_name='1.2.1.9 P(x) (a+b x+c x^2)^p (d+e x+f x^2)^q',
        rule_number=10,
    ),
    # Rule 11
    SymPyReplacementPattern(
        pattern=Int(Px_*(x**2*_c_ + a_)**p_*(x**2*_f_ + x*_e_ + d_)**q_, x),
        constraints=(FreeQ([a_, _c_, d_, _e_, _f_, q_], x), PolyQ(Px_, x, 2), LtQ(p_, -1), NeQ(a_*_c_*_e_**2 + (-a_*_f_ + _c_*d_)**2, 0), Not(And(Not(IntegerQ(p_)), ILtQ(q_, -1))), Not(IGtQ(q_, 0)),),
        replacement=With({A: Coeff(Px_, x, 0), B: Coeff(Px_, x, 1), C: Coeff(Px_, x, 2)}, Star(-1/(4*a_*_c_*(p_ + 1)*(a_*_c_*_e_**2 + (-a_*_f_ + _c_*d_)**2)), Int((x**2*_c_ + a_)**(p_ + 1)*(x**2*_f_ + x*_e_ + d_)**q_*Simp(-x**2*_c_*_f_*(2*A*_c_*(-a_*_f_ + _c_*d_) - 2*a_*(-B*_c_*_e_ - C*a_*_f_ + C*_c_*d_))*(2*p_ + 2*q_ + 5) - x*(_c_*_e_*(2*A*_c_*(-a_*_f_ + _c_*d_) - 2*a_*(-B*_c_*_e_ - C*a_*_f_ + C*_c_*d_))*(2*p_ + q_ + 4) + 2*_f_*(-B*a_*(-2*a_*_c_*_f_ + 2*_c_**2*d_) + 2*a_*_c_*_e_*(A*_c_ - C*a_))*(p_ + q_ + 2)) - _e_*(-B*a_*(-2*a_*_c_*_f_ + 2*_c_**2*d_) + 2*a_*_c_*_e_*(A*_c_ - C*a_))*(p_ + q_ + 2) + (p_ + 1)*(-2*A*_c_ - 2*C*a_)*(a_*_c_*_e_**2 + (-a_*_f_ + _c_*d_)**2) + (2*A*_c_*(-a_*_f_ + _c_*d_) - 2*a_*(-B*_c_*_e_ - C*a_*_f_ + C*_c_*d_))*(a_*_f_*(p_ + 1) - _c_*d_*(p_ + 2)), x), x)) - (x**2*_c_ + a_)**(p_ + 1)*(x**2*_f_ + x*_e_ + d_)**(q_ + 1)*(-B*a_*(-2*a_*_c_*_f_ + 2*_c_**2*d_) + x*_c_*(A*(-2*a_*_c_*_f_ + 2*_c_**2*d_) + 2*B*a_*_c_*_e_ - 2*C*a_*(-a_*_f_ + _c_*d_)) + 2*a_*_c_*_e_*(A*_c_ - C*a_))/(4*a_*_c_*(p_ + 1)*(a_*_c_*_e_**2 + (-a_*_f_ + _c_*d_)**2))),
        module_name='1.2.1.9 P(x) (a+b x+c x^2)^p (d+e x+f x^2)^q',
        rule_number=11,
    ),
    # Rule 12
    SymPyReplacementPattern(
        pattern=Int(Px_*(x**2*_f_ + d_)**q_*(x**2*_c_ + x*_b_ + a_)**p_, x),
        constraints=(FreeQ([a_, _b_, _c_, d_, _f_, q_], x), PolyQ(Px_, x, 2), LtQ(p_, -1), NeQ(_b_**2*d_*_f_ + (-a_*_f_ + _c_*d_)**2, 0), Not(And(Not(IntegerQ(p_)), ILtQ(q_, -1))), Not(IGtQ(q_, 0)),),
        replacement=With({A: Coeff(Px_, x, 0), B: Coeff(Px_, x, 1), C: Coeff(Px_, x, 2)}, Star(1/((p_ + 1)*(-4*a_*_c_ + _b_**2)*(_b_**2*d_*_f_ + (-a_*_f_ + _c_*d_)**2)), Int((x**2*_f_ + d_)**q_*(x**2*_c_ + x*_b_ + a_)**(p_ + 1)*Simp(-x**2*_c_*_f_*(2*p_ + 2*q_ + 5)*(2*A*_c_*(-a_*_f_ + _c_*d_) - 2*a_*(-C*a_*_f_ + C*_c_*d_) + _b_**2*(A*_f_ + C*d_) - _b_*(B*a_*_f_ + B*_c_*d_)) - x*(-_b_*_f_*(p_ + 1)*(2*A*_c_*(-a_*_f_ + _c_*d_) - 2*a_*(-C*a_*_f_ + C*_c_*d_) + _b_**2*(A*_f_ + C*d_) - _b_*(B*a_*_f_ + B*_c_*d_)) + 2*_f_*(-_b_*(A*_c_ - C*a_)*(a_*_f_ + _c_*d_) + (A*_b_ - B*a_)*(-2*a_*_c_*_f_ + _b_**2*_f_ + 2*_c_**2*d_))*(p_ + q_ + 2)) + (p_ + 1)*(_b_**2*d_*_f_ + (-a_*_f_ + _c_*d_)**2)*(-2*A*_c_ + B*_b_ - 2*C*a_) + (a_*_f_*(p_ + 1) - _c_*d_*(p_ + 2))*(2*A*_c_*(-a_*_f_ + _c_*d_) - 2*a_*(-C*a_*_f_ + C*_c_*d_) + _b_**2*(A*_f_ + C*d_) - _b_*(B*a_*_f_ + B*_c_*d_)), x), x)) + (x**2*_f_ + d_)**(q_ + 1)*(x**2*_c_ + x*_b_ + a_)**(p_ + 1)*(x*_c_*(A*(-2*a_*_c_*_f_ + _b_**2*_f_ + 2*_c_**2*d_) - B*(a_*_b_*_f_ + _b_*_c_*d_) + C*(-2*a_*(-a_*_f_ + _c_*d_) + _b_**2*d_)) - _b_*(A*_c_ - C*a_)*(a_*_f_ + _c_*d_) + (A*_b_ - B*a_)*(-2*a_*_c_*_f_ + _b_**2*_f_ + 2*_c_**2*d_))/((p_ + 1)*(-4*a_*_c_ + _b_**2)*(_b_**2*d_*_f_ + (-a_*_f_ + _c_*d_)**2))),
        module_name='1.2.1.9 P(x) (a+b x+c x^2)^p (d+e x+f x^2)^q',
        rule_number=12,
    ),
    # Rule 13
    SymPyReplacementPattern(
        pattern=Int(Px_*(x**2*_c_ + x*_b_ + a_)**p_*(x**2*_f_ + x*_e_ + d_)**q_, x),
        constraints=(FreeQ([a_, _b_, _c_, d_, _e_, _f_, q_], x), PolyQ(Px_, x, 2), GtQ(p_, 0), NeQ(p_ + q_ + 1, 0), NeQ(2*p_ + 2*q_ + 3, 0), Not(IGtQ(p_, 0)), Not(IGtQ(q_, 0)),),
        replacement=With({A: Coeff(Px_, x, 0), B: Coeff(Px_, x, 1), C: Coeff(Px_, x, 2)}, -Star(1/(2*_c_*_f_**2*(2*p_ + 2*q_ + 3)*(p_ + q_ + 1)), Int((x**2*_c_ + x*_b_ + a_)**(p_ - 1)*(x**2*_f_ + x*_e_ + d_)**q_*Simp(x**2*(p_*(-_b_*_f_ + _c_*_e_)*(C*(q_ + 1)*(-_b_*_f_ + _c_*_e_) - _c_*(-B*_f_ + C*_e_)*(2*p_ + 2*q_ + 3)) + (C*_f_**2*p_*(-4*a_*_c_ + _b_**2) - _c_**2*(C*(-4*d_*_f_ + _e_**2)*(2*p_ + q_ + 2) + _f_*(2*p_ + 2*q_ + 3)*(2*A*_f_ - B*_e_ + 2*C*d_)))*(p_ + q_ + 1)) + x*(2*p_*(-a_*_f_ + _c_*d_)*(C*(q_ + 1)*(-_b_*_f_ + _c_*_e_) - _c_*(-B*_f_ + C*_e_)*(2*p_ + 2*q_ + 3)) + (C*_e_*_f_*p_*(-4*a_*_c_ + _b_**2) - _b_*_c_*(C*(-4*d_*_f_ + _e_**2)*(2*p_ + q_ + 2) + _f_*(2*p_ + 2*q_ + 3)*(2*A*_f_ - B*_e_ + 2*C*d_)))*(p_ + q_ + 1)) + p_*(-a_*_e_ + _b_*d_)*(C*(q_ + 1)*(-_b_*_f_ + _c_*_e_) - _c_*(-B*_f_ + C*_e_)*(2*p_ + 2*q_ + 3)) + (C*_b_**2*d_*_f_*p_ + a_*_c_*(C*(2*d_*_f_ - _e_**2*(2*p_ + q_ + 2)) + _f_*(-2*A*_f_ + B*_e_)*(2*p_ + 2*q_ + 3)))*(p_ + q_ + 1), x), x)) + (x**2*_c_ + x*_b_ + a_)**p_*(x**2*_f_ + x*_e_ + d_)**(q_ + 1)*(B*_c_*_f_*(2*p_ + 2*q_ + 3) + 2*C*x*_c_*_f_*(p_ + q_ + 1) + C*(_b_*_f_*p_ - _c_*_e_*(2*p_ + q_ + 2)))/(2*_c_*_f_**2*(2*p_ + 2*q_ + 3)*(p_ + q_ + 1))),
        module_name='1.2.1.9 P(x) (a+b x+c x^2)^p (d+e x+f x^2)^q',
        rule_number=13,
    ),
    # Rule 14
    SymPyReplacementPattern(
        pattern=Int(Px_*(x**2*_c_ + a_)**p_*(x**2*_f_ + x*_e_ + d_)**q_, x),
        constraints=(FreeQ([a_, _c_, d_, _e_, _f_, q_], x), PolyQ(Px_, x, 2), GtQ(p_, 0), NeQ(p_ + q_ + 1, 0), NeQ(2*p_ + 2*q_ + 3, 0), Not(IGtQ(p_, 0)), Not(IGtQ(q_, 0)),),
        replacement=With({A: Coeff(Px_, x, 0), B: Coeff(Px_, x, 1), C: Coeff(Px_, x, 2)}, -Star(1/(2*_c_*_f_**2*(2*p_ + 2*q_ + 3)*(p_ + q_ + 1)), Int((x**2*_c_ + a_)**(p_ - 1)*(x**2*_f_ + x*_e_ + d_)**q_*Simp(x**2*(_c_*_e_*p_*(C*_c_*_e_*(q_ + 1) - _c_*(-B*_f_ + C*_e_)*(2*p_ + 2*q_ + 3)) + (-4*C*a_*_c_*_f_**2*p_ - _c_**2*(C*(-4*d_*_f_ + _e_**2)*(2*p_ + q_ + 2) + _f_*(2*p_ + 2*q_ + 3)*(2*A*_f_ - B*_e_ + 2*C*d_)))*(p_ + q_ + 1)) + x*(-4*C*a_*_c_*_e_*_f_*p_*(p_ + q_ + 1) + 2*p_*(-a_*_f_ + _c_*d_)*(C*_c_*_e_*(q_ + 1) - _c_*(-B*_f_ + C*_e_)*(2*p_ + 2*q_ + 3))) + a_*_c_*(C*(2*d_*_f_ - _e_**2*(2*p_ + q_ + 2)) + _f_*(-2*A*_f_ + B*_e_)*(2*p_ + 2*q_ + 3))*(p_ + q_ + 1) - a_*_e_*p_*(C*_c_*_e_*(q_ + 1) - _c_*(-B*_f_ + C*_e_)*(2*p_ + 2*q_ + 3)), x), x)) + (x**2*_c_ + a_)**p_*(x**2*_f_ + x*_e_ + d_)**(q_ + 1)*(B*_c_*_f_*(2*p_ + 2*q_ + 3) + 2*C*x*_c_*_f_*(p_ + q_ + 1) - C*_c_*_e_*(2*p_ + q_ + 2))/(2*_c_*_f_**2*(2*p_ + 2*q_ + 3)*(p_ + q_ + 1))),
        module_name='1.2.1.9 P(x) (a+b x+c x^2)^p (d+e x+f x^2)^q',
        rule_number=14,
    ),
    # Rule 15
    SymPyReplacementPattern(
        pattern=Int(Px_*(x**2*_f_ + d_)**q_*(x**2*_c_ + x*_b_ + a_)**p_, x),
        constraints=(FreeQ([a_, _b_, _c_, d_, _f_, q_], x), PolyQ(Px_, x, 2), GtQ(p_, 0), NeQ(p_ + q_ + 1, 0), NeQ(2*p_ + 2*q_ + 3, 0), Not(IGtQ(p_, 0)), Not(IGtQ(q_, 0)),),
        replacement=With({A: Coeff(Px_, x, 0), B: Coeff(Px_, x, 1), C: Coeff(Px_, x, 2)}, -Star(1/(2*_c_*_f_**2*(2*p_ + 2*q_ + 3)*(p_ + q_ + 1)), Int((x**2*_f_ + d_)**q_*(x**2*_c_ + x*_b_ + a_)**(p_ - 1)*Simp(x**2*(-_b_*_f_*p_*(B*_c_*_f_*(2*p_ + 2*q_ + 3) - C*_b_*_f_*(q_ + 1)) + (C*_f_**2*p_*(-4*a_*_c_ + _b_**2) - _c_**2*(-4*C*d_*_f_*(2*p_ + q_ + 2) + _f_*(2*A*_f_ + 2*C*d_)*(2*p_ + 2*q_ + 3)))*(p_ + q_ + 1)) + x*(-_b_*_c_*(-4*C*d_*_f_*(2*p_ + q_ + 2) + _f_*(2*A*_f_ + 2*C*d_)*(2*p_ + 2*q_ + 3))*(p_ + q_ + 1) + 2*p_*(-a_*_f_ + _c_*d_)*(B*_c_*_f_*(2*p_ + 2*q_ + 3) - C*_b_*_f_*(q_ + 1))) + _b_*d_*p_*(B*_c_*_f_*(2*p_ + 2*q_ + 3) - C*_b_*_f_*(q_ + 1)) + (C*_b_**2*d_*_f_*p_ + a_*_c_*(-2*A*_f_**2*(2*p_ + 2*q_ + 3) + 2*C*d_*_f_))*(p_ + q_ + 1), x), x)) + (x**2*_f_ + d_)**(q_ + 1)*(x**2*_c_ + x*_b_ + a_)**p_*(B*_c_*_f_*(2*p_ + 2*q_ + 3) + 2*C*x*_c_*_f_*(p_ + q_ + 1) + C*_b_*_f_*p_)/(2*_c_*_f_**2*(2*p_ + 2*q_ + 3)*(p_ + q_ + 1))),
        module_name='1.2.1.9 P(x) (a+b x+c x^2)^p (d+e x+f x^2)^q',
        rule_number=15,
    ),
    # Rule 16
    SymPyReplacementPattern(
        pattern=Int(Px_/((x**2*_c_ + x*_b_ + a_)*(x**2*_f_ + x*_e_ + d_)), x),
        constraints=(FreeQ([a_, _b_, _c_, d_, _e_, _f_], x), PolyQ(Px_, x, 2), NeQ(a_**2*_f_**2 - a_*_b_*_e_*_f_ - 2*a_*_c_*d_*_f_ + a_*_c_*_e_**2 + _b_**2*d_*_f_ - _b_*_c_*d_*_e_ + _c_**2*d_**2, 0),),
        replacement=With({A: Coeff(Px_, x, 0), B: Coeff(Px_, x, 1), C: Coeff(Px_, x, 2), q: a_**2*_f_**2 - a_*_b_*_e_*_f_ - 2*a_*_c_*d_*_f_ + a_*_c_*_e_**2 + _b_**2*d_*_f_ - _b_*_c_*d_*_e_ + _c_**2*d_**2}, Star(1/q, Int((-A*a_*_c_*_f_ + A*_b_**2*_f_ - A*_b_*_c_*_e_ + A*_c_**2*d_ - B*a_*_b_*_f_ + B*a_*_c_*_e_ + C*a_**2*_f_ - C*a_*_c_*d_ + x*_c_*(A*_b_*_f_ - A*_c_*_e_ - B*a_*_f_ + B*_c_*d_ + C*a_*_e_ - C*_b_*d_))/(x**2*_c_ + x*_b_ + a_), x)) + Star(1/q, Int((A*a_*_f_**2 - A*_b_*_e_*_f_ - A*_c_*d_*_f_ + A*_c_*_e_**2 + B*_b_*d_*_f_ - B*_c_*d_*_e_ - C*a_*d_*_f_ + C*_c_*d_**2 - x*_f_*(A*_b_*_f_ - A*_c_*_e_ - B*a_*_f_ + B*_c_*d_ + C*a_*_e_ - C*_b_*d_))/(x**2*_f_ + x*_e_ + d_), x))),
        module_name='1.2.1.9 P(x) (a+b x+c x^2)^p (d+e x+f x^2)^q',
        rule_number=16,
    ),
    # Rule 17
    SymPyReplacementPattern(
        pattern=Int(Px_/((x**2*_f_ + d_)*(x**2*_c_ + x*_b_ + a_)), x),
        constraints=(FreeQ([a_, _b_, _c_, d_, _f_], x), PolyQ(Px_, x, 2), NeQ(a_**2*_f_**2 - 2*a_*_c_*d_*_f_ + _b_**2*d_*_f_ + _c_**2*d_**2, 0),),
        replacement=With({A: Coeff(Px_, x, 0), B: Coeff(Px_, x, 1), C: Coeff(Px_, x, 2), q: a_**2*_f_**2 - 2*a_*_c_*d_*_f_ + _b_**2*d_*_f_ + _c_**2*d_**2}, Star(1/q, Int((A*a_*_f_**2 - A*_c_*d_*_f_ + B*_b_*d_*_f_ - C*a_*d_*_f_ + C*_c_*d_**2 - x*_f_*(A*_b_*_f_ - B*a_*_f_ + B*_c_*d_ - C*_b_*d_))/(x**2*_f_ + d_), x)) + Star(1/q, Int((-A*a_*_c_*_f_ + A*_b_**2*_f_ + A*_c_**2*d_ - B*a_*_b_*_f_ + C*a_**2*_f_ - C*a_*_c_*d_ + x*_c_*(A*_b_*_f_ - B*a_*_f_ + B*_c_*d_ - C*_b_*d_))/(x**2*_c_ + x*_b_ + a_), x))),
        module_name='1.2.1.9 P(x) (a+b x+c x^2)^p (d+e x+f x^2)^q',
        rule_number=17,
    ),
    # Rule 18
    SymPyReplacementPattern(
        pattern=Int(Px_/((x**2*_c_ + x*_b_ + a_)*sqrt(x**2*_f_ + x*_e_ + _d_)), x),
        constraints=(FreeQ([a_, _b_, _c_, _d_, _e_, _f_], x), PolyQ(Px_, x, 2),),
        replacement=With({A: Coeff(Px_, x, 0), B: Coeff(Px_, x, 1), C: Coeff(Px_, x, 2)}, Star(1/_c_, Int((A*_c_ - C*a_ + x*(B*_c_ - C*_b_))/((x**2*_c_ + x*_b_ + a_)*sqrt(x**2*_f_ + x*_e_ + _d_)), x)) + Star(C/_c_, Int(1/sqrt(x**2*_f_ + x*_e_ + _d_), x))),
        module_name='1.2.1.9 P(x) (a+b x+c x^2)^p (d+e x+f x^2)^q',
        rule_number=18,
    ),
    # Rule 19
    SymPyReplacementPattern(
        pattern=Int(Px_/((x**2*_c_ + a_)*sqrt(x**2*_f_ + x*_e_ + _d_)), x),
        constraints=(FreeQ([a_, _c_, _d_, _e_, _f_], x), PolyQ(Px_, x, 2),),
        replacement=With({A: Coeff(Px_, x, 0), B: Coeff(Px_, x, 1), C: Coeff(Px_, x, 2)}, Star(1/_c_, Int((A*_c_ + B*x*_c_ - C*a_)/((x**2*_c_ + a_)*sqrt(x**2*_f_ + x*_e_ + _d_)), x)) + Star(C/_c_, Int(1/sqrt(x**2*_f_ + x*_e_ + _d_), x))),
        module_name='1.2.1.9 P(x) (a+b x+c x^2)^p (d+e x+f x^2)^q',
        rule_number=19,
    ),
    # Rule 20
    SymPyReplacementPattern(
        pattern=Int(Px_/(sqrt(x**2*_f_ + _d_)*(x**2*_c_ + x*_b_ + a_)), x),
        constraints=(FreeQ([a_, _b_, _c_, _d_, _f_], x), PolyQ(Px_, x, 2),),
        replacement=With({A: Coeff(Px_, x, 0), B: Coeff(Px_, x, 1), C: Coeff(Px_, x, 2)}, Star(1/_c_, Int((A*_c_ - C*a_ + x*(B*_c_ - C*_b_))/(sqrt(x**2*_f_ + _d_)*(x**2*_c_ + x*_b_ + a_)), x)) + Star(C/_c_, Int(1/sqrt(x**2*_f_ + _d_), x))),
        module_name='1.2.1.9 P(x) (a+b x+c x^2)^p (d+e x+f x^2)^q',
        rule_number=20,
    ),
    # Rule 21
    SymPyReplacementPattern(
        pattern=Int((_A_ + _B_*u_ + _C_*u_**2)*(_a_ + _b_*u_ + _c_*u_**2)**_p_*(_d_ + _e_*u_ + _f_*u_**2)**_q_, x),
        constraints=(FreeQ([_a_, _b_, _c_, _d_, _e_, _f_, _A_, _B_, _C_, _p_, _q_], x), LinearQ(u_, x), NeQ(u_, x),),
        replacement=Star(1/Coefficient(u_, x, 1), Subst(Int((x**2*_C_ + x*_B_ + _A_)*(x**2*_c_ + x*_b_ + _a_)**_p_*(x**2*_f_ + x*_e_ + _d_)**_q_, x), x, u_)),
        module_name='1.2.1.9 P(x) (a+b x+c x^2)^p (d+e x+f x^2)^q',
        rule_number=21,
    ),
    # Rule 22
    SymPyReplacementPattern(
        pattern=Int((_A_ + _B_*u_)*(_a_ + _b_*u_ + _c_*u_**2)**_p_*(_d_ + _e_*u_ + _f_*u_**2)**_q_, x),
        constraints=(FreeQ([_a_, _b_, _c_, _d_, _e_, _f_, _A_, _B_, Symbol('C'), _p_, _q_], x), LinearQ(u_, x), NeQ(u_, x),),
        replacement=Star(1/Coefficient(u_, x, 1), Subst(Int((x*_B_ + _A_)*(x**2*_c_ + x*_b_ + _a_)**_p_*(x**2*_f_ + x*_e_ + _d_)**_q_, x), x, u_)),
        module_name='1.2.1.9 P(x) (a+b x+c x^2)^p (d+e x+f x^2)^q',
        rule_number=22,
    ),
    # Rule 23
    SymPyReplacementPattern(
        pattern=Int((_A_ + _C_*u_**2)*(_a_ + _b_*u_ + _c_*u_**2)**_p_*(_d_ + _e_*u_ + _f_*u_**2)**_q_, x),
        constraints=(FreeQ([_a_, _b_, _c_, _d_, _e_, _f_, _A_, _C_, _p_, _q_], x), LinearQ(u_, x), NeQ(u_, x),),
        replacement=Star(1/Coefficient(u_, x, 1), Subst(Int((x**2*_C_ + _A_)*(x**2*_c_ + x*_b_ + _a_)**_p_*(x**2*_f_ + x*_e_ + _d_)**_q_, x), x, u_)),
        module_name='1.2.1.9 P(x) (a+b x+c x^2)^p (d+e x+f x^2)^q',
        rule_number=23,
    ),
    # Rule 24
    SymPyReplacementPattern(
        pattern=Int((_a_ + _c_*u_**2)**_p_*(_A_ + _B_*u_ + _C_*u_**2)*(_d_ + _e_*u_ + _f_*u_**2)**_q_, x),
        constraints=(FreeQ([_a_, _c_, _d_, _e_, _f_, _A_, _B_, _C_, _p_, _q_], x), LinearQ(u_, x), NeQ(u_, x),),
        replacement=Star(1/Coefficient(u_, x, 1), Subst(Int((x**2*_c_ + _a_)**_p_*(x**2*_C_ + x*_B_ + _A_)*(x**2*_f_ + x*_e_ + _d_)**_q_, x), x, u_)),
        module_name='1.2.1.9 P(x) (a+b x+c x^2)^p (d+e x+f x^2)^q',
        rule_number=24,
    ),
    # Rule 25
    SymPyReplacementPattern(
        pattern=Int((_A_ + _B_*u_)*(_a_ + _c_*u_**2)**_p_*(_d_ + _e_*u_ + _f_*u_**2)**_q_, x),
        constraints=(FreeQ([_a_, _c_, _d_, _e_, _f_, _A_, _B_, Symbol('C'), _p_, _q_], x), LinearQ(u_, x), NeQ(u_, x),),
        replacement=Star(1/Coefficient(u_, x, 1), Subst(Int((x*_B_ + _A_)*(x**2*_c_ + _a_)**_p_*(x**2*_f_ + x*_e_ + _d_)**_q_, x), x, u_)),
        module_name='1.2.1.9 P(x) (a+b x+c x^2)^p (d+e x+f x^2)^q',
        rule_number=25,
    ),
    # Rule 26
    SymPyReplacementPattern(
        pattern=Int((_A_ + _C_*u_**2)*(_a_ + _c_*u_**2)**_p_*(_d_ + _e_*u_ + _f_*u_**2)**_q_, x),
        constraints=(FreeQ([_a_, _c_, _d_, _e_, _f_, _A_, _C_, _p_, _q_], x), LinearQ(u_, x), NeQ(u_, x),),
        replacement=Star(1/Coefficient(u_, x, 1), Subst(Int((x**2*_C_ + _A_)*(x**2*_c_ + _a_)**_p_*(x**2*_f_ + x*_e_ + _d_)**_q_, x), x, u_)),
        module_name='1.2.1.9 P(x) (a+b x+c x^2)^p (d+e x+f x^2)^q',
        rule_number=26,
    ),

]

# Summary: 26 rules translated, 0 skipped
