# -*- coding: utf-8 -*-
# =============================================================================
# !! AUTO-GENERATED FILE -- DO NOT EDIT !!
#
# Generated by: rubi_integrate/codegen/generate.py
# Source: 1.2.1.6 P(x) (a+b x+c x^2)^p.m
# Module: 1.2.1.6 P(x) (a+b x+c x^2)^p
#
# This file contains Rubi integration rules as SymPyReplacementPattern objects.
# Re-run the generator to update.
# =============================================================================
import sympy
from sympy import Symbol
from rubi_integrate.utils.rubi_utils import *  # bare-name access; sympy imports below override any conflicts (e.g. Not)
from sympy.logic.boolalg import Not

from sympy_matching.wild import WildSymbol, IDENTITY_ELEMENT
from rubi_integrate.base_objects import Int, SymPyReplacementPattern
# Inert trig markers (Rubi's lowercase sin/cos/... patterns). Distinct opaque heads,
# NOT subclasses of sympy.sin -- see rubi-trig-deactivation-dispatch project note.
from rubi_integrate.utils import (
    # Wolfram standard constraints
    FreeQ, IntegerQ, MatchQ, EqQ, NeQ, IGtQ, LtQ, LeQ, PolyQ,
)

# --- Integration variable ---
x = Symbol('x')

# --- Rubi global option stubs (default False/placeholder) ---
UseGamma = sympy.Symbol('UseGamma')  # Rubi global option; treated as False in Python
u = Symbol('u')  # Generic integrand placeholder used in some Rubi constraint calls

# --- Rubi selector symbols ---
# Rubi passes Min/Max as bare SYMBOLS, not calls: Expon[Px, x, Min] selects the
# minimum exponent. The code emitter round-trips through SymPy's printer, which
# renders Symbol('Min') as the bare name `Min`, so the name must exist here.
# (A genuine Min[a, b] call is emitted qualified, as sympy.Min(...), so these
# bindings cannot shadow it.)
Min = Symbol('Min')
Max = Symbol('Max')

# --- Wildcard symbols ---
# dot wildcards (must match exactly one expression)
# optional wildcards (can match identity element if absent in commutative ops)

Q = Symbol('Q')
e = Symbol('e')
f = Symbol('f')
g = Symbol('g')
q = Symbol('q')

Pq_ = WildSymbol('Pq')
_a_ = WildSymbol('a', optional_value=IDENTITY_ELEMENT)
a_ = WildSymbol('a')
_b_ = WildSymbol('b', optional_value=IDENTITY_ELEMENT)
b_ = WildSymbol('b')
_c_ = WildSymbol('c', optional_value=IDENTITY_ELEMENT)
c_ = WildSymbol('c')
_m_ = WildSymbol('m', optional_value=IDENTITY_ELEMENT)
m_ = WildSymbol('m')
_p_ = WildSymbol('p', optional_value=IDENTITY_ELEMENT)
p_ = WildSymbol('p')
_u_ = WildSymbol('u', optional_value=IDENTITY_ELEMENT)
u_ = WildSymbol('u')

RULES = [
    # Rule 1
    SymPyReplacementPattern(
        pattern=Int(Pq_*(x**2*_c_ + x*_b_ + a_)**_p_, x),
        constraints=(FreeQ([a_, _b_, _c_], x), PolyQ(Pq_, x), IGtQ(_p_, -2),),
        replacement=Int(ExpandIntegrand(Pq_*(x**2*_c_ + x*_b_ + a_)**_p_, x), x),
        module_name='1.2.1.6 P(x) (a+b x+c x^2)^p',
        rule_number=1,
    ),
    # Rule 2
    SymPyReplacementPattern(
        pattern=Int(Pq_*(x**2*_c_ + x*_b_ + _a_)**p_, x),
        constraints=(FreeQ([_a_, _b_, _c_, p_], x), PolyQ(Pq_, x), EqQ(Coeff(Pq_, x, 0), 0), Not(MatchQ(Pq_, Condition(x**_m_*_u_, IntegerQ(_m_)))),),
        replacement=Int(x*(x**2*_c_ + x*_b_ + _a_)**p_*PolynomialQuotient(Pq_, x, x), x),
        module_name='1.2.1.6 P(x) (a+b x+c x^2)^p',
        rule_number=2,
    ),
    # Rule 3
    SymPyReplacementPattern(
        pattern=Int(Pq_*(x**2*_c_ + x*_b_ + a_)**p_, x),
        constraints=(FreeQ([a_, _b_, _c_, p_], x), PolyQ(Pq_, x), EqQ(-4*a_*_c_ + _b_**2, 0),),
        replacement=Star((x**2*_c_ + x*_b_ + a_)**FracPart(p_)/((4*_c_)**IntPart(p_)*(2*x*_c_ + _b_)**(2*FracPart(p_))), Int(Pq_*(2*x*_c_ + _b_)**(2*p_), x)),
        module_name='1.2.1.6 P(x) (a+b x+c x^2)^p',
        rule_number=3,
    ),
    # Rule 4
    SymPyReplacementPattern(
        pattern=Int(Pq_*(x**2*_c_ + x*_b_ + _a_)**p_, x),
        constraints=(FreeQ([_a_, _b_, _c_], x), PolyQ(Pq_, x), NeQ(-4*_a_*_c_ + _b_**2, 0), LtQ(p_, -1),),
        replacement=With({Q: PolynomialQuotient(Pq_, x**2*_c_ + x*_b_ + _a_, x), f: Coeff(PolynomialRemainder(Pq_, x**2*_c_ + x*_b_ + _a_, x), x, 0), g: Coeff(PolynomialRemainder(Pq_, x**2*_c_ + x*_b_ + _a_, x), x, 1)}, Star(1/((p_ + 1)*(-4*_a_*_c_ + _b_**2)), Int((x**2*_c_ + x*_b_ + _a_)**(p_ + 1)*ExpandToSum(Q*(p_ + 1)*(-4*_a_*_c_ + _b_**2) - (2*p_ + 3)*(2*f*_c_ - g*_b_), x), x)) + (f*_b_ - 2*g*_a_ + x*(2*f*_c_ - g*_b_))*(x**2*_c_ + x*_b_ + _a_)**(p_ + 1)/((p_ + 1)*(-4*_a_*_c_ + _b_**2))),
        module_name='1.2.1.6 P(x) (a+b x+c x^2)^p',
        rule_number=4,
    ),
    # Rule 5
    SymPyReplacementPattern(
        pattern=Int(Pq_*(x**2*_c_ + x*_b_ + _a_)**p_, x),
        constraints=(FreeQ([_a_, _b_, _c_, p_], x), PolyQ(Pq_, x), NeQ(-4*_a_*_c_ + _b_**2, 0), Not(LeQ(p_, -1)),),
        replacement=With({e: Coeff(Pq_, x, Expon(Pq_, x)), q: Expon(Pq_, x)}, e*x**(q - 1)*(x**2*_c_ + x*_b_ + _a_)**(p_ + 1)/(_c_*(q + 2*p_ + 1)) + Star(1/(_c_*(q + 2*p_ + 1)), Int((x**2*_c_ + x*_b_ + _a_)**p_*ExpandToSum(-e*x**q*_c_*(q + 2*p_ + 1) - e*x**(q - 2)*_a_*(q - 1) - e*x**(q - 1)*_b_*(q + p_) + Pq_*_c_*(q + 2*p_ + 1), x), x))),
        module_name='1.2.1.6 P(x) (a+b x+c x^2)^p',
        rule_number=5,
    ),

]

# Summary: 5 rules translated, 0 skipped
