# -*- coding: utf-8 -*-
# =============================================================================
# !! AUTO-GENERATED FILE -- DO NOT EDIT !!
#
# Generated by: rubi_integrate/codegen/generate.py
# Source: 1.2.1.4 (a+b x+c x^2)^p (d+e x+f x^2)^q.m
# Module: 1.2.1.4 (a+b x+c x^2)^p (d+e x+f x^2)^q
#
# This file contains Rubi integration rules as SymPyReplacementPattern objects.
# Re-run the generator to update.
# =============================================================================
import sympy
from sympy import Symbol
from rubi_integrate.utils.rubi_utils import *  # bare-name access; sympy imports below override any conflicts (e.g. Not)
from sympy.logic.boolalg import Or, Not, And
from sympy import (
    sqrt,
)

from sympy_matching.wild import WildSymbol, IDENTITY_ELEMENT
from rubi_integrate.base_objects import Int, SymPyReplacementPattern
# Inert trig markers (Rubi's lowercase sin/cos/... patterns). Distinct opaque heads,
# NOT subclasses of sympy.sin -- see rubi-trig-deactivation-dispatch project note.
from rubi_integrate.utils import (
    # Wolfram standard constraints
    FreeQ, IntegerQ, EqQ, NeQ, IGtQ, ILtQ, GtQ, LtQ, PosQ, NegQ,
    LinearQ, NiceSqrtQ, FractionalPowerFactorQ,
)

# --- Integration variable ---
x = Symbol('x')

# --- Rubi global option stubs (default False/placeholder) ---
UseGamma = sympy.Symbol('UseGamma')  # Rubi global option; treated as False in Python
u = Symbol('u')  # Generic integrand placeholder used in some Rubi constraint calls

# --- Rubi selector symbols ---
# Rubi passes Min/Max as bare SYMBOLS, not calls: Expon[Px, x, Min] selects the
# minimum exponent. The code emitter round-trips through SymPy's printer, which
# renders Symbol('Min') as the bare name `Min`, so the name must exist here.
# (A genuine Min[a, b] call is emitted qualified, as sympy.Min(...), so these
# bindings cannot shadow it.)
Min = Symbol('Min')
Max = Symbol('Max')

# --- Wildcard symbols ---
# dot wildcards (must match exactly one expression)
# optional wildcards (can match identity element if absent in commutative ops)

q = Symbol('q')
r = Symbol('r')

_a_ = WildSymbol('a', optional_value=IDENTITY_ELEMENT)
a_ = WildSymbol('a')
_b_ = WildSymbol('b', optional_value=IDENTITY_ELEMENT)
b_ = WildSymbol('b')
_c_ = WildSymbol('c', optional_value=IDENTITY_ELEMENT)
c_ = WildSymbol('c')
_d_ = WildSymbol('d', optional_value=IDENTITY_ELEMENT)
d_ = WildSymbol('d')
_e_ = WildSymbol('e', optional_value=IDENTITY_ELEMENT)
e_ = WildSymbol('e')
_f_ = WildSymbol('f', optional_value=IDENTITY_ELEMENT)
f_ = WildSymbol('f')
_p_ = WildSymbol('p', optional_value=IDENTITY_ELEMENT)
p_ = WildSymbol('p')
_q_ = WildSymbol('q', optional_value=IDENTITY_ELEMENT)
q_ = WildSymbol('q')
u_ = WildSymbol('u')

RULES = [
    # Rule 1
    SymPyReplacementPattern(
        pattern=Int((x**2*_c_ + x*_b_ + a_)**_p_*(x**2*_f_ + x*_e_ + _d_)**_q_, x),
        constraints=(FreeQ([a_, _b_, _c_, _d_, _e_, _f_, _q_], x), EqQ(-4*a_*_c_ + _b_**2, 0), IntegerQ(_p_),),
        replacement=Star(_c_**(-_p_), Int((x*_c_ + _b_/2)**(2*_p_)*(x**2*_f_ + x*_e_ + _d_)**_q_, x)),
        module_name='1.2.1.4 (a+b x+c x^2)^p (d+e x+f x^2)^q',
        rule_number=1,
    ),
    # Rule 2
    SymPyReplacementPattern(
        pattern=Int((x**2*_c_ + x*_b_ + a_)**_p_*(x**2*_f_ + x*_e_ + d_)**_q_, x),
        constraints=(FreeQ([a_, _b_, _c_, d_, _e_, _f_, _p_, _q_], x), EqQ(-a_*_f_ + _c_*d_, 0), EqQ(-a_*_e_ + _b_*d_, 0), Or(IntegerQ(_p_), GtQ(_c_/_f_, 0)), Or(Not(IntegerQ(_q_)), LeafCount(x**2*_f_ + x*_e_ + d_) <= LeafCount(x**2*_c_ + x*_b_ + a_)),),
        replacement=Star((_c_/_f_)**_p_, Int((x**2*_f_ + x*_e_ + d_)**(_p_ + _q_), x)),
        module_name='1.2.1.4 (a+b x+c x^2)^p (d+e x+f x^2)^q',
        rule_number=2,
    ),
    # Rule 3
    SymPyReplacementPattern(
        pattern=Int((x**2*_c_ + x*_b_ + a_)**p_*(x**2*_f_ + x*_e_ + d_)**_q_, x),
        constraints=(FreeQ([a_, _b_, _c_, d_, _e_, _f_, p_, _q_], x), EqQ(-a_*_f_ + _c_*d_, 0), EqQ(-a_*_e_ + _b_*d_, 0), Not(IntegerQ(p_)), Not(IntegerQ(_q_)), Not(GtQ(_c_/_f_, 0)),),
        replacement=Star(a_**IntPart(p_)*(x**2*_c_ + x*_b_ + a_)**FracPart(p_)/(d_**IntPart(p_)*(x**2*_f_ + x*_e_ + d_)**FracPart(p_)), Int((x**2*_f_ + x*_e_ + d_)**(p_ + _q_), x)),
        module_name='1.2.1.4 (a+b x+c x^2)^p (d+e x+f x^2)^q',
        rule_number=3,
    ),
    # Rule 4
    SymPyReplacementPattern(
        pattern=Int((x**2*_c_ + x*_b_ + a_)**p_*(x**2*_f_ + x*_e_ + d_)**_q_, x),
        constraints=(FreeQ([a_, _b_, _c_, d_, _e_, _f_, p_, _q_], x), EqQ(-4*a_*_c_ + _b_**2, 0), Not(IntegerQ(p_)),),
        replacement=Star((x**2*_c_ + x*_b_ + a_)**FracPart(p_)/((4*_c_)**IntPart(p_)*(2*x*_c_ + _b_)**(2*FracPart(p_))), Int((2*x*_c_ + _b_)**(2*p_)*(x**2*_f_ + x*_e_ + d_)**_q_, x)),
        module_name='1.2.1.4 (a+b x+c x^2)^p (d+e x+f x^2)^q',
        rule_number=4,
    ),
    # Rule 5
    SymPyReplacementPattern(
        pattern=Int((x**2*_f_ + d_)**_q_*(x**2*_c_ + x*_b_ + a_)**p_, x),
        constraints=(FreeQ([a_, _b_, _c_, d_, _f_, p_, _q_], x), EqQ(-4*a_*_c_ + _b_**2, 0), Not(IntegerQ(p_)),),
        replacement=Star((x**2*_c_ + x*_b_ + a_)**FracPart(p_)/((4*_c_)**IntPart(p_)*(2*x*_c_ + _b_)**(2*FracPart(p_))), Int((2*x*_c_ + _b_)**(2*p_)*(x**2*_f_ + d_)**_q_, x)),
        module_name='1.2.1.4 (a+b x+c x^2)^p (d+e x+f x^2)^q',
        rule_number=5,
    ),
    # Rule 6
    SymPyReplacementPattern(
        pattern=Int((x**2*_c_ + x*_b_ + _a_)**p_*(x**2*_f_ + x*_e_ + _d_)**q_, x),
        constraints=(FreeQ([_a_, _b_, _c_, _d_, _e_, _f_], x), ILtQ(p_, 0), IntegerQ(q_), NiceSqrtQ(-4*_a_*_c_ + _b_**2), Or(EqQ(p_, -1), Not(FractionalPowerFactorQ(Rt(-4*_a_*_c_ + _b_**2, 2)))),),
        replacement=With({r: Rt(-4*_a_*_c_ + _b_**2, 2)}, Star(_c_**(-p_), Int(ExpandIntegrand((-r/2 + x*_c_ + _b_/2)**p_*(r/2 + x*_c_ + _b_/2)**p_*(x**2*_f_ + x*_e_ + _d_)**q_, x), x))),
        module_name='1.2.1.4 (a+b x+c x^2)^p (d+e x+f x^2)^q',
        rule_number=6,
    ),
    # Rule 7
    SymPyReplacementPattern(
        pattern=Int((x**2*_f_ + _d_)**q_*(x**2*_c_ + x*_b_ + _a_)**p_, x),
        constraints=(FreeQ([_a_, _b_, _c_, _d_, _f_], x), ILtQ(p_, 0), IntegerQ(q_), NiceSqrtQ(-4*_a_*_c_ + _b_**2), Or(EqQ(p_, -1), Not(FractionalPowerFactorQ(Rt(-4*_a_*_c_ + _b_**2, 2)))),),
        replacement=With({r: Rt(-4*_a_*_c_ + _b_**2, 2)}, Star(_c_**(-p_), Int(ExpandIntegrand((x**2*_f_ + _d_)**q_*(-r/2 + x*_c_ + _b_/2)**p_*(r/2 + x*_c_ + _b_/2)**p_, x), x))),
        module_name='1.2.1.4 (a+b x+c x^2)^p (d+e x+f x^2)^q',
        rule_number=7,
    ),
    # Rule 8
    SymPyReplacementPattern(
        pattern=Int((x**2*_c_ + _a_)**p_*(x**2*_f_ + x*_e_ + _d_)**q_, x),
        constraints=(FreeQ([_a_, _c_, _d_, _e_, _f_], x), ILtQ(p_, 0), IntegerQ(q_), NiceSqrtQ(-_a_*_c_), Or(EqQ(p_, -1), Not(FractionalPowerFactorQ(Rt(-_a_*_c_, 2)))),),
        replacement=With({r: Rt(-_a_*_c_, 2)}, Star(_c_**(-p_), Int(ExpandIntegrand((-r + x*_c_)**p_*(r + x*_c_)**p_*(x**2*_f_ + x*_e_ + _d_)**q_, x), x))),
        module_name='1.2.1.4 (a+b x+c x^2)^p (d+e x+f x^2)^q',
        rule_number=8,
    ),
    # Rule 9
    SymPyReplacementPattern(
        pattern=Int((x**2*_c_ + x*_b_ + _a_)**p_*(x**2*_f_ + x*_e_ + _d_)**q_, x),
        constraints=(FreeQ([_a_, _b_, _c_, _d_, _e_, _f_], x), NeQ(-4*_a_*_c_ + _b_**2, 0), NeQ(-4*_d_*_f_ + _e_**2, 0), LtQ(p_, -1), GtQ(q_, 0), Not(IGtQ(q_, 0)),),
        replacement=-Star(1/((p_ + 1)*(-4*_a_*_c_ + _b_**2)), Int((x**2*_c_ + x*_b_ + _a_)**(p_ + 1)*(x**2*_f_ + x*_e_ + _d_)**(q_ - 1)*Simp(2*x**2*_c_*_f_*(2*p_ + 2*q_ + 3) + x*(2*_b_*_f_*q_ + 2*_c_*_e_*(2*p_ + q_ + 3)) + _b_*_e_*q_ + 2*_c_*_d_*(2*p_ + 3), x), x)) + (2*x*_c_ + _b_)*(x**2*_c_ + x*_b_ + _a_)**(p_ + 1)*(x**2*_f_ + x*_e_ + _d_)**q_/((p_ + 1)*(-4*_a_*_c_ + _b_**2)),
        module_name='1.2.1.4 (a+b x+c x^2)^p (d+e x+f x^2)^q',
        rule_number=9,
    ),
    # Rule 10
    SymPyReplacementPattern(
        pattern=Int((x**2*_f_ + _d_)**q_*(x**2*_c_ + x*_b_ + _a_)**p_, x),
        constraints=(FreeQ([_a_, _b_, _c_, _d_, _f_], x), NeQ(-4*_a_*_c_ + _b_**2, 0), LtQ(p_, -1), GtQ(q_, 0), Not(IGtQ(q_, 0)),),
        replacement=-Star(1/((p_ + 1)*(-4*_a_*_c_ + _b_**2)), Int((x**2*_f_ + _d_)**(q_ - 1)*(x**2*_c_ + x*_b_ + _a_)**(p_ + 1)*Simp(2*x**2*_c_*_f_*(2*p_ + 2*q_ + 3) + 2*x*_b_*_f_*q_ + 2*_c_*_d_*(2*p_ + 3), x), x)) + (2*x*_c_ + _b_)*(x**2*_f_ + _d_)**q_*(x**2*_c_ + x*_b_ + _a_)**(p_ + 1)/((p_ + 1)*(-4*_a_*_c_ + _b_**2)),
        module_name='1.2.1.4 (a+b x+c x^2)^p (d+e x+f x^2)^q',
        rule_number=10,
    ),
    # Rule 11: SKIPPED - ValueError: upstream Rubi arity typo (rule is inert in Mathematica too): TypeError: NeQ.__init__() missing 1 required positional argument: 'v'
    # Rule 12
    SymPyReplacementPattern(
        pattern=Int((x**2*_c_ + x*_b_ + _a_)**p_*(x**2*_f_ + x*_e_ + _d_)**q_, x),
        constraints=(FreeQ([_a_, _b_, _c_, _d_, _e_, _f_, q_], x), NeQ(-4*_a_*_c_ + _b_**2, 0), NeQ(-4*_d_*_f_ + _e_**2, 0), LtQ(p_, -1), NeQ(-(-_a_*_e_ + _b_*_d_)*(-_b_*_f_ + _c_*_e_) + (-_a_*_f_ + _c_*_d_)**2, 0), Not(And(Not(IntegerQ(p_)), ILtQ(q_, -1))), Not(IGtQ(q_, 0)),),
        replacement=-Star(1/((p_ + 1)*(-4*_a_*_c_ + _b_**2)*(-(-_a_*_e_ + _b_*_d_)*(-_b_*_f_ + _c_*_e_) + (-_a_*_f_ + _c_*_d_)**2)), Int((x**2*_c_ + x*_b_ + _a_)**(p_ + 1)*(x**2*_f_ + x*_e_ + _d_)**q_*Simp(x**2*_c_*_f_*(2*p_ + 2*q_ + 5)*(_b_**2*_f_ + 2*_c_**2*_d_ - _c_*(2*_a_*_f_ + _b_*_e_)) + x*(2*_f_*(p_ + q_ + 2)*(2*_a_*_c_**2*_e_ + _b_**3*_f_ - _b_**2*_c_*_e_ + _b_*_c_*(-3*_a_*_f_ + _c_*_d_)) - (_b_*_f_*(p_ + 1) - _c_*_e_*(2*p_ + q_ + 4))*(_b_**2*_f_ + 2*_c_**2*_d_ - _c_*(2*_a_*_f_ + _b_*_e_))) + 2*_c_*(p_ + 1)*(-(-_a_*_e_ + _b_*_d_)*(-_b_*_f_ + _c_*_e_) + (-_a_*_f_ + _c_*_d_)**2) - _e_*(p_ + q_ + 2)*(-2*_a_*_c_**2*_e_ - _b_**3*_f_ + _b_**2*_c_*_e_ - _b_*_c_*(-3*_a_*_f_ + _c_*_d_)) - (_a_*_f_*(p_ + 1) - _c_*_d_*(p_ + 2))*(_b_**2*_f_ + 2*_c_**2*_d_ - _c_*(2*_a_*_f_ + _b_*_e_)), x), x)) + (x**2*_c_ + x*_b_ + _a_)**(p_ + 1)*(x**2*_f_ + x*_e_ + _d_)**(q_ + 1)*(x*_c_*(_b_**2*_f_ + 2*_c_**2*_d_ - _c_*(2*_a_*_f_ + _b_*_e_)) + 2*_a_*_c_**2*_e_ + _b_**3*_f_ - _b_**2*_c_*_e_ + _b_*_c_*(-3*_a_*_f_ + _c_*_d_))/((p_ + 1)*(-4*_a_*_c_ + _b_**2)*(-(-_a_*_e_ + _b_*_d_)*(-_b_*_f_ + _c_*_e_) + (-_a_*_f_ + _c_*_d_)**2)),
        module_name='1.2.1.4 (a+b x+c x^2)^p (d+e x+f x^2)^q',
        rule_number=12,
    ),
    # Rule 13
    SymPyReplacementPattern(
        pattern=Int((x**2*_f_ + _d_)**q_*(x**2*_c_ + x*_b_ + _a_)**p_, x),
        constraints=(FreeQ([_a_, _b_, _c_, _d_, _f_, q_], x), NeQ(-4*_a_*_c_ + _b_**2, 0), LtQ(p_, -1), NeQ(_b_**2*_d_*_f_ + (-_a_*_f_ + _c_*_d_)**2, 0), Not(And(Not(IntegerQ(p_)), ILtQ(q_, -1))), Not(IGtQ(q_, 0)),),
        replacement=-Star(1/((p_ + 1)*(-4*_a_*_c_ + _b_**2)*(_b_**2*_d_*_f_ + (-_a_*_f_ + _c_*_d_)**2)), Int((x**2*_f_ + _d_)**q_*(x**2*_c_ + x*_b_ + _a_)**(p_ + 1)*Simp(x**2*_c_*_f_*(2*p_ + 2*q_ + 5)*(-2*_a_*_c_*_f_ + _b_**2*_f_ + 2*_c_**2*_d_) + x*(-_b_*_f_*(p_ + 1)*(-2*_a_*_c_*_f_ + _b_**2*_f_ + 2*_c_**2*_d_) + 2*_f_*(_b_**3*_f_ + _b_*_c_*(-3*_a_*_f_ + _c_*_d_))*(p_ + q_ + 2)) + 2*_c_*(p_ + 1)*(_b_**2*_d_*_f_ + (-_a_*_f_ + _c_*_d_)**2) - (_a_*_f_*(p_ + 1) - _c_*_d_*(p_ + 2))*(-2*_a_*_c_*_f_ + _b_**2*_f_ + 2*_c_**2*_d_), x), x)) + (x**2*_f_ + _d_)**(q_ + 1)*(x**2*_c_ + x*_b_ + _a_)**(p_ + 1)*(x*_c_*(-2*_a_*_c_*_f_ + _b_**2*_f_ + 2*_c_**2*_d_) + _b_**3*_f_ + _b_*_c_*(-3*_a_*_f_ + _c_*_d_))/((p_ + 1)*(-4*_a_*_c_ + _b_**2)*(_b_**2*_d_*_f_ + (-_a_*_f_ + _c_*_d_)**2)),
        module_name='1.2.1.4 (a+b x+c x^2)^p (d+e x+f x^2)^q',
        rule_number=13,
    ),
    # Rule 14
    SymPyReplacementPattern(
        pattern=Int((x**2*_c_ + _a_)**p_*(x**2*_f_ + x*_e_ + _d_)**q_, x),
        constraints=(FreeQ([_a_, _c_, _d_, _e_, _f_, q_], x), NeQ(-4*_d_*_f_ + _e_**2, 0), LtQ(p_, -1), NeQ(_a_*_c_*_e_**2 + (-_a_*_f_ + _c_*_d_)**2, 0), Not(And(Not(IntegerQ(p_)), ILtQ(q_, -1))), Not(IGtQ(q_, 0)),),
        replacement=-Star(-1/(4*_a_*_c_*(p_ + 1)*(_a_*_c_*_e_**2 + (-_a_*_f_ + _c_*_d_)**2)), Int((x**2*_c_ + _a_)**(p_ + 1)*(x**2*_f_ + x*_e_ + _d_)**q_*Simp(x**2*_c_*_f_*(-2*_a_*_c_*_f_ + 2*_c_**2*_d_)*(2*p_ + 2*q_ + 5) + x*(4*_a_*_c_**2*_e_*_f_*(p_ + q_ + 2) + _c_*_e_*(-2*_a_*_c_*_f_ + 2*_c_**2*_d_)*(2*p_ + q_ + 4)) + 2*_a_*_c_**2*_e_**2*(p_ + q_ + 2) + 2*_c_*(p_ + 1)*(_a_*_c_*_e_**2 + (-_a_*_f_ + _c_*_d_)**2) - (-2*_a_*_c_*_f_ + 2*_c_**2*_d_)*(_a_*_f_*(p_ + 1) - _c_*_d_*(p_ + 2)), x), x)) - (x**2*_c_ + _a_)**(p_ + 1)*(x*_c_*(-2*_a_*_c_*_f_ + 2*_c_**2*_d_) + 2*_a_*_c_**2*_e_)*(x**2*_f_ + x*_e_ + _d_)**(q_ + 1)/(4*_a_*_c_*(p_ + 1)*(_a_*_c_*_e_**2 + (-_a_*_f_ + _c_*_d_)**2)),
        module_name='1.2.1.4 (a+b x+c x^2)^p (d+e x+f x^2)^q',
        rule_number=14,
    ),
    # Rule 15
    SymPyReplacementPattern(
        pattern=Int((x**2*_c_ + x*_b_ + _a_)**p_*(x**2*_f_ + x*_e_ + _d_)**q_, x),
        constraints=(FreeQ([_a_, _b_, _c_, _d_, _e_, _f_, q_], x), NeQ(-4*_a_*_c_ + _b_**2, 0), NeQ(-4*_d_*_f_ + _e_**2, 0), GtQ(p_, 1), NeQ(p_ + q_, 0), NeQ(2*p_ + 2*q_ + 1, 0), Not(IGtQ(p_, 0)), Not(IGtQ(q_, 0)),),
        replacement=-Star(1/(2*_f_**2*(p_ + q_)*(2*p_ + 2*q_ + 1)), Int((x**2*_c_ + x*_b_ + _a_)**(p_ - 2)*(x**2*_f_ + x*_e_ + _d_)**q_*Simp(x**2*(_c_*(p_ + q_)*(-_c_*(2*_d_*_f_*(1 - 2*p_) + _e_**2*(3*p_ + q_ - 1)) + _f_*(-2*_a_*_f_ + _b_*_e_)*(4*p_ + 2*q_ - 1)) + p_*(1 - p_)*(-_b_*_f_ + _c_*_e_)**2) + x*((1 - p_)*(2*p_ + q_)*(-2*_a_*_f_ + 2*_c_*_d_)*(-_b_*_f_ + _c_*_e_) - (p_ + q_)*(_b_*(_c_*(2*p_ + q_)*(-4*_d_*_f_ + _e_**2) + _f_*(2*p_ + 2*q_ + 1)*(2*_a_*_f_ - _b_*_e_ + 2*_c_*_d_)) + _e_*_f_*(1 - p_)*(-4*_a_*_c_ + _b_**2))) + (1 - p_)*(2*p_ + q_)*(-_a_*_e_ + _b_*_d_)*(-_b_*_f_ + _c_*_e_) - (p_ + q_)*(-_a_*(_c_*(2*_d_*_f_ - _e_**2*(2*p_ + q_)) + _f_*(-2*_a_*_f_ + _b_*_e_)*(2*p_ + 2*q_ + 1)) + _b_**2*_d_*_f_*(1 - p_)), x), x)) + (x**2*_c_ + x*_b_ + _a_)**(p_ - 1)*(x**2*_f_ + x*_e_ + _d_)**(q_ + 1)*(2*x*_c_*_f_*(p_ + q_) + _b_*_f_*(3*p_ + 2*q_) - _c_*_e_*(2*p_ + q_))/(2*_f_**2*(p_ + q_)*(2*p_ + 2*q_ + 1)),
        module_name='1.2.1.4 (a+b x+c x^2)^p (d+e x+f x^2)^q',
        rule_number=15,
    ),
    # Rule 16
    SymPyReplacementPattern(
        pattern=Int((x**2*_f_ + _d_)**q_*(x**2*_c_ + x*_b_ + _a_)**p_, x),
        constraints=(FreeQ([_a_, _b_, _c_, _d_, _f_, q_], x), NeQ(-4*_a_*_c_ + _b_**2, 0), GtQ(p_, 1), NeQ(p_ + q_, 0), NeQ(2*p_ + 2*q_ + 1, 0), Not(IGtQ(p_, 0)), Not(IGtQ(q_, 0)),),
        replacement=-Star(1/(2*_f_*(p_ + q_)*(2*p_ + 2*q_ + 1)), Int((x**2*_f_ + _d_)**q_*(x**2*_c_ + x*_b_ + _a_)**(p_ - 2)*Simp(x**2*(_b_**2*_f_*p_*(1 - p_) + 2*_c_*(p_ + q_)*(-_a_*_f_*(4*p_ + 2*q_ - 1) + _c_*_d_*(2*p_ - 1))) - x*(2*_b_*(1 - p_)*(2*p_ + q_)*(-_a_*_f_ + _c_*_d_) - _b_*(2*p_ + 2*q_)*(2*_c_*_d_*(2*p_ + q_) - (_a_*_f_ + _c_*_d_)*(2*p_ + 2*q_ + 1))) + _b_**2*_d_*(2*p_ + q_)*(p_ - 1) - (p_ + q_)*(-2*_a_*(-_a_*_f_*(2*p_ + 2*q_ + 1) + _c_*_d_) + _b_**2*_d_*(1 - p_)), x), x)) + (x**2*_f_ + _d_)**(q_ + 1)*(2*x*_c_*(p_ + q_) + _b_*(3*p_ + 2*q_))*(x**2*_c_ + x*_b_ + _a_)**(p_ - 1)/(2*_f_*(p_ + q_)*(2*p_ + 2*q_ + 1)),
        module_name='1.2.1.4 (a+b x+c x^2)^p (d+e x+f x^2)^q',
        rule_number=16,
    ),
    # Rule 17
    SymPyReplacementPattern(
        pattern=Int((x**2*_c_ + _a_)**p_*(x**2*_f_ + x*_e_ + _d_)**q_, x),
        constraints=(FreeQ([_a_, _c_, _d_, _e_, _f_, q_], x), NeQ(-4*_d_*_f_ + _e_**2, 0), GtQ(p_, 1), NeQ(p_ + q_, 0), NeQ(2*p_ + 2*q_ + 1, 0), Not(IGtQ(p_, 0)), Not(IGtQ(q_, 0)),),
        replacement=-_c_*(x**2*_c_ + _a_)**(p_ - 1)*(-2*x*_f_*(p_ + q_) + _e_*(2*p_ + q_))*(x**2*_f_ + x*_e_ + _d_)**(q_ + 1)/(2*_f_**2*(p_ + q_)*(2*p_ + 2*q_ + 1)) - Star(1/(2*_f_**2*(p_ + q_)*(2*p_ + 2*q_ + 1)), Int((x**2*_c_ + _a_)**(p_ - 2)*(x**2*_f_ + x*_e_ + _d_)**q_*Simp(x**2*(_c_**2*_e_**2*p_*(1 - p_) - _c_*(p_ + q_)*(2*_a_*_f_**2*(4*p_ + 2*q_ - 1) + _c_*(2*_d_*_f_*(1 - 2*p_) + _e_**2*(3*p_ + q_ - 1)))) + x*(4*_a_*_c_*_e_*_f_*(1 - p_)*(p_ + q_) + _c_*_e_*(1 - p_)*(2*p_ + q_)*(-2*_a_*_f_ + 2*_c_*_d_)) - _a_*_c_*_e_**2*(1 - p_)*(2*p_ + q_) + _a_*(p_ + q_)*(-2*_a_*_f_**2*(2*p_ + 2*q_ + 1) + _c_*(2*_d_*_f_ - _e_**2*(2*p_ + q_))), x), x)),
        module_name='1.2.1.4 (a+b x+c x^2)^p (d+e x+f x^2)^q',
        rule_number=17,
    ),
    # Rule 18
    SymPyReplacementPattern(
        pattern=Int(1/((x**2*_c_ + x*_b_ + a_)*(x**2*_f_ + x*_e_ + d_)), x),
        constraints=(FreeQ([a_, _b_, _c_, d_, _e_, _f_], x), NeQ(-4*a_*_c_ + _b_**2, 0), NeQ(-4*d_*_f_ + _e_**2, 0), NeQ(a_**2*_f_**2 - a_*_b_*_e_*_f_ - 2*a_*_c_*d_*_f_ + a_*_c_*_e_**2 + _b_**2*d_*_f_ - _b_*_c_*d_*_e_ + _c_**2*d_**2, 0),),
        replacement=With({q: a_**2*_f_**2 - a_*_b_*_e_*_f_ - 2*a_*_c_*d_*_f_ + a_*_c_*_e_**2 + _b_**2*d_*_f_ - _b_*_c_*d_*_e_ + _c_**2*d_**2}, Star(1/q, Int((-x*(-_b_*_c_*_f_ + _c_**2*_e_) - a_*_c_*_f_ + _b_**2*_f_ - _b_*_c_*_e_ + _c_**2*d_)/(x**2*_c_ + x*_b_ + a_), x)) + Star(1/q, Int((x*(-_b_*_f_**2 + _c_*_e_*_f_) + a_*_f_**2 - _b_*_e_*_f_ - _c_*d_*_f_ + _c_*_e_**2)/(x**2*_f_ + x*_e_ + d_), x))),
        module_name='1.2.1.4 (a+b x+c x^2)^p (d+e x+f x^2)^q',
        rule_number=18,
    ),
    # Rule 19
    SymPyReplacementPattern(
        pattern=Int(1/((x**2*_f_ + d_)*(x**2*_c_ + x*_b_ + a_)), x),
        constraints=(FreeQ([a_, _b_, _c_, d_, _f_], x), NeQ(-4*a_*_c_ + _b_**2, 0), NeQ(a_**2*_f_**2 - 2*a_*_c_*d_*_f_ + _b_**2*d_*_f_ + _c_**2*d_**2, 0),),
        replacement=With({q: a_**2*_f_**2 - 2*a_*_c_*d_*_f_ + _b_**2*d_*_f_ + _c_**2*d_**2}, -Star(1/q, Int((x*_b_*_f_**2 - a_*_f_**2 + _c_*d_*_f_)/(x**2*_f_ + d_), x)) + Star(1/q, Int((x*_b_*_c_*_f_ - a_*_c_*_f_ + _b_**2*_f_ + _c_**2*d_)/(x**2*_c_ + x*_b_ + a_), x))),
        module_name='1.2.1.4 (a+b x+c x^2)^p (d+e x+f x^2)^q',
        rule_number=19,
    ),
    # Rule 20
    SymPyReplacementPattern(
        pattern=Int(1/((x**2*_c_ + x*_b_ + a_)*sqrt(x**2*_f_ + x*_e_ + _d_)), x),
        constraints=(FreeQ([a_, _b_, _c_, _d_, _e_, _f_], x), NeQ(-4*a_*_c_ + _b_**2, 0), NeQ(-4*_d_*_f_ + _e_**2, 0), EqQ(-_b_*_f_ + _c_*_e_, 0),),
        replacement=Star(-2*_e_, Subst(Int(1/(-x**2*(-a_*_e_ + _b_*_d_) + _e_*(-4*a_*_f_ + _b_*_e_)), x), x, (2*x*_f_ + _e_)/sqrt(x**2*_f_ + x*_e_ + _d_))),
        module_name='1.2.1.4 (a+b x+c x^2)^p (d+e x+f x^2)^q',
        rule_number=20,
    ),
    # Rule 21
    SymPyReplacementPattern(
        pattern=Int(1/((x**2*_c_ + x*_b_ + a_)*sqrt(x**2*_f_ + x*_e_ + _d_)), x),
        constraints=(FreeQ([a_, _b_, _c_, _d_, _e_, _f_], x), NeQ(-4*a_*_c_ + _b_**2, 0), NeQ(-4*_d_*_f_ + _e_**2, 0), NeQ(-_b_*_f_ + _c_*_e_, 0), PosQ(-4*a_*_c_ + _b_**2),),
        replacement=With({q: Rt(-4*a_*_c_ + _b_**2, 2)}, Star(2*_c_/q, Int(1/((-q + 2*x*_c_ + _b_)*sqrt(x**2*_f_ + x*_e_ + _d_)), x)) - Star(2*_c_/q, Int(1/((q + 2*x*_c_ + _b_)*sqrt(x**2*_f_ + x*_e_ + _d_)), x))),
        module_name='1.2.1.4 (a+b x+c x^2)^p (d+e x+f x^2)^q',
        rule_number=21,
    ),
    # Rule 22
    SymPyReplacementPattern(
        pattern=Int(1/(sqrt(x**2*_f_ + d_)*(x**2*_c_ + x*_b_ + a_)), x),
        constraints=(FreeQ([a_, _b_, _c_, d_, _f_], x), NeQ(-4*a_*_c_ + _b_**2, 0), PosQ(-4*a_*_c_ + _b_**2),),
        replacement=With({q: Rt(-4*a_*_c_ + _b_**2, 2)}, Star(2*_c_/q, Int(1/(sqrt(x**2*_f_ + d_)*(-q + 2*x*_c_ + _b_)), x)) - Star(2*_c_/q, Int(1/(sqrt(x**2*_f_ + d_)*(q + 2*x*_c_ + _b_)), x))),
        module_name='1.2.1.4 (a+b x+c x^2)^p (d+e x+f x^2)^q',
        rule_number=22,
    ),
    # Rule 23
    SymPyReplacementPattern(
        pattern=Int(1/((x**2*_c_ + a_)*sqrt(x**2*_f_ + x*_e_ + _d_)), x),
        constraints=(FreeQ([a_, _c_, _d_, _e_, _f_], x), NeQ(-4*_d_*_f_ + _e_**2, 0), PosQ(-a_*_c_),),
        replacement=Star(sympy.S.Half, Int(1/((-x*Rt(-a_*_c_, 2) + a_)*sqrt(x**2*_f_ + x*_e_ + _d_)), x)) + Star(sympy.S.Half, Int(1/((x*Rt(-a_*_c_, 2) + a_)*sqrt(x**2*_f_ + x*_e_ + _d_)), x)),
        module_name='1.2.1.4 (a+b x+c x^2)^p (d+e x+f x^2)^q',
        rule_number=23,
    ),
    # Rule 24
    SymPyReplacementPattern(
        pattern=Int(1/((x**2*_c_ + x*_b_ + _a_)*sqrt(x**2*_f_ + x*_e_ + _d_)), x),
        constraints=(FreeQ([_a_, _b_, _c_, _d_, _e_, _f_], x), NeQ(-4*_a_*_c_ + _b_**2, 0), NeQ(-4*_d_*_f_ + _e_**2, 0), NeQ(-_b_*_f_ + _c_*_e_, 0), NegQ(-4*_a_*_c_ + _b_**2),),
        replacement=With({q: Rt(-(-_a_*_e_ + _b_*_d_)*(-_b_*_f_ + _c_*_e_) + (-_a_*_f_ + _c_*_d_)**2, 2)}, -Star(1/(2*q), Int((-q + x*(-_b_*_f_ + _c_*_e_) - _a_*_f_ + _c_*_d_)/((x**2*_c_ + x*_b_ + _a_)*sqrt(x**2*_f_ + x*_e_ + _d_)), x)) + Star(1/(2*q), Int((q + x*(-_b_*_f_ + _c_*_e_) - _a_*_f_ + _c_*_d_)/((x**2*_c_ + x*_b_ + _a_)*sqrt(x**2*_f_ + x*_e_ + _d_)), x))),
        module_name='1.2.1.4 (a+b x+c x^2)^p (d+e x+f x^2)^q',
        rule_number=24,
    ),
    # Rule 25
    SymPyReplacementPattern(
        pattern=Int(1/((x**2*_c_ + _a_)*sqrt(x**2*_f_ + x*_e_ + _d_)), x),
        constraints=(FreeQ([_a_, _c_, _d_, _e_, _f_], x), NeQ(-4*_d_*_f_ + _e_**2, 0), NegQ(-_a_*_c_),),
        replacement=With({q: Rt(_a_*_c_*_e_**2 + (-_a_*_f_ + _c_*_d_)**2, 2)}, -Star(1/(2*q), Int((-q + x*_c_*_e_ - _a_*_f_ + _c_*_d_)/((x**2*_c_ + _a_)*sqrt(x**2*_f_ + x*_e_ + _d_)), x)) + Star(1/(2*q), Int((q + x*_c_*_e_ - _a_*_f_ + _c_*_d_)/((x**2*_c_ + _a_)*sqrt(x**2*_f_ + x*_e_ + _d_)), x))),
        module_name='1.2.1.4 (a+b x+c x^2)^p (d+e x+f x^2)^q',
        rule_number=25,
    ),
    # Rule 26
    SymPyReplacementPattern(
        pattern=Int(1/(sqrt(x**2*_f_ + _d_)*(x**2*_c_ + x*_b_ + _a_)), x),
        constraints=(FreeQ([_a_, _b_, _c_, _d_, _f_], x), NeQ(-4*_a_*_c_ + _b_**2, 0), NegQ(-4*_a_*_c_ + _b_**2),),
        replacement=With({q: Rt(_b_**2*_d_*_f_ + (-_a_*_f_ + _c_*_d_)**2, 2)}, -Star(1/(2*q), Int((-q - x*_b_*_f_ - _a_*_f_ + _c_*_d_)/(sqrt(x**2*_f_ + _d_)*(x**2*_c_ + x*_b_ + _a_)), x)) + Star(1/(2*q), Int((q - x*_b_*_f_ - _a_*_f_ + _c_*_d_)/(sqrt(x**2*_f_ + _d_)*(x**2*_c_ + x*_b_ + _a_)), x))),
        module_name='1.2.1.4 (a+b x+c x^2)^p (d+e x+f x^2)^q',
        rule_number=26,
    ),
    # Rule 27
    SymPyReplacementPattern(
        pattern=Int(sqrt(x**2*_c_ + x*_b_ + a_)/(x**2*_f_ + x*_e_ + d_), x),
        constraints=(FreeQ([a_, _b_, _c_, d_, _e_, _f_], x), NeQ(-4*a_*_c_ + _b_**2, 0), NeQ(-4*d_*_f_ + _e_**2, 0),),
        replacement=-Star(1/_f_, Int((x*(-_b_*_f_ + _c_*_e_) - a_*_f_ + _c_*d_)/(sqrt(x**2*_c_ + x*_b_ + a_)*(x**2*_f_ + x*_e_ + d_)), x)) + Star(_c_/_f_, Int(1/sqrt(x**2*_c_ + x*_b_ + a_), x)),
        module_name='1.2.1.4 (a+b x+c x^2)^p (d+e x+f x^2)^q',
        rule_number=27,
    ),
    # Rule 28
    SymPyReplacementPattern(
        pattern=Int(sqrt(x**2*_c_ + x*_b_ + a_)/(x**2*_f_ + d_), x),
        constraints=(FreeQ([a_, _b_, _c_, d_, _f_], x), NeQ(-4*a_*_c_ + _b_**2, 0),),
        replacement=-Star(1/_f_, Int((-x*_b_*_f_ - a_*_f_ + _c_*d_)/((x**2*_f_ + d_)*sqrt(x**2*_c_ + x*_b_ + a_)), x)) + Star(_c_/_f_, Int(1/sqrt(x**2*_c_ + x*_b_ + a_), x)),
        module_name='1.2.1.4 (a+b x+c x^2)^p (d+e x+f x^2)^q',
        rule_number=28,
    ),
    # Rule 29
    SymPyReplacementPattern(
        pattern=Int(sqrt(x**2*_c_ + a_)/(x**2*_f_ + x*_e_ + d_), x),
        constraints=(FreeQ([a_, _c_, d_, _e_, _f_], x), NeQ(-4*d_*_f_ + _e_**2, 0),),
        replacement=-Star(1/_f_, Int((x*_c_*_e_ - a_*_f_ + _c_*d_)/(sqrt(x**2*_c_ + a_)*(x**2*_f_ + x*_e_ + d_)), x)) + Star(_c_/_f_, Int(1/sqrt(x**2*_c_ + a_), x)),
        module_name='1.2.1.4 (a+b x+c x^2)^p (d+e x+f x^2)^q',
        rule_number=29,
    ),
    # Rule 30
    SymPyReplacementPattern(
        pattern=Int(1/(sqrt(x**2*_c_ + x*_b_ + a_)*sqrt(x**2*_f_ + x*_e_ + d_)), x),
        constraints=(FreeQ([a_, _b_, _c_, d_, _e_, _f_], x), NeQ(-4*a_*_c_ + _b_**2, 0), NeQ(-4*d_*_f_ + _e_**2, 0),),
        replacement=With({r: Rt(-4*a_*_c_ + _b_**2, 2)}, Star(sqrt(x*(r + _b_) + 2*a_)*sqrt(r + 2*x*_c_ + _b_)/sqrt(x**2*_c_ + x*_b_ + a_), Int(1/(sqrt(x*(r + _b_) + 2*a_)*sqrt(r + 2*x*_c_ + _b_)*sqrt(x**2*_f_ + x*_e_ + d_)), x))),
        module_name='1.2.1.4 (a+b x+c x^2)^p (d+e x+f x^2)^q',
        rule_number=30,
    ),
    # Rule 31
    SymPyReplacementPattern(
        pattern=Int(1/(sqrt(x**2*_f_ + d_)*sqrt(x**2*_c_ + x*_b_ + a_)), x),
        constraints=(FreeQ([a_, _b_, _c_, d_, _f_], x), NeQ(-4*a_*_c_ + _b_**2, 0),),
        replacement=With({r: Rt(-4*a_*_c_ + _b_**2, 2)}, Star(sqrt(x*(r + _b_) + 2*a_)*sqrt(r + 2*x*_c_ + _b_)/sqrt(x**2*_c_ + x*_b_ + a_), Int(1/(sqrt(x*(r + _b_) + 2*a_)*sqrt(x**2*_f_ + d_)*sqrt(r + 2*x*_c_ + _b_)), x))),
        module_name='1.2.1.4 (a+b x+c x^2)^p (d+e x+f x^2)^q',
        rule_number=31,
    ),
    # Rule 32
    SymPyReplacementPattern(
        pattern=Int((x**2*_c_ + x*_b_ + _a_)**p_*(x**2*_f_ + x*_e_ + _d_)**q_, x),
        constraints=(FreeQ([_a_, _b_, _c_, _d_, _e_, _f_, p_, q_], x), Not(IGtQ(p_, 0)), Not(IGtQ(q_, 0)),),
        replacement=Unintegrable((x**2*_c_ + x*_b_ + _a_)**p_*(x**2*_f_ + x*_e_ + _d_)**q_, x),
        module_name='1.2.1.4 (a+b x+c x^2)^p (d+e x+f x^2)^q',
        rule_number=32,
    ),
    # Rule 33
    SymPyReplacementPattern(
        pattern=Int((x**2*_c_ + a_)**p_*(x**2*_f_ + x*_e_ + _d_)**q_, x),
        constraints=(FreeQ([a_, _c_, _d_, _e_, _f_, p_, q_], x), Not(IGtQ(p_, 0)), Not(IGtQ(q_, 0)),),
        replacement=Unintegrable((x**2*_c_ + a_)**p_*(x**2*_f_ + x*_e_ + _d_)**q_, x),
        module_name='1.2.1.4 (a+b x+c x^2)^p (d+e x+f x^2)^q',
        rule_number=33,
    ),
    # Rule 34
    SymPyReplacementPattern(
        pattern=Int((_a_ + _b_*u_ + _c_*u_**2)**_p_*(_d_ + _e_*u_ + _f_*u_**2)**_q_, x),
        constraints=(FreeQ([_a_, _b_, _c_, _d_, _e_, _f_, _p_, _q_], x), LinearQ(u_, x), NeQ(u_, x),),
        replacement=Star(1/Coefficient(u_, x, 1), Subst(Int((x**2*_c_ + x*_b_ + _a_)**_p_*(x**2*_f_ + x*_e_ + _d_)**_q_, x), x, u_)),
        module_name='1.2.1.4 (a+b x+c x^2)^p (d+e x+f x^2)^q',
        rule_number=34,
    ),
    # Rule 35
    SymPyReplacementPattern(
        pattern=Int((_a_ + _c_*u_**2)**_p_*(_d_ + _e_*u_ + _f_*u_**2)**_q_, x),
        constraints=(FreeQ([_a_, _c_, _d_, _e_, _f_, _p_, _q_], x), LinearQ(u_, x), NeQ(u_, x),),
        replacement=Star(1/Coefficient(u_, x, 1), Subst(Int((x**2*_c_ + _a_)**_p_*(x**2*_f_ + x*_e_ + _d_)**_q_, x), x, u_)),
        module_name='1.2.1.4 (a+b x+c x^2)^p (d+e x+f x^2)^q',
        rule_number=35,
    ),

]

# Summary: 34 rules translated, 1 skipped
