# -*- coding: utf-8 -*-
# =============================================================================
# !! AUTO-GENERATED FILE -- DO NOT EDIT !!
#
# Generated by: rubi_integrate/codegen/generate.py
# Source: 1.1.1.3 (a+b x)^m (c+d x)^n (e+f x)^p.m
# Module: 1.1.1.3 (a+b x)^m (c+d x)^n (e+f x)^p
#
# This file contains Rubi integration rules as SymPyReplacementPattern objects.
# Re-run the generator to update.
# =============================================================================
import sympy
from sympy import Symbol
from rubi_integrate.utils.rubi_utils import *  # bare-name access; sympy imports below override any conflicts (e.g. Not)
from sympy.logic.boolalg import Or, Not, And
from sympy import (
    appellf1, asin, atan, elliptic_e, elliptic_f, floor, frac, hyper, log, sqrt,
)

from sympy_matching.wild import WildSymbol, IDENTITY_ELEMENT
from rubi_integrate.base_objects import Int, SymPyReplacementPattern
# Inert trig markers (Rubi's lowercase sin/cos/... patterns). Distinct opaque heads,
# NOT subclasses of sympy.sin -- see rubi-trig-deactivation-dispatch project note.
from rubi_integrate.utils import (
    # Wolfram standard constraints
    FreeQ, IntegerQ, EqQ, NeQ, IGtQ, ILtQ, GtQ, LtQ, GeQ, LeQ, PosQ, NegQ,
    IntegersQ, FractionQ, RationalQ, LinearQ, SimplerQ, SumSimplerQ,
)

# --- Integration variable ---
x = Symbol('x')

# --- Rubi global option stubs (default False/placeholder) ---
UseGamma = sympy.Symbol('UseGamma')  # Rubi global option; treated as False in Python
u = Symbol('u')  # Generic integrand placeholder used in some Rubi constraint calls

# --- Rubi selector symbols ---
# Rubi passes Min/Max as bare SYMBOLS, not calls: Expon[Px, x, Min] selects the
# minimum exponent. The code emitter round-trips through SymPy's printer, which
# renders Symbol('Min') as the bare name `Min`, so the name must exist here.
# (A genuine Min[a, b] call is emitted qualified, as sympy.Min(...), so these
# bindings cannot shadow it.)
Min = Symbol('Min')
Max = Symbol('Max')

# --- Wildcard symbols ---
# dot wildcards (must match exactly one expression)
# optional wildcards (can match identity element if absent in commutative ops)

k = Symbol('k')
q = Symbol('q')

_a_ = WildSymbol('a', optional_value=IDENTITY_ELEMENT)
a_ = WildSymbol('a')
_b_ = WildSymbol('b', optional_value=IDENTITY_ELEMENT)
b_ = WildSymbol('b')
_c_ = WildSymbol('c', optional_value=IDENTITY_ELEMENT)
c_ = WildSymbol('c')
_d_ = WildSymbol('d', optional_value=IDENTITY_ELEMENT)
d_ = WildSymbol('d')
_e_ = WildSymbol('e', optional_value=IDENTITY_ELEMENT)
e_ = WildSymbol('e')
_f_ = WildSymbol('f', optional_value=IDENTITY_ELEMENT)
f_ = WildSymbol('f')
_m_ = WildSymbol('m', optional_value=IDENTITY_ELEMENT)
m_ = WildSymbol('m')
_n_ = WildSymbol('n', optional_value=IDENTITY_ELEMENT)
n_ = WildSymbol('n')
_p_ = WildSymbol('p', optional_value=IDENTITY_ELEMENT)
p_ = WildSymbol('p')
u_ = WildSymbol('u')

RULES = [
    # Rule 1
    SymPyReplacementPattern(
        pattern=Int((x*_b_ + a_)**_m_*(x*_d_ + c_)**_n_*(x*_f_ + _e_)**_p_, x),
        constraints=(FreeQ([a_, _b_, c_, _d_, _e_, _f_, _m_, _n_, _p_], x), EqQ(a_*_d_ + _b_*c_, 0), EqQ(_n_, _m_), IntegerQ(_m_), Or(NeQ(_m_, -1), And(EqQ(_e_, 0), Or(EqQ(_p_, 1), Not(IntegerQ(_p_))))),),
        replacement=Int((x*_f_ + _e_)**_p_*(x**2*_b_*_d_ + a_*c_)**_m_, x),
        module_name='1.1.1.3 (a+b x)^m (c+d x)^n (e+f x)^p',
        rule_number=1,
    ),
    # Rule 2
    SymPyReplacementPattern(
        pattern=Int((x*_b_ + _a_)*(x*_d_ + _c_)**_n_*(x*_f_ + _e_)**_p_, x),
        constraints=(FreeQ([_a_, _b_, _c_, _d_, _e_, _f_, _n_, _p_], x), NeQ(_n_ + _p_ + 2, 0), EqQ(_a_*_d_*_f_*(_n_ + _p_ + 2) - _b_*(_c_*_f_*(_p_ + 1) + _d_*_e_*(_n_ + 1)), 0),),
        replacement=_b_*(x*_d_ + _c_)**(_n_ + 1)*(x*_f_ + _e_)**(_p_ + 1)/(_d_*_f_*(_n_ + _p_ + 2)),
        module_name='1.1.1.3 (a+b x)^m (c+d x)^n (e+f x)^p',
        rule_number=2,
    ),
    # Rule 3
    SymPyReplacementPattern(
        pattern=Int((x*_d_)**_n_*(x*_b_ + a_)*(x*_f_ + e_)**_p_, x),
        constraints=(FreeQ([a_, _b_, _d_, e_, _f_, _n_], x), IGtQ(_p_, 0), EqQ(a_*_f_ + _b_*e_, 0), Not(And(ILtQ(_n_ + _p_ + 2, 0), GtQ(_n_ + 2*_p_, 0))),),
        replacement=Int(ExpandIntegrand((x*_d_)**_n_*(x*_b_ + a_)*(x*_f_ + e_)**_p_, x), x),
        module_name='1.1.1.3 (a+b x)^m (c+d x)^n (e+f x)^p',
        rule_number=3,
    ),
    # Rule 4
    SymPyReplacementPattern(
        pattern=Int((x*_d_)**_n_*(x*_b_ + a_)*(x*_f_ + e_)**_p_, x),
        constraints=(FreeQ([a_, _b_, _d_, e_, _f_, _n_], x), IGtQ(_p_, 0), Or(NeQ(_n_, -1), EqQ(_p_, 1)), NeQ(a_*_f_ + _b_*e_, 0), Or(Not(IntegerQ(_n_)), LtQ(5*_n_ + 9*_p_, 0), GeQ(_n_ + _p_ + 1, 0), And(GeQ(_n_ + _p_ + 2, 0), RationalQ(a_, _b_, _d_, e_, _f_))), Or(NeQ(_n_ + _p_ + 3, 0), EqQ(_p_, 1)),),
        replacement=Int(ExpandIntegrand((x*_d_)**_n_*(x*_b_ + a_)*(x*_f_ + e_)**_p_, x), x),
        module_name='1.1.1.3 (a+b x)^m (c+d x)^n (e+f x)^p',
        rule_number=4,
    ),
    # Rule 5
    SymPyReplacementPattern(
        pattern=Int((x*_b_ + _a_)*(x*_d_ + c_)**_n_*(x*_f_ + _e_)**_p_, x),
        constraints=(FreeQ([_a_, _b_, c_, _d_, _e_, _f_, _n_], x), NeQ(-_a_*_d_ + _b_*c_, 0), Or(And(ILtQ(_n_, 0), ILtQ(_p_, 0)), EqQ(_p_, 1), And(IGtQ(_p_, 0), Or(Not(IntegerQ(_n_)), LeQ(5*_n_ + 9*_p_ + 10, 0), GeQ(_n_ + _p_ + 1, 0), And(GeQ(_n_ + _p_ + 2, 0), RationalQ(_a_, _b_, c_, _d_, _e_, _f_))))),),
        replacement=Int(ExpandIntegrand((x*_b_ + _a_)*(x*_d_ + c_)**_n_*(x*_f_ + _e_)**_p_, x), x),
        module_name='1.1.1.3 (a+b x)^m (c+d x)^n (e+f x)^p',
        rule_number=5,
    ),
    # Rule 6
    SymPyReplacementPattern(
        pattern=Int((x*_b_ + _a_)*(x*_d_ + _c_)**_n_*(x*_f_ + _e_)**_p_, x),
        constraints=(FreeQ([_a_, _b_, _c_, _d_, _e_, _f_, _n_], x), LtQ(_p_, -1), Or(Not(LtQ(_n_, -1)), IntegerQ(_p_), Not(Or(IntegerQ(_n_), Not(Or(EqQ(_e_, 0), Not(Or(EqQ(_c_, 0), LtQ(_p_, _n_)))))))),),
        replacement=(x*_d_ + _c_)**(_n_ + 1)*(x*_f_ + _e_)**(_p_ + 1)*(_a_*_f_ - _b_*_e_)/(_f_*(_p_ + 1)*(_c_*_f_ - _d_*_e_)) - (_a_*_d_*_f_*(_n_ + _p_ + 2) - _b_*(_c_*_f_*(_p_ + 1) + _d_*_e_*(_n_ + 1)))*Int((x*_d_ + _c_)**_n_*(x*_f_ + _e_)**(_p_ + 1), x)/(_f_*(_p_ + 1)*(_c_*_f_ - _d_*_e_)),
        module_name='1.1.1.3 (a+b x)^m (c+d x)^n (e+f x)^p',
        rule_number=6,
    ),
    # Rule 7
    SymPyReplacementPattern(
        pattern=Int((x*_b_ + _a_)*(x*_d_ + _c_)**_n_*(x*_f_ + _e_)**_p_, x),
        constraints=(FreeQ([_a_, _b_, _c_, _d_, _e_, _f_, _n_, _p_], x), Not(RationalQ(_p_)), SumSimplerQ(_p_, 1),),
        replacement=(x*_d_ + _c_)**(_n_ + 1)*(x*_f_ + _e_)**(_p_ + 1)*(_a_*_f_ - _b_*_e_)/(_f_*(_p_ + 1)*(_c_*_f_ - _d_*_e_)) - (_a_*_d_*_f_*(_n_ + _p_ + 2) - _b_*(_c_*_f_*(_p_ + 1) + _d_*_e_*(_n_ + 1)))*Int((x*_d_ + _c_)**_n_*(x*_f_ + _e_)**Simplify(_p_ + 1), x)/(_f_*(_p_ + 1)*(_c_*_f_ - _d_*_e_)),
        module_name='1.1.1.3 (a+b x)^m (c+d x)^n (e+f x)^p',
        rule_number=7,
    ),
    # Rule 8
    SymPyReplacementPattern(
        pattern=Int((x*_b_ + _a_)*(x*_d_ + _c_)**_n_*(x*_f_ + _e_)**_p_, x),
        constraints=(FreeQ([_a_, _b_, _c_, _d_, _e_, _f_, _n_, _p_], x), NeQ(_n_ + _p_ + 2, 0),),
        replacement=_b_*(x*_d_ + _c_)**(_n_ + 1)*(x*_f_ + _e_)**(_p_ + 1)/(_d_*_f_*(_n_ + _p_ + 2)) + (_a_*_d_*_f_*(_n_ + _p_ + 2) - _b_*(_c_*_f_*(_p_ + 1) + _d_*_e_*(_n_ + 1)))*Int((x*_d_ + _c_)**_n_*(x*_f_ + _e_)**_p_, x)/(_d_*_f_*(_n_ + _p_ + 2)),
        module_name='1.1.1.3 (a+b x)^m (c+d x)^n (e+f x)^p',
        rule_number=8,
    ),
    # Rule 9
    SymPyReplacementPattern(
        pattern=Int((x*_b_ + _a_)**2*(x*_d_ + _c_)**_n_*(x*_f_ + _e_)**_p_, x),
        constraints=(FreeQ([_a_, _b_, _c_, _d_, _e_, _f_, _n_, _p_], x), NeQ(_n_ + _p_ + 2, 0), NeQ(_n_ + _p_ + 3, 0), EqQ(-_b_*(_c_*_f_*(_p_ + 1) + _d_*_e_*(_n_ + 1))*(_a_*_d_*_f_*(_n_ + _p_ + 4) - _b_*(_c_*_f_*(_p_ + 2) + _d_*_e_*(_n_ + 2))) + _d_*_f_*(_a_**2*_d_*_f_*(_n_ + _p_ + 3) - _b_*(_a_*(_c_*_f_*(_p_ + 1) + _d_*_e_*(_n_ + 1)) + _b_*_c_*_e_))*(_n_ + _p_ + 2), 0),),
        replacement=_b_*(x*_d_ + _c_)**(_n_ + 1)*(x*_f_ + _e_)**(_p_ + 1)*(x*_b_*_d_*_f_*(_n_ + _p_ + 2) + 2*_a_*_d_*_f_*(_n_ + _p_ + 3) - _b_*(_c_*_f_*(_p_ + 2) + _d_*_e_*(_n_ + 2)))/(_d_**2*_f_**2*(_n_ + _p_ + 2)*(_n_ + _p_ + 3)),
        module_name='1.1.1.3 (a+b x)^m (c+d x)^n (e+f x)^p',
        rule_number=9,
    ),
    # Rule 10
    SymPyReplacementPattern(
        pattern=Int((x*_f_)**_p_*(x*_b_ + _a_)**_m_*(x*_d_ + _c_)**_n_, x),
        constraints=(FreeQ([_a_, _b_, _c_, _d_, _f_, _m_, _n_, _p_], x), EqQ(_a_*_d_ + _b_*_c_, 0), EqQ(_m_ - _n_ - 1, 0), Not(RationalQ(_p_)), Not(IGtQ(_m_, 0)), NeQ(_m_ + _n_ + _p_ + 2, 0),),
        replacement=_a_*Int((x*_f_)**_p_*(x*_b_ + _a_)**_n_*(x*_d_ + _c_)**_n_, x) + _b_*Int((x*_f_)**(_p_ + 1)*(x*_b_ + _a_)**_n_*(x*_d_ + _c_)**_n_, x)/_f_,
        module_name='1.1.1.3 (a+b x)^m (c+d x)^n (e+f x)^p',
        rule_number=10,
    ),
    # Rule 11
    SymPyReplacementPattern(
        pattern=Int((x*_f_ + _e_)**_p_/((x*_b_ + _a_)*(x*_d_ + _c_)), x),
        constraints=(FreeQ([_a_, _b_, _c_, _d_, _e_, _f_], x), IntegerQ(_p_),),
        replacement=Int(ExpandIntegrand((x*_f_ + _e_)**_p_/((x*_b_ + _a_)*(x*_d_ + _c_)), x), x),
        module_name='1.1.1.3 (a+b x)^m (c+d x)^n (e+f x)^p',
        rule_number=11,
    ),
    # Rule 12
    SymPyReplacementPattern(
        pattern=Int((x*_f_ + _e_)**p_/((x*_b_ + _a_)*(x*_d_ + _c_)), x),
        constraints=(FreeQ([_a_, _b_, _c_, _d_, _e_, _f_], x), LtQ(0, p_, 1),),
        replacement=(-_a_*_f_ + _b_*_e_)*Int((x*_f_ + _e_)**(p_ - 1)/(x*_b_ + _a_), x)/(-_a_*_d_ + _b_*_c_) - (-_c_*_f_ + _d_*_e_)*Int((x*_f_ + _e_)**(p_ - 1)/(x*_d_ + _c_), x)/(-_a_*_d_ + _b_*_c_),
        module_name='1.1.1.3 (a+b x)^m (c+d x)^n (e+f x)^p',
        rule_number=12,
    ),
    # Rule 13
    SymPyReplacementPattern(
        pattern=Int((x*_f_ + _e_)**p_/((x*_b_ + _a_)*(x*_d_ + _c_)), x),
        constraints=(FreeQ([_a_, _b_, _c_, _d_, _e_, _f_], x), GtQ(p_, 1),),
        replacement=_f_*(x*_f_ + _e_)**(p_ - 1)/(_b_*_d_*(p_ - 1)) + Int((x*_f_ + _e_)**(p_ - 2)*(x*_f_*(-_a_*_d_*_f_ - _b_*_c_*_f_ + 2*_b_*_d_*_e_) - _a_*_c_*_f_**2 + _b_*_d_*_e_**2)/((x*_b_ + _a_)*(x*_d_ + _c_)), x)/(_b_*_d_),
        module_name='1.1.1.3 (a+b x)^m (c+d x)^n (e+f x)^p',
        rule_number=13,
    ),
    # Rule 14
    SymPyReplacementPattern(
        pattern=Int((x*_f_ + _e_)**p_/((x*_b_ + _a_)*(x*_d_ + _c_)), x),
        constraints=(FreeQ([_a_, _b_, _c_, _d_, _e_, _f_], x), LtQ(p_, -1),),
        replacement=_f_*(x*_f_ + _e_)**(p_ + 1)/((p_ + 1)*(-_a_*_f_ + _b_*_e_)*(-_c_*_f_ + _d_*_e_)) + Int((x*_f_ + _e_)**(p_ + 1)*(-x*_b_*_d_*_f_ - _a_*_d_*_f_ - _b_*_c_*_f_ + _b_*_d_*_e_)/((x*_b_ + _a_)*(x*_d_ + _c_)), x)/((-_a_*_f_ + _b_*_e_)*(-_c_*_f_ + _d_*_e_)),
        module_name='1.1.1.3 (a+b x)^m (c+d x)^n (e+f x)^p',
        rule_number=14,
    ),
    # Rule 15
    SymPyReplacementPattern(
        pattern=Int((x*_f_ + _e_)**p_/((x*_b_ + _a_)*(x*_d_ + _c_)), x),
        constraints=(FreeQ([_a_, _b_, _c_, _d_, _e_, _f_, p_], x), Not(IntegerQ(p_)),),
        replacement=_b_*Int((x*_f_ + _e_)**p_/(x*_b_ + _a_), x)/(-_a_*_d_ + _b_*_c_) - _d_*Int((x*_f_ + _e_)**p_/(x*_d_ + _c_), x)/(-_a_*_d_ + _b_*_c_),
        module_name='1.1.1.3 (a+b x)^m (c+d x)^n (e+f x)^p',
        rule_number=15,
    ),
    # Rule 16
    SymPyReplacementPattern(
        pattern=Int((x*_d_ + _c_)**_n_*(x*_f_ + _e_)**p_/(x*_b_ + _a_), x),
        constraints=(FreeQ([_a_, _b_, _c_, _d_, _e_, _f_], x), IGtQ(_n_, 0), LtQ(p_, -1), FractionQ(p_),),
        replacement=Int(ExpandIntegrand((x*_f_ + _e_)**frac(p_), (x*_d_ + _c_)**_n_*(x*_f_ + _e_)**floor(p_)/(x*_b_ + _a_), x), x),
        module_name='1.1.1.3 (a+b x)^m (c+d x)^n (e+f x)^p',
        rule_number=16,
    ),
    # Rule 17
    SymPyReplacementPattern(
        pattern=Int((x*_b_ + _a_)**_m_*(x*_d_ + _c_)**_n_*(x*_f_ + _e_)**_p_, x),
        constraints=(FreeQ([_a_, _b_, _c_, _d_, _e_, _f_, _p_], x), IntegersQ(_m_, _n_), Or(IntegerQ(_p_), And(GtQ(_m_, 0), GeQ(_n_, -1))),),
        replacement=Int(ExpandIntegrand((x*_b_ + _a_)**_m_*(x*_d_ + _c_)**_n_*(x*_f_ + _e_)**_p_, x), x),
        module_name='1.1.1.3 (a+b x)^m (c+d x)^n (e+f x)^p',
        rule_number=17,
    ),
    # Rule 18
    SymPyReplacementPattern(
        pattern=Int((x*_b_ + _a_)**2*(x*_d_ + _c_)**_n_*(x*_f_ + _e_)**_p_, x),
        constraints=(FreeQ([_a_, _b_, _c_, _d_, _e_, _f_, _n_, _p_], x), Or(LtQ(_n_, -1), And(EqQ(_n_ + _p_ + 3, 0), NeQ(_n_, -1), Or(SumSimplerQ(_n_, 1), Not(SumSimplerQ(_p_, 1))))),),
        replacement=(x*_d_ + _c_)**(_n_ + 1)*(x*_f_ + _e_)**(_p_ + 1)*(-_a_*_d_ + _b_*_c_)**2/(_d_**2*(_n_ + 1)*(-_c_*_f_ + _d_*_e_)) - Int((x*_d_ + _c_)**(_n_ + 1)*(x*_f_ + _e_)**_p_*Simp(-x*_b_**2*_d_*(_n_ + 1)*(-_c_*_f_ + _d_*_e_) + _a_**2*_d_**2*_f_*(_n_ + _p_ + 2) - 2*_a_*_b_*_d_*(_c_*_f_*(_p_ + 1) + _d_*_e_*(_n_ + 1)) + _b_**2*_c_*(_c_*_f_*(_p_ + 1) + _d_*_e_*(_n_ + 1)), x), x)/(_d_**2*(_n_ + 1)*(-_c_*_f_ + _d_*_e_)),
        module_name='1.1.1.3 (a+b x)^m (c+d x)^n (e+f x)^p',
        rule_number=18,
    ),
    # Rule 19
    SymPyReplacementPattern(
        pattern=Int((x*_b_ + _a_)**2*(x*_d_ + _c_)**_n_*(x*_f_ + _e_)**_p_, x),
        constraints=(FreeQ([_a_, _b_, _c_, _d_, _e_, _f_, _n_, _p_], x), NeQ(_n_ + _p_ + 3, 0),),
        replacement=_b_*(x*_b_ + _a_)*(x*_d_ + _c_)**(_n_ + 1)*(x*_f_ + _e_)**(_p_ + 1)/(_d_*_f_*(_n_ + _p_ + 3)) + Int((x*_d_ + _c_)**_n_*(x*_f_ + _e_)**_p_*Simp(x*_b_*(_a_*_d_*_f_*(_n_ + _p_ + 4) - _b_*(_c_*_f_*(_p_ + 2) + _d_*_e_*(_n_ + 2))) + _a_**2*_d_*_f_*(_n_ + _p_ + 3) - _b_*(_a_*(_c_*_f_*(_p_ + 1) + _d_*_e_*(_n_ + 1)) + _b_*_c_*_e_), x), x)/(_d_*_f_*(_n_ + _p_ + 3)),
        module_name='1.1.1.3 (a+b x)^m (c+d x)^n (e+f x)^p',
        rule_number=19,
    ),
    # Rule 20
    SymPyReplacementPattern(
        pattern=Int(1/((x*_b_ + _a_)**(sympy.S(1)/3)*(x*_d_ + _c_)**(sympy.S(2)/3)*(x*_f_ + _e_)), x),
        constraints=(FreeQ([_a_, _b_, _c_, _d_, _e_, _f_], x),),
        replacement=With({q: Rt((-_c_*_f_ + _d_*_e_)/(-_a_*_f_ + _b_*_e_), 3)}, -sqrt(3)*q*atan(2*sqrt(3)*q*(x*_b_ + _a_)**(sympy.S(1)/3)/(3*(x*_d_ + _c_)**(sympy.S(1)/3)) + sqrt(3)/3)/(-_c_*_f_ + _d_*_e_) - 3*q*log(q*(x*_b_ + _a_)**(sympy.S(1)/3) - (x*_d_ + _c_)**(sympy.S(1)/3))/(-2*_c_*_f_ + 2*_d_*_e_) + q*log(x*_f_ + _e_)/(-2*_c_*_f_ + 2*_d_*_e_)),
        module_name='1.1.1.3 (a+b x)^m (c+d x)^n (e+f x)^p',
        rule_number=20,
    ),
    # Rule 21
    SymPyReplacementPattern(
        pattern=Int(1/(sqrt(x*_b_ + _a_)*sqrt(x*_d_ + _c_)*(x*_f_ + _e_)), x),
        constraints=(FreeQ([_a_, _b_, _c_, _d_, _e_, _f_], x), EqQ(2*_b_*_d_*_e_ - _f_*(_a_*_d_ + _b_*_c_), 0),),
        replacement=_b_*_f_*Subst(Int(1/(x**2*_b_*_f_**2 + _d_*(-_a_*_f_ + _b_*_e_)**2), x), x, sqrt(x*_b_ + _a_)*sqrt(x*_d_ + _c_)),
        module_name='1.1.1.3 (a+b x)^m (c+d x)^n (e+f x)^p',
        rule_number=21,
    ),
    # Rule 22
    SymPyReplacementPattern(
        pattern=Int((x*_b_ + _a_)**m_*(x*_d_ + _c_)**n_/(x*_f_ + _e_), x),
        constraints=(FreeQ([_a_, _b_, _c_, _d_, _e_, _f_], x), EqQ(m_ + n_ + 1, 0), RationalQ(n_), LtQ(-1, m_, 0), SimplerQ(x*_b_ + _a_, x*_d_ + _c_),),
        replacement=With({q: Denominator(m_)}, q*Subst(Int(x**(q*(m_ + 1) - 1)/(-x**q*(-_c_*_f_ + _d_*_e_) - _a_*_f_ + _b_*_e_), x), x, (x*_b_ + _a_)**(1/q)/(x*_d_ + _c_)**(1/q))),
        module_name='1.1.1.3 (a+b x)^m (c+d x)^n (e+f x)^p',
        rule_number=22,
    ),
    # Rule 23
    SymPyReplacementPattern(
        pattern=Int((x*_b_ + _a_)**m_*(x*_d_ + _c_)**_n_*(x*_f_ + _e_)**_p_, x),
        constraints=(FreeQ([_a_, _b_, _c_, _d_, _e_, _f_, m_, _p_], x), EqQ(m_ + _n_ + _p_ + 2, 0), GtQ(_n_, 0), Or(SumSimplerQ(m_, 1), Not(SumSimplerQ(_p_, 1))), NeQ(m_, -1),),
        replacement=-_n_*(-_c_*_f_ + _d_*_e_)*Int((x*_b_ + _a_)**(m_ + 1)*(x*_d_ + _c_)**(_n_ - 1)*(x*_f_ + _e_)**_p_, x)/((m_ + 1)*(-_a_*_f_ + _b_*_e_)) + (x*_b_ + _a_)**(m_ + 1)*(x*_d_ + _c_)**_n_*(x*_f_ + _e_)**(_p_ + 1)/((m_ + 1)*(-_a_*_f_ + _b_*_e_)),
        module_name='1.1.1.3 (a+b x)^m (c+d x)^n (e+f x)^p',
        rule_number=23,
    ),
    # Rule 24
    SymPyReplacementPattern(
        pattern=Int((x*_b_ + _a_)**m_*(x*_d_ + _c_)**_n_*(x*_f_ + _e_)**_p_, x),
        constraints=(FreeQ([_a_, _b_, _c_, _d_, _e_, _f_, m_, _n_, _p_], x), EqQ(Simplify(m_ + _n_ + _p_ + 3), 0), EqQ(_a_*_d_*_f_*(m_ + 1) + _b_*_c_*_f_*(_n_ + 1) + _b_*_d_*_e_*(_p_ + 1), 0), NeQ(m_, -1),),
        replacement=_b_*(x*_b_ + _a_)**(m_ + 1)*(x*_d_ + _c_)**(_n_ + 1)*(x*_f_ + _e_)**(_p_ + 1)/((m_ + 1)*(-_a_*_d_ + _b_*_c_)*(-_a_*_f_ + _b_*_e_)),
        module_name='1.1.1.3 (a+b x)^m (c+d x)^n (e+f x)^p',
        rule_number=24,
    ),
    # Rule 25
    SymPyReplacementPattern(
        pattern=Int((x*_b_ + _a_)**m_*(x*_d_ + _c_)**_n_*(x*_f_ + _e_)**_p_, x),
        constraints=(FreeQ([_a_, _b_, _c_, _d_, _e_, _f_, m_, _n_, _p_], x), EqQ(Simplify(m_ + _n_ + _p_ + 3), 0), Or(LtQ(m_, -1), SumSimplerQ(m_, 1)),),
        replacement=_b_*(x*_b_ + _a_)**(m_ + 1)*(x*_d_ + _c_)**(_n_ + 1)*(x*_f_ + _e_)**(_p_ + 1)/((m_ + 1)*(-_a_*_d_ + _b_*_c_)*(-_a_*_f_ + _b_*_e_)) + (_a_*_d_*_f_*(m_ + 1) + _b_*_c_*_f_*(_n_ + 1) + _b_*_d_*_e_*(_p_ + 1))*Int((x*_b_ + _a_)**(m_ + 1)*(x*_d_ + _c_)**_n_*(x*_f_ + _e_)**_p_, x)/((m_ + 1)*(-_a_*_d_ + _b_*_c_)*(-_a_*_f_ + _b_*_e_)),
        module_name='1.1.1.3 (a+b x)^m (c+d x)^n (e+f x)^p',
        rule_number=25,
    ),
    # Rule 26
    SymPyReplacementPattern(
        pattern=Int((x*_b_ + _a_)**m_*(x*_d_ + _c_)**_n_*(x*_f_ + _e_)**_p_, x),
        constraints=(FreeQ([_a_, _b_, _c_, _d_, _e_, _f_], x), LtQ(m_, -1), GtQ(_n_, 0), GtQ(_p_, 0), Or(IntegersQ(2*m_, 2*_n_, 2*_p_), IntegersQ(m_, _n_ + _p_), IntegersQ(_p_, m_ + _n_)),),
        replacement=(x*_b_ + _a_)**(m_ + 1)*(x*_d_ + _c_)**_n_*(x*_f_ + _e_)**_p_/(_b_*(m_ + 1)) - Int((x*_b_ + _a_)**(m_ + 1)*(x*_d_ + _c_)**(_n_ - 1)*(x*_f_ + _e_)**(_p_ - 1)*Simp(x*_d_*_f_*(_n_ + _p_) + _c_*_f_*_p_ + _d_*_e_*_n_, x), x)/(_b_*(m_ + 1)),
        module_name='1.1.1.3 (a+b x)^m (c+d x)^n (e+f x)^p',
        rule_number=26,
    ),
    # Rule 27
    SymPyReplacementPattern(
        pattern=Int((x*_b_ + _a_)**m_*(x*_d_ + _c_)**_n_*(x*_f_ + _e_)**_p_, x),
        constraints=(FreeQ([_a_, _b_, _c_, _d_, _e_, _f_, _p_], x), LtQ(m_, -1), GtQ(_n_, 1), Or(IntegersQ(2*m_, 2*_n_, 2*_p_), IntegersQ(m_, _n_ + _p_), IntegersQ(_p_, m_ + _n_)),),
        replacement=(x*_b_ + _a_)**(m_ + 1)*(x*_d_ + _c_)**(_n_ - 1)*(x*_f_ + _e_)**(_p_ + 1)*(-_a_*_d_ + _b_*_c_)/(_b_*(m_ + 1)*(-_a_*_f_ + _b_*_e_)) + Int((x*_b_ + _a_)**(m_ + 1)*(x*_d_ + _c_)**(_n_ - 2)*(x*_f_ + _e_)**_p_*Simp(x*_d_*(_a_*_d_*_f_*(_n_ + _p_) + _b_*(-_c_*_f_*(m_ + _n_ + _p_ + 1) + _d_*_e_*(m_ + 1))) + _a_*_d_*(_c_*_f_*(_p_ + 1) + _d_*_e_*(_n_ - 1)) + _b_*_c_*(-_c_*_f_*(m_ + _p_ + 2) + _d_*_e_*(m_ - _n_ + 2)), x), x)/(_b_*(m_ + 1)*(-_a_*_f_ + _b_*_e_)),
        module_name='1.1.1.3 (a+b x)^m (c+d x)^n (e+f x)^p',
        rule_number=27,
    ),
    # Rule 28
    SymPyReplacementPattern(
        pattern=Int((x*_b_ + _a_)**m_*(x*_d_ + _c_)**_n_*(x*_f_ + _e_)**_p_, x),
        constraints=(FreeQ([_a_, _b_, _c_, _d_, _e_, _f_, _p_], x), LtQ(m_, -1), GtQ(_n_, 0), Or(IntegersQ(2*m_, 2*_n_, 2*_p_), IntegersQ(m_, _n_ + _p_), IntegersQ(_p_, m_ + _n_)),),
        replacement=(x*_b_ + _a_)**(m_ + 1)*(x*_d_ + _c_)**_n_*(x*_f_ + _e_)**(_p_ + 1)/((m_ + 1)*(-_a_*_f_ + _b_*_e_)) - Int((x*_b_ + _a_)**(m_ + 1)*(x*_d_ + _c_)**(_n_ - 1)*(x*_f_ + _e_)**_p_*Simp(x*_d_*_f_*(m_ + _n_ + _p_ + 2) + _c_*_f_*(m_ + _p_ + 2) + _d_*_e_*_n_, x), x)/((m_ + 1)*(-_a_*_f_ + _b_*_e_)),
        module_name='1.1.1.3 (a+b x)^m (c+d x)^n (e+f x)^p',
        rule_number=28,
    ),
    # Rule 29
    SymPyReplacementPattern(
        pattern=Int((x*_b_ + _a_)**m_*(x*_d_ + _c_)**_n_*(x*_f_ + _e_)**_p_, x),
        constraints=(FreeQ([_a_, _b_, _c_, _d_, _e_, _f_, _n_, _p_], x), GtQ(m_, 1), NeQ(m_ + _n_ + _p_ + 1, 0), IntegerQ(m_),),
        replacement=_b_*(x*_b_ + _a_)**(m_ - 1)*(x*_d_ + _c_)**(_n_ + 1)*(x*_f_ + _e_)**(_p_ + 1)/(_d_*_f_*(m_ + _n_ + _p_ + 1)) + Int((x*_b_ + _a_)**(m_ - 2)*(x*_d_ + _c_)**_n_*(x*_f_ + _e_)**_p_*Simp(x*_b_*(_a_*_d_*_f_*(2*m_ + _n_ + _p_) - _b_*(_c_*_f_*(m_ + _p_) + _d_*_e_*(m_ + _n_))) + _a_**2*_d_*_f_*(m_ + _n_ + _p_ + 1) - _b_*(_a_*(_c_*_f_*(_p_ + 1) + _d_*_e_*(_n_ + 1)) + _b_*_c_*_e_*(m_ - 1)), x), x)/(_d_*_f_*(m_ + _n_ + _p_ + 1)),
        module_name='1.1.1.3 (a+b x)^m (c+d x)^n (e+f x)^p',
        rule_number=29,
    ),
    # Rule 30
    SymPyReplacementPattern(
        pattern=Int((x*_b_ + _a_)**_m_*(x*_d_ + _c_)**_n_*(x*_f_ + _e_)**_p_, x),
        constraints=(FreeQ([_a_, _b_, _c_, _d_, _e_, _f_, _p_], x), GtQ(_m_, 0), GtQ(_n_, 0), NeQ(_m_ + _n_ + _p_ + 1, 0), Or(IntegersQ(2*_m_, 2*_n_, 2*_p_), Or(IntegersQ(_m_, _n_ + _p_), IntegersQ(_p_, _m_ + _n_))),),
        replacement=(x*_b_ + _a_)**_m_*(x*_d_ + _c_)**_n_*(x*_f_ + _e_)**(_p_ + 1)/(_f_*(_m_ + _n_ + _p_ + 1)) - Int((x*_b_ + _a_)**(_m_ - 1)*(x*_d_ + _c_)**(_n_ - 1)*(x*_f_ + _e_)**_p_*Simp(x*(_b_*_n_*(-_c_*_f_ + _d_*_e_) + _d_*_m_*(-_a_*_f_ + _b_*_e_)) + _a_*_n_*(-_c_*_f_ + _d_*_e_) + _c_*_m_*(-_a_*_f_ + _b_*_e_), x), x)/(_f_*(_m_ + _n_ + _p_ + 1)),
        module_name='1.1.1.3 (a+b x)^m (c+d x)^n (e+f x)^p',
        rule_number=30,
    ),
    # Rule 31
    SymPyReplacementPattern(
        pattern=Int((x*_b_ + _a_)**m_*(x*_d_ + _c_)**_n_*(x*_f_ + _e_)**_p_, x),
        constraints=(FreeQ([_a_, _b_, _c_, _d_, _e_, _f_, _n_, _p_], x), GtQ(m_, 1), NeQ(m_ + _n_ + _p_ + 1, 0), IntegersQ(2*m_, 2*_n_, 2*_p_),),
        replacement=_b_*(x*_b_ + _a_)**(m_ - 1)*(x*_d_ + _c_)**(_n_ + 1)*(x*_f_ + _e_)**(_p_ + 1)/(_d_*_f_*(m_ + _n_ + _p_ + 1)) + Int((x*_b_ + _a_)**(m_ - 2)*(x*_d_ + _c_)**_n_*(x*_f_ + _e_)**_p_*Simp(x*_b_*(_a_*_d_*_f_*(2*m_ + _n_ + _p_) - _b_*(_c_*_f_*(m_ + _p_) + _d_*_e_*(m_ + _n_))) + _a_**2*_d_*_f_*(m_ + _n_ + _p_ + 1) - _b_*(_a_*(_c_*_f_*(_p_ + 1) + _d_*_e_*(_n_ + 1)) + _b_*_c_*_e_*(m_ - 1)), x), x)/(_d_*_f_*(m_ + _n_ + _p_ + 1)),
        module_name='1.1.1.3 (a+b x)^m (c+d x)^n (e+f x)^p',
        rule_number=31,
    ),
    # Rule 32
    SymPyReplacementPattern(
        pattern=Int((x*_b_ + _a_)**m_*(x*_d_ + _c_)**_n_*(x*_f_ + _e_)**_p_, x),
        constraints=(FreeQ([_a_, _b_, _c_, _d_, _e_, _f_, _n_, _p_], x), ILtQ(m_, -1), Or(IntegerQ(_n_), IntegersQ(2*_n_, 2*_p_), ILtQ(m_ + _n_ + _p_ + 3, 0)),),
        replacement=_b_*(x*_b_ + _a_)**(m_ + 1)*(x*_d_ + _c_)**(_n_ + 1)*(x*_f_ + _e_)**(_p_ + 1)/((m_ + 1)*(-_a_*_d_ + _b_*_c_)*(-_a_*_f_ + _b_*_e_)) + Int((x*_b_ + _a_)**(m_ + 1)*(x*_d_ + _c_)**_n_*(x*_f_ + _e_)**_p_*Simp(-x*_b_*_d_*_f_*(m_ + _n_ + _p_ + 3) + _a_*_d_*_f_*(m_ + 1) - _b_*(_c_*_f_*(m_ + _p_ + 2) + _d_*_e_*(m_ + _n_ + 2)), x), x)/((m_ + 1)*(-_a_*_d_ + _b_*_c_)*(-_a_*_f_ + _b_*_e_)),
        module_name='1.1.1.3 (a+b x)^m (c+d x)^n (e+f x)^p',
        rule_number=32,
    ),
    # Rule 33
    SymPyReplacementPattern(
        pattern=Int((x*_b_ + _a_)**m_*(x*_d_ + _c_)**_n_*(x*_f_ + _e_)**_p_, x),
        constraints=(FreeQ([_a_, _b_, _c_, _d_, _e_, _f_, _n_, _p_], x), LtQ(m_, -1), IntegersQ(2*m_, 2*_n_, 2*_p_),),
        replacement=_b_*(x*_b_ + _a_)**(m_ + 1)*(x*_d_ + _c_)**(_n_ + 1)*(x*_f_ + _e_)**(_p_ + 1)/((m_ + 1)*(-_a_*_d_ + _b_*_c_)*(-_a_*_f_ + _b_*_e_)) + Int((x*_b_ + _a_)**(m_ + 1)*(x*_d_ + _c_)**_n_*(x*_f_ + _e_)**_p_*Simp(-x*_b_*_d_*_f_*(m_ + _n_ + _p_ + 3) + _a_*_d_*_f_*(m_ + 1) - _b_*(_c_*_f_*(m_ + _p_ + 2) + _d_*_e_*(m_ + _n_ + 2)), x), x)/((m_ + 1)*(-_a_*_d_ + _b_*_c_)*(-_a_*_f_ + _b_*_e_)),
        module_name='1.1.1.3 (a+b x)^m (c+d x)^n (e+f x)^p',
        rule_number=33,
    ),
    # Rule 34
    SymPyReplacementPattern(
        pattern=Int(1/((x*_b_ + _a_)*sqrt(x*_d_ + _c_)*(x*_f_ + _e_)**(sympy.S(1)/4)), x),
        constraints=(FreeQ([_a_, _b_, _c_, _d_, _e_, _f_], x), GtQ(-_f_/(-_c_*_f_ + _d_*_e_), 0),),
        replacement=-4*Subst(Int(x**2/((-x**4*_b_ - _a_*_f_ + _b_*_e_)*sqrt(x**4*_d_/_f_ + _c_ - _d_*_e_/_f_)), x), x, (x*_f_ + _e_)**(sympy.S(1)/4)),
        module_name='1.1.1.3 (a+b x)^m (c+d x)^n (e+f x)^p',
        rule_number=34,
    ),
    # Rule 35
    SymPyReplacementPattern(
        pattern=Int(1/((x*_b_ + _a_)*sqrt(x*_d_ + _c_)*(x*_f_ + _e_)**(sympy.S(1)/4)), x),
        constraints=(FreeQ([_a_, _b_, _c_, _d_, _e_, _f_], x), Not(GtQ(-_f_/(-_c_*_f_ + _d_*_e_), 0)),),
        replacement=sqrt(-_f_*(x*_d_ + _c_)/(-_c_*_f_ + _d_*_e_))*Int(1/((x*_b_ + _a_)*(x*_f_ + _e_)**(sympy.S(1)/4)*sqrt(-x*_d_*_f_/(-_c_*_f_ + _d_*_e_) - _c_*_f_/(-_c_*_f_ + _d_*_e_))), x)/sqrt(x*_d_ + _c_),
        module_name='1.1.1.3 (a+b x)^m (c+d x)^n (e+f x)^p',
        rule_number=35,
    ),
    # Rule 36
    SymPyReplacementPattern(
        pattern=Int(1/((x*_b_ + _a_)*sqrt(x*_d_ + _c_)*(x*_f_ + _e_)**(sympy.S(3)/4)), x),
        constraints=(FreeQ([_a_, _b_, _c_, _d_, _e_, _f_], x), GtQ(-_f_/(-_c_*_f_ + _d_*_e_), 0),),
        replacement=-4*Subst(Int(1/((-x**4*_b_ - _a_*_f_ + _b_*_e_)*sqrt(x**4*_d_/_f_ + _c_ - _d_*_e_/_f_)), x), x, (x*_f_ + _e_)**(sympy.S(1)/4)),
        module_name='1.1.1.3 (a+b x)^m (c+d x)^n (e+f x)^p',
        rule_number=36,
    ),
    # Rule 37
    SymPyReplacementPattern(
        pattern=Int(1/((x*_b_ + _a_)*sqrt(x*_d_ + _c_)*(x*_f_ + _e_)**(sympy.S(3)/4)), x),
        constraints=(FreeQ([_a_, _b_, _c_, _d_, _e_, _f_], x), Not(GtQ(-_f_/(-_c_*_f_ + _d_*_e_), 0)),),
        replacement=sqrt(-_f_*(x*_d_ + _c_)/(-_c_*_f_ + _d_*_e_))*Int(1/((x*_b_ + _a_)*(x*_f_ + _e_)**(sympy.S(3)/4)*sqrt(-x*_d_*_f_/(-_c_*_f_ + _d_*_e_) - _c_*_f_/(-_c_*_f_ + _d_*_e_))), x)/sqrt(x*_d_ + _c_),
        module_name='1.1.1.3 (a+b x)^m (c+d x)^n (e+f x)^p',
        rule_number=37,
    ),
    # Rule 38
    SymPyReplacementPattern(
        pattern=Int(sqrt(x*_f_ + e_)/(sqrt(x*_b_)*sqrt(x*_d_ + c_)), x),
        constraints=(FreeQ([_b_, c_, _d_, e_, _f_], x), NeQ(-c_*_f_ + _d_*e_, 0), GtQ(c_, 0), GtQ(e_, 0), Not(LtQ(-_b_/_d_, 0)),),
        replacement=2*sqrt(e_)*Rt(-_b_/_d_, 2)*elliptic_e(asin(sqrt(x*_b_)/(sqrt(c_)*Rt(-_b_/_d_, 2))), c_*_f_/(_d_*e_))/_b_,
        module_name='1.1.1.3 (a+b x)^m (c+d x)^n (e+f x)^p',
        rule_number=38,
    ),
    # Rule 39
    SymPyReplacementPattern(
        pattern=Int(sqrt(x*_f_ + e_)/(sqrt(x*_b_)*sqrt(x*_d_ + c_)), x),
        constraints=(FreeQ([_b_, c_, _d_, e_, _f_], x), NeQ(-c_*_f_ + _d_*e_, 0), GtQ(c_, 0), GtQ(e_, 0), LtQ(-_b_/_d_, 0),),
        replacement=sqrt(-x*_b_)*Int(sqrt(x*_f_ + e_)/(sqrt(-x*_b_)*sqrt(x*_d_ + c_)), x)/sqrt(x*_b_),
        module_name='1.1.1.3 (a+b x)^m (c+d x)^n (e+f x)^p',
        rule_number=39,
    ),
    # Rule 40
    SymPyReplacementPattern(
        pattern=Int(sqrt(x*_f_ + e_)/(sqrt(x*_b_)*sqrt(x*_d_ + c_)), x),
        constraints=(FreeQ([_b_, c_, _d_, e_, _f_], x), NeQ(-c_*_f_ + _d_*e_, 0), Not(And(GtQ(c_, 0), GtQ(e_, 0))),),
        replacement=sqrt(x*_f_ + e_)*sqrt(x*_d_/c_ + 1)*Int(sqrt(x*_f_/e_ + 1)/(sqrt(x*_b_)*sqrt(x*_d_/c_ + 1)), x)/(sqrt(x*_d_ + c_)*sqrt(x*_f_/e_ + 1)),
        module_name='1.1.1.3 (a+b x)^m (c+d x)^n (e+f x)^p',
        rule_number=40,
    ),
    # Rule 41
    SymPyReplacementPattern(
        pattern=Int(sqrt(x*_f_ + _e_)/(sqrt(x*_b_ + a_)*sqrt(x*_d_ + c_)), x),
        constraints=(FreeQ([a_, _b_, c_, _d_, _e_, _f_], x), GtQ(_b_/(-a_*_d_ + _b_*c_), 0), GtQ(_b_/(-a_*_f_ + _b_*_e_), 0), Not(LtQ((a_*_d_ - _b_*c_)/_d_, 0)), Not(And(SimplerQ(x*_d_ + c_, x*_b_ + a_), GtQ(-_d_/(-a_*_d_ + _b_*c_), 0), GtQ(_d_/(-c_*_f_ + _d_*_e_), 0), Not(LtQ((-a_*_d_ + _b_*c_)/_b_, 0)))),),
        replacement=2*Rt((a_*_f_ - _b_*_e_)/_d_, 2)*elliptic_e(asin(sqrt(x*_b_ + a_)/Rt((a_*_d_ - _b_*c_)/_d_, 2)), _f_*(-a_*_d_ + _b_*c_)/(_d_*(-a_*_f_ + _b_*_e_)))/_b_,
        module_name='1.1.1.3 (a+b x)^m (c+d x)^n (e+f x)^p',
        rule_number=41,
    ),
    # Rule 42
    SymPyReplacementPattern(
        pattern=Int(sqrt(x*_f_ + _e_)/(sqrt(x*_b_ + a_)*sqrt(x*_d_ + c_)), x),
        constraints=(FreeQ([a_, _b_, c_, _d_, _e_, _f_], x), Not(And(GtQ(_b_/(-a_*_d_ + _b_*c_), 0), GtQ(_b_/(-a_*_f_ + _b_*_e_), 0))), Not(LtQ((a_*_d_ - _b_*c_)/_d_, 0)),),
        replacement=sqrt(_b_*(x*_d_ + c_)/(-a_*_d_ + _b_*c_))*sqrt(x*_f_ + _e_)*Int(sqrt(x*_b_*_f_/(-a_*_f_ + _b_*_e_) + _b_*_e_/(-a_*_f_ + _b_*_e_))/(sqrt(x*_b_ + a_)*sqrt(x*_b_*_d_/(-a_*_d_ + _b_*c_) + _b_*c_/(-a_*_d_ + _b_*c_))), x)/(sqrt(_b_*(x*_f_ + _e_)/(-a_*_f_ + _b_*_e_))*sqrt(x*_d_ + c_)),
        module_name='1.1.1.3 (a+b x)^m (c+d x)^n (e+f x)^p',
        rule_number=42,
    ),
    # Rule 43
    SymPyReplacementPattern(
        pattern=Int(1/(sqrt(x*_b_)*sqrt(x*_d_ + c_)*sqrt(x*_f_ + e_)), x),
        constraints=(FreeQ([_b_, c_, _d_, e_, _f_], x), GtQ(c_, 0), GtQ(e_, 0), Or(GtQ(-_b_/_d_, 0), LtQ(-_b_/_f_, 0)),),
        replacement=2*Rt(-_b_/_d_, 2)*elliptic_f(asin(sqrt(x*_b_)/(sqrt(c_)*Rt(-_b_/_d_, 2))), c_*_f_/(_d_*e_))/(_b_*sqrt(e_)),
        module_name='1.1.1.3 (a+b x)^m (c+d x)^n (e+f x)^p',
        rule_number=43,
    ),
    # Rule 44
    SymPyReplacementPattern(
        pattern=Int(1/(sqrt(x*_b_)*sqrt(x*_d_ + c_)*sqrt(x*_f_ + e_)), x),
        constraints=(FreeQ([_b_, c_, _d_, e_, _f_], x), GtQ(c_, 0), GtQ(e_, 0), Or(PosQ(-_b_/_d_), NegQ(-_b_/_f_)),),
        replacement=2*Rt(-_b_/_d_, 2)*elliptic_f(asin(sqrt(x*_b_)/(sqrt(c_)*Rt(-_b_/_d_, 2))), c_*_f_/(_d_*e_))/(_b_*sqrt(e_)),
        module_name='1.1.1.3 (a+b x)^m (c+d x)^n (e+f x)^p',
        rule_number=44,
    ),
    # Rule 45
    SymPyReplacementPattern(
        pattern=Int(1/(sqrt(x*_b_)*sqrt(x*_d_ + c_)*sqrt(x*_f_ + e_)), x),
        constraints=(FreeQ([_b_, c_, _d_, e_, _f_], x), Not(And(GtQ(c_, 0), GtQ(e_, 0))),),
        replacement=sqrt(x*_d_/c_ + 1)*sqrt(x*_f_/e_ + 1)*Int(1/(sqrt(x*_b_)*sqrt(x*_d_/c_ + 1)*sqrt(x*_f_/e_ + 1)), x)/(sqrt(x*_d_ + c_)*sqrt(x*_f_ + e_)),
        module_name='1.1.1.3 (a+b x)^m (c+d x)^n (e+f x)^p',
        rule_number=45,
    ),
    # Rule 46
    SymPyReplacementPattern(
        pattern=Int(1/(sqrt(x*_b_ + a_)*sqrt(x*_d_ + c_)*sqrt(x*_f_ + e_)), x),
        constraints=(FreeQ([a_, _b_, c_, _d_, e_, _f_], x), GtQ(_d_/_b_, 0), GtQ(_f_/_b_, 0), LeQ(c_, a_*_d_/_b_), LeQ(e_, a_*_f_/_b_),),
        replacement=-2*sqrt(_d_/_f_)*elliptic_f(asin(Rt((a_*_f_ - _b_*e_)/_f_, 2)/sqrt(x*_b_ + a_)), _f_*(-a_*_d_ + _b_*c_)/(_d_*(-a_*_f_ + _b_*e_)))/(_d_*Rt((a_*_f_ - _b_*e_)/_f_, 2)),
        module_name='1.1.1.3 (a+b x)^m (c+d x)^n (e+f x)^p',
        rule_number=46,
    ),
    # Rule 47
    SymPyReplacementPattern(
        pattern=Int(1/(sqrt(x*_b_ + a_)*sqrt(x*_d_ + c_)*sqrt(x*_f_ + e_)), x),
        constraints=(FreeQ([a_, _b_, c_, _d_, e_, _f_], x), GtQ((-a_*_d_ + _b_*c_)/_b_, 0), GtQ((-a_*_f_ + _b_*e_)/_b_, 0), PosQ(-_b_/_d_), Not(And(SimplerQ(x*_d_ + c_, x*_b_ + a_), GtQ((-c_*_f_ + _d_*e_)/_d_, 0), GtQ(-_d_/_b_, 0))), Not(And(SimplerQ(x*_d_ + c_, x*_b_ + a_), GtQ((a_*_f_ - _b_*e_)/_f_, 0), GtQ(-_f_/_b_, 0))), Not(And(SimplerQ(x*_f_ + e_, x*_b_ + a_), GtQ((c_*_f_ - _d_*e_)/_f_, 0), GtQ((a_*_f_ - _b_*e_)/_f_, 0), Or(PosQ(-_f_/_d_), PosQ(-_f_/_b_)))),),
        replacement=2*Rt(-_b_/_d_, 2)*elliptic_f(asin(sqrt(x*_b_ + a_)/(sqrt((-a_*_d_ + _b_*c_)/_b_)*Rt(-_b_/_d_, 2))), _f_*(-a_*_d_ + _b_*c_)/(_d_*(-a_*_f_ + _b_*e_)))/(_b_*sqrt((-a_*_f_ + _b_*e_)/_b_)),
        module_name='1.1.1.3 (a+b x)^m (c+d x)^n (e+f x)^p',
        rule_number=47,
    ),
    # Rule 48
    SymPyReplacementPattern(
        pattern=Int(1/(sqrt(x*_b_ + a_)*sqrt(x*_d_ + c_)*sqrt(x*_f_ + e_)), x),
        constraints=(FreeQ([a_, _b_, c_, _d_, e_, _f_], x), GtQ(_b_/(-a_*_d_ + _b_*c_), 0), GtQ(_b_/(-a_*_f_ + _b_*e_), 0), SimplerQ(x*_b_ + a_, x*_d_ + c_), SimplerQ(x*_b_ + a_, x*_f_ + e_), Or(PosQ((a_*_d_ - _b_*c_)/_d_), NegQ((a_*_f_ - _b_*e_)/_f_)),),
        replacement=2*Rt(-_b_/_d_, 2)*elliptic_f(asin(sqrt(x*_b_ + a_)/(sqrt((-a_*_d_ + _b_*c_)/_b_)*Rt(-_b_/_d_, 2))), _f_*(-a_*_d_ + _b_*c_)/(_d_*(-a_*_f_ + _b_*e_)))/(_b_*sqrt((-a_*_f_ + _b_*e_)/_b_)),
        module_name='1.1.1.3 (a+b x)^m (c+d x)^n (e+f x)^p',
        rule_number=48,
    ),
    # Rule 49
    SymPyReplacementPattern(
        pattern=Int(1/(sqrt(x*_b_ + a_)*sqrt(x*_d_ + c_)*sqrt(x*_f_ + e_)), x),
        constraints=(FreeQ([a_, _b_, c_, _d_, e_, _f_], x), Not(GtQ((-a_*_d_ + _b_*c_)/_b_, 0)), SimplerQ(x*_b_ + a_, x*_d_ + c_), SimplerQ(x*_b_ + a_, x*_f_ + e_),),
        replacement=sqrt(_b_*(x*_d_ + c_)/(-a_*_d_ + _b_*c_))*Int(1/(sqrt(x*_b_ + a_)*sqrt(x*_f_ + e_)*sqrt(x*_b_*_d_/(-a_*_d_ + _b_*c_) + _b_*c_/(-a_*_d_ + _b_*c_))), x)/sqrt(x*_d_ + c_),
        module_name='1.1.1.3 (a+b x)^m (c+d x)^n (e+f x)^p',
        rule_number=49,
    ),
    # Rule 50
    SymPyReplacementPattern(
        pattern=Int(1/(sqrt(x*_b_ + a_)*sqrt(x*_d_ + c_)*sqrt(x*_f_ + e_)), x),
        constraints=(FreeQ([a_, _b_, c_, _d_, e_, _f_], x), Not(GtQ((-a_*_f_ + _b_*e_)/_b_, 0)),),
        replacement=sqrt(_b_*(x*_f_ + e_)/(-a_*_f_ + _b_*e_))*Int(1/(sqrt(x*_b_ + a_)*sqrt(x*_d_ + c_)*sqrt(x*_b_*_f_/(-a_*_f_ + _b_*e_) + _b_*e_/(-a_*_f_ + _b_*e_))), x)/sqrt(x*_f_ + e_),
        module_name='1.1.1.3 (a+b x)^m (c+d x)^n (e+f x)^p',
        rule_number=50,
    ),
    # Rule 51
    SymPyReplacementPattern(
        pattern=Int(1/((x*_b_ + _a_)*(x*_d_ + _c_)**(sympy.S(1)/3)*(x*_f_ + _e_)**(sympy.S(1)/3)), x),
        constraints=(FreeQ([_a_, _b_, _c_, _d_, _e_, _f_], x), EqQ(-_a_*_d_*_f_ - _b_*_c_*_f_ + 2*_b_*_d_*_e_, 0),),
        replacement=With({q: Rt(_b_*(-_a_*_f_ + _b_*_e_)/(-_a_*_d_ + _b_*_c_)**2, 3)}, 3*log(q*(x*_d_ + _c_)**(sympy.S(2)/3) - (x*_f_ + _e_)**(sympy.S(1)/3))/(4*q*(-_a_*_d_ + _b_*_c_)) - log(x*_b_ + _a_)/(2*q*(-_a_*_d_ + _b_*_c_)) - sqrt(3)*atan(2*sqrt(3)*q*(x*_d_ + _c_)**(sympy.S(2)/3)/(3*(x*_f_ + _e_)**(sympy.S(1)/3)) + sqrt(3)/3)/(2*q*(-_a_*_d_ + _b_*_c_))),
        module_name='1.1.1.3 (a+b x)^m (c+d x)^n (e+f x)^p',
        rule_number=51,
    ),
    # Rule 52
    SymPyReplacementPattern(
        pattern=Int((x*_b_ + _a_)**m_/((x*_d_ + _c_)**(sympy.S(1)/3)*(x*_f_ + _e_)**(sympy.S(1)/3)), x),
        constraints=(FreeQ([_a_, _b_, _c_, _d_, _e_, _f_], x), EqQ(-_a_*_d_*_f_ - _b_*_c_*_f_ + 2*_b_*_d_*_e_, 0), ILtQ(m_, -1),),
        replacement=_b_*(x*_b_ + _a_)**(m_ + 1)*(x*_d_ + _c_)**(sympy.S(2)/3)*(x*_f_ + _e_)**(sympy.S(2)/3)/((m_ + 1)*(-_a_*_d_ + _b_*_c_)*(-_a_*_f_ + _b_*_e_)) + _f_*Int((x*_b_ + _a_)**(m_ + 1)*(-2*x*_b_*_d_*(3*m_ + 7) + _a_*_d_*(3*m_ + 1) - 3*_b_*_c_*(3*m_ + 5))/((x*_d_ + _c_)**(sympy.S(1)/3)*(x*_f_ + _e_)**(sympy.S(1)/3)), x)/((6*m_ + 6)*(-_a_*_d_ + _b_*_c_)*(-_a_*_f_ + _b_*_e_)),
        module_name='1.1.1.3 (a+b x)^m (c+d x)^n (e+f x)^p',
        rule_number=52,
    ),
    # Rule 53
    SymPyReplacementPattern(
        pattern=Int((x*_f_)**_p_*(x*_b_ + _a_)**_m_*(x*_d_ + _c_)**_n_, x),
        constraints=(FreeQ([_a_, _b_, _c_, _d_, _f_, _m_, _n_, _p_], x), EqQ(_a_*_d_ + _b_*_c_, 0), EqQ(_n_, _m_), GtQ(_a_, 0), GtQ(_c_, 0),),
        replacement=Int((x*_f_)**_p_*(x**2*_b_*_d_ + _a_*_c_)**_m_, x),
        module_name='1.1.1.3 (a+b x)^m (c+d x)^n (e+f x)^p',
        rule_number=53,
    ),
    # Rule 54
    SymPyReplacementPattern(
        pattern=Int((x*_f_)**_p_*(x*_b_ + _a_)**_m_*(x*_d_ + _c_)**_n_, x),
        constraints=(FreeQ([_a_, _b_, _c_, _d_, _f_, _m_, _n_, _p_], x), EqQ(_a_*_d_ + _b_*_c_, 0), EqQ(_n_, _m_),),
        replacement=(x*_b_ + _a_)**FracPart(_m_)*(x*_d_ + _c_)**FracPart(_m_)*Int((x*_f_)**_p_*(x**2*_b_*_d_ + _a_*_c_)**_m_, x)/(x**2*_b_*_d_ + _a_*_c_)**FracPart(_m_),
        module_name='1.1.1.3 (a+b x)^m (c+d x)^n (e+f x)^p',
        rule_number=54,
    ),
    # Rule 55
    SymPyReplacementPattern(
        pattern=Int((x*_b_ + _a_)**_m_*(x*_d_ + _c_)**_n_*(x*_f_ + _e_)**_p_, x),
        constraints=(FreeQ([_a_, _b_, _c_, _d_, _e_, _f_, _n_, _p_], x), Or(IGtQ(_m_, 0), And(ILtQ(_m_, 0), ILtQ(_n_, 0))),),
        replacement=Int(ExpandIntegrand((x*_b_ + _a_)**_m_*(x*_d_ + _c_)**_n_*(x*_f_ + _e_)**_p_, x), x),
        module_name='1.1.1.3 (a+b x)^m (c+d x)^n (e+f x)^p',
        rule_number=55,
    ),
    # Rule 56
    SymPyReplacementPattern(
        pattern=Int((x*_e_)**p_*(x*_b_ + a_)**m_*(x*_d_ + c_)**n_, x),
        constraints=(FreeQ([a_, _b_, c_, _d_, _e_, m_, n_], x), NeQ(-a_*_d_ + _b_*c_, 0), FractionQ(p_), IntegerQ(m_),),
        replacement=With({k: Denominator(p_)}, k*Subst(Int(x**(k*(p_ + 1) - 1)*(x**k*_b_/_e_ + a_)**m_*(x**k*_d_/_e_ + c_)**n_, x), x, (x*_e_)**(1/k))/_e_),
        module_name='1.1.1.3 (a+b x)^m (c+d x)^n (e+f x)^p',
        rule_number=56,
    ),
    # Rule 57
    SymPyReplacementPattern(
        pattern=Int((x*_b_ + _a_)**m_*(x*_d_ + _c_)**n_/(x*_f_ + _e_)**2, x),
        constraints=(FreeQ([_a_, _b_, _c_, _d_, _e_, _f_, m_, n_], x), IGtQ(m_ + n_, 0), EqQ(2*_b_*_d_*_e_ - _f_*(_a_*_d_ + _b_*_c_), 0),),
        replacement=_b_*_d_*Int((x*_b_ + _a_)**(m_ - 1)*(x*_d_ + _c_)**(n_ - 1), x)/_f_**2 + (-_a_*_f_ + _b_*_e_)*(-_c_*_f_ + _d_*_e_)*Int((x*_b_ + _a_)**(m_ - 1)*(x*_d_ + _c_)**(n_ - 1)/(x*_f_ + _e_)**2, x)/_f_**2,
        module_name='1.1.1.3 (a+b x)^m (c+d x)^n (e+f x)^p',
        rule_number=57,
    ),
    # Rule 58
    SymPyReplacementPattern(
        pattern=Int((x*_b_ + _a_)**_m_*(x*_d_ + _c_)**_n_*(x*_f_ + _e_)**p_, x),
        constraints=(FreeQ([_a_, _b_, _c_, _d_, _e_, _f_, _m_, _n_], x), EqQ(_m_ + _n_ + p_, 0), ILtQ(p_, 0), Or(LtQ(_m_, 0), SumSimplerQ(_m_, 1), Not(Or(LtQ(_n_, 0), SumSimplerQ(_n_, 1)))),),
        replacement=_f_**(p_ - 1)*Int((x*_b_ + _a_)**_m_*(x*_d_ + _c_)**(-_m_ - 1)*(x*_f_ + _e_)**p_*ExpandToSum(_f_**(1 - p_)*(x*_d_ + _c_)**(1 - p_) - (x*_d_*_f_ - _c_*_f_*(p_ - 1) + _d_*_e_*p_)/(_d_**p_*(x*_f_ + _e_)**p_), x), x) + _f_**(p_ - 1)*Int((x*_b_ + _a_)**_m_*(x*_d_ + _c_)**(-_m_ - 1)*(x*_d_*_f_ - _c_*_f_*(p_ - 1) + _d_*_e_*p_), x)/_d_**p_,
        module_name='1.1.1.3 (a+b x)^m (c+d x)^n (e+f x)^p',
        rule_number=58,
    ),
    # Rule 59
    SymPyReplacementPattern(
        pattern=Int((x*_b_ + _a_)**_m_*(x*_d_ + _c_)**_n_*(x*_f_ + _e_)**p_, x),
        constraints=(FreeQ([_a_, _b_, _c_, _d_, _e_, _f_, _m_, _n_], x), EqQ(_m_ + _n_ + p_ + 1, 0), ILtQ(p_, 0), Or(GtQ(_m_, 0), SumSimplerQ(_m_, -1), Not(Or(GtQ(_n_, 0), SumSimplerQ(_n_, -1)))),),
        replacement=_b_*_d_**(_m_ + _n_)*_f_**p_*Int((x*_b_ + _a_)**(_m_ - 1)/(x*_d_ + _c_)**_m_, x) + Int((x*_b_ + _a_)**(_m_ - 1)*(x*_f_ + _e_)**p_*ExpandToSum(-_b_*_d_**(-p_ - 1)*_f_**p_/(x*_f_ + _e_)**p_ + (x*_b_ + _a_)*(x*_d_ + _c_)**(-p_ - 1), x)/(x*_d_ + _c_)**_m_, x),
        module_name='1.1.1.3 (a+b x)^m (c+d x)^n (e+f x)^p',
        rule_number=59,
    ),
    # Rule 60
    SymPyReplacementPattern(
        pattern=Int((x*_b_ + _a_)**m_*(x*_d_ + _c_)**_n_*(x*_f_ + _e_)**p_, x),
        constraints=(FreeQ([_a_, _b_, _c_, _d_, _e_, _f_, m_, p_], x), EqQ(m_ + _n_ + p_ + 2, 0), ILtQ(_n_, 0), Or(SumSimplerQ(m_, 1), Not(SumSimplerQ(p_, 1))), Not(ILtQ(m_, 0)),),
        replacement=(x*_b_ + _a_)**(m_ + 1)*(x*_f_ + _e_)**(-m_ - 1)*(-_a_*_d_ + _b_*_c_)**_n_*(-_a_*_f_ + _b_*_e_)**(-_n_ - 1)*hyper((-_n_, m_ + 1), (m_ + 2,), (x*_b_ + _a_)*(_c_*_f_ - _d_*_e_)/((x*_f_ + _e_)*(-_a_*_d_ + _b_*_c_)))/(m_ + 1),
        module_name='1.1.1.3 (a+b x)^m (c+d x)^n (e+f x)^p',
        rule_number=60,
    ),
    # Rule 61
    SymPyReplacementPattern(
        pattern=Int((x*_b_ + _a_)**m_*(x*_d_ + _c_)**n_*(x*_f_ + _e_)**p_, x),
        constraints=(FreeQ([_a_, _b_, _c_, _d_, _e_, _f_, m_, n_, p_], x), EqQ(m_ + n_ + p_ + 2, 0), Not(IntegerQ(n_)),),
        replacement=(x*_b_ + _a_)**(m_ + 1)*(x*_d_ + _c_)**n_*(x*_f_ + _e_)**(p_ + 1)*hyper((-n_, m_ + 1), (m_ + 2,), (x*_b_ + _a_)*(_c_*_f_ - _d_*_e_)/((x*_f_ + _e_)*(-_a_*_d_ + _b_*_c_)))/(((x*_d_ + _c_)*(-_a_*_f_ + _b_*_e_)/((x*_f_ + _e_)*(-_a_*_d_ + _b_*_c_)))**n_*(m_ + 1)*(-_a_*_f_ + _b_*_e_)),
        module_name='1.1.1.3 (a+b x)^m (c+d x)^n (e+f x)^p',
        rule_number=61,
    ),
    # Rule 62
    SymPyReplacementPattern(
        pattern=Int((x*_b_ + _a_)**m_*(x*_d_ + _c_)**n_/(x*_f_ + _e_), x),
        constraints=(FreeQ([_a_, _b_, _c_, _d_, _e_, _f_, m_, n_], x), IGtQ(m_ + n_ + 1, 0), Or(LtQ(m_, 0), SumSimplerQ(m_, 1), Not(Or(LtQ(n_, 0), SumSimplerQ(n_, 1)))),),
        replacement=_f_**(-m_ - n_ - 1)*(_c_*_f_ - _d_*_e_)**(m_ + n_ + 1)*Int((x*_b_ + _a_)**m_*(x*_d_ + _c_)**(-m_ - 1)/(x*_f_ + _e_), x) + _f_**(-m_ - n_ - 1)*Int((x*_b_ + _a_)**m_*(x*_d_ + _c_)**(-m_ - 1)*ExpandToSum((_f_**(m_ + n_ + 1)*(x*_d_ + _c_)**(m_ + n_ + 1) - (_c_*_f_ - _d_*_e_)**(m_ + n_ + 1))/(x*_f_ + _e_), x), x),
        module_name='1.1.1.3 (a+b x)^m (c+d x)^n (e+f x)^p',
        rule_number=62,
    ),
    # Rule 63
    SymPyReplacementPattern(
        pattern=Int((x*_b_ + _a_)**m_*(x*_d_ + _c_)**_n_*(x*_f_ + _e_)**_p_, x),
        constraints=(FreeQ([_a_, _b_, _c_, _d_, _e_, _f_, m_, _n_, _p_], x), ILtQ(m_ + _n_ + _p_ + 2, 0), NeQ(m_, -1), Or(SumSimplerQ(m_, 1), And(Not(SumSimplerQ(_n_, 1)), Not(SumSimplerQ(_p_, 1)))),),
        replacement=_b_*(x*_b_ + _a_)**(m_ + 1)*(x*_d_ + _c_)**(_n_ + 1)*(x*_f_ + _e_)**(_p_ + 1)/((m_ + 1)*(-_a_*_d_ + _b_*_c_)*(-_a_*_f_ + _b_*_e_)) + Int((x*_b_ + _a_)**(m_ + 1)*(x*_d_ + _c_)**_n_*(x*_f_ + _e_)**_p_*Simp(-x*_b_*_d_*_f_*(m_ + _n_ + _p_ + 3) + _a_*_d_*_f_*(m_ + 1) - _b_*(_c_*_f_*(m_ + _p_ + 2) + _d_*_e_*(m_ + _n_ + 2)), x), x)/((m_ + 1)*(-_a_*_d_ + _b_*_c_)*(-_a_*_f_ + _b_*_e_)),
        module_name='1.1.1.3 (a+b x)^m (c+d x)^n (e+f x)^p',
        rule_number=63,
    ),
    # Rule 64
    SymPyReplacementPattern(
        pattern=Int((x*_f_)**_p_*(x*_b_ + _a_)**_m_*(x*_d_ + _c_)**_n_, x),
        constraints=(FreeQ([_a_, _b_, _c_, _d_, _f_, _m_, _n_, _p_], x), EqQ(_a_*_d_ + _b_*_c_, 0), IGtQ(_m_ - _n_, 0), NeQ(_m_ + _n_ + _p_ + 2, 0),),
        replacement=Int(ExpandIntegrand((x*_f_)**_p_*(x*_b_ + _a_)**_n_*(x*_d_ + _c_)**_n_, (x*_b_ + _a_)**(_m_ - _n_), x), x),
        module_name='1.1.1.3 (a+b x)^m (c+d x)^n (e+f x)^p',
        rule_number=64,
    ),
    # Rule 65
    SymPyReplacementPattern(
        pattern=Int((x*_b_)**m_*(x*_d_ + c_)**n_*(x*_f_ + e_)**p_, x),
        constraints=(FreeQ([_b_, c_, _d_, e_, _f_, m_, n_, p_], x), Not(IntegerQ(m_)), Not(IntegerQ(n_)), GtQ(c_, 0), Or(IntegerQ(p_), GtQ(e_, 0)),),
        replacement=c_**n_*e_**p_*(x*_b_)**(m_ + 1)*appellf1(m_ + 1, -n_, -p_, m_ + 2, -x*_d_/c_, -x*_f_/e_)/(_b_*(m_ + 1)),
        module_name='1.1.1.3 (a+b x)^m (c+d x)^n (e+f x)^p',
        rule_number=65,
    ),
    # Rule 66
    SymPyReplacementPattern(
        pattern=Int((x*_b_)**m_*(x*_d_ + c_)**n_*(x*_f_ + e_)**p_, x),
        constraints=(FreeQ([_b_, c_, _d_, e_, _f_, m_, n_, p_], x), Not(IntegerQ(m_)), Not(IntegerQ(n_)), GtQ(-_d_/(_b_*c_), 0), Or(IntegerQ(p_), GtQ(_d_/(-c_*_f_ + _d_*e_), 0)),),
        replacement=(x*_d_ + c_)**(n_ + 1)*appellf1(n_ + 1, -m_, -p_, n_ + 2, x*_d_/c_ + 1, -_f_*(x*_d_ + c_)/(-c_*_f_ + _d_*e_))/(_d_*(_d_/(-c_*_f_ + _d_*e_))**p_*(-_d_/(_b_*c_))**m_*(n_ + 1)),
        module_name='1.1.1.3 (a+b x)^m (c+d x)^n (e+f x)^p',
        rule_number=66,
    ),
    # Rule 67
    SymPyReplacementPattern(
        pattern=Int((x*_b_)**m_*(x*_d_ + c_)**n_*(x*_f_ + e_)**p_, x),
        constraints=(FreeQ([_b_, c_, _d_, e_, _f_, m_, n_, p_], x), Not(IntegerQ(m_)), Not(IntegerQ(n_)), Not(GtQ(c_, 0)),),
        replacement=c_**IntPart(n_)*(x*_d_ + c_)**FracPart(n_)*Int((x*_b_)**m_*(x*_f_ + e_)**p_*(x*_d_/c_ + 1)**n_, x)/(x*_d_/c_ + 1)**FracPart(n_),
        module_name='1.1.1.3 (a+b x)^m (c+d x)^n (e+f x)^p',
        rule_number=67,
    ),
    # Rule 68
    SymPyReplacementPattern(
        pattern=Int((x*_b_ + a_)**m_*(x*_d_ + _c_)**n_*(x*_f_ + _e_)**p_, x),
        constraints=(FreeQ([a_, _b_, _c_, _d_, _e_, _f_, m_, n_], x), Not(IntegerQ(m_)), Not(IntegerQ(n_)), IntegerQ(p_), GtQ(_b_/(-a_*_d_ + _b_*_c_), 0), Not(And(GtQ(_d_/(a_*_d_ - _b_*_c_), 0), SimplerQ(x*_d_ + _c_, x*_b_ + a_))),),
        replacement=_b_**(-p_ - 1)*(x*_b_ + a_)**(m_ + 1)*(-a_*_f_ + _b_*_e_)**p_*appellf1(m_ + 1, -n_, -p_, m_ + 2, -_d_*(x*_b_ + a_)/(-a_*_d_ + _b_*_c_), -_f_*(x*_b_ + a_)/(-a_*_f_ + _b_*_e_))/((_b_/(-a_*_d_ + _b_*_c_))**n_*(m_ + 1)),
        module_name='1.1.1.3 (a+b x)^m (c+d x)^n (e+f x)^p',
        rule_number=68,
    ),
    # Rule 69
    SymPyReplacementPattern(
        pattern=Int((x*_b_ + a_)**m_*(x*_d_ + _c_)**n_*(x*_f_ + _e_)**p_, x),
        constraints=(FreeQ([a_, _b_, _c_, _d_, _e_, _f_, m_, n_], x), Not(IntegerQ(m_)), Not(IntegerQ(n_)), IntegerQ(p_), Not(GtQ(_b_/(-a_*_d_ + _b_*_c_), 0)), Not(SimplerQ(x*_d_ + _c_, x*_b_ + a_)),),
        replacement=(x*_d_ + _c_)**FracPart(n_)*Int((x*_b_ + a_)**m_*(x*_f_ + _e_)**p_*(x*_b_*_d_/(-a_*_d_ + _b_*_c_) + _b_*_c_/(-a_*_d_ + _b_*_c_))**n_, x)/((_b_/(-a_*_d_ + _b_*_c_))**IntPart(n_)*(_b_*(x*_d_ + _c_)/(-a_*_d_ + _b_*_c_))**FracPart(n_)),
        module_name='1.1.1.3 (a+b x)^m (c+d x)^n (e+f x)^p',
        rule_number=69,
    ),
    # Rule 70
    SymPyReplacementPattern(
        pattern=Int((x*_b_ + a_)**m_*(x*_d_ + _c_)**n_*(x*_f_ + _e_)**p_, x),
        constraints=(FreeQ([a_, _b_, _c_, _d_, _e_, _f_, m_, n_, p_], x), Not(IntegerQ(m_)), Not(IntegerQ(n_)), Not(IntegerQ(p_)), GtQ(_b_/(-a_*_d_ + _b_*_c_), 0), GtQ(_b_/(-a_*_f_ + _b_*_e_), 0), Not(And(GtQ(_d_/(a_*_d_ - _b_*_c_), 0), GtQ(_d_/(-_c_*_f_ + _d_*_e_), 0), SimplerQ(x*_d_ + _c_, x*_b_ + a_))), Not(And(GtQ(_f_/(a_*_f_ - _b_*_e_), 0), GtQ(_f_/(_c_*_f_ - _d_*_e_), 0), SimplerQ(x*_f_ + _e_, x*_b_ + a_))),),
        replacement=(x*_b_ + a_)**(m_ + 1)*appellf1(m_ + 1, -n_, -p_, m_ + 2, -_d_*(x*_b_ + a_)/(-a_*_d_ + _b_*_c_), -_f_*(x*_b_ + a_)/(-a_*_f_ + _b_*_e_))/(_b_*(_b_/(-a_*_d_ + _b_*_c_))**n_*(_b_/(-a_*_f_ + _b_*_e_))**p_*(m_ + 1)),
        module_name='1.1.1.3 (a+b x)^m (c+d x)^n (e+f x)^p',
        rule_number=70,
    ),
    # Rule 71
    SymPyReplacementPattern(
        pattern=Int((x*_b_ + a_)**m_*(x*_d_ + _c_)**n_*(x*_f_ + _e_)**p_, x),
        constraints=(FreeQ([a_, _b_, _c_, _d_, _e_, _f_, m_, n_, p_], x), Not(IntegerQ(m_)), Not(IntegerQ(n_)), Not(IntegerQ(p_)), GtQ(_b_/(-a_*_d_ + _b_*_c_), 0), Not(GtQ(_b_/(-a_*_f_ + _b_*_e_), 0)),),
        replacement=(x*_f_ + _e_)**FracPart(p_)*Int((x*_b_ + a_)**m_*(x*_d_ + _c_)**n_*(x*_b_*_f_/(-a_*_f_ + _b_*_e_) + _b_*_e_/(-a_*_f_ + _b_*_e_))**p_, x)/((_b_/(-a_*_f_ + _b_*_e_))**IntPart(p_)*(_b_*(x*_f_ + _e_)/(-a_*_f_ + _b_*_e_))**FracPart(p_)),
        module_name='1.1.1.3 (a+b x)^m (c+d x)^n (e+f x)^p',
        rule_number=71,
    ),
    # Rule 72
    SymPyReplacementPattern(
        pattern=Int((x*_b_ + a_)**m_*(x*_d_ + _c_)**n_*(x*_f_ + _e_)**p_, x),
        constraints=(FreeQ([a_, _b_, _c_, _d_, _e_, _f_, m_, n_, p_], x), Not(IntegerQ(m_)), Not(IntegerQ(n_)), Not(IntegerQ(p_)), Not(GtQ(_b_/(-a_*_d_ + _b_*_c_), 0)), Not(SimplerQ(x*_d_ + _c_, x*_b_ + a_)), Not(SimplerQ(x*_f_ + _e_, x*_b_ + a_)),),
        replacement=(x*_d_ + _c_)**FracPart(n_)*Int((x*_b_ + a_)**m_*(x*_f_ + _e_)**p_*(x*_b_*_d_/(-a_*_d_ + _b_*_c_) + _b_*_c_/(-a_*_d_ + _b_*_c_))**n_, x)/((_b_/(-a_*_d_ + _b_*_c_))**IntPart(n_)*(_b_*(x*_d_ + _c_)/(-a_*_d_ + _b_*_c_))**FracPart(n_)),
        module_name='1.1.1.3 (a+b x)^m (c+d x)^n (e+f x)^p',
        rule_number=72,
    ),
    # Rule 73
    SymPyReplacementPattern(
        pattern=Int((_a_ + _b_*u_)**_m_*(_c_ + _d_*u_)**_n_*(e_ + _f_*u_)**_p_, x),
        constraints=(FreeQ([_a_, _b_, _c_, _d_, e_, _f_, _m_, _n_, _p_], x), LinearQ(u_, x), NeQ(u_, x),),
        replacement=Subst(Int((x*_b_ + _a_)**_m_*(x*_d_ + _c_)**_n_*(x*_f_ + e_)**_p_, x), x, u_)/Coefficient(u_, x, 1),
        module_name='1.1.1.3 (a+b x)^m (c+d x)^n (e+f x)^p',
        rule_number=73,
    ),

]

# Summary: 73 rules translated, 0 skipped
