# -*- coding: utf-8 -*-
# =============================================================================
# !! AUTO-GENERATED FILE -- DO NOT EDIT !!
#
# Generated by: rubi_integrate/codegen/generate.py
# Source: 5.3.5 u (a+b arctan(c+d x))^p.m
# Module: 5.3.5 u (a+b arctan(c+d x))^p
#
# This file contains Rubi integration rules as SymPyReplacementPattern objects.
# Re-run the generator to update.
# =============================================================================
import sympy
from sympy import Symbol
from rubi_integrate.utils.rubi_utils import *  # bare-name access; sympy imports below override any conflicts (e.g. Not)
from sympy.logic.boolalg import Not
from sympy import (
    I, acot, atan, log,
)

from sympy_matching.wild import WildSymbol, IDENTITY_ELEMENT
from rubi_integrate.base_objects import Int, SymPyReplacementPattern
# Inert trig markers (Rubi's lowercase sin/cos/... patterns). Distinct opaque heads,
# NOT subclasses of sympy.sin -- see rubi-trig-deactivation-dispatch project note.
from rubi_integrate.utils import (
    # Wolfram standard constraints
    FreeQ, EqQ, IGtQ, ILtQ, RationalQ,
)

# --- Integration variable ---
x = Symbol('x')

# --- Rubi global option stubs (default False/placeholder) ---
UseGamma = sympy.Symbol('UseGamma')  # Rubi global option; treated as False in Python
u = Symbol('u')  # Generic integrand placeholder used in some Rubi constraint calls

# --- Rubi selector symbols ---
# Rubi passes Min/Max as bare SYMBOLS, not calls: Expon[Px, x, Min] selects the
# minimum exponent. The code emitter round-trips through SymPy's printer, which
# renders Symbol('Min') as the bare name `Min`, so the name must exist here.
# (A genuine Min[a, b] call is emitted qualified, as sympy.Min(...), so these
# bindings cannot shadow it.)
Min = Symbol('Min')
Max = Symbol('Max')

# --- Wildcard symbols ---
# dot wildcards (must match exactly one expression)
# optional wildcards (can match identity element if absent in commutative ops)

_A_ = WildSymbol('A', optional_value=IDENTITY_ELEMENT)
A_ = WildSymbol('A')
_B_ = WildSymbol('B', optional_value=IDENTITY_ELEMENT)
B_ = WildSymbol('B')
_C_ = WildSymbol('C', optional_value=IDENTITY_ELEMENT)
C_ = WildSymbol('C')
_a_ = WildSymbol('a', optional_value=IDENTITY_ELEMENT)
a_ = WildSymbol('a')
_b_ = WildSymbol('b', optional_value=IDENTITY_ELEMENT)
b_ = WildSymbol('b')
c_ = WildSymbol('c')
_d_ = WildSymbol('d', optional_value=IDENTITY_ELEMENT)
d_ = WildSymbol('d')
_e_ = WildSymbol('e', optional_value=IDENTITY_ELEMENT)
e_ = WildSymbol('e')
_f_ = WildSymbol('f', optional_value=IDENTITY_ELEMENT)
f_ = WildSymbol('f')
_m_ = WildSymbol('m', optional_value=IDENTITY_ELEMENT)
m_ = WildSymbol('m')
_n_ = WildSymbol('n', optional_value=IDENTITY_ELEMENT)
n_ = WildSymbol('n')
_p_ = WildSymbol('p', optional_value=IDENTITY_ELEMENT)
p_ = WildSymbol('p')
_q_ = WildSymbol('q', optional_value=IDENTITY_ELEMENT)
q_ = WildSymbol('q')

RULES = [
    # Rule 1
    SymPyReplacementPattern(
        pattern=Int((_a_ + _b_*atan(x*_d_ + c_))**_p_, x),
        constraints=(FreeQ([_a_, _b_, c_, _d_], x), IGtQ(_p_, 0),),
        replacement=Subst(Int((_a_ + _b_*atan(x))**_p_, x), x, x*_d_ + c_)/_d_,
        module_name='5.3.5 u (a+b arctan(c+d x))^p',
        rule_number=1,
    ),
    # Rule 2
    SymPyReplacementPattern(
        pattern=Int((_a_ + _b_*acot(x*_d_ + c_))**_p_, x),
        constraints=(FreeQ([_a_, _b_, c_, _d_], x), IGtQ(_p_, 0),),
        replacement=Subst(Int((_a_ + _b_*acot(x))**_p_, x), x, x*_d_ + c_)/_d_,
        module_name='5.3.5 u (a+b arctan(c+d x))^p',
        rule_number=2,
    ),
    # Rule 3
    SymPyReplacementPattern(
        pattern=Int((_a_ + _b_*atan(x*_d_ + c_))**p_, x),
        constraints=(FreeQ([_a_, _b_, c_, _d_, p_], x), Not(IGtQ(p_, 0)),),
        replacement=Unintegrable((_a_ + _b_*atan(x*_d_ + c_))**p_, x),
        module_name='5.3.5 u (a+b arctan(c+d x))^p',
        rule_number=3,
    ),
    # Rule 4
    SymPyReplacementPattern(
        pattern=Int((_a_ + _b_*acot(x*_d_ + c_))**p_, x),
        constraints=(FreeQ([_a_, _b_, c_, _d_, p_], x), Not(IGtQ(p_, 0)),),
        replacement=Unintegrable((_a_ + _b_*acot(x*_d_ + c_))**p_, x),
        module_name='5.3.5 u (a+b arctan(c+d x))^p',
        rule_number=4,
    ),
    # Rule 5
    SymPyReplacementPattern(
        pattern=Int((_a_ + _b_*atan(x*_d_ + c_))**_p_*(x*_f_ + _e_)**_m_, x),
        constraints=(FreeQ([_a_, _b_, c_, _d_, _e_, _f_, _m_], x), EqQ(-c_*_f_ + _d_*_e_, 0), IGtQ(_p_, 0),),
        replacement=Subst(Int((x*_f_/_d_)**_m_*(_a_ + _b_*atan(x))**_p_, x), x, x*_d_ + c_)/_d_,
        module_name='5.3.5 u (a+b arctan(c+d x))^p',
        rule_number=5,
    ),
    # Rule 6
    SymPyReplacementPattern(
        pattern=Int((_a_ + _b_*acot(x*_d_ + c_))**_p_*(x*_f_ + _e_)**_m_, x),
        constraints=(FreeQ([_a_, _b_, c_, _d_, _e_, _f_, _m_], x), EqQ(-c_*_f_ + _d_*_e_, 0), IGtQ(_p_, 0),),
        replacement=Subst(Int((x*_f_/_d_)**_m_*(_a_ + _b_*acot(x))**_p_, x), x, x*_d_ + c_)/_d_,
        module_name='5.3.5 u (a+b arctan(c+d x))^p',
        rule_number=6,
    ),
    # Rule 7
    SymPyReplacementPattern(
        pattern=Int((_a_ + _b_*atan(x*_d_ + c_))**_p_*(x*_f_ + _e_)**m_, x),
        constraints=(FreeQ([_a_, _b_, c_, _d_, _e_, _f_], x), IGtQ(_p_, 0), ILtQ(m_, -1),),
        replacement=-_b_*_d_*_p_*Int((_a_ + _b_*atan(x*_d_ + c_))**(_p_ - 1)*(x*_f_ + _e_)**(m_ + 1)/((x*_d_ + c_)**2 + 1), x)/(_f_*(m_ + 1)) + (_a_ + _b_*atan(x*_d_ + c_))**_p_*(x*_f_ + _e_)**(m_ + 1)/(_f_*(m_ + 1)),
        module_name='5.3.5 u (a+b arctan(c+d x))^p',
        rule_number=7,
    ),
    # Rule 8
    SymPyReplacementPattern(
        pattern=Int((_a_ + _b_*acot(x*_d_ + c_))**_p_*(x*_f_ + _e_)**m_, x),
        constraints=(FreeQ([_a_, _b_, c_, _d_, _e_, _f_], x), IGtQ(_p_, 0), ILtQ(m_, -1),),
        replacement=_b_*_d_*_p_*Int((_a_ + _b_*acot(x*_d_ + c_))**(_p_ - 1)*(x*_f_ + _e_)**(m_ + 1)/((x*_d_ + c_)**2 + 1), x)/(_f_*(m_ + 1)) + (_a_ + _b_*acot(x*_d_ + c_))**_p_*(x*_f_ + _e_)**(m_ + 1)/(_f_*(m_ + 1)),
        module_name='5.3.5 u (a+b arctan(c+d x))^p',
        rule_number=8,
    ),
    # Rule 9
    SymPyReplacementPattern(
        pattern=Int((_a_ + _b_*atan(x*_d_ + c_))**_p_*(x*_f_ + _e_)**_m_, x),
        constraints=(FreeQ([_a_, _b_, c_, _d_, _e_, _f_, _m_, _p_], x), IGtQ(_p_, 0),),
        replacement=Subst(Int((_a_ + _b_*atan(x))**_p_*(x*_f_/_d_ + (-c_*_f_ + _d_*_e_)/_d_)**_m_, x), x, x*_d_ + c_)/_d_,
        module_name='5.3.5 u (a+b arctan(c+d x))^p',
        rule_number=9,
    ),
    # Rule 10
    SymPyReplacementPattern(
        pattern=Int((_a_ + _b_*acot(x*_d_ + c_))**_p_*(x*_f_ + _e_)**_m_, x),
        constraints=(FreeQ([_a_, _b_, c_, _d_, _e_, _f_, _m_, _p_], x), IGtQ(_p_, 0),),
        replacement=Subst(Int((_a_ + _b_*acot(x))**_p_*(x*_f_/_d_ + (-c_*_f_ + _d_*_e_)/_d_)**_m_, x), x, x*_d_ + c_)/_d_,
        module_name='5.3.5 u (a+b arctan(c+d x))^p',
        rule_number=10,
    ),
    # Rule 11
    SymPyReplacementPattern(
        pattern=Int((_a_ + _b_*atan(x*_d_ + c_))**p_*(x*_f_ + _e_)**_m_, x),
        constraints=(FreeQ([_a_, _b_, c_, _d_, _e_, _f_, _m_, p_], x), Not(IGtQ(p_, 0)),),
        replacement=Unintegrable((_a_ + _b_*atan(x*_d_ + c_))**p_*(x*_f_ + _e_)**_m_, x),
        module_name='5.3.5 u (a+b arctan(c+d x))^p',
        rule_number=11,
    ),
    # Rule 12
    SymPyReplacementPattern(
        pattern=Int((_a_ + _b_*acot(x*_d_ + c_))**p_*(x*_f_ + _e_)**_m_, x),
        constraints=(FreeQ([_a_, _b_, c_, _d_, _e_, _f_, _m_, p_], x), Not(IGtQ(p_, 0)),),
        replacement=Unintegrable((_a_ + _b_*acot(x*_d_ + c_))**p_*(x*_f_ + _e_)**_m_, x),
        module_name='5.3.5 u (a+b arctan(c+d x))^p',
        rule_number=12,
    ),
    # Rule 13
    SymPyReplacementPattern(
        pattern=Int(atan(x*_b_ + a_)/(x**_n_*_d_ + c_), x),
        constraints=(FreeQ([a_, _b_, c_, _d_], x), RationalQ(_n_),),
        replacement=I*Int(log(-I*x*_b_ - I*a_ + 1)/(x**_n_*_d_ + c_), x)/2 - I*Int(log(I*x*_b_ + I*a_ + 1)/(x**_n_*_d_ + c_), x)/2,
        module_name='5.3.5 u (a+b arctan(c+d x))^p',
        rule_number=13,
    ),
    # Rule 14
    SymPyReplacementPattern(
        pattern=Int(acot(x*_b_ + a_)/(x**_n_*_d_ + c_), x),
        constraints=(FreeQ([a_, _b_, c_, _d_], x), RationalQ(_n_),),
        replacement=I*Int(log((x*_b_ + a_ - I)/(x*_b_ + a_))/(x**_n_*_d_ + c_), x)/2 - I*Int(log((x*_b_ + a_ + I)/(x*_b_ + a_))/(x**_n_*_d_ + c_), x)/2,
        module_name='5.3.5 u (a+b arctan(c+d x))^p',
        rule_number=14,
    ),
    # Rule 15
    SymPyReplacementPattern(
        pattern=Int(atan(x*_b_ + a_)/(x**n_*_d_ + c_), x),
        constraints=(FreeQ([a_, _b_, c_, _d_, n_], x), Not(RationalQ(n_)),),
        replacement=Unintegrable(atan(x*_b_ + a_)/(x**n_*_d_ + c_), x),
        module_name='5.3.5 u (a+b arctan(c+d x))^p',
        rule_number=15,
    ),
    # Rule 16
    SymPyReplacementPattern(
        pattern=Int(acot(x*_b_ + a_)/(x**n_*_d_ + c_), x),
        constraints=(FreeQ([a_, _b_, c_, _d_, n_], x), Not(RationalQ(n_)),),
        replacement=Unintegrable(acot(x*_b_ + a_)/(x**n_*_d_ + c_), x),
        module_name='5.3.5 u (a+b arctan(c+d x))^p',
        rule_number=16,
    ),
    # Rule 17
    SymPyReplacementPattern(
        pattern=Int((_a_ + _b_*atan(x*_d_ + c_))**_p_*(x**2*_C_ + x*_B_ + _A_)**_q_, x),
        constraints=(FreeQ([_a_, _b_, c_, _d_, _A_, _B_, _C_, _p_, _q_], x), EqQ(-2*_A_*c_*_d_ + _B_*(c_**2 + 1), 0), EqQ(-_B_*_d_ + 2*_C_*c_, 0),),
        replacement=Subst(Int((_a_ + _b_*atan(x))**_p_*(x**2*_C_/_d_**2 + _C_/_d_**2)**_q_, x), x, x*_d_ + c_)/_d_,
        module_name='5.3.5 u (a+b arctan(c+d x))^p',
        rule_number=17,
    ),
    # Rule 18
    SymPyReplacementPattern(
        pattern=Int((_a_ + _b_*acot(x*_d_ + c_))**_p_*(x**2*_C_ + x*_B_ + _A_)**_q_, x),
        constraints=(FreeQ([_a_, _b_, c_, _d_, _A_, _B_, _C_, _p_, _q_], x), EqQ(-2*_A_*c_*_d_ + _B_*(c_**2 + 1), 0), EqQ(-_B_*_d_ + 2*_C_*c_, 0),),
        replacement=Subst(Int((_a_ + _b_*acot(x))**_p_*(x**2*_C_/_d_**2 + _C_/_d_**2)**_q_, x), x, x*_d_ + c_)/_d_,
        module_name='5.3.5 u (a+b arctan(c+d x))^p',
        rule_number=18,
    ),
    # Rule 19
    SymPyReplacementPattern(
        pattern=Int((_a_ + _b_*atan(x*_d_ + c_))**_p_*(x*_f_ + _e_)**_m_*(x**2*_C_ + x*_B_ + _A_)**_q_, x),
        constraints=(FreeQ([_a_, _b_, c_, _d_, _e_, _f_, _A_, _B_, _C_, _m_, _p_, _q_], x), EqQ(-2*_A_*c_*_d_ + _B_*(c_**2 + 1), 0), EqQ(-_B_*_d_ + 2*_C_*c_, 0),),
        replacement=Subst(Int((_a_ + _b_*atan(x))**_p_*(x*_f_/_d_ + (-c_*_f_ + _d_*_e_)/_d_)**_m_*(x**2*_C_/_d_**2 + _C_/_d_**2)**_q_, x), x, x*_d_ + c_)/_d_,
        module_name='5.3.5 u (a+b arctan(c+d x))^p',
        rule_number=19,
    ),
    # Rule 20
    SymPyReplacementPattern(
        pattern=Int((_a_ + _b_*acot(x*_d_ + c_))**_p_*(x*_f_ + _e_)**_m_*(x**2*_C_ + x*_B_ + _A_)**_q_, x),
        constraints=(FreeQ([_a_, _b_, c_, _d_, _e_, _f_, _A_, _B_, _C_, _m_, _p_, _q_], x), EqQ(-2*_A_*c_*_d_ + _B_*(c_**2 + 1), 0), EqQ(-_B_*_d_ + 2*_C_*c_, 0),),
        replacement=Subst(Int((_a_ + _b_*acot(x))**_p_*(x*_f_/_d_ + (-c_*_f_ + _d_*_e_)/_d_)**_m_*(x**2*_C_/_d_**2 + _C_/_d_**2)**_q_, x), x, x*_d_ + c_)/_d_,
        module_name='5.3.5 u (a+b arctan(c+d x))^p',
        rule_number=20,
    ),

]

# Summary: 20 rules translated, 0 skipped
