# -*- coding: utf-8 -*-
# =============================================================================
# !! AUTO-GENERATED FILE -- DO NOT EDIT !!
#
# Generated by: rubi_integrate/codegen/generate.py
# Source: 4.1.6 (a+b cos+c sin)^n.m
# Module: 4.1.6 (a+b cos+c sin)^n
#
# This file contains Rubi integration rules as SymPyReplacementPattern objects.
# Re-run the generator to update.
# =============================================================================
import sympy
from sympy import Symbol
from rubi_integrate.utils.rubi_utils import *  # bare-name access; sympy imports below override any conflicts (e.g. Not)
from sympy.logic.boolalg import Not
from sympy import (
    atan2, cos, cot, csc, log, pi, sec, sin, sqrt, tan,
)

from sympy_matching.wild import WildSymbol, IDENTITY_ELEMENT
from rubi_integrate.base_objects import Int, SymPyReplacementPattern
# Inert trig markers (Rubi's lowercase sin/cos/... patterns). Distinct opaque heads,
# NOT subclasses of sympy.sin -- see rubi-trig-deactivation-dispatch project note.
from rubi_integrate.utils.inert_functions import (
    InertSin, InertCos, InertTan, InertCot, InertSec, InertCsc)
from rubi_integrate.utils import (
    # Wolfram standard constraints
    FreeQ, IntegerQ, EqQ, NeQ, GtQ, LtQ,
)

# --- Integration variable ---
x = Symbol('x')

# --- Rubi global option stubs (default False/placeholder) ---
UseGamma = sympy.Symbol('UseGamma')  # Rubi global option; treated as False in Python
u = Symbol('u')  # Generic integrand placeholder used in some Rubi constraint calls

# --- Rubi selector symbols ---
# Rubi passes Min/Max as bare SYMBOLS, not calls: Expon[Px, x, Min] selects the
# minimum exponent. The code emitter round-trips through SymPy's printer, which
# renders Symbol('Min') as the bare name `Min`, so the name must exist here.
# (A genuine Min[a, b] call is emitted qualified, as sympy.Min(...), so these
# bindings cannot shadow it.)
Min = Symbol('Min')
Max = Symbol('Max')

# --- Wildcard symbols ---
# dot wildcards (must match exactly one expression)
# optional wildcards (can match identity element if absent in commutative ops)

f = Symbol('f')

_A_ = WildSymbol('A', optional_value=IDENTITY_ELEMENT)
A_ = WildSymbol('A')
_B_ = WildSymbol('B', optional_value=IDENTITY_ELEMENT)
B_ = WildSymbol('B')
_C_ = WildSymbol('C', optional_value=IDENTITY_ELEMENT)
C_ = WildSymbol('C')
_a_ = WildSymbol('a', optional_value=IDENTITY_ELEMENT)
a_ = WildSymbol('a')
_b_ = WildSymbol('b', optional_value=IDENTITY_ELEMENT)
b_ = WildSymbol('b')
_c_ = WildSymbol('c', optional_value=IDENTITY_ELEMENT)
c_ = WildSymbol('c')
_d_ = WildSymbol('d', optional_value=IDENTITY_ELEMENT)
d_ = WildSymbol('d')
_e_ = WildSymbol('e', optional_value=IDENTITY_ELEMENT)
e_ = WildSymbol('e')
m_ = WildSymbol('m')
_n_ = WildSymbol('n', optional_value=IDENTITY_ELEMENT)
n_ = WildSymbol('n')

RULES = [
    # Rule 1
    SymPyReplacementPattern(
        pattern=Int(sqrt(a_ + _b_*InertCos(x*_e_ + _d_) + _c_*InertSin(x*_e_ + _d_)), x),
        constraints=(FreeQ([a_, _b_, _c_, _d_, _e_], x), EqQ(a_**2 - _b_**2 - _c_**2, 0),),
        replacement=(2*_b_*sin(x*_e_ + _d_) - 2*_c_*cos(x*_e_ + _d_))/(_e_*sqrt(a_ + _b_*cos(x*_e_ + _d_) + _c_*sin(x*_e_ + _d_))),
        module_name='4.1.6 (a+b cos+c sin)^n',
        rule_number=1,
    ),
    # Rule 2
    SymPyReplacementPattern(
        pattern=Int((a_ + _b_*InertCos(x*_e_ + _d_) + _c_*InertSin(x*_e_ + _d_))**n_, x),
        constraints=(FreeQ([a_, _b_, _c_, _d_, _e_], x), EqQ(a_**2 - _b_**2 - _c_**2, 0), GtQ(n_, 0),),
        replacement=a_*(2*n_ - 1)*Int((a_ + _b_*cos(x*_e_ + _d_) + _c_*sin(x*_e_ + _d_))**(n_ - 1), x)/n_ + (_b_*sin(x*_e_ + _d_) - _c_*cos(x*_e_ + _d_))*(a_ + _b_*cos(x*_e_ + _d_) + _c_*sin(x*_e_ + _d_))**(n_ - 1)/(_e_*n_),
        module_name='4.1.6 (a+b cos+c sin)^n',
        rule_number=2,
    ),
    # Rule 3
    SymPyReplacementPattern(
        pattern=Int(1/(a_ + _b_*InertCos(x*_e_ + _d_) + _c_*InertSin(x*_e_ + _d_)), x),
        constraints=(FreeQ([a_, _b_, _c_, _d_, _e_], x), EqQ(a_**2 - _b_**2 - _c_**2, 0),),
        replacement=(a_*sin(x*_e_ + _d_) - _c_)/(_c_*_e_*(-_b_*sin(x*_e_ + _d_) + _c_*cos(x*_e_ + _d_))),
        module_name='4.1.6 (a+b cos+c sin)^n',
        rule_number=3,
    ),
    # Rule 4
    SymPyReplacementPattern(
        pattern=Int(1/sqrt(a_ + _b_*InertCos(x*_e_ + _d_) + _c_*InertSin(x*_e_ + _d_)), x),
        constraints=(FreeQ([a_, _b_, _c_, _d_, _e_], x), EqQ(a_**2 - _b_**2 - _c_**2, 0),),
        replacement=Int(1/sqrt(a_ + sqrt(_b_**2 + _c_**2)*cos(x*_e_ + _d_ - atan2(_c_, _b_))), x),
        module_name='4.1.6 (a+b cos+c sin)^n',
        rule_number=4,
    ),
    # Rule 5
    SymPyReplacementPattern(
        pattern=Int((a_ + _b_*InertCos(x*_e_ + _d_) + _c_*InertSin(x*_e_ + _d_))**n_, x),
        constraints=(FreeQ([a_, _b_, _c_, _d_, _e_], x), EqQ(a_**2 - _b_**2 - _c_**2, 0), LtQ(n_, -1),),
        replacement=(n_ + 1)*Int((a_ + _b_*cos(x*_e_ + _d_) + _c_*sin(x*_e_ + _d_))**(n_ + 1), x)/(a_*(2*n_ + 1)) + (-_b_*sin(x*_e_ + _d_) + _c_*cos(x*_e_ + _d_))*(a_ + _b_*cos(x*_e_ + _d_) + _c_*sin(x*_e_ + _d_))**n_/(a_*_e_*(2*n_ + 1)),
        module_name='4.1.6 (a+b cos+c sin)^n',
        rule_number=5,
    ),
    # Rule 6
    SymPyReplacementPattern(
        pattern=Int(sqrt(a_ + _b_*InertCos(x*_e_ + _d_) + _c_*InertSin(x*_e_ + _d_)), x),
        constraints=(FreeQ([a_, _b_, _c_, _d_, _e_], x), EqQ(_b_**2 + _c_**2, 0),),
        replacement=_b_*Subst(Int(sqrt(x + a_)/x, x), x, _b_*cos(x*_e_ + _d_) + _c_*sin(x*_e_ + _d_))/(_c_*_e_),
        module_name='4.1.6 (a+b cos+c sin)^n',
        rule_number=6,
    ),
    # Rule 7
    SymPyReplacementPattern(
        pattern=Int(sqrt(a_ + _b_*InertCos(x*_e_ + _d_) + _c_*InertSin(x*_e_ + _d_)), x),
        constraints=(FreeQ([a_, _b_, _c_, _d_, _e_], x), NeQ(_b_**2 + _c_**2, 0), GtQ(a_ + sqrt(_b_**2 + _c_**2), 0),),
        replacement=Int(sqrt(a_ + sqrt(_b_**2 + _c_**2)*cos(x*_e_ + _d_ - atan2(_c_, _b_))), x),
        module_name='4.1.6 (a+b cos+c sin)^n',
        rule_number=7,
    ),
    # Rule 8
    SymPyReplacementPattern(
        pattern=Int(sqrt(a_ + _b_*InertCos(x*_e_ + _d_) + _c_*InertSin(x*_e_ + _d_)), x),
        constraints=(FreeQ([a_, _b_, _c_, _d_, _e_], x), NeQ(a_**2 - _b_**2 - _c_**2, 0), NeQ(_b_**2 + _c_**2, 0), Not(GtQ(a_ + sqrt(_b_**2 + _c_**2), 0)),),
        replacement=sqrt(a_ + _b_*cos(x*_e_ + _d_) + _c_*sin(x*_e_ + _d_))*Int(sqrt(a_/(a_ + sqrt(_b_**2 + _c_**2)) + sqrt(_b_**2 + _c_**2)*cos(x*_e_ + _d_ - atan2(_c_, _b_))/(a_ + sqrt(_b_**2 + _c_**2))), x)/sqrt((a_ + _b_*cos(x*_e_ + _d_) + _c_*sin(x*_e_ + _d_))/(a_ + sqrt(_b_**2 + _c_**2))),
        module_name='4.1.6 (a+b cos+c sin)^n',
        rule_number=8,
    ),
    # Rule 9
    SymPyReplacementPattern(
        pattern=Int((a_ + _b_*InertCos(x*_e_ + _d_) + _c_*InertSin(x*_e_ + _d_))**n_, x),
        constraints=(FreeQ([a_, _b_, _c_, _d_, _e_], x), NeQ(a_**2 - _b_**2 - _c_**2, 0), GtQ(n_, 1),),
        replacement=Int((a_ + _b_*cos(x*_e_ + _d_) + _c_*sin(x*_e_ + _d_))**(n_ - 2)*Simp(a_**2*n_ + a_*_b_*(2*n_ - 1)*cos(x*_e_ + _d_) + a_*_c_*(2*n_ - 1)*sin(x*_e_ + _d_) + (_b_**2 + _c_**2)*(n_ - 1), x), x)/n_ + (_b_*sin(x*_e_ + _d_) - _c_*cos(x*_e_ + _d_))*(a_ + _b_*cos(x*_e_ + _d_) + _c_*sin(x*_e_ + _d_))**(n_ - 1)/(_e_*n_),
        module_name='4.1.6 (a+b cos+c sin)^n',
        rule_number=9,
    ),
    # Rule 10
    SymPyReplacementPattern(
        pattern=Int(1/(a_ + _b_*InertCos(x*_e_ + _d_) + _c_*InertSin(x*_e_ + _d_)), x),
        constraints=(FreeQ([a_, _b_, _c_, _d_, _e_], x), EqQ(a_ + _b_, 0),),
        replacement=Module({f: FreeFactors(cot(x*_e_/2 + _d_/2), x)}, -f*Subst(Int(1/(f*x*_c_ + a_), x), x, cot(x*_e_/2 + _d_/2)/f)/_e_),
        module_name='4.1.6 (a+b cos+c sin)^n',
        rule_number=10,
    ),
    # Rule 11
    SymPyReplacementPattern(
        pattern=Int(1/(a_ + _b_*InertCos(x*_e_ + _d_) + _c_*InertSin(x*_e_ + _d_)), x),
        constraints=(FreeQ([a_, _b_, _c_, _d_, _e_], x), EqQ(a_ + _c_, 0),),
        replacement=Module({f: FreeFactors(tan(x*_e_/2 + _d_/2 + pi/4), x)}, f*Subst(Int(1/(f*x*_b_ + a_), x), x, tan(x*_e_/2 + _d_/2 + pi/4)/f)/_e_),
        module_name='4.1.6 (a+b cos+c sin)^n',
        rule_number=11,
    ),
    # Rule 12
    SymPyReplacementPattern(
        pattern=Int(1/(a_ + _b_*InertCos(x*_e_ + _d_) + _c_*InertSin(x*_e_ + _d_)), x),
        constraints=(FreeQ([a_, _b_, _c_, _d_, _e_], x), EqQ(a_ - _c_, 0), NeQ(a_ - _b_, 0),),
        replacement=Module({f: FreeFactors(cot(x*_e_/2 + _d_/2 + pi/4), x)}, -f*Subst(Int(1/(f*x*_b_ + a_), x), x, cot(x*_e_/2 + _d_/2 + pi/4)/f)/_e_),
        module_name='4.1.6 (a+b cos+c sin)^n',
        rule_number=12,
    ),
    # Rule 13
    SymPyReplacementPattern(
        pattern=Int(1/(a_ + _b_*InertCos(x*_e_ + _d_) + _c_*InertSin(x*_e_ + _d_)), x),
        constraints=(FreeQ([a_, _b_, _c_, _d_, _e_], x), NeQ(a_**2 - _b_**2 - _c_**2, 0),),
        replacement=Module({f: FreeFactors(tan(x*_e_/2 + _d_/2), x)}, 2*f*Subst(Int(1/(f**2*x**2*(a_ - _b_) + 2*f*x*_c_ + a_ + _b_), x), x, tan(x*_e_/2 + _d_/2)/f)/_e_),
        module_name='4.1.6 (a+b cos+c sin)^n',
        rule_number=13,
    ),
    # Rule 14
    SymPyReplacementPattern(
        pattern=Int(1/sqrt(a_ + _b_*InertCos(x*_e_ + _d_) + _c_*InertSin(x*_e_ + _d_)), x),
        constraints=(FreeQ([a_, _b_, _c_, _d_, _e_], x), EqQ(_b_**2 + _c_**2, 0),),
        replacement=_b_*Subst(Int(1/(x*sqrt(x + a_)), x), x, _b_*cos(x*_e_ + _d_) + _c_*sin(x*_e_ + _d_))/(_c_*_e_),
        module_name='4.1.6 (a+b cos+c sin)^n',
        rule_number=14,
    ),
    # Rule 15
    SymPyReplacementPattern(
        pattern=Int(1/sqrt(a_ + _b_*InertCos(x*_e_ + _d_) + _c_*InertSin(x*_e_ + _d_)), x),
        constraints=(FreeQ([a_, _b_, _c_, _d_, _e_], x), NeQ(_b_**2 + _c_**2, 0), GtQ(a_ + sqrt(_b_**2 + _c_**2), 0),),
        replacement=Int(1/sqrt(a_ + sqrt(_b_**2 + _c_**2)*cos(x*_e_ + _d_ - atan2(_c_, _b_))), x),
        module_name='4.1.6 (a+b cos+c sin)^n',
        rule_number=15,
    ),
    # Rule 16
    SymPyReplacementPattern(
        pattern=Int(1/sqrt(a_ + _b_*InertCos(x*_e_ + _d_) + _c_*InertSin(x*_e_ + _d_)), x),
        constraints=(FreeQ([a_, _b_, _c_, _d_, _e_], x), NeQ(a_**2 - _b_**2 - _c_**2, 0), NeQ(_b_**2 + _c_**2, 0), Not(GtQ(a_ + sqrt(_b_**2 + _c_**2), 0)),),
        replacement=sqrt((a_ + _b_*cos(x*_e_ + _d_) + _c_*sin(x*_e_ + _d_))/(a_ + sqrt(_b_**2 + _c_**2)))*Int(1/sqrt(a_/(a_ + sqrt(_b_**2 + _c_**2)) + sqrt(_b_**2 + _c_**2)*cos(x*_e_ + _d_ - atan2(_c_, _b_))/(a_ + sqrt(_b_**2 + _c_**2))), x)/sqrt(a_ + _b_*cos(x*_e_ + _d_) + _c_*sin(x*_e_ + _d_)),
        module_name='4.1.6 (a+b cos+c sin)^n',
        rule_number=16,
    ),
    # Rule 17
    SymPyReplacementPattern(
        pattern=Int((a_ + _b_*InertCos(x*_e_ + _d_) + _c_*InertSin(x*_e_ + _d_))**(sympy.S(-3)/2), x),
        constraints=(FreeQ([a_, _b_, _c_, _d_, _e_], x), NeQ(a_**2 - _b_**2 - _c_**2, 0),),
        replacement=Int(sqrt(a_ + _b_*cos(x*_e_ + _d_) + _c_*sin(x*_e_ + _d_)), x)/(a_**2 - _b_**2 - _c_**2) + (-2*_b_*sin(x*_e_ + _d_) + 2*_c_*cos(x*_e_ + _d_))/(_e_*(a_**2 - _b_**2 - _c_**2)*sqrt(a_ + _b_*cos(x*_e_ + _d_) + _c_*sin(x*_e_ + _d_))),
        module_name='4.1.6 (a+b cos+c sin)^n',
        rule_number=17,
    ),
    # Rule 18
    SymPyReplacementPattern(
        pattern=Int((a_ + _b_*InertCos(x*_e_ + _d_) + _c_*InertSin(x*_e_ + _d_))**n_, x),
        constraints=(FreeQ([a_, _b_, _c_, _d_, _e_], x), NeQ(a_**2 - _b_**2 - _c_**2, 0), LtQ(n_, -1), NeQ(n_, sympy.S(-3)/2),),
        replacement=Int((a_ + _b_*cos(x*_e_ + _d_) + _c_*sin(x*_e_ + _d_))**(n_ + 1)*(a_*(n_ + 1) - _b_*(n_ + 2)*cos(x*_e_ + _d_) - _c_*(n_ + 2)*sin(x*_e_ + _d_)), x)/((n_ + 1)*(a_**2 - _b_**2 - _c_**2)) + (_b_*sin(x*_e_ + _d_) - _c_*cos(x*_e_ + _d_))*(a_ + _b_*cos(x*_e_ + _d_) + _c_*sin(x*_e_ + _d_))**(n_ + 1)/(_e_*(n_ + 1)*(a_**2 - _b_**2 - _c_**2)),
        module_name='4.1.6 (a+b cos+c sin)^n',
        rule_number=18,
    ),
    # Rule 19
    SymPyReplacementPattern(
        pattern=Int((_A_ + _B_*InertCos(x*_e_ + _d_) + _C_*InertSin(x*_e_ + _d_))/(a_ + _b_*InertCos(x*_e_ + _d_) + _c_*InertSin(x*_e_ + _d_)), x),
        constraints=(FreeQ([a_, _b_, _c_, _d_, _e_, _A_, _B_, _C_], x), EqQ(_b_**2 + _c_**2, 0),),
        replacement=x*(2*_A_*a_ - _B_*_b_ - _C_*_c_)/(2*a_**2) - (_B_*_b_ + _C_*_c_)*(_b_*cos(x*_e_ + _d_) - _c_*sin(x*_e_ + _d_))/(2*a_*_b_*_c_*_e_) + (-2*_A_*a_*_b_**2 + a_**2*(_B_*_b_ - _C_*_c_) + _b_**2*(_B_*_b_ + _C_*_c_))*log(a_ + _b_*cos(x*_e_ + _d_) + _c_*sin(x*_e_ + _d_))/(2*a_**2*_b_*_c_*_e_),
        module_name='4.1.6 (a+b cos+c sin)^n',
        rule_number=19,
    ),
    # Rule 20
    SymPyReplacementPattern(
        pattern=Int((_A_ + _C_*InertSin(x*_e_ + _d_))/(a_ + _b_*InertCos(x*_e_ + _d_) + _c_*InertSin(x*_e_ + _d_)), x),
        constraints=(FreeQ([a_, _b_, _c_, _d_, _e_, _A_, _C_], x), EqQ(_b_**2 + _c_**2, 0),),
        replacement=x*(2*_A_*a_ - _C_*_c_)/(2*a_**2) - _C_*cos(x*_e_ + _d_)/(2*a_*_e_) + _C_*_c_*sin(x*_e_ + _d_)/(2*a_*_b_*_e_) + (2*_A_*a_*_c_ - _C_*a_**2 + _C_*_b_**2)*log(a_ + _b_*cos(x*_e_ + _d_) + _c_*sin(x*_e_ + _d_))/(2*a_**2*_b_*_e_),
        module_name='4.1.6 (a+b cos+c sin)^n',
        rule_number=20,
    ),
    # Rule 21
    SymPyReplacementPattern(
        pattern=Int((_A_ + _B_*InertCos(x*_e_ + _d_))/(a_ + _b_*InertCos(x*_e_ + _d_) + _c_*InertSin(x*_e_ + _d_)), x),
        constraints=(FreeQ([a_, _b_, _c_, _d_, _e_, _A_, _B_], x), EqQ(_b_**2 + _c_**2, 0),),
        replacement=x*(2*_A_*a_ - _B_*_b_)/(2*a_**2) - _B_*_b_*cos(x*_e_ + _d_)/(2*a_*_c_*_e_) + _B_*sin(x*_e_ + _d_)/(2*a_*_e_) + (-2*_A_*a_*_b_ + _B_*a_**2 + _B_*_b_**2)*log(a_ + _b_*cos(x*_e_ + _d_) + _c_*sin(x*_e_ + _d_))/(2*a_**2*_c_*_e_),
        module_name='4.1.6 (a+b cos+c sin)^n',
        rule_number=21,
    ),
    # Rule 22
    SymPyReplacementPattern(
        pattern=Int((_A_ + _B_*InertCos(x*_e_ + _d_) + _C_*InertSin(x*_e_ + _d_))/(_a_ + _b_*InertCos(x*_e_ + _d_) + _c_*InertSin(x*_e_ + _d_)), x),
        constraints=(FreeQ([_a_, _b_, _c_, _d_, _e_, _A_, _B_, _C_], x), NeQ(_b_**2 + _c_**2, 0), EqQ(_A_*(_b_**2 + _c_**2) - _a_*(_B_*_b_ + _C_*_c_), 0),),
        replacement=x*(_B_*_b_ + _C_*_c_)/(_b_**2 + _c_**2) + (_B_*_c_ - _C_*_b_)*log(_a_ + _b_*cos(x*_e_ + _d_) + _c_*sin(x*_e_ + _d_))/(_e_*(_b_**2 + _c_**2)),
        module_name='4.1.6 (a+b cos+c sin)^n',
        rule_number=22,
    ),
    # Rule 23
    SymPyReplacementPattern(
        pattern=Int((_A_ + _C_*InertSin(x*_e_ + _d_))/(_a_ + _b_*InertCos(x*_e_ + _d_) + _c_*InertSin(x*_e_ + _d_)), x),
        constraints=(FreeQ([_a_, _b_, _c_, _d_, _e_, _A_, _C_], x), NeQ(_b_**2 + _c_**2, 0), EqQ(_A_*(_b_**2 + _c_**2) - _C_*_a_*_c_, 0),),
        replacement=x*_C_*_c_/(_b_**2 + _c_**2) - _C_*_b_*log(_a_ + _b_*cos(x*_e_ + _d_) + _c_*sin(x*_e_ + _d_))/(_e_*(_b_**2 + _c_**2)),
        module_name='4.1.6 (a+b cos+c sin)^n',
        rule_number=23,
    ),
    # Rule 24
    SymPyReplacementPattern(
        pattern=Int((_A_ + _B_*InertCos(x*_e_ + _d_))/(_a_ + _b_*InertCos(x*_e_ + _d_) + _c_*InertSin(x*_e_ + _d_)), x),
        constraints=(FreeQ([_a_, _b_, _c_, _d_, _e_, _A_, _B_], x), NeQ(_b_**2 + _c_**2, 0), EqQ(_A_*(_b_**2 + _c_**2) - _B_*_a_*_b_, 0),),
        replacement=x*_B_*_b_/(_b_**2 + _c_**2) + _B_*_c_*log(_a_ + _b_*cos(x*_e_ + _d_) + _c_*sin(x*_e_ + _d_))/(_e_*(_b_**2 + _c_**2)),
        module_name='4.1.6 (a+b cos+c sin)^n',
        rule_number=24,
    ),
    # Rule 25
    SymPyReplacementPattern(
        pattern=Int((_A_ + _B_*InertCos(x*_e_ + _d_) + _C_*InertSin(x*_e_ + _d_))/(_a_ + _b_*InertCos(x*_e_ + _d_) + _c_*InertSin(x*_e_ + _d_)), x),
        constraints=(FreeQ([_a_, _b_, _c_, _d_, _e_, _A_, _B_, _C_], x), NeQ(_b_**2 + _c_**2, 0), NeQ(_A_*(_b_**2 + _c_**2) - _a_*(_B_*_b_ + _C_*_c_), 0),),
        replacement=x*(_B_*_b_ + _C_*_c_)/(_b_**2 + _c_**2) + (_A_*(_b_**2 + _c_**2) - _a_*(_B_*_b_ + _C_*_c_))*Int(1/(_a_ + _b_*cos(x*_e_ + _d_) + _c_*sin(x*_e_ + _d_)), x)/(_b_**2 + _c_**2) + (_B_*_c_ - _C_*_b_)*log(_a_ + _b_*cos(x*_e_ + _d_) + _c_*sin(x*_e_ + _d_))/(_e_*(_b_**2 + _c_**2)),
        module_name='4.1.6 (a+b cos+c sin)^n',
        rule_number=25,
    ),
    # Rule 26
    SymPyReplacementPattern(
        pattern=Int((_A_ + _C_*InertSin(x*_e_ + _d_))/(_a_ + _b_*InertCos(x*_e_ + _d_) + _c_*InertSin(x*_e_ + _d_)), x),
        constraints=(FreeQ([_a_, _b_, _c_, _d_, _e_, _A_, _C_], x), NeQ(_b_**2 + _c_**2, 0), NeQ(_A_*(_b_**2 + _c_**2) - _C_*_a_*_c_, 0),),
        replacement=-_C_*_b_*log(_a_ + _b_*cos(x*_e_ + _d_) + _c_*sin(x*_e_ + _d_))/(_e_*(_b_**2 + _c_**2)) + _C_*_c_*(x*_e_ + _d_)/(_e_*(_b_**2 + _c_**2)) + (_A_*(_b_**2 + _c_**2) - _C_*_a_*_c_)*Int(1/(_a_ + _b_*cos(x*_e_ + _d_) + _c_*sin(x*_e_ + _d_)), x)/(_b_**2 + _c_**2),
        module_name='4.1.6 (a+b cos+c sin)^n',
        rule_number=26,
    ),
    # Rule 27
    SymPyReplacementPattern(
        pattern=Int((_A_ + _B_*InertCos(x*_e_ + _d_))/(_a_ + _b_*InertCos(x*_e_ + _d_) + _c_*InertSin(x*_e_ + _d_)), x),
        constraints=(FreeQ([_a_, _b_, _c_, _d_, _e_, _A_, _B_], x), NeQ(_b_**2 + _c_**2, 0), NeQ(_A_*(_b_**2 + _c_**2) - _B_*_a_*_b_, 0),),
        replacement=_B_*_b_*(x*_e_ + _d_)/(_e_*(_b_**2 + _c_**2)) + _B_*_c_*log(_a_ + _b_*cos(x*_e_ + _d_) + _c_*sin(x*_e_ + _d_))/(_e_*(_b_**2 + _c_**2)) + (_A_*(_b_**2 + _c_**2) - _B_*_a_*_b_)*Int(1/(_a_ + _b_*cos(x*_e_ + _d_) + _c_*sin(x*_e_ + _d_)), x)/(_b_**2 + _c_**2),
        module_name='4.1.6 (a+b cos+c sin)^n',
        rule_number=27,
    ),
    # Rule 28
    SymPyReplacementPattern(
        pattern=Int((_A_ + _B_*InertCos(x*_e_ + _d_) + _C_*InertSin(x*_e_ + _d_))*(a_ + _b_*InertCos(x*_e_ + _d_) + _c_*InertSin(x*_e_ + _d_))**_n_, x),
        constraints=(FreeQ([a_, _b_, _c_, _d_, _e_, _A_, _B_, _C_, _n_], x), NeQ(_n_, -1), EqQ(a_**2 - _b_**2 - _c_**2, 0), EqQ(_A_*a_*(_n_ + 1) + _n_*(_B_*_b_ + _C_*_c_), 0),),
        replacement=(a_ + _b_*cos(x*_e_ + _d_) + _c_*sin(x*_e_ + _d_))**_n_*(_B_*a_*sin(x*_e_ + _d_) + _B_*_c_ - _C_*a_*cos(x*_e_ + _d_) - _C_*_b_)/(a_*_e_*(_n_ + 1)),
        module_name='4.1.6 (a+b cos+c sin)^n',
        rule_number=28,
    ),
    # Rule 29
    SymPyReplacementPattern(
        pattern=Int((_A_ + _C_*InertSin(x*_e_ + _d_))*(a_ + _b_*InertCos(x*_e_ + _d_) + _c_*InertSin(x*_e_ + _d_))**_n_, x),
        constraints=(FreeQ([a_, _b_, _c_, _d_, _e_, _A_, _C_, _n_], x), NeQ(_n_, -1), EqQ(a_**2 - _b_**2 - _c_**2, 0), EqQ(_A_*a_*(_n_ + 1) + _C_*_c_*_n_, 0),),
        replacement=(-_C_*a_*cos(x*_e_ + _d_) - _C_*_b_)*(a_ + _b_*cos(x*_e_ + _d_) + _c_*sin(x*_e_ + _d_))**_n_/(a_*_e_*(_n_ + 1)),
        module_name='4.1.6 (a+b cos+c sin)^n',
        rule_number=29,
    ),
    # Rule 30
    SymPyReplacementPattern(
        pattern=Int((_A_ + _B_*InertCos(x*_e_ + _d_))*(a_ + _b_*InertCos(x*_e_ + _d_) + _c_*InertSin(x*_e_ + _d_))**_n_, x),
        constraints=(FreeQ([a_, _b_, _c_, _d_, _e_, _A_, _B_, _n_], x), NeQ(_n_, -1), EqQ(a_**2 - _b_**2 - _c_**2, 0), EqQ(_A_*a_*(_n_ + 1) + _B_*_b_*_n_, 0),),
        replacement=(_B_*a_*sin(x*_e_ + _d_) + _B_*_c_)*(a_ + _b_*cos(x*_e_ + _d_) + _c_*sin(x*_e_ + _d_))**_n_/(a_*_e_*(_n_ + 1)),
        module_name='4.1.6 (a+b cos+c sin)^n',
        rule_number=30,
    ),
    # Rule 31
    SymPyReplacementPattern(
        pattern=Int((_A_ + _B_*InertCos(x*_e_ + _d_) + _C_*InertSin(x*_e_ + _d_))*(a_ + _b_*InertCos(x*_e_ + _d_) + _c_*InertSin(x*_e_ + _d_))**_n_, x),
        constraints=(FreeQ([a_, _b_, _c_, _d_, _e_, _A_, _B_, _C_, _n_], x), NeQ(_n_, -1), EqQ(a_**2 - _b_**2 - _c_**2, 0), NeQ(_A_*a_*(_n_ + 1) + _n_*(_B_*_b_ + _C_*_c_), 0),),
        replacement=(_A_*a_*(_n_ + 1) + _n_*(_B_*_b_ + _C_*_c_))*Int((a_ + _b_*cos(x*_e_ + _d_) + _c_*sin(x*_e_ + _d_))**_n_, x)/(a_*(_n_ + 1)) + (a_ + _b_*cos(x*_e_ + _d_) + _c_*sin(x*_e_ + _d_))**_n_*(_B_*a_*sin(x*_e_ + _d_) + _B_*_c_ - _C_*a_*cos(x*_e_ + _d_) - _C_*_b_)/(a_*_e_*(_n_ + 1)),
        module_name='4.1.6 (a+b cos+c sin)^n',
        rule_number=31,
    ),
    # Rule 32
    SymPyReplacementPattern(
        pattern=Int((_A_ + _C_*InertSin(x*_e_ + _d_))*(a_ + _b_*InertCos(x*_e_ + _d_) + _c_*InertSin(x*_e_ + _d_))**_n_, x),
        constraints=(FreeQ([a_, _b_, _c_, _d_, _e_, _A_, _C_, _n_], x), NeQ(_n_, -1), EqQ(a_**2 - _b_**2 - _c_**2, 0), NeQ(_A_*a_*(_n_ + 1) + _C_*_c_*_n_, 0),),
        replacement=(_A_*a_*(_n_ + 1) + _C_*_c_*_n_)*Int((a_ + _b_*cos(x*_e_ + _d_) + _c_*sin(x*_e_ + _d_))**_n_, x)/(a_*(_n_ + 1)) + (-_C_*a_*cos(x*_e_ + _d_) - _C_*_b_)*(a_ + _b_*cos(x*_e_ + _d_) + _c_*sin(x*_e_ + _d_))**_n_/(a_*_e_*(_n_ + 1)),
        module_name='4.1.6 (a+b cos+c sin)^n',
        rule_number=32,
    ),
    # Rule 33
    SymPyReplacementPattern(
        pattern=Int((_A_ + _B_*InertCos(x*_e_ + _d_))*(a_ + _b_*InertCos(x*_e_ + _d_) + _c_*InertSin(x*_e_ + _d_))**_n_, x),
        constraints=(FreeQ([a_, _b_, _c_, _d_, _e_, _A_, _B_, _n_], x), NeQ(_n_, -1), EqQ(a_**2 - _b_**2 - _c_**2, 0), NeQ(_A_*a_*(_n_ + 1) + _B_*_b_*_n_, 0),),
        replacement=(_A_*a_*(_n_ + 1) + _B_*_b_*_n_)*Int((a_ + _b_*cos(x*_e_ + _d_) + _c_*sin(x*_e_ + _d_))**_n_, x)/(a_*(_n_ + 1)) + (_B_*a_*sin(x*_e_ + _d_) + _B_*_c_)*(a_ + _b_*cos(x*_e_ + _d_) + _c_*sin(x*_e_ + _d_))**_n_/(a_*_e_*(_n_ + 1)),
        module_name='4.1.6 (a+b cos+c sin)^n',
        rule_number=33,
    ),
    # Rule 34
    SymPyReplacementPattern(
        pattern=Int((_B_*InertCos(x*_e_ + _d_) + _C_*InertSin(x*_e_ + _d_))*(_b_*InertCos(x*_e_ + _d_) + _c_*InertSin(x*_e_ + _d_))**_n_, x),
        constraints=(FreeQ([_b_, _c_, _d_, _e_, _B_, _C_], x), NeQ(_n_, -1), NeQ(_b_**2 + _c_**2, 0), EqQ(_B_*_b_ + _C_*_c_, 0),),
        replacement=(_B_*_c_ - _C_*_b_)*(_b_*cos(x*_e_ + _d_) + _c_*sin(x*_e_ + _d_))**(_n_ + 1)/(_e_*(_b_**2 + _c_**2)*(_n_ + 1)),
        module_name='4.1.6 (a+b cos+c sin)^n',
        rule_number=34,
    ),
    # Rule 35
    SymPyReplacementPattern(
        pattern=Int((_A_ + _B_*InertCos(x*_e_ + _d_) + _C_*InertSin(x*_e_ + _d_))*(a_ + _b_*InertCos(x*_e_ + _d_) + _c_*InertSin(x*_e_ + _d_))**_n_, x),
        constraints=(FreeQ([a_, _b_, _c_, _d_, _e_, _A_, _B_, _C_], x), GtQ(_n_, 0), NeQ(a_**2 - _b_**2 - _c_**2, 0),),
        replacement=Int((a_ + _b_*cos(x*_e_ + _d_) + _c_*sin(x*_e_ + _d_))**(_n_ - 1)*Simp(_A_*a_**2*(_n_ + 1) + a_*_n_*(_B_*_b_ + _C_*_c_) + (_A_*a_*_b_*(_n_ + 1) + _n_*(_B_*a_**2 - _B_*_c_**2 + _C_*_b_*_c_))*cos(x*_e_ + _d_) + (_A_*a_*_c_*(_n_ + 1) + _n_*(_B_*_b_*_c_ + _C_*a_**2 - _C_*_b_**2))*sin(x*_e_ + _d_), x), x)/(a_*(_n_ + 1)) + (a_ + _b_*cos(x*_e_ + _d_) + _c_*sin(x*_e_ + _d_))**_n_*(_B_*a_*sin(x*_e_ + _d_) + _B_*_c_ - _C_*a_*cos(x*_e_ + _d_) - _C_*_b_)/(a_*_e_*(_n_ + 1)),
        module_name='4.1.6 (a+b cos+c sin)^n',
        rule_number=35,
    ),
    # Rule 36
    SymPyReplacementPattern(
        pattern=Int((_A_ + _C_*InertSin(x*_e_ + _d_))*(a_ + _b_*InertCos(x*_e_ + _d_) + _c_*InertSin(x*_e_ + _d_))**_n_, x),
        constraints=(FreeQ([a_, _b_, _c_, _d_, _e_, _A_, _C_], x), GtQ(_n_, 0), NeQ(a_**2 - _b_**2 - _c_**2, 0),),
        replacement=Int((a_ + _b_*cos(x*_e_ + _d_) + _c_*sin(x*_e_ + _d_))**(_n_ - 1)*Simp(_A_*a_**2*(_n_ + 1) + _C_*a_*_c_*_n_ + (_A_*a_*_b_*(_n_ + 1) + _C_*_b_*_c_*_n_)*cos(x*_e_ + _d_) + (_A_*a_*_c_*(_n_ + 1) + _C_*a_**2*_n_ - _C_*_b_**2*_n_)*sin(x*_e_ + _d_), x), x)/(a_*(_n_ + 1)) + (-_C_*a_*cos(x*_e_ + _d_) - _C_*_b_)*(a_ + _b_*cos(x*_e_ + _d_) + _c_*sin(x*_e_ + _d_))**_n_/(a_*_e_*(_n_ + 1)),
        module_name='4.1.6 (a+b cos+c sin)^n',
        rule_number=36,
    ),
    # Rule 37
    SymPyReplacementPattern(
        pattern=Int((_A_ + _B_*InertCos(x*_e_ + _d_))*(a_ + _b_*InertCos(x*_e_ + _d_) + _c_*InertSin(x*_e_ + _d_))**_n_, x),
        constraints=(FreeQ([a_, _b_, _c_, _d_, _e_, _A_, _B_], x), GtQ(_n_, 0), NeQ(a_**2 - _b_**2 - _c_**2, 0),),
        replacement=Int((a_ + _b_*cos(x*_e_ + _d_) + _c_*sin(x*_e_ + _d_))**(_n_ - 1)*Simp(_A_*a_**2*(_n_ + 1) + _B_*a_*_b_*_n_ + (_A_*a_*_c_*(_n_ + 1) + _B_*_b_*_c_*_n_)*sin(x*_e_ + _d_) + (_A_*a_*_b_*(_n_ + 1) + _B_*a_**2*_n_ - _B_*_c_**2*_n_)*cos(x*_e_ + _d_), x), x)/(a_*(_n_ + 1)) + (_B_*a_*sin(x*_e_ + _d_) + _B_*_c_)*(a_ + _b_*cos(x*_e_ + _d_) + _c_*sin(x*_e_ + _d_))**_n_/(a_*_e_*(_n_ + 1)),
        module_name='4.1.6 (a+b cos+c sin)^n',
        rule_number=37,
    ),
    # Rule 38
    SymPyReplacementPattern(
        pattern=Int((_A_ + _B_*InertCos(x*_e_ + _d_) + _C_*InertSin(x*_e_ + _d_))/sqrt(a_ + _b_*InertCos(x*_e_ + _d_) + _c_*InertSin(x*_e_ + _d_)), x),
        constraints=(FreeQ([a_, _b_, _c_, _d_, _e_, _A_, _B_, _C_], x), EqQ(_B_*_c_ - _C_*_b_, 0), NeQ(_A_*_b_ - _B_*a_, 0),),
        replacement=_B_*Int(sqrt(a_ + _b_*cos(x*_e_ + _d_) + _c_*sin(x*_e_ + _d_)), x)/_b_ + (_A_*_b_ - _B_*a_)*Int(1/sqrt(a_ + _b_*cos(x*_e_ + _d_) + _c_*sin(x*_e_ + _d_)), x)/_b_,
        module_name='4.1.6 (a+b cos+c sin)^n',
        rule_number=38,
    ),
    # Rule 39
    SymPyReplacementPattern(
        pattern=Int((_A_ + _B_*InertCos(x*_e_ + _d_) + _C_*InertSin(x*_e_ + _d_))/(_a_ + _b_*InertCos(x*_e_ + _d_) + _c_*InertSin(x*_e_ + _d_))**2, x),
        constraints=(FreeQ([_a_, _b_, _c_, _d_, _e_, _A_, _B_, _C_], x), NeQ(_a_**2 - _b_**2 - _c_**2, 0), EqQ(_A_*_a_ - _B_*_b_ - _C_*_c_, 0),),
        replacement=(_B_*_c_ - _C_*_b_ + (-_A_*_b_ + _B_*_a_)*sin(x*_e_ + _d_) - (-_A_*_c_ + _C_*_a_)*cos(x*_e_ + _d_))/(_e_*(_a_**2 - _b_**2 - _c_**2)*(_a_ + _b_*cos(x*_e_ + _d_) + _c_*sin(x*_e_ + _d_))),
        module_name='4.1.6 (a+b cos+c sin)^n',
        rule_number=39,
    ),
    # Rule 40
    SymPyReplacementPattern(
        pattern=Int((_A_ + _C_*InertSin(x*_e_ + _d_))/(_a_ + _b_*InertCos(x*_e_ + _d_) + _c_*InertSin(x*_e_ + _d_))**2, x),
        constraints=(FreeQ([_a_, _b_, _c_, _d_, _e_, _A_, _C_], x), NeQ(_a_**2 - _b_**2 - _c_**2, 0), EqQ(_A_*_a_ - _C_*_c_, 0),),
        replacement=(-_A_*_b_*sin(x*_e_ + _d_) - _C_*_b_ - (-_A_*_c_ + _C_*_a_)*cos(x*_e_ + _d_))/(_e_*(_a_**2 - _b_**2 - _c_**2)*(_a_ + _b_*cos(x*_e_ + _d_) + _c_*sin(x*_e_ + _d_))),
        module_name='4.1.6 (a+b cos+c sin)^n',
        rule_number=40,
    ),
    # Rule 41
    SymPyReplacementPattern(
        pattern=Int((_A_ + _B_*InertCos(x*_e_ + _d_))/(_a_ + _b_*InertCos(x*_e_ + _d_) + _c_*InertSin(x*_e_ + _d_))**2, x),
        constraints=(FreeQ([_a_, _b_, _c_, _d_, _e_, _A_, _B_], x), NeQ(_a_**2 - _b_**2 - _c_**2, 0), EqQ(_A_*_a_ - _B_*_b_, 0),),
        replacement=(_A_*_c_*cos(x*_e_ + _d_) + _B_*_c_ + (-_A_*_b_ + _B_*_a_)*sin(x*_e_ + _d_))/(_e_*(_a_**2 - _b_**2 - _c_**2)*(_a_ + _b_*cos(x*_e_ + _d_) + _c_*sin(x*_e_ + _d_))),
        module_name='4.1.6 (a+b cos+c sin)^n',
        rule_number=41,
    ),
    # Rule 42
    SymPyReplacementPattern(
        pattern=Int((_A_ + _B_*InertCos(x*_e_ + _d_) + _C_*InertSin(x*_e_ + _d_))/(_a_ + _b_*InertCos(x*_e_ + _d_) + _c_*InertSin(x*_e_ + _d_))**2, x),
        constraints=(FreeQ([_a_, _b_, _c_, _d_, _e_, _A_, _B_, _C_], x), NeQ(_a_**2 - _b_**2 - _c_**2, 0), NeQ(_A_*_a_ - _B_*_b_ - _C_*_c_, 0),),
        replacement=(_A_*_a_ - _B_*_b_ - _C_*_c_)*Int(1/(_a_ + _b_*cos(x*_e_ + _d_) + _c_*sin(x*_e_ + _d_)), x)/(_a_**2 - _b_**2 - _c_**2) + (_B_*_c_ - _C_*_b_ + (-_A_*_b_ + _B_*_a_)*sin(x*_e_ + _d_) - (-_A_*_c_ + _C_*_a_)*cos(x*_e_ + _d_))/(_e_*(_a_**2 - _b_**2 - _c_**2)*(_a_ + _b_*cos(x*_e_ + _d_) + _c_*sin(x*_e_ + _d_))),
        module_name='4.1.6 (a+b cos+c sin)^n',
        rule_number=42,
    ),
    # Rule 43
    SymPyReplacementPattern(
        pattern=Int((_A_ + _C_*InertSin(x*_e_ + _d_))/(_a_ + _b_*InertCos(x*_e_ + _d_) + _c_*InertSin(x*_e_ + _d_))**2, x),
        constraints=(FreeQ([_a_, _b_, _c_, _d_, _e_, _A_, _C_], x), NeQ(_a_**2 - _b_**2 - _c_**2, 0), NeQ(_A_*_a_ - _C_*_c_, 0),),
        replacement=(_A_*_a_ - _C_*_c_)*Int(1/(_a_ + _b_*cos(x*_e_ + _d_) + _c_*sin(x*_e_ + _d_)), x)/(_a_**2 - _b_**2 - _c_**2) + (-_A_*_b_*sin(x*_e_ + _d_) - _C_*_b_ - (-_A_*_c_ + _C_*_a_)*cos(x*_e_ + _d_))/(_e_*(_a_**2 - _b_**2 - _c_**2)*(_a_ + _b_*cos(x*_e_ + _d_) + _c_*sin(x*_e_ + _d_))),
        module_name='4.1.6 (a+b cos+c sin)^n',
        rule_number=43,
    ),
    # Rule 44
    SymPyReplacementPattern(
        pattern=Int((_A_ + _B_*InertCos(x*_e_ + _d_))/(_a_ + _b_*InertCos(x*_e_ + _d_) + _c_*InertSin(x*_e_ + _d_))**2, x),
        constraints=(FreeQ([_a_, _b_, _c_, _d_, _e_, _A_, _B_], x), NeQ(_a_**2 - _b_**2 - _c_**2, 0), NeQ(_A_*_a_ - _B_*_b_, 0),),
        replacement=(_A_*_a_ - _B_*_b_)*Int(1/(_a_ + _b_*cos(x*_e_ + _d_) + _c_*sin(x*_e_ + _d_)), x)/(_a_**2 - _b_**2 - _c_**2) + (_A_*_c_*cos(x*_e_ + _d_) + _B_*_c_ + (-_A_*_b_ + _B_*_a_)*sin(x*_e_ + _d_))/(_e_*(_a_**2 - _b_**2 - _c_**2)*(_a_ + _b_*cos(x*_e_ + _d_) + _c_*sin(x*_e_ + _d_))),
        module_name='4.1.6 (a+b cos+c sin)^n',
        rule_number=44,
    ),
    # Rule 45
    SymPyReplacementPattern(
        pattern=Int((_A_ + _B_*InertCos(x*_e_ + _d_) + _C_*InertSin(x*_e_ + _d_))*(_a_ + _b_*InertCos(x*_e_ + _d_) + _c_*InertSin(x*_e_ + _d_))**n_, x),
        constraints=(FreeQ([_a_, _b_, _c_, _d_, _e_, _A_, _B_, _C_], x), LtQ(n_, -1), NeQ(_a_**2 - _b_**2 - _c_**2, 0), NeQ(n_, -2),),
        replacement=Int((_a_ + _b_*cos(x*_e_ + _d_) + _c_*sin(x*_e_ + _d_))**(n_ + 1)*Simp((n_ + 1)*(_A_*_a_ - _B_*_b_ - _C_*_c_) + (n_ + 2)*(-_A_*_b_ + _B_*_a_)*cos(x*_e_ + _d_) + (n_ + 2)*(-_A_*_c_ + _C_*_a_)*sin(x*_e_ + _d_), x), x)/((n_ + 1)*(_a_**2 - _b_**2 - _c_**2)) + (_a_ + _b_*cos(x*_e_ + _d_) + _c_*sin(x*_e_ + _d_))**(n_ + 1)*(-_B_*_c_ + _C_*_b_ - (-_A_*_b_ + _B_*_a_)*sin(x*_e_ + _d_) + (-_A_*_c_ + _C_*_a_)*cos(x*_e_ + _d_))/(_e_*(n_ + 1)*(_a_**2 - _b_**2 - _c_**2)),
        module_name='4.1.6 (a+b cos+c sin)^n',
        rule_number=45,
    ),
    # Rule 46
    SymPyReplacementPattern(
        pattern=Int((_A_ + _C_*InertSin(x*_e_ + _d_))*(_a_ + _b_*InertCos(x*_e_ + _d_) + _c_*InertSin(x*_e_ + _d_))**n_, x),
        constraints=(FreeQ([_a_, _b_, _c_, _d_, _e_, _A_, _C_], x), LtQ(n_, -1), NeQ(_a_**2 - _b_**2 - _c_**2, 0), NeQ(n_, -2),),
        replacement=Int((_a_ + _b_*cos(x*_e_ + _d_) + _c_*sin(x*_e_ + _d_))**(n_ + 1)*Simp(-_A_*_b_*(n_ + 2)*cos(x*_e_ + _d_) + (n_ + 1)*(_A_*_a_ - _C_*_c_) + (n_ + 2)*(-_A_*_c_ + _C_*_a_)*sin(x*_e_ + _d_), x), x)/((n_ + 1)*(_a_**2 - _b_**2 - _c_**2)) + (_a_ + _b_*cos(x*_e_ + _d_) + _c_*sin(x*_e_ + _d_))**(n_ + 1)*(_A_*_b_*sin(x*_e_ + _d_) + _C_*_b_ + (-_A_*_c_ + _C_*_a_)*cos(x*_e_ + _d_))/(_e_*(n_ + 1)*(_a_**2 - _b_**2 - _c_**2)),
        module_name='4.1.6 (a+b cos+c sin)^n',
        rule_number=46,
    ),
    # Rule 47
    SymPyReplacementPattern(
        pattern=Int((_A_ + _B_*InertCos(x*_e_ + _d_))*(_a_ + _b_*InertCos(x*_e_ + _d_) + _c_*InertSin(x*_e_ + _d_))**n_, x),
        constraints=(FreeQ([_a_, _b_, _c_, _d_, _e_, _A_, _B_], x), LtQ(n_, -1), NeQ(_a_**2 - _b_**2 - _c_**2, 0), NeQ(n_, -2),),
        replacement=Int((_a_ + _b_*cos(x*_e_ + _d_) + _c_*sin(x*_e_ + _d_))**(n_ + 1)*Simp(-_A_*_c_*(n_ + 2)*sin(x*_e_ + _d_) + (n_ + 1)*(_A_*_a_ - _B_*_b_) + (n_ + 2)*(-_A_*_b_ + _B_*_a_)*cos(x*_e_ + _d_), x), x)/((n_ + 1)*(_a_**2 - _b_**2 - _c_**2)) + (_a_ + _b_*cos(x*_e_ + _d_) + _c_*sin(x*_e_ + _d_))**(n_ + 1)*(-_A_*_c_*cos(x*_e_ + _d_) - _B_*_c_ - (-_A_*_b_ + _B_*_a_)*sin(x*_e_ + _d_))/(_e_*(n_ + 1)*(_a_**2 - _b_**2 - _c_**2)),
        module_name='4.1.6 (a+b cos+c sin)^n',
        rule_number=47,
    ),
    # Rule 48
    SymPyReplacementPattern(
        pattern=Int(1/(_a_ + _b_*InertSec(x*_e_ + _d_) + _c_*InertTan(x*_e_ + _d_)), x),
        constraints=(FreeQ([_a_, _b_, _c_, _d_, _e_], x),),
        replacement=Int(cos(x*_e_ + _d_)/(_a_*cos(x*_e_ + _d_) + _b_ + _c_*sin(x*_e_ + _d_)), x),
        module_name='4.1.6 (a+b cos+c sin)^n',
        rule_number=48,
    ),
    # Rule 49
    SymPyReplacementPattern(
        pattern=Int(1/(_a_ + _b_*InertCsc(x*_e_ + _d_) + _c_*InertCot(x*_e_ + _d_)), x),
        constraints=(FreeQ([_a_, _b_, _c_, _d_, _e_], x),),
        replacement=Int(sin(x*_e_ + _d_)/(_a_*sin(x*_e_ + _d_) + _b_ + _c_*cos(x*_e_ + _d_)), x),
        module_name='4.1.6 (a+b cos+c sin)^n',
        rule_number=49,
    ),
    # Rule 50
    SymPyReplacementPattern(
        pattern=Int((_a_ + _b_*InertSec(x*_e_ + _d_) + _c_*InertTan(x*_e_ + _d_))**_n_*InertCos(x*_e_ + _d_)**_n_, x),
        constraints=(FreeQ([_a_, _b_, _c_, _d_, _e_], x), IntegerQ(_n_),),
        replacement=Int((_a_*cos(x*_e_ + _d_) + _b_ + _c_*sin(x*_e_ + _d_))**_n_, x),
        module_name='4.1.6 (a+b cos+c sin)^n',
        rule_number=50,
    ),
    # Rule 51
    SymPyReplacementPattern(
        pattern=Int((_a_ + _b_*InertCsc(x*_e_ + _d_) + _c_*InertCot(x*_e_ + _d_))**_n_*InertSin(x*_e_ + _d_)**_n_, x),
        constraints=(FreeQ([_a_, _b_, _c_, _d_, _e_], x), IntegerQ(_n_),),
        replacement=Int((_a_*sin(x*_e_ + _d_) + _b_ + _c_*cos(x*_e_ + _d_))**_n_, x),
        module_name='4.1.6 (a+b cos+c sin)^n',
        rule_number=51,
    ),
    # Rule 52
    SymPyReplacementPattern(
        pattern=Int((_a_ + _b_*InertSec(x*_e_ + _d_) + _c_*InertTan(x*_e_ + _d_))**n_*InertCos(x*_e_ + _d_)**n_, x),
        constraints=(FreeQ([_a_, _b_, _c_, _d_, _e_], x), Not(IntegerQ(n_)),),
        replacement=(_a_ + _b_*sec(x*_e_ + _d_) + _c_*tan(x*_e_ + _d_))**n_*Int((_a_*cos(x*_e_ + _d_) + _b_ + _c_*sin(x*_e_ + _d_))**n_, x)*cos(x*_e_ + _d_)**n_/(_a_*cos(x*_e_ + _d_) + _b_ + _c_*sin(x*_e_ + _d_))**n_,
        module_name='4.1.6 (a+b cos+c sin)^n',
        rule_number=52,
    ),
    # Rule 53
    SymPyReplacementPattern(
        pattern=Int((_a_ + _b_*InertCsc(x*_e_ + _d_) + _c_*InertCot(x*_e_ + _d_))**n_*InertSin(x*_e_ + _d_)**n_, x),
        constraints=(FreeQ([_a_, _b_, _c_, _d_, _e_], x), Not(IntegerQ(n_)),),
        replacement=(_a_ + _b_*csc(x*_e_ + _d_) + _c_*cot(x*_e_ + _d_))**n_*Int((_a_*sin(x*_e_ + _d_) + _b_ + _c_*cos(x*_e_ + _d_))**n_, x)*sin(x*_e_ + _d_)**n_/(_a_*sin(x*_e_ + _d_) + _b_ + _c_*cos(x*_e_ + _d_))**n_,
        module_name='4.1.6 (a+b cos+c sin)^n',
        rule_number=53,
    ),
    # Rule 54
    SymPyReplacementPattern(
        pattern=Int((_a_ + _b_*InertSec(x*_e_ + _d_) + _c_*InertTan(x*_e_ + _d_))**m_*InertSec(x*_e_ + _d_)**_n_, x),
        constraints=(FreeQ([_a_, _b_, _c_, _d_, _e_], x), EqQ(m_ + _n_, 0), IntegerQ(_n_),),
        replacement=Int((_a_*cos(x*_e_ + _d_) + _b_ + _c_*sin(x*_e_ + _d_))**(-_n_), x),
        module_name='4.1.6 (a+b cos+c sin)^n',
        rule_number=54,
    ),
    # Rule 55
    SymPyReplacementPattern(
        pattern=Int((_a_ + _b_*InertCsc(x*_e_ + _d_) + _c_*InertCot(x*_e_ + _d_))**m_*InertCsc(x*_e_ + _d_)**_n_, x),
        constraints=(FreeQ([_a_, _b_, _c_, _d_, _e_], x), EqQ(m_ + _n_, 0), IntegerQ(_n_),),
        replacement=Int((_a_*sin(x*_e_ + _d_) + _b_ + _c_*cos(x*_e_ + _d_))**(-_n_), x),
        module_name='4.1.6 (a+b cos+c sin)^n',
        rule_number=55,
    ),
    # Rule 56
    SymPyReplacementPattern(
        pattern=Int((_a_ + _b_*InertSec(x*_e_ + _d_) + _c_*InertTan(x*_e_ + _d_))**m_*InertSec(x*_e_ + _d_)**_n_, x),
        constraints=(FreeQ([_a_, _b_, _c_, _d_, _e_], x), EqQ(m_ + _n_, 0), Not(IntegerQ(_n_)),),
        replacement=(_a_*cos(x*_e_ + _d_) + _b_ + _c_*sin(x*_e_ + _d_))**_n_*Int((_a_*cos(x*_e_ + _d_) + _b_ + _c_*sin(x*_e_ + _d_))**(-_n_), x)*sec(x*_e_ + _d_)**_n_/(_a_ + _b_*sec(x*_e_ + _d_) + _c_*tan(x*_e_ + _d_))**_n_,
        module_name='4.1.6 (a+b cos+c sin)^n',
        rule_number=56,
    ),
    # Rule 57
    SymPyReplacementPattern(
        pattern=Int((_a_ + _b_*InertCsc(x*_e_ + _d_) + _c_*InertCot(x*_e_ + _d_))**m_*InertCsc(x*_e_ + _d_)**_n_, x),
        constraints=(FreeQ([_a_, _b_, _c_, _d_, _e_], x), EqQ(m_ + _n_, 0), Not(IntegerQ(_n_)),),
        replacement=(_a_*sin(x*_e_ + _d_) + _b_ + _c_*cos(x*_e_ + _d_))**_n_*Int((_a_*sin(x*_e_ + _d_) + _b_ + _c_*cos(x*_e_ + _d_))**(-_n_), x)*csc(x*_e_ + _d_)**_n_/(_a_ + _b_*csc(x*_e_ + _d_) + _c_*cot(x*_e_ + _d_))**_n_,
        module_name='4.1.6 (a+b cos+c sin)^n',
        rule_number=57,
    ),

]

# Summary: 57 rules translated, 0 skipped
