# -*- coding: utf-8 -*-
# =============================================================================
# !! AUTO-GENERATED FILE -- DO NOT EDIT !!
#
# Generated by: rubi_integrate/codegen/generate.py
# Source: 4.1.8 trig^m (a+b cos^p+c sin^q)^n.m
# Module: 4.1.8 trig^m (a+b cos^p+c sin^q)^n
#
# This file contains Rubi integration rules as SymPyReplacementPattern objects.
# Re-run the generator to update.
# =============================================================================
import sympy
from sympy import Symbol
from rubi_integrate.utils.rubi_utils import *  # bare-name access; sympy imports below override any conflicts (e.g. Not)
from sympy import (
    cot, tan,
)

from sympy_matching.wild import WildSymbol, IDENTITY_ELEMENT
from rubi_integrate.base_objects import Int, SymPyReplacementPattern
# Inert trig markers (Rubi's lowercase sin/cos/... patterns). Distinct opaque heads,
# NOT subclasses of sympy.sin -- see rubi-trig-deactivation-dispatch project note.
from rubi_integrate.utils.inert_functions import (
    InertSin, InertCos)
from rubi_integrate.utils import (
    # Wolfram standard constraints
    FreeQ, IntegerQ, GtQ, LtQ, LeQ,
)

# --- Integration variable ---
x = Symbol('x')

# --- Rubi global option stubs (default False/placeholder) ---
UseGamma = sympy.Symbol('UseGamma')  # Rubi global option; treated as False in Python
u = Symbol('u')  # Generic integrand placeholder used in some Rubi constraint calls

# --- Rubi selector symbols ---
# Rubi passes Min/Max as bare SYMBOLS, not calls: Expon[Px, x, Min] selects the
# minimum exponent. The code emitter round-trips through SymPy's printer, which
# renders Symbol('Min') as the bare name `Min`, so the name must exist here.
# (A genuine Min[a, b] call is emitted qualified, as sympy.Min(...), so these
# bindings cannot shadow it.)
Min = Symbol('Min')
Max = Symbol('Max')

# --- Wildcard symbols ---
# dot wildcards (must match exactly one expression)
# optional wildcards (can match identity element if absent in commutative ops)

f = Symbol('f')

a_ = WildSymbol('a')
_b_ = WildSymbol('b', optional_value=IDENTITY_ELEMENT)
b_ = WildSymbol('b')
_c_ = WildSymbol('c', optional_value=IDENTITY_ELEMENT)
c_ = WildSymbol('c')
_d_ = WildSymbol('d', optional_value=IDENTITY_ELEMENT)
d_ = WildSymbol('d')
_e_ = WildSymbol('e', optional_value=IDENTITY_ELEMENT)
e_ = WildSymbol('e')
m_ = WildSymbol('m')
n_ = WildSymbol('n')
p_ = WildSymbol('p')
q_ = WildSymbol('q')

RULES = [
    # Rule 1
    SymPyReplacementPattern(
        pattern=Int((a_ + _b_*InertCos(x*_e_ + _d_)**p_ + _c_*InertSin(x*_e_ + _d_)**q_)**n_*InertSin(x*_e_ + _d_)**m_, x),
        constraints=(FreeQ([a_, _b_, _c_, _d_, _e_], x), IntegerQ(m_/2), IntegerQ(p_/2), IntegerQ(q_/2), IntegerQ(n_), GtQ(p_, 0), LeQ(p_, q_),),
        replacement=Module({f: FreeFactors(cot(x*_e_ + _d_), x)}, -f*Subst(Int((f**2*x**2 + 1)**(-m_/2 - n_*q_/2 - 1)*ExpandToSum(a_*(f**2*x**2 + 1)**(q_/2) + _b_*(f**2*x**2 + 1)**(-p_/2 + q_/2) + _c_, x)**n_, x), x, cot(x*_e_ + _d_)/f)/_e_),
        module_name='4.1.8 trig^m (a+b cos^p+c sin^q)^n',
        rule_number=1,
    ),
    # Rule 2
    SymPyReplacementPattern(
        pattern=Int((a_ + _b_*InertSin(x*_e_ + _d_)**p_ + _c_*InertCos(x*_e_ + _d_)**q_)**n_*InertCos(x*_e_ + _d_)**m_, x),
        constraints=(FreeQ([a_, _b_, _c_, _d_, _e_], x), IntegerQ(m_/2), IntegerQ(p_/2), IntegerQ(q_/2), IntegerQ(n_), GtQ(p_, 0), LeQ(p_, q_),),
        replacement=Module({f: FreeFactors(tan(x*_e_ + _d_), x)}, f*Subst(Int((f**2*x**2 + 1)**(-m_/2 - n_*q_/2 - 1)*ExpandToSum(a_*(f**2*x**2 + 1)**(q_/2) + _b_*(f**2*x**2 + 1)**(-p_/2 + q_/2) + _c_, x)**n_, x), x, tan(x*_e_ + _d_)/f)/_e_),
        module_name='4.1.8 trig^m (a+b cos^p+c sin^q)^n',
        rule_number=2,
    ),
    # Rule 3
    SymPyReplacementPattern(
        pattern=Int((a_ + _b_*InertCos(x*_e_ + _d_)**p_ + _c_*InertSin(x*_e_ + _d_)**q_)**n_*InertSin(x*_e_ + _d_)**m_, x),
        constraints=(FreeQ([a_, _b_, _c_, _d_, _e_], x), IntegerQ(m_/2), IntegerQ(p_/2), IntegerQ(q_/2), IntegerQ(n_), LtQ(0, q_, p_),),
        replacement=Module({f: FreeFactors(cot(x*_e_ + _d_), x)}, -f*Subst(Int((f**2*x**2 + 1)**(-m_/2 - n_*p_/2 - 1)*ExpandToSum(f**p_*x**p_*_b_ + a_*(f**2*x**2 + 1)**(p_/2) + _c_*(f**2*x**2 + 1)**(p_/2 - q_/2), x)**n_, x), x, cot(x*_e_ + _d_)/f)/_e_),
        module_name='4.1.8 trig^m (a+b cos^p+c sin^q)^n',
        rule_number=3,
    ),
    # Rule 4
    SymPyReplacementPattern(
        pattern=Int((a_ + _b_*InertSin(x*_e_ + _d_)**p_ + _c_*InertCos(x*_e_ + _d_)**q_)**n_*InertCos(x*_e_ + _d_)**m_, x),
        constraints=(FreeQ([a_, _b_, _c_, _d_, _e_], x), IntegerQ(m_/2), IntegerQ(p_/2), IntegerQ(q_/2), IntegerQ(n_), LtQ(0, q_, p_),),
        replacement=Module({f: FreeFactors(tan(x*_e_ + _d_), x)}, f*Subst(Int((f**2*x**2 + 1)**(-m_/2 - n_*p_/2 - 1)*ExpandToSum(f**p_*x**p_*_b_ + a_*(f**2*x**2 + 1)**(p_/2) + _c_*(f**2*x**2 + 1)**(p_/2 - q_/2), x)**n_, x), x, tan(x*_e_ + _d_)/f)/_e_),
        module_name='4.1.8 trig^m (a+b cos^p+c sin^q)^n',
        rule_number=4,
    ),
    # Rule 5
    SymPyReplacementPattern(
        pattern=Int((a_ + _b_*InertCos(x*_e_ + _d_)**p_ + _c_*InertSin(x*_e_ + _d_)**q_)**n_*InertSin(x*_e_ + _d_)**m_, x),
        constraints=(FreeQ([a_, _b_, _c_, _d_, _e_], x), IntegerQ(m_/2), IntegerQ(p_/2), IntegerQ(q_/2), IntegerQ(n_), GtQ(p_, 0), LeQ(p_, q_),),
        replacement=Module({f: FreeFactors(cot(x*_e_ + _d_), x)}, -f*Subst(Int((f**2*x**2 + 1)**(-m_/2 - n_*q_/2 - 1)*ExpandToSum(a_*(f**2*x**2 + 1)**(q_/2) + _b_*(f**2*x**2 + 1)**(-p_/2 + q_/2) + _c_, x)**n_, x), x, cot(x*_e_ + _d_)/f)/_e_),
        module_name='4.1.8 trig^m (a+b cos^p+c sin^q)^n',
        rule_number=5,
    ),
    # Rule 6
    SymPyReplacementPattern(
        pattern=Int((a_ + _b_*InertSin(x*_e_ + _d_)**p_ + _c_*InertCos(x*_e_ + _d_)**q_)**n_*InertCos(x*_e_ + _d_)**m_, x),
        constraints=(FreeQ([a_, _b_, _c_, _d_, _e_], x), IntegerQ(m_/2), IntegerQ(p_/2), IntegerQ(q_/2), IntegerQ(n_), GtQ(p_, 0), LeQ(p_, q_),),
        replacement=Module({f: FreeFactors(tan(x*_e_ + _d_), x)}, f*Subst(Int((f**2*x**2 + 1)**(-m_/2 - n_*q_/2 - 1)*ExpandToSum(a_*(f**2*x**2 + 1)**(q_/2) + _b_*(f**2*x**2 + 1)**(-p_/2 + q_/2) + _c_, x)**n_, x), x, tan(x*_e_ + _d_)/f)/_e_),
        module_name='4.1.8 trig^m (a+b cos^p+c sin^q)^n',
        rule_number=6,
    ),
    # Rule 7
    SymPyReplacementPattern(
        pattern=Int((a_ + _b_*InertCos(x*_e_ + _d_)**p_ + _c_*InertSin(x*_e_ + _d_)**q_)**n_*InertSin(x*_e_ + _d_)**m_, x),
        constraints=(FreeQ([a_, _b_, _c_, _d_, _e_], x), IntegerQ(m_/2), IntegerQ(p_/2), IntegerQ(q_/2), IntegerQ(n_), LtQ(0, q_, p_),),
        replacement=Module({f: FreeFactors(cot(x*_e_ + _d_), x)}, -f*Subst(Int((f**2*x**2 + 1)**(-m_/2 - n_*p_/2 - 1)*ExpandToSum(f**p_*x**p_*_b_ + a_*(f**2*x**2 + 1)**(p_/2) + _c_*(f**2*x**2 + 1)**(p_/2 - q_/2), x)**n_, x), x, cot(x*_e_ + _d_)/f)/_e_),
        module_name='4.1.8 trig^m (a+b cos^p+c sin^q)^n',
        rule_number=7,
    ),
    # Rule 8
    SymPyReplacementPattern(
        pattern=Int((a_ + _b_*InertSin(x*_e_ + _d_)**p_ + _c_*InertCos(x*_e_ + _d_)**q_)**n_*InertCos(x*_e_ + _d_)**m_, x),
        constraints=(FreeQ([a_, _b_, _c_, _d_, _e_], x), IntegerQ(m_/2), IntegerQ(p_/2), IntegerQ(q_/2), IntegerQ(n_), LtQ(0, q_, p_),),
        replacement=Module({f: FreeFactors(tan(x*_e_ + _d_), x)}, f*Subst(Int((f**2*x**2 + 1)**(-m_/2 - n_*p_/2 - 1)*ExpandToSum(f**p_*x**p_*_b_ + a_*(f**2*x**2 + 1)**(p_/2) + _c_*(f**2*x**2 + 1)**(p_/2 - q_/2), x)**n_, x), x, tan(x*_e_ + _d_)/f)/_e_),
        module_name='4.1.8 trig^m (a+b cos^p+c sin^q)^n',
        rule_number=8,
    ),

]

# Summary: 8 rules translated, 0 skipped
