# -*- coding: utf-8 -*-
# =============================================================================
# !! AUTO-GENERATED FILE -- DO NOT EDIT !!
#
# Generated by: rubi_integrate/codegen/generate.py
# Source: 1.1.2.x P(x) (a+b x^2)^p.m
# Module: 1.1.2.x P(x) (a+b x^2)^p
#
# This file contains Rubi integration rules as SymPyReplacementPattern objects.
# Re-run the generator to update.
# =============================================================================
import sympy
from sympy import Symbol
from rubi_integrate.utils.rubi_utils import *  # bare-name access; sympy imports below override any conflicts (e.g. Not)
from sympy.logic.boolalg import Not

from sympy_matching.wild import WildSymbol, IDENTITY_ELEMENT
from rubi_integrate.base_objects import Int, SymPyReplacementPattern
# Inert trig markers (Rubi's lowercase sin/cos/... patterns). Distinct opaque heads,
# NOT subclasses of sympy.sin -- see rubi-trig-deactivation-dispatch project note.
from rubi_integrate.utils import (
    # Wolfram standard constraints
    FreeQ, IntegerQ, MatchQ, EqQ, IGtQ, ILtQ, LtQ, LeQ, PolyQ,
)

# --- Integration variable ---
x = Symbol('x')

# --- Rubi global option stubs (default False/placeholder) ---
UseGamma = sympy.Symbol('UseGamma')  # Rubi global option; treated as False in Python
u = Symbol('u')  # Generic integrand placeholder used in some Rubi constraint calls

# --- Rubi selector symbols ---
# Rubi passes Min/Max as bare SYMBOLS, not calls: Expon[Px, x, Min] selects the
# minimum exponent. The code emitter round-trips through SymPy's printer, which
# renders Symbol('Min') as the bare name `Min`, so the name must exist here.
# (A genuine Min[a, b] call is emitted qualified, as sympy.Min(...), so these
# bindings cannot shadow it.)
Min = Symbol('Min')
Max = Symbol('Max')

# --- Wildcard symbols ---
# dot wildcards (must match exactly one expression)
# optional wildcards (can match identity element if absent in commutative ops)

A = Symbol('A')
Q = Symbol('Q')
e = Symbol('e')
f = Symbol('f')
g = Symbol('g')
q = Symbol('q')

Pq_ = WildSymbol('Pq')
Px_ = WildSymbol('Px')
a_ = WildSymbol('a')
_b_ = WildSymbol('b', optional_value=IDENTITY_ELEMENT)
b_ = WildSymbol('b')
_m_ = WildSymbol('m', optional_value=IDENTITY_ELEMENT)
m_ = WildSymbol('m')
_p_ = WildSymbol('p', optional_value=IDENTITY_ELEMENT)
p_ = WildSymbol('p')
_u_ = WildSymbol('u', optional_value=IDENTITY_ELEMENT)
u_ = WildSymbol('u')

RULES = [
    # Rule 1
    SymPyReplacementPattern(
        pattern=Int(Pq_*(x**2*_b_ + a_)**_p_, x),
        constraints=(FreeQ([a_, _b_], x), PolyQ(Pq_, x), IGtQ(_p_, -2),),
        replacement=Int(ExpandIntegrand(Pq_*(x**2*_b_ + a_)**_p_, x), x),
        module_name='1.1.2.x P(x) (a+b x^2)^p',
        rule_number=1,
    ),
    # Rule 2
    SymPyReplacementPattern(
        pattern=Int(Pq_*(x**2*_b_ + a_)**p_, x),
        constraints=(FreeQ([a_, _b_, p_], x), PolyQ(Pq_, x), EqQ(Coeff(Pq_, x, 0), 0), Not(MatchQ(Pq_, Condition(x**_m_*_u_, IntegerQ(_m_)))),),
        replacement=Int(x*(x**2*_b_ + a_)**p_*PolynomialQuotient(Pq_, x, x), x),
        module_name='1.1.2.x P(x) (a+b x^2)^p',
        rule_number=2,
    ),
    # Rule 3
    SymPyReplacementPattern(
        pattern=Int(Px_*(x**2*_b_ + a_)**_p_, x),
        constraints=(FreeQ([a_, _b_, _p_], x), PolyQ(Px_, x), EqQ(PolynomialRemainder(Px_, x**2*_b_ + a_, x), 0),),
        replacement=Int((x**2*_b_ + a_)**(_p_ + 1)*PolynomialQuotient(Px_, x**2*_b_ + a_, x), x),
        module_name='1.1.2.x P(x) (a+b x^2)^p',
        rule_number=3,
    ),
    # Rule 4
    SymPyReplacementPattern(
        pattern=Int(Pq_*(x**2*_b_ + a_)**p_, x),
        constraints=(FreeQ([a_, _b_], x), PolyQ(Pq_, x**2), ILtQ(p_ + sympy.S.Half, 0), LtQ(2*p_ + Expon(Pq_, x) + 1, 0),),
        replacement=With({A: Coeff(Pq_, x, 0), Q: PolynomialQuotient(Pq_ - Coeff(Pq_, x, 0), x**2, x)}, A*x*(x**2*_b_ + a_)**(p_ + 1)/a_ + Int(x**2*(x**2*_b_ + a_)**p_*(-A*_b_*(2*p_ + 3) + Q*a_), x)/a_),
        module_name='1.1.2.x P(x) (a+b x^2)^p',
        rule_number=4,
    ),
    # Rule 5
    SymPyReplacementPattern(
        pattern=Int(Pq_*(x**2*_b_ + a_)**p_, x),
        constraints=(FreeQ([a_, _b_], x), PolyQ(Pq_, x), LtQ(p_, -1),),
        replacement=With({Q: PolynomialQuotient(Pq_, x**2*_b_ + a_, x), f: Coeff(PolynomialRemainder(Pq_, x**2*_b_ + a_, x), x, 0), g: Coeff(PolynomialRemainder(Pq_, x**2*_b_ + a_, x), x, 1)}, Int((x**2*_b_ + a_)**(p_ + 1)*ExpandToSum(2*Q*a_*(p_ + 1) + f*(2*p_ + 3), x), x)/(2*a_*(p_ + 1)) + (x**2*_b_ + a_)**(p_ + 1)*(-f*x*_b_ + g*a_)/(2*a_*_b_*(p_ + 1))),
        module_name='1.1.2.x P(x) (a+b x^2)^p',
        rule_number=5,
    ),
    # Rule 6
    SymPyReplacementPattern(
        pattern=Int(Pq_*(x**2*_b_ + a_)**p_, x),
        constraints=(FreeQ([a_, _b_, p_], x), PolyQ(Pq_, x), Not(LeQ(p_, -1)),),
        replacement=With({e: Coeff(Pq_, x, Expon(Pq_, x)), q: Expon(Pq_, x)}, e*x**(q - 1)*(x**2*_b_ + a_)**(p_ + 1)/(_b_*(q + 2*p_ + 1)) + Int((x**2*_b_ + a_)**p_*ExpandToSum(-e*x**q*_b_*(q + 2*p_ + 1) - e*x**(q - 2)*a_*(q - 1) + Pq_*_b_*(q + 2*p_ + 1), x), x)/(_b_*(q + 2*p_ + 1))),
        module_name='1.1.2.x P(x) (a+b x^2)^p',
        rule_number=6,
    ),

]

# Summary: 6 rules translated, 0 skipped
