# -*- coding: utf-8 -*-
# =============================================================================
# !! AUTO-GENERATED FILE -- DO NOT EDIT !!
#
# Generated by: rubi_integrate/codegen/generate.py
# Source: 7.1.1 (a+b arcsinh(c x))^n.m
# Module: 7.1.1 (a+b arcsinh(c x))^n
#
# This file contains Rubi integration rules as SymPyReplacementPattern objects.
# Re-run the generator to update.
# =============================================================================
import sympy
from sympy import Symbol
from rubi_integrate.utils.rubi_utils import *  # bare-name access; sympy imports below override any conflicts (e.g. Not)
from sympy import (
    asinh, cosh, sqrt,
)

from sympy_matching.wild import WildSymbol, IDENTITY_ELEMENT
from rubi_integrate.base_objects import Int, SymPyReplacementPattern
# Inert trig markers (Rubi's lowercase sin/cos/... patterns). Distinct opaque heads,
# NOT subclasses of sympy.sin -- see rubi-trig-deactivation-dispatch project note.
from rubi_integrate.utils import (
    # Wolfram standard constraints
    FreeQ, GtQ, LtQ,
)

# --- Integration variable ---
x = Symbol('x')

# --- Rubi global option stubs (default False/placeholder) ---
UseGamma = sympy.Symbol('UseGamma')  # Rubi global option; treated as False in Python
u = Symbol('u')  # Generic integrand placeholder used in some Rubi constraint calls

# --- Rubi selector symbols ---
# Rubi passes Min/Max as bare SYMBOLS, not calls: Expon[Px, x, Min] selects the
# minimum exponent. The code emitter round-trips through SymPy's printer, which
# renders Symbol('Min') as the bare name `Min`, so the name must exist here.
# (A genuine Min[a, b] call is emitted qualified, as sympy.Min(...), so these
# bindings cannot shadow it.)
Min = Symbol('Min')
Max = Symbol('Max')

# --- Wildcard symbols ---
# dot wildcards (must match exactly one expression)
# optional wildcards (can match identity element if absent in commutative ops)

_a_ = WildSymbol('a', optional_value=IDENTITY_ELEMENT)
a_ = WildSymbol('a')
_b_ = WildSymbol('b', optional_value=IDENTITY_ELEMENT)
b_ = WildSymbol('b')
_c_ = WildSymbol('c', optional_value=IDENTITY_ELEMENT)
c_ = WildSymbol('c')
_n_ = WildSymbol('n', optional_value=IDENTITY_ELEMENT)
n_ = WildSymbol('n')

RULES = [
    # Rule 1
    SymPyReplacementPattern(
        pattern=Int((_a_ + _b_*asinh(x*_c_))**_n_, x),
        constraints=(FreeQ([_a_, _b_, _c_], x), GtQ(_n_, 0),),
        replacement=x*(_a_ + _b_*asinh(x*_c_))**_n_ - _b_*_c_*_n_*Int(x*(_a_ + _b_*asinh(x*_c_))**(_n_ - 1)/sqrt(x**2*_c_**2 + 1), x),
        module_name='7.1.1 (a+b arcsinh(c x))^n',
        rule_number=1,
    ),
    # Rule 2
    SymPyReplacementPattern(
        pattern=Int((_a_ + _b_*asinh(x*_c_))**n_, x),
        constraints=(FreeQ([_a_, _b_, _c_], x), LtQ(n_, -1),),
        replacement=-_c_*Int(x*(_a_ + _b_*asinh(x*_c_))**(n_ + 1)/sqrt(x**2*_c_**2 + 1), x)/(_b_*(n_ + 1)) + (_a_ + _b_*asinh(x*_c_))**(n_ + 1)*sqrt(x**2*_c_**2 + 1)/(_b_*_c_*(n_ + 1)),
        module_name='7.1.1 (a+b arcsinh(c x))^n',
        rule_number=2,
    ),
    # Rule 3
    SymPyReplacementPattern(
        pattern=Int((_a_ + _b_*asinh(x*_c_))**n_, x),
        constraints=(FreeQ([_a_, _b_, _c_, n_], x),),
        replacement=Subst(Int(x**n_*cosh(x/_b_ - _a_/_b_), x), x, _a_ + _b_*asinh(x*_c_))/(_b_*_c_),
        module_name='7.1.1 (a+b arcsinh(c x))^n',
        rule_number=3,
    ),

]

# Summary: 3 rules translated, 0 skipped
